# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A continuous Evolution Strategy incorporating mutational step size self-adaptation per coordinate axis.
# Search state: Stores parent population vectors, coordinate-wise mutation step sizes, objective values, and global optimum.
# Candidate generation: Offspring are generated by first log-normally mutating coordinate step sizes, then applying Gaussian jumps scaled by these new step sizes.
# Selection and replacement: Evaluates offspring batch and selects the top mu individuals to replace the parent generation.
# Adaptation: Coordinate step sizes self-adapt dynamically via multiplicative log-normal Gaussian perturbations during offspring creation.
# Exploration mechanisms: Global tau factor allows overall step size expansions to escape local minima across all dimensions.
# Exploitation mechanisms: Coordinate tau factor permits fine-tuning step sizes along individual axes during local convergence.
# Boundary handling: All mutated candidate coordinates are strictly bounded inside domain constraints via clipping.
# Budget strategy: Iterates in batches of lambda offspring per generation, strictly stopping when the budget ceiling is reached.
# Closest known influences: Self-Adaptive Evolution Strategies (Schwefel).
# Novelty or unusual aspects: Combines global intermediate recombination with explicit coordinate variance tracking without matrix inversions.
# Failure modes: Can experience step size starvation on noisy surfaces if fortuitous small steps are selected early.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np
import math

class Algorithm:
    def __init__(self, budget: int, dim: int):
        self.budget = int(budget)
        self.dim = int(dim)
        self.eval_count = 0
        self.lam = int(min(self.budget // 5, max(16, 2 * self.dim)))
        if self.lam > 60:
            self.lam = 60
        self.mu = max(2, self.lam // 2)

    def __call__(self, func):
        try:
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        except AttributeError:
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)

        self.eval_count = 0
        domain_range = ub - lb

        best_x = None
        best_y = float("inf")

        # Initialize parent population and step sizes
        parents_x = np.random.uniform(lb, ub, size=(self.mu, self.dim))
        parents_sigma = np.full((self.mu, self.dim), 0.2 * domain_range)
        parents_y = np.zeros(self.mu)

        for i in range(self.mu):
            if self.eval_count >= self.budget:
                parents_y[i] = float("inf")
                continue
            y = float(func(parents_x[i]))
            self.eval_count += 1
            parents_y[i] = y
            if y < best_y:
                best_y = y
                best_x = parents_x[i].copy()

        tau_global = 1.0 / math.sqrt(2.0 * self.dim)
        tau_local = 1.0 / math.sqrt(2.0 * math.sqrt(self.dim))
        min_sigma = 1e-6 * domain_range

        while self.eval_count < self.budget:
            offspring_x = np.zeros((self.lam, self.dim))
            offspring_sigma = np.zeros((self.lam, self.dim))
            offspring_y = np.full(self.lam, float("inf"))

            for i in range(self.lam):
                if self.eval_count >= self.budget:
                    break

                # Global intermediate recombination for parent selection
                r1, r2 = np.random.choice(self.mu, size=2, replace=False)
                base_x = 0.5 * (parents_x[r1] + parents_x[r2])
                base_sigma = 0.5 * (parents_sigma[r1] + parents_sigma[r2])

                # Mutation
                z_global = np.random.normal(0, 1)
                z_local = np.random.normal(0, 1, size=self.dim)
                
                mut_sigma = base_sigma * np.exp(tau_global * z_global + tau_local * z_local)
                mut_sigma = np.maximum(mut_sigma, min_sigma)

                step = np.random.normal(0, 1, size=self.dim) * mut_sigma
                cand_x = np.clip(base_x + step, lb, ub)

                y = float(func(cand_x))
                self.eval_count += 1

                offspring_x[i] = cand_x
                offspring_sigma[i] = mut_sigma
                offspring_y[i] = y

                if y < best_y:
                    best_y = y
                    best_x = cand_x.copy()

            if self.eval_count >= self.budget:
                break

            # Selection (mu, lambda)
            sorted_idx = np.argsort(offspring_y)[:self.mu]
            parents_x = offspring_x[sorted_idx]
            parents_sigma = offspring_sigma[sorted_idx]
            parents_y = offspring_y[sorted_idx]

        if best_x is None:
            best_x = np.random.uniform(lb, ub, size=self.dim)

        return best_x, best_y
