# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: An adaptive random walk algorithm that maintains search momentum along successful trajectory directions and adjusts step sizes.
# Search state: Retains the current incumbent point, step size vector, directional momentum vector, stagnation counter, and the global optimum.
# Candidate generation: New trial points are generated by adding the momentum vector and Gaussian noise scaled by current step sizes to the incumbent.
# Selection and replacement: If a trial point improves the objective, it becomes the new incumbent and updates the momentum.
# Adaptation: Successful steps expand the step size and build momentum; failed steps contract the step size and dampen momentum.
# Exploration mechanisms: Generates random restarts when local stagnation occurs or when step sizes drop below a minimum threshold.
# Exploitation mechanisms: Directional momentum accelerates descent along smooth gradients or valleys.
# Boundary handling: Trial points are clipped to the box constraints before evaluation.
# Budget strategy: Executes single-trajectory steps sequentially until the exact evaluation budget is reached.
# Closest known influences: Solis & Wets randomized hill climber with momentum.
# Novelty or unusual aspects: Combines exponential step size expansion/contraction with explicit directional inertia tracking.
# Failure modes: Single trajectory can get trapped in local optima until stagnation triggers a restart.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget: int, dim: int):
        self.budget = int(budget)
        self.dim = int(dim)
        self.eval_count = 0

    def __call__(self, func):
        try:
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        except AttributeError:
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)

        self.eval_count = 0
        domain_range = ub - lb

        curr_x = np.random.uniform(lb, ub, size=self.dim)
        curr_y = float(func(curr_x))
        self.eval_count += 1

        best_x = curr_x.copy()
        best_y = curr_y

        sigma = 0.1 * domain_range
        momentum = np.zeros(self.dim)
        stagnation = 0
        max_stagnation = max(50, 5 * self.dim)

        while self.eval_count < self.budget:
            # Generate candidate
            step = np.random.normal(0, 1, size=self.dim) * sigma
            trial = curr_x + momentum + step
            trial = np.clip(trial, lb, ub)

            y = float(func(trial))
            self.eval_count += 1

            if y < curr_y:
                # Success: update momentum and expand step size
                step_diff = trial - curr_x
                momentum = 0.5 * momentum + 0.5 * step_diff
                sigma = np.minimum(1.2 * sigma, 0.3 * domain_range)
                curr_x = trial.copy()
                curr_y = y
                stagnation = 0

                if y < best_y:
                    best_y = y
                    best_x = trial.copy()
            else:
                # Failure: contract step size and dampen momentum
                momentum = 0.2 * momentum
                sigma = np.maximum(0.85 * sigma, 1e-6 * domain_range)
                stagnation += 1

            # Restart mechanism on stagnation
            if stagnation > max_stagnation or np.max(sigma / domain_range) < 1e-5:
                curr_x = np.random.uniform(lb, ub, size=self.dim)
                if self.eval_count < self.budget:
                    curr_y = float(func(curr_x))
                    self.eval_count += 1
                    if curr_y < best_y:
                        best_y = curr_y
                        best_x = curr_x.copy()
                sigma = 0.1 * domain_range
                momentum = np.zeros(self.dim)
                stagnation = 0

        return best_x, best_y
