# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A self-adaptive Differential Evolution (jDE) implementation optimized for black-box minimization.
# Search state: A population of candidate solutions, their corresponding objective values, and individual control parameters (F and Cr).
# Candidate generation: Uses the 'rand/1/bin' strategy. A mutant vector is generated by combining three random members, and binomial crossover is applied to create the trial candidate.
# Selection and replacement: A simple greedy selection mechanism where the trial vector replaces the current population member if it achieves a lower or equal objective value.
# Adaptation: Employs self-adaptation for the scaling factor (F) and crossover probability (Cr). Each individual carries its own parameters which are perturbed with a small probability (0.1) in each generation.
# Exploration mechanisms: Differential mutation provides global exploration by utilizing the diverse directions present in the population.
# Exploitation mechanisms: Binomial crossover and greedy selection focus the search on promising directions. The adaptation of F and Cr allows for fine-tuning as the population converges.
# Boundary handling: Trial vectors are clipped to the hypercube defined by the problem bounds.
# Budget strategy: The population size is dynamically determined based on dimensionality and total budget. The evaluation counter is strictly checked to ensure the budget is never exceeded.
# Closest known influences: Brest et al. (2006) "Self-Adapting Control Parameters in Differential Evolution (jDE)".
# Novelty or unusual aspects: Compact logic that collapses the jDE framework into a single robust class, handling edge cases like small populations or limited budgets gracefully.
# Failure modes: May converge prematurely on highly rugged landscapes if the budget is extremely low relative to the dimensionality.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        # Heuristic for population size: 10 * dim is standard, but must fit within budget
        self.pop_size = max(min(10 * dim, budget // 2), 5)
        if self.pop_size > budget:
            self.pop_size = budget

    def __call__(self, func):
        # Extract bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        else:
            lb = np.zeros(self.dim)
            ub = np.ones(self.dim)
            
        # Ensure bounds are arrays of correct dimension
        if lb.ndim == 0: lb = np.full(self.dim, lb)
        if ub.ndim == 0: ub = np.full(self.dim, ub)

        # Initialize search state
        evals = 0
        best_x = None
        best_y = float('inf')
        
        # Safe pop_size for mutation logic
        pop_size = int(self.pop_size)
        
        # Initial population
        pop = lb + (ub - lb) * np.random.rand(pop_size, self.dim)
        fitness = np.full(pop_size, np.inf)
        
        # Control parameters for self-adaptation
        F = np.full(pop_size, 0.5)
        Cr = np.full(pop_size, 0.9)
        
        # Initial evaluation
        for i in range(pop_size):
            if evals >= self.budget:
                break
            y = func(pop[i])
            evals += 1
            fitness[i] = y
            if y < best_y:
                best_y = y
                best_x = pop[i].copy()
                
        # Main optimization loop
        while evals < self.budget:
            for i in range(pop_size):
                if evals >= self.budget:
                    break
                
                # 1. Parameter adaptation (jDE logic)
                current_F = F[i]
                current_Cr = Cr[i]
                if np.random.rand() < 0.1:
                    current_F = 0.1 + np.random.rand() * 0.9
                if np.random.rand() < 0.1:
                    current_Cr = np.random.rand()
                
                # 2. Mutation (rand/1)
                others = [idx for idx in range(pop_size) if idx != i]
                if len(others) >= 3:
                    r1, r2, r3 = np.random.choice(others, 3, replace=False)
                    mutant = pop[r1] + current_F * (pop[r2] - pop[r3])
                else:
                    # Fallback mutation for very small populations
                    mutant = pop[i] + 0.1 * (ub - lb) * np.random.standard_normal(self.dim)
                
                # 3. Crossover (binomial)
                trial = np.copy(pop[i])
                j_rand = np.random.randint(self.dim)
                for j in range(self.dim):
                    if np.random.rand() < current_Cr or j == j_rand:
                        trial[j] = mutant[j]
                
                # 4. Boundary handling (clipping)
                trial = np.clip(trial, lb, ub)
                
                # 5. Selection
                y_trial = func(trial)
                evals += 1
                
                if y_trial <= fitness[i]:
                    pop[i] = trial
                    fitness[i] = y_trial
                    F[i] = current_F
                    Cr[i] = current_Cr
                    if y_trial < best_y:
                        best_y = y_trial
                        best_x = trial.copy()
                        
        # Ensure we return a valid point if budget was too small to even initialize
        if best_x is None:
            best_x = lb + (ub - lb) * np.random.rand(self.dim)
            best_y = func(best_x)
            
        return best_x, best_y
