import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A diagonal (1+1) Evolution Strategy with adaptive step size and coordinate-wise scaling.
# Search state: Current best solution, global step size (sigma), and a vector of coordinate-specific scaling factors.
# Candidate generation: A single offspring is generated by adding Gaussian noise to the current best solution, scaled by both the global sigma and the coordinate-specific scaling vector.
# Selection and replacement: An elitist (1+1) selection strategy is used, where the new candidate replaces the current solution only if it achieves a lower objective value.
# Adaptation: The global step size is adapted using a success-based rule similar to the 1/5th success rule. The coordinate-specific scaling factors are updated using exponential smoothing based on the absolute values of the successful perturbations, allowing the search to adapt to the local aspect ratio of the fitness landscape.
# Exploration mechanisms: The algorithm employs restarts when the global step size falls below a threshold or when progress stagnates, ensuring coverage of different regions of the search space.
# Exploitation mechanisms: Local search is refined through the simultaneous adaptation of the global step size and the internal scaling vector, allowing for efficient convergence in narrow valleys.
# Boundary handling: Candidates are strictly clipped to the feasible domain defined by the problem bounds.
# Budget strategy: The algorithm explicitly counts evaluations and terminates when the budget is exhausted, across all restart cycles.
# Closest known influences: (1+1)-CMA-ES, Matyas's Random Search, and various Adaptive Random Search techniques.
# Novelty or unusual aspects: Uses a simplified diagonal scaling update that provides much of the benefit of covariance adaptation with significantly lower computational and implementation complexity.
# Failure modes: May converge slowly on functions with extremely high correlations between variables (non-separable, non-axis-aligned ridges).
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evals_done = 0

    def __call__(self, func):
        # Bound extraction
        if hasattr(func, "lower") and func.lower is not None:
            lb, ub = np.array(func.lower), np.array(func.upper)
        elif hasattr(func, "bounds"):
            lb, ub = np.array(func.bounds.lb), np.array(func.bounds.ub)
        else:
            lb, ub = np.zeros(self.dim), np.ones(self.dim)

        best_x = None
        best_y = float('inf')

        # Global budget loop
        while self.evals_done < self.budget:
            # Restart: initialize position and hyperparameters
            curr_x = lb + np.random.rand(self.dim) * (ub - lb)
            
            if self.evals_done >= self.budget:
                break
            curr_y = func(curr_x)
            self.evals_done += 1

            if curr_y < best_y:
                best_y = curr_y
                best_x = curr_x.copy()

            # Local search state
            sigma = 0.2 * np.max(ub - lb)
            diag_std = np.ones(self.dim)
            
            # Adaptation parameters
            c_std = 1.0 / (3.0 + self.dim)
            p_target = 0.2
            damping = 1.0 + self.dim
            
            stagnation_limit = 100 + 20 * self.dim
            stagnation_counter = 0

            # Local search loop (within one restart)
            while self.evals_done < self.budget:
                # Sample standard normal noise
                z = np.random.standard_normal(self.dim)
                
                # Create candidate solution using current scale and sigma
                candidate = curr_x + sigma * diag_std * z
                candidate = np.clip(candidate, lb, ub)

                if self.evals_done >= self.budget:
                    break
                cand_y = func(candidate)
                self.evals_done += 1

                if cand_y < curr_y:
                    # Improvement found (Success)
                    stagnation_counter = 0
                    
                    # Update global step size (expand)
                    sigma *= np.exp((1.0 - p_target) / damping)
                    
                    # Update coordinate scaling (0.7979 is approx E[|N(0,1)|])
                    diag_std = (1.0 - c_std) * diag_std + c_std * (np.abs(z) / 0.7979)
                    
                    curr_x, curr_y = candidate, cand_y
                    if curr_y < best_y:
                        best_y, best_x = curr_y, curr_x.copy()
                else:
                    # No improvement (Failure)
                    stagnation_counter += 1
                    
                    # Update global step size (contract)
                    sigma *= np.exp(-p_target / damping)
                
                # Check for convergence or stagnation to trigger a restart
                if sigma < 1e-12 * np.max(ub - lb) or stagnation_counter > stagnation_limit:
                    break
        
        return best_x, best_y
