# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses an Adaptive (1+1) Evolution Strategy (ES) with periodic restarts.
# It maintains a single search point and adapts its mutation strength (sigma) based on the success rate 
# of generated candidates.
# Search state: Current best solution vector (x), current objective value (y), current mutation 
# strength (sigma), and success tracking counters.
# Candidate generation: Candidates are generated by adding Gaussian noise to the current best 
# solution, scaled by the current sigma and the range of the search space.
# Selection and replacement: A simple greedy selection is used; the candidate replaces the 
# current point only if its objective value is strictly lower.
# Adaptation: The mutation strength (sigma) is adjusted using a simplified 1/5th success rule. 
# After a window of trials, if the success rate is high, sigma increases; if low, it decreases.
# Exploration mechanisms: Initial points for each restart are sampled uniformly within the bounds. 
# Large initial sigma values and periodic restarts help escape local optima.
# Exploitation mechanisms: Local Gaussian perturbations allow for fine-grained refinement 
# of the solution as sigma decreases during successful local search phases.
# Boundary handling: Candidates are clipped to the hypercube defined by the lower and upper bounds.
# Budget strategy: The algorithm tracks total evaluations and terminates immediately once 
# the budget is exhausted. Restarts are scheduled to ensure the budget is used effectively 
# even if a single local search converges early.
# Closest known influences: Classical (1+1)-ES (Rechenberg), Matyas function optimization strategies.
# Novelty or unusual aspects: Combines a very lightweight success-rule adaptation with 
# a restart logic tailored for black-box constraints without needing complex matrix updates.
# Failure modes: May struggle with highly non-separable or extremely rugged landscapes 
# where gradient-like local search is consistently misled.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the Adaptive (1+1) Evolution Strategy.
        
        Args:
            budget (int): Total number of function evaluations allowed.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.eval_count = 0

    def __call__(self, func):
        """
        Executes the optimization process.
        
        Args:
            func (callable): The objective function to minimize.
        
        Returns:
            tuple: (best_x, best_y) representing the best solution found.
        """
        # Retrieve bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Fallback for unexpected interface
            lb = np.zeros(self.dim)
            ub = np.ones(self.dim)

        span = ub - lb
        best_x = None
        best_y = float('inf')

        # Evaluation wrapper to enforce budget
        def evaluate(x):
            nonlocal best_x, best_y
            if self.eval_count >= self.budget:
                return best_y
            
            y = func(x)
            self.eval_count += 1
            
            if y < best_y:
                best_y = y
                best_x = np.copy(x)
            return y

        # Success rule parameters
        target_success_rate = 0.2
        increase_factor = 1.22
        decrease_factor = 0.82
        window_size = 10 + int(3 * np.sqrt(self.dim))

        # Optimization loop with Restarts
        while self.eval_count < self.budget:
            # Random initialization for the current restart
            curr_x = lb + np.random.rand(self.dim) * span
            curr_y = evaluate(curr_x)
            
            # Initial step size is a fraction of the search space
            sigma = 0.2
            
            success_history = []
            
            # Local search loop
            while self.eval_count < self.budget:
                # Generate candidate
                noise = np.random.randn(self.dim)
                candidate = curr_x + sigma * span * noise
                candidate = np.clip(candidate, lb, ub)
                
                cand_y = evaluate(candidate)
                
                # Selection
                if cand_y < curr_y:
                    success_history.append(True)
                    curr_x, curr_y = candidate, cand_y
                else:
                    success_history.append(False)
                
                # Adapt sigma based on success history
                if len(success_history) >= window_size:
                    success_rate = sum(success_history) / len(success_history)
                    if success_rate > target_success_rate:
                        sigma *= increase_factor
                    else:
                        sigma *= decrease_factor
                    
                    success_history = []
                    
                # Convergence check for restart: if sigma is effectively zero
                if sigma < 1e-12:
                    break
        
        return best_x, best_y
