# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A population-based coordinate descent algorithm that maintains several independent incumbents. Each incumbent performs local, axis-aligned searches with adaptive step sizes (a variant of pattern search).
# Search state: A set of incumbents, each consisting of a position vector, its objective value, and a vector of per-dimension step sizes (scales).
# Candidate generation: Candidates are generated by perturbing a single dimension of an incumbent by its current step size in either the positive or negative direction.
# Selection and replacement: Greedy selection is used. If a perturbed point is better than the incumbent, it replaces the incumbent. If an incumbent's step sizes fall below a threshold (stagnation), the incumbent is re-initialized to a random location in the search space.
# Adaptation: Step sizes are expanded (multiplied by 1.2) when a move in a specific dimension is successful and contracted (multiplied by 0.5) when moves in both directions fail for that dimension.
# Exploration mechanisms: Initial random sampling of multiple points and periodic restarts for stagnated search points ensure coverage of different regions of the search space.
# Exploitation mechanisms: Local coordinate-wise probing allows for fine-tuning solutions in the vicinity of known local minima.
# Boundary handling: All generated candidate points are clipped to the specified lower and upper bounds.
# Budget strategy: The algorithm tracks evaluations and terminates immediately upon reaching the budget. Initial population size is scaled based on dimension but capped to ensure sufficient budget remains for local refinement.
# Closest known influences: Hooke-Jeeves Pattern Search, Adaptive Coordinate Descent.
# Novelty or unusual aspects: The algorithm maintains independent step sizes for every dimension for every incumbent, allowing it to adapt to different scales and sensitivities across the landscape.
# Failure modes: The algorithm may struggle with highly rotated landscapes where the optimal path is not axis-aligned, or with extremely noisy functions that trigger premature step-size contraction.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.eval_count = 0
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Extract bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        # Helper to evaluate and track the best
        def evaluate(x):
            if self.eval_count >= self.budget:
                return float('inf')
            # Ensure within bounds
            x_clipped = np.clip(x, lb, ub)
            y = func(x_clipped)
            self.eval_count += 1
            if y < self.best_y:
                self.best_y = y
                self.best_x = x_clipped.copy()
            return y

        # Population of incumbents
        # Each incumbent: {'x': point, 'y': value, 'sigmas': array, 'dim_idx': current_dim}
        pop_size = min(max(3, self.dim), 10)
        population = []

        # Initial random sampling
        for _ in range(pop_size):
            if self.eval_count >= self.budget:
                break
            x = np.random.uniform(lb, ub, self.dim)
            y = evaluate(x)
            sigmas = (ub - lb) * 0.1
            population.append({
                'x': x,
                'y': y,
                'sigmas': sigmas,
                'dim_idx': 0
            })

        if not population:
            return self.best_x, self.best_y

        # Main loop: Coordinate-wise probing
        while self.eval_count < self.budget:
            for i in range(len(population)):
                if self.eval_count >= self.budget:
                    break
                
                ind = population[i]
                d = ind['dim_idx']
                
                # Attempt move in the current dimension
                improved = False
                original_val = ind['y']
                
                # Try positive direction
                x_new = ind['x'].copy()
                x_new[d] += ind['sigmas'][d]
                y_new = evaluate(x_new)
                
                if y_new < ind['y']:
                    ind['x'] = x_new
                    ind['y'] = y_new
                    ind['sigmas'][d] *= 1.2 # Expand
                    improved = True
                else:
                    if self.eval_count >= self.budget:
                        break
                    # Try negative direction
                    x_new = ind['x'].copy()
                    x_new[d] -= ind['sigmas'][d]
                    y_new = evaluate(x_new)
                    
                    if y_new < ind['y']:
                        ind['x'] = x_new
                        ind['y'] = y_new
                        ind['sigmas'][d] *= 1.2 # Expand
                        improved = True
                
                if not improved:
                    # Shrink step size if no improvement in either direction
                    ind['sigmas'][d] *= 0.5
                
                # Move to the next dimension for this incumbent
                ind['dim_idx'] = (d + 1) % self.dim
                
                # Check for stagnation: if all sigmas are tiny, restart this individual
                if np.all(ind['sigmas'] < (ub - lb) * 1e-7):
                    new_x = np.random.uniform(lb, ub, self.dim)
                    new_y = evaluate(new_x)
                    ind['x'] = new_x
                    ind['y'] = new_y
                    ind['sigmas'] = (ub - lb) * 0.1
                    ind['dim_idx'] = 0

        return self.best_x, self.best_y
