# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust Differential Evolution (DE) implementation using the 'best/1/bin' strategy with scaling factor dithering.
# Search state: A population of candidate solutions, their corresponding fitness values, and a pointer to the global best found so far.
# Candidate generation: Offspring are generated by taking the current best individual and adding a scaled difference vector between two random members (mutation), then performing binomial crossover with the target individual.
# Selection and replacement: A greedy selection mechanism where the offspring replaces the parent if and only if its fitness is better (lower).
# Adaptation: Employs 'jitter' or dithering on the mutation scale factor (F), randomly varying it between 0.4 and 1.0 for each mutation to maintain diversity.
# Exploration mechanisms: Initial uniform sampling across the search space and the stochastic nature of mutation/crossover.
# Exploitation mechanisms: The mutation strategy explicitly uses the 'best' known individual as the base vector to drive the search towards high-performance regions.
# Boundary handling: Candidates are clipped to the hyper-rectangle defined by the lower and upper bounds.
# Budget strategy: A strict evaluation counter is maintained. The search terminates immediately when the evaluation budget is exhausted, even during population initialization.
# Closest known influences: Standard Differential Evolution (Storn & Price), specifically the DE/best/1/bin variant.
# Novelty or unusual aspects: Minimalist implementation focused on standard library compatibility and robustness across variable dimensions and budgets.
# Failure modes: May converge prematurely on highly rugged, multimodal landscapes if the population size is too small relative to the complexity.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Differential Evolution (DE/best/1/bin) with scaling jitter.
    Optimized for black-box minimization within a fixed budget.
    """
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evals = 0
        
        # Hyperparameters
        # Population size scales with dimension but is constrained by the budget.
        self.pop_size = max(10, min(15 * dim, budget // 2))
        self.cr = 0.9  # Crossover probability
        self.f_range = (0.4, 1.0) # Range for mutation scaling factor jitter

    def __call__(self, func):
        # 1. Determine Search Bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb, ub = func.lower, func.upper
        elif hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            # Fallback to unit hypercube if no bounds are provided
            lb, ub = np.zeros(self.dim), np.ones(self.dim)
        
        # Ensure lb and ub are numpy arrays of the correct dimension
        if np.isscalar(lb): lb = np.full(self.dim, lb)
        if np.isscalar(ub): ub = np.full(self.dim, ub)
        
        # 2. Initialize Population
        # Population initialization counts against the budget.
        pop = np.random.uniform(lb, ub, (self.pop_size, self.dim))
        fitness = np.full(self.pop_size, np.inf)
        
        best_idx = 0
        best_y = np.inf
        best_x = None

        for i in range(self.pop_size):
            if self.evals >= self.budget:
                break
            fitness[i] = func(pop[i])
            self.evals += 1
            if fitness[i] < best_y:
                best_y = fitness[i]
                best_x = pop[i].copy()
                best_idx = i

        # 3. Optimization Loop
        while self.evals < self.budget:
            for i in range(self.pop_size):
                if self.evals >= self.budget:
                    break
                
                # Mutation: DE/best/1
                # Select two random indices that are not the current best or current index
                candidates = [idx for idx in range(self.pop_size) if idx != best_idx]
                if len(candidates) < 2:
                    # Fallback for very small populations
                    r1, r2 = np.random.choice(self.pop_size, 2, replace=True)
                else:
                    r1, r2 = np.random.choice(candidates, 2, replace=False)
                
                # Jitter F
                f = np.random.uniform(self.f_range[0], self.f_range[1])
                
                # Create mutant
                mutant = best_x + f * (pop[r1] - pop[r2])
                
                # Binomial Crossover
                cross_points = np.random.rand(self.dim) <= self.cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary Handling: Clip trial vector to bounds
                trial = np.clip(trial, lb, ub)
                
                # Evaluation
                f_trial = func(trial)
                self.evals += 1
                
                # Selection
                if f_trial <= fitness[i]:
                    pop[i] = trial
                    fitness[i] = f_trial
                    if f_trial < best_y:
                        best_y = f_trial
                        best_x = trial.copy()
                        best_idx = i
                        
        return best_x, best_y
