# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A (1+1)-Evolution Strategy (ES) with 1/5th success rule step-size adaptation and periodic restarts.
# Search state: Current best vector (x_best), current best value (y_best), adaptive step size (sigma), and success tracking counters.
# Candidate generation: New candidates are generated by adding isotropic Gaussian noise (scaled by sigma) to the current best vector.
# Selection and replacement: A simple greedy (plus) selection is used; the candidate replaces the current best if its objective value is strictly lower.
# Adaptation: The step size (sigma) is adjusted after every iteration. It increases upon a successful improvement and decreases otherwise, aiming for a success rate of approximately 20% (Rechenberg's rule).
# Exploration mechanisms: Restarts are triggered when the step size becomes smaller than a specific tolerance relative to the search space, allowing the algorithm to escape local optima or stagnant regions.
# Exploitation mechanisms: The Gaussian mutation provides local refinement, with sigma narrowing down to the local minimum during periods of consistent improvement.
# Boundary handling: Candidates are clipped to the hypercube defined by the problem bounds.
# Budget strategy: The algorithm tracks evaluations and terminates exactly when the budget is exhausted. Initial samples are used to seed the search.
# Closest known influences: Rechenberg's (1+1)-ES, Basic Evolution Strategies.
# Novelty or unusual aspects: Extremely lightweight implementation focusing on robustness across varying dimensions and budget sizes without external dependencies.
# Failure modes: May struggle with highly non-separable or extremely rugged landscapes where the isotropic assumption of the mutation operator is inefficient.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the (1+1)-ES optimizer.
        :param budget: Total number of function evaluations allowed.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.eval_count = 0

    def _get_bounds(self, func):
        """
        Extracts lower and upper bounds from the function object.
        """
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        elif hasattr(func, 'lower'):
            lb = func.lower
            ub = func.upper
        else:
            raise AttributeError("Function object does not provide bounds.")
        
        # Ensure lb and ub are numpy arrays
        return np.asarray(lb, dtype=float), np.asarray(ub, dtype=float)

    def __call__(self, func):
        """
        Executes the optimization process.
        :param func: The objective function to minimize.
        :return: (best_x, best_y)
        """
        lb, ub = self._get_bounds(func)
        span = ub - lb
        
        # Global best trackers
        global_best_x = None
        global_best_y = float('inf')

        # Optimization hyper-parameters
        increase_factor = 1.25
        decrease_factor = 0.85
        sigma_init = 0.1 * np.mean(span)
        sigma_min = 1e-9 * np.mean(span)

        while self.eval_count < self.budget:
            # Restart: Initialize a new local search
            x_best = np.random.uniform(lb, ub)
            y_best = func(x_best)
            self.eval_count += 1
            
            if y_best < global_best_y:
                global_best_y = y_best
                global_best_x = np.copy(x_best)
            
            if self.eval_count >= self.budget:
                break

            sigma = sigma_init
            
            # Local search loop (1+1)-ES
            while self.eval_count < self.budget:
                # Generate candidate
                noise = np.random.normal(0, 1, self.dim)
                x_cand = x_best + sigma * noise
                
                # Boundary handling: Clipping
                x_cand = np.clip(x_cand, lb, ub)
                
                # Evaluate
                y_cand = func(x_cand)
                self.eval_count += 1
                
                # Selection and Adaptation
                if y_cand < y_best:
                    # Success
                    y_best = y_cand
                    x_best = x_cand
                    sigma *= increase_factor
                    
                    if y_best < global_best_y:
                        global_best_y = y_best
                        global_best_x = np.copy(x_best)
                else:
                    # Failure
                    sigma *= decrease_factor
                
                # Check for convergence of local search to trigger restart
                if sigma < sigma_min:
                    break
        
        return global_best_x, global_best_y

# The harness provides the seed via numpy.random.seed() before calling Algorithm.__call__().
# The Algorithm uses standard numpy random generation which respects that seed.
