# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust implementation of the Differential Evolution (DE) algorithm, specifically the DE/rand/1/bin variant. It is designed to handle black-box minimization tasks under strict evaluation budgets and box constraints.
# Search state: Maintains a population of candidate solutions (vectors) and their corresponding objective function values, along with the current global best found.
# Candidate generation: Trial vectors are generated by selecting three distinct random individuals from the population to create a mutant vector (via vector subtraction and scaling), which is then combined with the parent vector using binomial crossover.
# Selection and replacement: A greedy selection mechanism is used where a trial vector replaces its parent in the population only if its objective value is less than or equal to the parent's value.
# Adaptation: The mutation scale factor (F) and the crossover probability (Cr) are randomized for each candidate generation to provide a balance between exploration and exploitation without manual tuning.
# Exploration mechanisms: Differential mutation provides a self-scaling search step, while the 'rand/1' strategy and randomized parameters ensure the algorithm avoids premature convergence in diverse regions of the search space.
# Exploitation mechanisms: The selection process ensures that the population improves over time, and binomial crossover allows for refinement along specific dimensions.
# Boundary handling: Candidate solutions are constrained to the search space using clipping (clamping values to the lower and upper bounds).
# Budget strategy: The algorithm tracks evaluations explicitly and terminates immediately when the budget is exhausted, even mid-generation.
# Closest known influences: The classic Differential Evolution algorithm by Storn and Price (1997).
# Novelty or unusual aspects: Minimalist, single-class implementation with adaptive population sizing relative to the problem dimension and budget.
# Failure modes: May struggle with highly deceptive landscapes or functions where global optima reside in extremely small basins of attraction relative to the search space.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the Differential Evolution optimizer.
        
        :param budget: Total number of function evaluations allowed.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.evals = 0

    def __call__(self, func):
        """
        Executes the optimization process.
        
        :param func: The objective function to minimize. 
                     Expected to have .lower/.upper or .bounds attributes.
        :return: (best_x, best_y)
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower, dtype=float)
            ub = np.array(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb, dtype=float)
            ub = np.array(func.bounds.ub, dtype=float)
        else:
            # Standard default if no bounds are detected
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        # Determine population size based on dimensionality and budget
        # DE typically needs at least 4 members for the rand/1 strategy.
        pop_size = min(self.budget, max(10, min(100, 10 * self.dim)))
        if pop_size < 5:
            pop_size = max(1, pop_size)

        # Initialize population
        population = lb + np.random.rand(pop_size, self.dim) * (ub - lb)
        fitness = np.zeros(pop_size)
        
        best_x = None
        best_y = float('inf')

        # Initial evaluation of the population
        for i in range(pop_size):
            if self.evals >= self.budget:
                break
            
            y = float(func(population[i]))
            fitness[i] = y
            self.evals += 1
            
            if y < best_y:
                best_y = y
                best_x = population[i].copy()

        # Main Evolution Loop
        while self.evals < self.budget:
            for i in range(pop_size):
                if self.evals >= self.budget:
                    break
                
                # Pick three distinct individuals different from the current one
                indices = [idx for idx in range(pop_size) if idx != i]
                if len(indices) < 3:
                    # Fallback for extremely small populations/budgets
                    r1, r2, r3 = np.random.choice(pop_size, 3, replace=True)
                else:
                    r1, r2, r3 = np.random.choice(indices, 3, replace=False)

                # Parameters F and Cr (randomized for adaptation)
                F = np.random.uniform(0.4, 1.0)
                Cr = np.random.uniform(0.1, 0.9)

                # Mutation (DE/rand/1)
                mutant = population[r1] + F * (population[r2] - population[r3])
                
                # Boundary Handling (Clipping)
                mutant = np.clip(mutant, lb, ub)

                # Binomial Crossover
                cross_points = np.random.rand(self.dim) < Cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial_x = np.where(cross_points, mutant, population[i])

                # Selection
                trial_y = float(func(trial_x))
                self.evals += 1

                if trial_y <= fitness[i]:
                    population[i] = trial_x
                    fitness[i] = trial_y
                    if trial_y < best_y:
                        best_y = trial_y
                        best_x = trial_x.copy()

        return best_x, best_y
