# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust implementation of Differential Evolution (DE) using the 'rand/1/bin' strategy.
# Search state: A population of candidate solutions maintained in a numpy array, along with an array of their corresponding fitness values and the current global best found.
# Candidate generation: For each individual in the population, a mutant vector is generated by adding the scaled difference of two random members to a third. A trial vector is then created through binomial crossover with the target individual.
# Selection and replacement: The algorithm uses greedy selection, where the trial vector replaces the target individual in the population only if its fitness is less than or equal to the target's fitness.
# Adaptation: Population size is dynamically scaled based on the problem dimension and total budget to ensure a balance between exploration and the number of generations possible. Mutation scale (F=0.8) and crossover probability (Cr=0.9) are fixed at values known for general-purpose robustness.
# Exploration mechanisms: Mutation using randomly selected individuals from the population provides global exploration, while the stochastic nature of binomial crossover introduces variety in the search directions.
# Exploitation mechanisms: The greedy replacement strategy and the best-so-far tracking ensure that the search focuses on improving existing solutions.
# Boundary handling: Candidates are clipped to the hyper-rectangle defined by the function's lower and upper bounds using numpy's clipping function.
# Budget strategy: The algorithm monitors the evaluation count strictly and terminates immediately once the budget is reached, including during the initialization phase.
# Closest known influences: Storn and Price's classical Differential Evolution (1997).
# Novelty or unusual aspects: Highly compact, vectorized implementation focused on staying within constraints while being adaptive to both dimensionality and budget.
# Failure modes: May experience slow convergence on extremely high-dimensional landscapes or get trapped in local optima on highly rugged surfaces when the budget is very limited.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initialize the optimizer with a given evaluation budget and problem dimension.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Execute the minimization process on the provided objective function.
        """
        # Determine search space bounds from the function object
        try:
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        except AttributeError:
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)

        # Heuristic population size: scaled by dimension but limited by budget
        # We need at least 4 members for the rand/1 mutation strategy
        pop_size = int(max(5, min(15 + self.dim // 2, 80, self.budget // 5)))
        
        # Hyperparameters for Differential Evolution
        F = 0.8  # Mutation scale factor
        Cr = 0.9 # Crossover probability

        # Initialize population and fitness tracking
        # We initialize best_x to a random point within bounds to handle budget=0 cases
        best_x = lb + np.random.rand(self.dim) * (ub - lb)
        best_y = np.inf
        evals = 0
        
        pop = lb + np.random.rand(pop_size, self.dim) * (ub - lb)
        fitness = np.full(pop_size, np.inf)

        # Initial evaluation of the population
        for i in range(pop_size):
            if evals >= self.budget:
                break
            
            y = func(pop[i])
            evals += 1
            fitness[i] = y
            
            if y < best_y:
                best_y = y
                best_x = pop[i].copy()

        # Evolution loop
        while evals < self.budget:
            for i in range(pop_size):
                if evals >= self.budget:
                    break

                # Mutation: select 3 distinct individuals other than the current one
                idxs = [j for j in range(pop_size) if j != i]
                a, b, c = np.random.choice(idxs, 3, replace=False)
                mutant = pop[a] + F * (pop[b] - pop[c])

                # Binomial Crossover
                cross_points = np.random.rand(self.dim) < Cr
                # Ensure at least one dimension is inherited from the mutant
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary Handling: Clip to feasible region
                trial = np.clip(trial, lb, ub)

                # Evaluation and Selection
                f_trial = func(trial)
                evals += 1

                if f_trial <= fitness[i]:
                    fitness[i] = f_trial
                    pop[i] = trial
                    if f_trial < best_y:
                        best_y = f_trial
                        best_x = trial.copy()

        return best_x, best_y
