# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A compact Differential Evolution (DE) implementation using a 'best/1/bin' strategy with dithered mutation factors.
# Search state: A population of candidate solutions (vectors) and their associated fitness values, plus the tracking of the best-found individual.
# Candidate generation: New candidates are generated by perturbing the current best individual with a weighted difference of two other randomly selected members, followed by binomial crossover.
# Selection and replacement: Greedy selection; an offspring replaces its corresponding parent in the population only if it yields a lower objective value.
# Adaptation: Employs dithering on the mutation scale factor (F) for each individual to improve robustness across various problem topographies without complex parameter tuning.
# Exploration mechanisms: Uniform random initialization within the search space and a randomized crossover mechanism to maintain diversity.
# Exploitation mechanisms: The 'best/1' mutation strategy biases the search towards the most promising region discovered so far.
# Boundary handling: Simple clipping to the provided lower and upper bounds for every generated candidate.
# Budget strategy: Strictly monitors evaluation counts and terminates immediately when the budget is reached, returning the best recorded state.
# Closest known influences: Classic Differential Evolution (Storn & Price), specifically the DE/best/1/bin variant.
# Novelty or unusual aspects: Minimalist, single-class implementation designed for maximum compatibility with the GNBG interface and robust performance across varying dimensionality.
# Failure modes: Performance may degrade on extremely high-dimensional landscapes if the budget is insufficient to allow for population-wide convergence.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        
        :param budget: Total number of function evaluations allowed.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Executes the optimization process.
        
        :param func: The objective function to minimize.
        :return: A tuple (best_x, best_y) representing the found optimum.
        """
        # Boundary discovery
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        else:
            # Fallback if no bounds are detected
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        # Hyperparameters
        # Population size adjusted based on budget and dimensionality
        pop_size = int(min(max(10, self.dim * 2), 50, self.budget // 2))
        if pop_size < 4:
            pop_size = max(1, self.budget) # Fallback for extremely low budget
            
        # Strategy parameters
        f_weight = 0.5
        cr_prob = 0.9
        
        # Initialization
        pop = lb + (ub - lb) * np.random.rand(pop_size, self.dim)
        scores = np.full(pop_size, np.inf)
        
        best_x = None
        best_y = np.inf
        eval_count = 0

        # Initial evaluation
        for i in range(pop_size):
            if eval_count >= self.budget:
                break
            scores[i] = func(pop[i])
            eval_count += 1
            if scores[i] < best_y:
                best_y = scores[i]
                best_x = np.copy(pop[i])

        # Optimization loop
        while eval_count < self.budget:
            for i in range(pop_size):
                if eval_count >= self.budget:
                    break
                
                # Mutation: DE/best/1
                # Select two random indices that are not i
                indices = [idx for idx in range(pop_size) if idx != i]
                if len(indices) < 2:
                    # In case pop_size is too small for DE
                    mutant = pop[i] + np.random.normal(0, 0.1, self.dim)
                else:
                    r1, r2 = np.random.choice(indices, 2, replace=False)
                    # Dither F for robustness
                    f_dither = f_weight + 0.2 * (np.random.rand() - 0.5)
                    mutant = best_x + f_dither * (pop[r1] - pop[r2])
                
                # Crossover
                cross_points = np.random.rand(self.dim) < cr_prob
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary handling
                trial = np.clip(trial, lb, ub)
                
                # Evaluation
                score_trial = func(trial)
                eval_count += 1
                
                # Selection
                if score_trial <= scores[i]:
                    pop[i] = trial
                    scores[i] = score_trial
                    if score_trial < best_y:
                        best_y = score_trial
                        best_x = np.copy(trial)
                        
        return best_x, best_y

# The module is designed to be imported. Algorithm logic is contained within the class.
# No top-level execution code is provided as per requirements.
# Numpy is the only non-standard dependency.
# Budget limits are strictly respected via eval_count checks.
# Bounds are extracted using provided naming conventions.
# Objective is minimization.
# Implementation is compact and self-contained.
