# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A Multi-Restart Adaptive (1+1)-Evolution Strategy ((1+1)-ES).
# Search state: The current search center (curr_x, curr_y), the best solution found globally (best_x, best_y), and the current mutation strength (sigma).
# Candidate generation: A single offspring is generated by adding Gaussian noise to the current center, scaled by the adaptive sigma.
# Selection and replacement: Greedy (1+1) selection where the offspring replaces the current search center if its objective value is less than or equal to the parent's.
# Adaptation: The mutation strength (sigma) is adjusted continuously based on success or failure: it increases by a factor of 1.2 on success and decreases by 0.85 on failure, mimicking the 1/5th success rule.
# Exploration mechanisms: The algorithm uses periodic restarts from random uniform positions within the search bounds when local search stalls or converges.
# Exploitation mechanisms: The step-size contraction (sigma reduction) allows for high-precision local refinement once a promising region is found.
# Boundary handling: All candidate solutions are clipped to the hyper-rectangular search space defined by the problem bounds.
# Budget strategy: The algorithm tracks total evaluations and distributes them across successive restarts until the provided budget is completely consumed.
# Closest known influences: Rechenberg's Evolution Strategy, (1+1)-ES, and basic adaptive hill-climbing.
# Novelty or unusual aspects: Implementation is designed to be highly compact and robust across varying dimensions without requiring complex matrix decompositions or external dependencies.
# Failure modes: The search may be inefficient on extremely ill-conditioned landscapes where the optimal search direction is highly restricted and not aligned with the axes.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initialize the optimization algorithm.
        
        Args:
            budget (int): Total number of function evaluations allowed.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Execute the minimization process.
        
        Args:
            func (callable): Objective function to minimize.
            
        Returns:
            tuple: (best_x, best_y) representing the best found position and value.
        """
        # Determine search bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        else:
            # Default bounds if none are provided
            lb = np.zeros(self.dim)
            ub = np.ones(self.dim)

        # Handle scalar bounds by expanding them to vectors
        if lb.ndim == 0:
            lb = np.full(self.dim, lb)
        if ub.ndim == 0:
            ub = np.full(self.dim, ub)

        evals = 0
        best_x = None
        best_y = float('inf')

        # Global search loop (Multi-Restart)
        while evals < self.budget:
            # Initialize a new search point within bounds
            curr_x = np.random.uniform(lb, ub)
            curr_y = func(curr_x)
            evals += 1
            
            # Update global record
            if curr_y < best_y:
                best_y = curr_y
                best_x = curr_x.copy()
            
            if evals >= self.budget:
                break

            # Local search parameters for this restart
            # Initial sigma proportional to the average span of the dimensions
            sigma = 0.2 * np.mean(ub - lb)
            stagnant_counter = 0
            stagnant_limit = 20 + 2 * self.dim

            # Local search loop (Adaptive (1+1)-ES)
            while evals < self.budget:
                # Generate a candidate point using Gaussian mutation
                noise = np.random.normal(0, 1, self.dim)
                cand_x = curr_x + sigma * noise
                
                # Apply boundary constraints
                cand_x = np.clip(cand_x, lb, ub)
                
                cand_y = func(cand_x)
                evals += 1
                
                if cand_y <= curr_y:
                    # Success: Move to new point and expand search radius
                    curr_x, curr_y = cand_x, cand_y
                    sigma *= 1.2
                    stagnant_counter = 0
                    
                    if curr_y < best_y:
                        best_y = curr_y
                        best_x = curr_x.copy()
                else:
                    # Failure: Retain point and contract search radius
                    sigma *= 0.85
                    stagnant_counter += 1
                
                # Check for convergence or stagnation to trigger a restart
                if stagnant_counter > stagnant_limit or sigma < 1e-12 * np.mean(ub - lb):
                    break

        # Safety check for empty budget cases
        if best_x is None:
            best_x = np.random.uniform(lb, ub)
            best_y = float('inf')

        return best_x, best_y
