# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm implements a variant of Differential Evolution (DE) using a "best/1/bin" strategy. It is designed to be robust across dimensions and budget constraints by dynamically determining population size and employing randomized parameter variation for F and Cr.
# Search state: The state consists of a population of candidate vectors, their corresponding objective function values, and the current global best solution found.
# Candidate generation: New candidates are generated by taking the current best individual and adding a scaled difference between two other randomly selected population members (mutation). This is followed by a binomial crossover with the original parent.
# Selection and replacement: A greedy selection mechanism is used where a trial vector replaces its parent in the population only if it yields a lower (or equal) objective function value.
# Adaptation: The mutation scale factor (F) and crossover probability (Cr) are not fixed; instead, they are sampled from ranges (F in [0.4, 1.0], Cr in [0.7, 1.0]) to provide a mix of exploration and exploitation without needing complex history-based tuning.
# Exploration mechanisms: Random selection of vectors for mutation and the probabilistic crossover mechanism ensure that different regions of the search space are sampled, particularly early in the search.
# Exploitation mechanisms: The "DE/best/1" strategy biases the mutation towards the current global best, focusing the search on promising regions as the population converges.
# Boundary handling: Candidates are clipped to the specified lower and upper bounds using numpy.clip before evaluation.
# Budget strategy: The algorithm tracks evaluations meticulously. It initializes a population based on the available budget and dimension, then iterates through the population until the budget is exhausted.
# Closest known influences: Standard Differential Evolution (Storn & Price), specifically the DE/best/1/bin variant.
# Novelty or unusual aspects: The implementation is self-contained and prioritizes robustness and strict budget adherence over specific algorithmic complexity.
# Failure modes: On extremely high-dimensional landscapes with very tight budgets, the population may not converge. In highly plateaued landscapes, the differential vectors may become too small to progress.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    A robust black-box optimization algorithm using Differential Evolution (DE/best/1/bin).
    Designed to handle varying dimensions and budgets effectively.
    """
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        
        # Determine population size based on dimension and budget.
        # We aim for a balance: enough individuals for DE to work, but not so many
        # that we can't perform enough iterations.
        self.pop_size = max(min(10 * dim, 100), 5)
        
        # Adjust population size if the budget is extremely limited.
        if self.pop_size * 2 > self.budget:
            self.pop_size = max(self.budget // 2, 2)

    def __call__(self, func):
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Fallback for safety, though standard GNBG targets provide bounds.
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        evals = 0
        
        # Initialize population
        # Use a simple uniform random distribution across bounds.
        pop = lb + np.random.rand(self.pop_size, self.dim) * (ub - lb)
        fitness = np.zeros(self.pop_size)
        
        best_idx = 0
        for i in range(self.pop_size):
            if evals >= self.budget:
                # If budget is hit during initialization, return the best found so far.
                # fitness[:i] are the only valid ones.
                idx = np.argmin(fitness[:i])
                return pop[idx], fitness[idx]
            
            fitness[i] = func(pop[i])
            evals += 1
            if fitness[i] < fitness[best_idx]:
                best_idx = i

        # Main DE Loop
        while evals < self.budget:
            for i in range(self.pop_size):
                if evals >= self.budget:
                    break
                
                # Mutation: DE/best/1 strategy
                # Pick two random distinct indices excluding the current best (often better for exploitation)
                # or just any two indices.
                idxs = [idx for idx in range(self.pop_size) if idx != best_idx]
                if len(idxs) < 2:
                    # Fallback for tiny populations
                    r1, r2 = np.random.choice(self.pop_size, 2, replace=True)
                else:
                    r1, r2 = np.random.choice(idxs, 2, replace=False)
                
                # Randomized parameters to improve robustness
                F = np.random.uniform(0.4, 1.0)
                Cr = np.random.uniform(0.7, 1.0)
                
                # Create mutant vector
                mutant = pop[best_idx] + F * (pop[r1] - pop[r2])
                
                # Crossover: Binomial
                cross_points = np.random.rand(self.dim) < Cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary Handling: Clip to bounds
                trial = np.clip(trial, lb, ub)
                
                # Evaluation
                f_trial = func(trial)
                evals += 1
                
                # Selection
                if f_trial <= fitness[i]:
                    pop[i] = trial
                    fitness[i] = f_trial
                    if f_trial < fitness[best_idx]:
                        best_idx = i

        return pop[best_idx], fitness[best_idx]
