# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust Differential Evolution (DE) variant (DE/rand/1/bin) designed for general-purpose black-box minimization.
# Search state: A population of candidate solutions and their corresponding objective function values, along with the current best found solution.
# Candidate generation: New candidates are generated by selecting three distinct individuals from the population to create a mutant vector (base + F * (diff)), followed by binomial crossover with the current target vector.
# Selection and replacement: Offspring replace their corresponding target individuals in the population if they yield a lower or equal objective value (greedy selection).
# Adaptation: Uses static parameters (differential weight F=0.5, crossover probability CR=0.9) selected for their broad effectiveness across various optimization landscapes.
# Exploration mechanisms: Initialized with random uniform sampling; exploration is maintained by the differential mutation process which samples directions based on population diversity.
# Exploitation mechanisms: Crossover encourages local search around existing successful points; greedy selection ensures the population moves toward lower objective values.
# Boundary handling: Offspring coordinates are clipped to the specified lower and upper bounds before evaluation.
# Budget strategy: Strictly monitors evaluation counts, terminating the search process and returning the best found individual as soon as the budget is reached.
# Closest known influences: Classic Differential Evolution by Storn and Price.
# Novelty or unusual aspects: Minimalist, self-contained implementation optimized for the specific constraints of the GNBG benchmark interface.
# Failure modes: May converge prematurely on highly rugged landscapes if the population loses diversity before finding the global basin; efficiency may be lower on highly separable problems compared to coordinate-descent methods.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Differential Evolution (DE/rand/1/bin) implementation for black-box minimization.
    """
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        # Population size scaling: at least 5, up to 100, or limited by budget
        self.pop_size = max(5, min(budget // 2, 10 * dim, 100))
        # DE parameters
        self.F = 0.5   # Mutation scale factor
        self.CR = 0.9  # Crossover probability

    def __call__(self, func):
        # Extract bounds from the provided function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        else:
            # Fallback bounds if none are provided
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        eval_count = 0
        best_x = None
        best_y = float('inf')

        # Initialize population
        pop = lb + (ub - lb) * np.random.rand(self.pop_size, self.dim)
        scores = np.zeros(self.pop_size)

        # Initial evaluation loop
        for i in range(self.pop_size):
            if eval_count >= self.budget:
                break
            
            y = func(pop[i])
            scores[i] = y
            eval_count += 1

            if y < best_y:
                best_y = y
                best_x = np.copy(pop[i])

        # If budget exhausted during initialization, return current best
        if eval_count >= self.budget:
            return best_x, best_y

        # Evolution loop
        while eval_count < self.budget:
            for i in range(self.pop_size):
                if eval_count >= self.budget:
                    break

                # Mutation: Select 3 distinct candidates excluding the current index i
                indices = [idx for idx in range(self.pop_size) if idx != i]
                r1, r2, r3 = np.random.choice(indices, 3, replace=False)
                
                # Create mutant vector
                mutant = pop[r1] + self.F * (pop[r2] - pop[r3])
                
                # Boundary clipping
                mutant = np.clip(mutant, lb, ub)
                
                # Binomial Crossover
                cross_points = np.random.rand(self.dim) < self.CR
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial_x = np.where(cross_points, mutant, pop[i])
                
                # Selection
                trial_y = func(trial_x)
                eval_count += 1
                
                if trial_y <= scores[i]:
                    pop[i] = trial_x
                    scores[i] = trial_y
                    if trial_y < best_y:
                        best_y = trial_y
                        best_x = np.copy(trial_x)

        return best_x, best_y
