# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust implementation of Differential Evolution (DE) using the DE/best/1/bin strategy. 
# It includes a restart mechanism to handle potential stagnation and adapts to the dimensionality 
# of the problem by scaling the population size.
# Search state: The algorithm maintains a population of candidate solutions (vectors) and their 
# corresponding objective function values, along with the current global best found.
# Candidate generation: New candidates are generated by taking the current best individual 
# and adding a weighted difference between two randomly selected population members (mutation), 
# followed by a binomial crossover with the original parent.
# Selection and replacement: A greedy selection strategy is used where a trial vector replaces 
# its parent in the population only if it yields a lower or equal objective value.
# Adaptation: The population size is scaled based on dimension but capped by the budget. 
# Parameters F (scaling factor) and Cr (crossover probability) are kept within standard ranges 
# (F=0.5, Cr=0.9) to ensure stability across diverse black-box functions.
# Exploration mechanisms: Random vector selection for mutation and periodic restarts of the 
# population (while keeping the best known solution) if progress stalls.
# Exploitation mechanisms: The "DE/best" strategy focuses search around the current global 
# minimum, and the binomial crossover preserves successful components of existing solutions.
# Boundary handling: Candidates are clipped to the hypercube defined by the problem bounds 
# using np.clip to ensure feasibility.
# Budget strategy: The algorithm tracks evaluations strictly and terminates immediately 
# when the budget is exhausted. Evaluation checks are performed before every function call.
# Closest known influences: Storn & Price (Differential Evolution), standard 1/5th success rule 
# logic for restarts (simplified).
# Novelty or unusual aspects: Dynamic population sizing relative to budget/dimension and 
# an automatic restart trigger when the population variance falls below a threshold.
# Failure modes: May struggle with extremely high-dimensional landscapes where the budget 
# is too small to form a representative population, or highly discretized/flat landscapes.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        :param budget: Maximum number of function evaluations.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        
        # Adaptive population size: usually between 10 and 100
        self.pop_size = int(min(max(10, 2 * dim), 100))
        # Ensure pop_size doesn't exceed a significant fraction of the budget
        if self.pop_size * 2 > self.budget:
            self.pop_size = max(4, self.budget // 10)
            
        self.eval_count = 0
        self.best_x = None
        self.best_y = float('inf')

    def _get_bounds(self, func):
        """Extracts lower and upper bounds from the function object."""
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb, ub = func.lower, func.upper
        elif hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            raise AttributeError("Function object does not provide bounds.")
            
        # Ensure bounds are numpy arrays
        return np.asarray(lb, dtype=float), np.asarray(ub, dtype=float)

    def __call__(self, func):
        """
        Executes the minimization.
        :param func: The objective function to minimize.
        :return: (best_x, best_y)
        """
        lb, ub = self._get_bounds(func)
        
        # Initial Population
        pop = np.random.uniform(lb, ub, (self.pop_size, self.dim))
        fitness = np.full(self.pop_size, float('inf'))
        
        # Initial Evaluation
        for i in range(self.pop_size):
            if self.eval_count >= self.budget:
                break
            fitness[i] = func(pop[i])
            self.eval_count += 1
            if fitness[i] < self.best_y:
                self.best_y = fitness[i]
                self.best_x = pop[i].copy()
                
        # DE Parameters
        F = 0.5  # Differential weight
        Cr = 0.9 # Crossover probability
        
        # Main Evolution Loop
        while self.eval_count < self.budget:
            # Check for stagnation / convergence to trigger a restart
            if np.std(fitness) < 1e-12 * (abs(self.best_y) + 1e-12):
                # Restart population but keep the best solution
                pop = np.random.uniform(lb, ub, (self.pop_size, self.dim))
                pop[0] = self.best_x.copy()
                for i in range(self.pop_size):
                    if self.eval_count >= self.budget: break
                    fitness[i] = func(pop[i])
                    self.eval_count += 1
                if self.eval_count >= self.budget: break

            for i in range(self.pop_size):
                if self.eval_count >= self.budget:
                    break
                
                # Mutation: DE/best/1
                # Select two random indices that are not i
                idxs = [idx for idx in range(self.pop_size) if idx != i]
                r1, r2 = np.random.choice(idxs, 2, replace=False)
                
                # Mutant vector
                mutant = self.best_x + F * (pop[r1] - pop[r2])
                mutant = np.clip(mutant, lb, ub)
                
                # Crossover: Binomial
                cross_points = np.random.rand(self.dim) < Cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Selection
                f_trial = func(trial)
                self.eval_count += 1
                
                if f_trial <= fitness[i]:
                    pop[i] = trial
                    fitness[i] = f_trial
                    if f_trial < self.best_y:
                        self.best_y = f_trial
                        self.best_x = trial.copy()
                        
        return self.best_x, self.best_y

# The module is designed to be imported. The harness provides the seed.
