# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A (1+1) Evolution Strategy using Rechenberg's 1/5th success rule for step-size adaptation.
# Search state: The current best candidate vector (best_x), its objective value (best_y), the current mutation strength (sigma), and a sliding window of recent success/failure results.
# Candidate generation: New candidates are generated by adding Gaussian noise (scaled by sigma) to the current best point.
# Selection and replacement: Greedy selection is used; a candidate replaces the current best if its objective value is strictly lower.
# Adaptation: The mutation radius (sigma) is adjusted every 'window_size' iterations. If the success rate is above 20%, sigma increases to explore further; if below 20%, sigma decreases to focus on local exploitation.
# Exploration mechanisms: Initial sampling is uniform across the search space. High success rates trigger sigma expansion, allowing the search to jump out of small local minima.
# Exploitation mechanisms: Failure to improve results in a contraction of sigma, allowing for fine-grained convergence on the local optimum.
# Boundary handling: Candidates are clipped to the hypercube defined by the problem bounds before evaluation.
# Budget strategy: The algorithm runs in a single loop, evaluating one candidate per iteration until the provided budget is exhausted.
# Closest known influences: Rechenberg's Evolution Strategy, specifically the (1+1)-ES with the 1/5th success rule.
# Novelty or unusual aspects: The implementation uses a simplified, robust adaptation logic tailored for black-box constraints without needing complex covariance matrix updates.
# Failure modes: May struggle with highly non-separable or extremely rugged landscapes where the 1/5th rule might prematurely converge or oscillate.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the (1+1)-ES optimizer.
        :param budget: Total number of function evaluations allowed.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.eval_count = 0

    def __call__(self, func):
        """
        Executes the minimization search.
        :param func: The objective function to minimize.
        :return: (best_x, best_y)
        """
        # Retrieve bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Fallback for unexpected interface
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        range_width = ub - lb
        
        # Initialization: Start at a random position within bounds
        best_x = lb + np.random.rand(self.dim) * range_width
        best_y = func(best_x)
        self.eval_count += 1
        
        # Initial sigma: 10% of the mean range width
        sigma = np.mean(range_width) * 0.1
        
        # Adaptation parameters
        # We adjust sigma every 'window_size' evaluations
        window_size = max(10, self.dim * 2)
        success_count = 0
        iteration = 0

        # Optimization loop
        while self.eval_count < self.budget:
            iteration += 1
            
            # Generate candidate using Gaussian mutation
            noise = np.random.standard_normal(self.dim)
            candidate = best_x + sigma * noise
            
            # Boundary handling: Clip to feasible region
            candidate = np.clip(candidate, lb, ub)
            
            # Evaluation
            y = func(candidate)
            self.eval_count += 1
            
            # Selection: Greedy update
            if y < best_y:
                best_y = y
                best_x = candidate
                success_count += 1
            
            # Adaptation: Rechenberg's 1/5th success rule
            if iteration % window_size == 0:
                success_rate = success_count / window_size
                if success_rate > 0.2:
                    # High success: increase search radius
                    sigma *= 1.5
                elif success_rate < 0.2:
                    # Low success: decrease search radius
                    sigma *= 0.8
                
                # Reset success counter for next window
                success_count = 0
                
            # Safety break if sigma becomes effectively zero
            if sigma < 1e-15:
                # Re-initialize sigma to allow potential escape if budget remains
                sigma = np.mean(range_width) * 0.01

        return best_x, best_y

# The harness will instantiate and call this class.
# The random seed is managed externally.
