import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact, budget-aware black-box minimizer for
# bounded box constraints using a hybrid strategy: global exploration by random
# sampling, followed by a local derivative-free search around the current best
# using coordinate probes and stochastic step-size adaptation.
# Search state: The algorithm tracks the current best point x_best and its objective
# value y_best, plus a population of candidate points in the current local region.
# Candidate generation: Candidates are generated by (1) uniform random sampling
# within bounds for exploration, and (2) local mutations from x_best using
# coordinate-wise Gaussian perturbations scaled by a step size sigma.
# Selection and replacement: For each batch, objective values are computed (one at
# most per candidate) and the best-scoring candidate replaces x_best. Local
# candidates that improve are kept conceptually via updating x_best; sigma is
# adjusted based on whether improvements occurred.
# Adaptation: Sigma (the mutation scale) is adapted using a success counter:
# improvements increase sigma slightly, stagnation decreases it, ensuring robust
# behavior across different dimensions and landscapes.
# Exploration mechanisms: A fraction of the budget is devoted to global random
# sampling; additionally, occasional large perturbations are used to escape
# stagnation during the local phase.
# Exploitation mechanisms: The local phase uses anisotropic coordinate probes
# (sign-flipped perturbations and coordinate-wise offsets) centered at x_best,
# which improves efficiency without gradients.
# Boundary handling: All candidates are clipped to the feasible bounds before
# evaluation. This guarantees feasibility and avoids boundary-violating points.
# Budget strategy: The algorithm uses at most the provided evaluation budget by
# counting every objective call and stopping when the remaining budget is exhausted.
# Closest known influences: This resembles a lightweight evolution strategy / CMA-like
# local search with step-size adaptation, adapted to a strict budget and simple
# coordinate probes, with early random global exploration.
# Novelty or unusual aspects: The implementation is deliberately compact yet robust:
# it uses a deterministic budget-aware batching scheme, coordinate-wise local probes,
# and a success-based sigma scheduler, all without any external dependencies.
# Failure modes: If the objective is extremely noisy or highly ill-conditioned,
# the success-based adaptation can mis-tune sigma; clipping can also saturate
# searches at the bounds. In very high dimensions with tiny feasible optima,
# uniform exploration may be insufficient within limited budgets.
# ALGORITHM_ANALYSIS_NOTE_END


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        # ---- Bounds handling ----
        lb = None
        ub = None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds") and hasattr(func.bounds, "lb") and hasattr(func.bounds, "ub"):
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)

        if lb is None or ub is None:
            raise ValueError("Function must provide bounds via func.lower/func.upper or func.bounds.lb/func.bounds.ub.")

        lb = np.broadcast_to(lb, (self.dim,)).astype(float, copy=False)
        ub = np.broadcast_to(ub, (self.dim,)).astype(float, copy=False)
        span = ub - lb
        # Handle degenerate bounds safely
        span = np.where(span > 0, span, 1.0)

        # ---- Budget-aware evaluation helper ----
        evals = 0

        def eval_one(x):
            nonlocal evals
            if evals >= self.budget:
                # Hard stop: do not exceed budget.
                return np.inf
            # Ensure vector type
            x = np.asarray(x, dtype=float).reshape(self.dim)
            # Clip to bounds for feasibility
            x = np.minimum(np.maximum(x, lb), ub)
            y = func(x)
            evals += 1
            return float(y)

        # ---- Initialization: start with one random point + global exploration ----
        # A small initial probe around a random point helps stability.
        x_best = None
        y_best = np.inf

        def sample_uniform():
            r = np.random.random(self.dim)
            return lb + r * (ub - lb)

        # Number of points to sample globally: adaptive to budget/dimension
        # Keep it small enough to leave budget for local improvement.
        # Minimum of 1 exploration eval; maximum 40% of budget.
        frac = 0.4
        n_global = max(1, min(self.budget, int(max(2, self.dim * 2)), int(self.budget * frac)))
        # First random point always considered
        for _ in range(min(n_global, self.budget)):
            x = sample_uniform()
            y = eval_one(x)
            if y < y_best:
                x_best, y_best = x, y

        if evals >= self.budget:
            return np.array(x_best, dtype=float, copy=True), float(y_best)

        # ---- Local search with step-size adaptation ----
        # Initial sigma based on average span; clamp to reasonable scale.
        avg_span = float(np.mean(span))
        sigma = 0.3 * avg_span / max(1.0, np.sqrt(self.dim))
        sigma = max(1e-12, float(sigma))

        # Success-based adaptation targets ~10-30% improvement rate locally.
        # Use a small window in a budget-safe way.
        local_evals_remaining = self.budget - evals

        # Choose local candidate batch size:
        # - If budget is small: keep batch small.
        # - Otherwise: batch up a few candidates to improve throughput.
        max_batch = 8
        batch = min(max_batch, max(2, int(np.sqrt(self.dim)) + 1))
        batch = min(batch, local_evals_remaining) if local_evals_remaining > 0 else batch

        # Exploration probability during local phase to escape stagnation.
        # Increases slightly with dimension and decreases as sigma shrinks.
        stagnation = 0
        success_counter = 0
        success_total = 0

        while evals < self.budget:
            # If batch exceeds remaining budget, shrink.
            b = min(batch, self.budget - evals)
            if b <= 0:
                break

            # Create candidate points around x_best.
            candidates = []
            # We will generate b candidates. Use a mix of:
            # - coordinate probes
            # - Gaussian perturbations
            # - occasional large jumps (escape)
            prob_escape = 0.15 + 0.05 * (self.dim / (self.dim + 5.0))

            # Coordinate probes: try a few coordinates deterministically.
            # Pick indices spread over dimensions for robustness.
            k_probe = min(self.dim, max(1, b // 2))
            if k_probe > 0:
                # Equally spaced indices
                idxs = (np.linspace(0, self.dim - 1, num=k_probe).astype(int) if self.dim > 1
                        else np.array([0], dtype=int))
            else:
                idxs = np.array([], dtype=int)

            # Always include at least one Gaussian candidate
            # and one sign-flipped coordinate candidate when possible.
            for i in range(b):
                x = np.array(x_best, copy=True)
                # Decide mechanism
                if i < len(idxs) and sigma > 0:
                    j = int(idxs[i])
                    # Sign-flipped coordinate probe with scaled step
                    s = 1.0 if (np.random.random() < 0.5) else -1.0
                    step = s * sigma * (0.5 + np.random.random())
                    x[j] = x[j] + step
                else:
                    # Gaussian mutation
                    # Add slight axis bias by scaling with per-dim random factors.
                    if np.random.random() < prob_escape:
                        # Escape jump: bigger perturbation
                        esc_scale = 1.5 + 2.0 * np.random.random()
                        y = np.random.normal(0.0, 1.0, size=self.dim)
                        x = x_best + esc_scale * sigma * (0.5 + np.random.random()) * y
                    else:
                        g = np.random.normal(0.0, 1.0, size=self.dim)
                        # Slightly anisotropic scaling for robustness
                        scale = 0.7 + 0.6 * np.random.random(self.dim)
                        x = x_best + sigma * (scale * g)

                candidates.append(x)

            # Evaluate candidates
            improved = False
            best_local_x = None
            best_local_y = y_best
            for x in candidates:
                if evals >= self.budget:
                    break
                y = eval_one(x)
                if y < best_local_y:
                    best_local_y = y
                    best_local_x = np.asarray(x, dtype=float).reshape(self.dim)
                    improved = True

            # Update best and adapt sigma
            if improved and best_local_x is not None:
                if best_local_y < y_best:
                    x_best, y_best = best_local_x, best_local_y
                success_counter += 1
                success_total += 1
                stagnation = 0
                # Increase sigma slightly to keep exploration if making progress
                sigma *= 1.08
            else:
                stagnation += 1
                success_total += 1
                # Decrease sigma on stagnation
                sigma *= 0.82

            # Keep sigma within feasible scale (avoid collapsing to zero or exploding)
            sigma_min = 1e-12
            sigma_max = 1.0 * avg_span  # cannot sensibly exceed span scale
            sigma = float(min(sigma_max, max(sigma_min, sigma)))

            # If repeated stagnation, add a small random restart around best (still budget-safe)
            if stagnation >= 3 and evals < self.budget:
                # Small restart uses remaining evals; only one or two evals.
                n_restart = min(2, self.budget - evals)
                for _ in range(n_restart):
                    x = x_best + np.random.normal(0.0, 1.0, size=self.dim) * (0.5 * sigma + 0.1 * avg_span)
                    # clipping in eval_one
                    y = eval_one(x)
                    if y < y_best:
                        x_best, y_best = np.asarray(x, dtype=float).reshape(self.dim), y
                        sigma *= 1.05
                        stagnation = 0
                        break

        return np.array(x_best, dtype=float, copy=True), float(y_best)
