# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact derivative-free black-box minimizer
# for the GNBG benchmark setting. It uses a repeatedly-refined population of
# candidate points and alternates between exploration (random directions
# around the current best) and exploitation (local, scale-adapting search).
# Search state: The algorithm maintains a current best point x_best and its
# objective value y_best, plus a step-size (sigma) that controls how far
# candidate points may move each iteration. It also tracks the remaining
# evaluation budget.
# Candidate generation: At each iteration, it samples a small set of candidates
# from a Gaussian around x_best using the current sigma. It also includes a
# few "structured" candidates generated by perturbing coordinates in random
# directions to improve coverage in higher dimensions.
# Selection and replacement: All sampled candidates are evaluated, then the best
# among them replaces the global best if it improves y_best. The population
# does not need to persist; instead, each iteration proposes candidates around
# the latest best (a hall-of-mirrors but budget-safe variant of local search).
# Adaptation: If the iteration finds an improvement, sigma is slightly increased
# (to move faster into promising regions). If no improvement occurs, sigma
# is decreased (to refine locally). This is inspired by step-size control in
# evolution strategies.
# Exploration mechanisms: Random Gaussian sampling plus occasional coordinate-
# oriented perturbations prevent premature convergence.
# Exploitation mechanisms: The search is centered around x_best, so successful
# improvements naturally drive the sampling region to exploit local basins.
# Boundary handling: Proposed points are clipped to the given bound box on every
# evaluation candidate, ensuring feasibility at all times.
# Budget strategy: The algorithm strictly limits the number of objective calls
# to the provided budget. It computes the maximum number of iterations from the
# budget and a per-iteration batch size, and then uses any leftover budget for
# a final partial batch.
# Closest known influences: The design is a small, readable blend of
# (μ+1)/(1+1)-ES ideas with adaptive step-size and bounded sampling.
# Novelty or unusual aspects: It uses a hybrid candidate set (Gaussian plus
# occasional coordinate steps) while staying compact and robust across dimensions.
# Failure modes: If the objective is extremely noisy or the optimum is very
# narrow, clipping plus simple step adaptation may struggle. In very high
# dimensions, limited budget can still lead to slow progress; the algorithm
# mitigates this by varying candidate directions and adapting sigma.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        # ---- Bounds handling (as required) ----
        lb = None
        ub = None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds") and hasattr(func.bounds, "lb") and hasattr(
            func.bounds, "ub"
        ):
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)

        if lb is None or ub is None:
            raise AttributeError(
                "Objective must provide bounds via func.lower/func.upper or "
                "func.bounds.lb/func.bounds.ub."
            )

        # Ensure shapes are compatible with dim
        if lb.shape == () and self.dim > 1:
            lb = np.full(self.dim, float(lb))
        if ub.shape == () and self.dim > 1:
            ub = np.full(self.dim, float(ub))
        lb = np.broadcast_to(lb, (self.dim,)).astype(float)
        ub = np.broadcast_to(ub, (self.dim,)).astype(float)

        # Protect against inverted bounds
        lo = np.minimum(lb, ub)
        hi = np.maximum(lb, ub)

        # ---- Budget-safe evaluation wrapper ----
        remaining = self.budget
        if remaining <= 0:
            # Degenerate case: no evaluations possible; return center of bounds.
            x0 = 0.5 * (lo + hi)
            return x0, float("inf")

        def clip(x):
            return np.minimum(np.maximum(x, lo), hi)

        def eval_one(x):
            nonlocal remaining
            if remaining <= 0:
                # Should not happen if budgeting is correct.
                return float("inf")
            remaining -= 1
            return float(func(x))

        # ---- Initialization ----
        # Use a midpoint start and a couple of random points to find a good anchor.
        x_best = clip(0.5 * (lo + hi))
        y_best = eval_one(x_best)

        # Small, budget-dependent warmup
        warmup = min(3, self.budget - 1)
        if warmup > 0:
            # Random uniform within bounds
            for _ in range(warmup):
                xr = lo + np.random.rand(self.dim) * (hi - lo)
                yr = eval_one(xr)
                if yr < y_best:
                    x_best, y_best = xr, yr

        # Step size initialization: scaled by the box size
        box = hi - lo
        # Avoid zero box lengths: set a minimal scale per dimension
        box_safe = np.where(box > 0, box, 1.0)
        sigma = 0.25 * np.mean(box_safe)
        sigma = max(sigma, 1e-12)

        # Iteration batch size: propose several candidates per iteration
        # Keep it small for budget discipline and robustness.
        batch = min(max(6, self.dim), 24)
        # We'll use leftover budget efficiently with partial final batches.
        # The number of evaluations per iteration equals batch (since we already used warmup evaluations).

        # Budget left after initialization
        eval_left = remaining
        if eval_left <= 0:
            return x_best, y_best

        # Determine number of full iterations and whether there is a partial last iteration
        full_iters = eval_left // batch
        rem = eval_left - full_iters * batch

        # Candidate generation: Gaussian around x_best + occasional coordinate steps
        # Exploitation/exploration controlled by sigma.
        # Adaptation uses success indicator.
        for _ in range(int(full_iters)):
            # Sample candidates around x_best
            # Gaussian: better global exploration then local exploitation as sigma adapts.
            Z = np.random.randn(batch, self.dim)
            X = x_best + sigma * Z

            # Occasional coordinate-oriented candidates for better directional coverage
            # (helps when sigma is small and Gaussian may be too diffuse or too correlated).
            # We'll replace some candidates with coordinate perturbations.
            # Number of coordinate candidates depends on dimension but stays small.
            coord_k = min(max(1, self.dim // 5), batch)
            if coord_k > 0:
                idxs = np.random.choice(batch, size=coord_k, replace=False)
                # random coordinates per candidate
                for bi in idxs:
                    j = np.random.randint(0, self.dim)
                    step = sigma * (0.5 + np.random.rand())  # positive scale; sign via random coin
                    if np.random.rand() < 0.5:
                        step = -step
                    X[bi] = x_best
                    X[bi, j] = x_best[j] + step

            # Clip to bounds and evaluate
            X = clip(X)
            # Track best in this batch
            y_local_best = y_best
            x_local_best = x_best

            for bi in range(batch):
                yi = eval_one(X[bi])
                if yi < y_local_best:
                    y_local_best = yi
                    x_local_best = X[bi]

            # Adaptation: if success, increase sigma slightly; else decrease.
            if y_local_best < y_best:
                x_best, y_best = x_local_best, y_local_best
                sigma *= 1.12
            else:
                sigma *= 0.83

            # Prevent sigma from vanishing too fast or exploding
            sigma = float(np.clip(sigma, 1e-12, 2.0 * np.mean(box_safe) if np.any(box_safe) else 1.0))

        # Final partial batch if budget remains
        if rem > 0:
            batch2 = int(rem)
            Z = np.random.randn(batch2, self.dim)
            X = x_best + sigma * Z

            coord_k = min(max(1, self.dim // 5), batch2)
            if coord_k > 0:
                idxs = np.random.choice(batch2, size=coord_k, replace=False)
                for bi in idxs:
                    j = np.random.randint(0, self.dim)
                    step = sigma * (0.5 + np.random.rand())
                    if np.random.rand() < 0.5:
                        step = -step
                    X[bi] = x_best
                    X[bi, j] = x_best[j] + step

            X = clip(X)
            y_local_best = y_best
            x_local_best = x_best

            for bi in range(batch2):
                yi = eval_one(X[bi])
                if yi < y_local_best:
                    y_local_best = yi
                    x_local_best = X[bi]

            if y_local_best < y_best:
                x_best, y_best = x_local_best, y_local_best

        return x_best, y_best
