# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact black-box minimization algorithm
# (derivative-free, population-based) for the GNBG-style benchmark. It uses
# a small population of candidate solutions and an adaptive strategy that
# alternates between exploration (broad sampling) and exploitation (local
# refinement) while respecting a strict evaluation budget.
#
# Search state: The algorithm maintains a population of points, their objective
# values, and the best-so-far solution. It also keeps a step size ("sigma")
# that is adapted based on whether recent iterations improve the best value.
#
# Candidate generation: Each iteration generates new candidates by sampling
# Gaussian perturbations around selected parent points. With some probability
# it samples globally (centered around the current best with a larger sigma)
# to escape stagnation.
#
# Selection and replacement: For each new candidate, its objective is evaluated.
# If it improves over the current worst individual in the population, it replaces
# that individual (elitist replacement). The global best is updated whenever a
# better point is found.
#
# Adaptation: Sigma shrinks when the best improves and grows (slightly) when no
# improvement is observed for a while, balancing local search and global exploration.
#
# Exploration mechanisms: Occasional larger-variance sampling and multi-parent
# generation increase the chance of leaving local basins.
#
# Exploitation mechanisms: Most offspring are generated by perturbing top-ranking
# parents with smaller sigma, effectively performing local refinement around
# promising regions.
#
# Boundary handling: Samples are clipped to the provided bounds to ensure all
# evaluations remain feasible.
#
# Budget strategy: The algorithm computes the maximum number of evaluations from
# the provided budget and ensures it never calls the objective more times than
# allowed. It uses the budget to limit both the initial population evaluation and
# subsequent iterations.
#
# Closest known influences: The design resembles simplified evolution strategies /
# CMA-ES-like ideas (population + sigma adaptation + elitist selection) but is
# kept intentionally lightweight and implementation-robust for varying dimensions.
#
# Novelty or unusual aspects: The code uses a mix of local and occasional
# quasi-global sampling with step-size adaptation driven by best improvement
# events, without any covariance matrix estimation.
#
# Failure modes: In very high dimensions or extremely rugged landscapes, the
# limited population size and simple adaptation may converge slowly or get stuck.
# If bounds are extremely narrow or the budget is tiny, it may rely mostly on
# initial sampling and greedy improvements.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim

        # Read bounds from func (supporting two common conventions).
        lb = None
        ub = None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds") and func.bounds is not None:
            b = func.bounds
            if hasattr(b, "lb") and hasattr(b, "ub"):
                lb = np.asarray(b.lb, dtype=float)
                ub = np.asarray(b.ub, dtype=float)

        if lb is None or ub is None:
            raise AttributeError(
                "Objective must provide bounds via func.lower/func.upper or func.bounds.lb/func.bounds.ub"
            )

        if lb.shape == ():
            lb = np.full(dim, float(lb))
        if ub.shape == ():
            ub = np.full(dim, float(ub))

        lb = np.asarray(lb, dtype=float).reshape(dim)
        ub = np.asarray(ub, dtype=float).reshape(dim)

        # Ensure feasible ordering.
        if np.any(ub < lb):
            raise ValueError("Invalid bounds: require ub >= lb elementwise.")

        # Strictly enforce budget.
        max_evals = max(0, self.budget)
        if max_evals == 0:
            # No evaluations allowed; return a deterministic feasible point.
            x0 = lb.copy()
            y0 = np.inf
            return x0, y0

        eval_count = 0

        def clip(x):
            return np.minimum(ub, np.maximum(lb, x))

        def eval_obj(x):
            nonlocal eval_count
            if eval_count >= max_evals:
                # Should never happen if logic is correct; guard just in case.
                return np.inf
            y = func(x)
            eval_count += 1
            return float(y)

        # Initialize sigma based on bounds scale.
        scale = ub - lb
        # Avoid zero scale producing sigma==0 everywhere.
        base_range = float(np.max(scale)) if np.max(scale) > 0 else 1.0
        sigma0 = 0.25 * base_range / max(1.0, (dim ** 0.5))
        sigma0 = max(sigma0, 1e-12)

        # Choose population size: small for speed, larger for robustness.
        # Must not exceed budget.
        pop_size = int(min(max(4, 2 + dim // 2), max_evals))
        # If budget is extremely small, adjust.
        pop_size = max(1, pop_size)

        # Create initial population: uniform samples + mid-point.
        mid = 0.5 * (lb + ub)
        pop = np.empty((pop_size, dim), dtype=float)
        # Always include midpoint for stability when possible.
        if pop_size >= 1:
            pop[0] = clip(mid)

        for i in range(1, pop_size):
            r = np.random.rand(dim)
            pop[i] = clip(lb + r * (ub - lb))

        # Evaluate initial population.
        y = np.empty(pop_size, dtype=float)
        for i in range(pop_size):
            y[i] = eval_obj(pop[i])

        best_idx = int(np.argmin(y))
        best_x = pop[best_idx].copy()
        best_y = float(y[best_idx])

        # Candidate generation and evolution.
        # Sigma adapts based on improvement frequency.
        sigma = sigma0
        no_improve_steps = 0

        # How many candidates to generate per outer loop:
        # We'll generate in chunks of at most remaining budget.
        # Each candidate evaluation potentially replaces the worst in population.
        while eval_count < max_evals:
            remaining = max_evals - eval_count
            # Per generation, try a small batch for better throughput.
            batch = int(min(remaining, max(1, pop_size // 2)))

            # Rank parents by objective (smaller is better).
            order = np.argsort(y)
            parents = order[: max(2, min(pop_size, 3 + dim // 10))]

            # Determine exploration probability: higher when stuck.
            # Keeps exploitation mostly on top parents.
            stuck_ratio = min(5.0, no_improve_steps / 5.0)
            p_explore = 0.15 + 0.15 * (stuck_ratio / 5.0)  # in [0.15, ~0.30]

            for _ in range(batch):
                if eval_count >= max_evals:
                    break

                # Select parent: either top-k or best for exploitation.
                if np.random.rand() < 0.7:
                    p = pop[int(np.random.choice(parents))]
                else:
                    p = best_x

                # Occasionally increase variance for exploration.
                if np.random.rand() < p_explore:
                    # Larger step: encourage leaving the basin.
                    local_sigma = sigma * (1.5 + 2.0 * np.random.rand())
                    center = p
                else:
                    # Local refinement around parent.
                    local_sigma = sigma * (0.5 + 0.7 * np.random.rand())
                    center = p

                # Directional / isotropic perturbation.
                # To reduce random walk in higher dimensions, mix in scaled
                # difference from population best.
                if pop_size >= 2 and np.random.rand() < 0.5:
                    # Compute a small correlated drift towards best point.
                    # Choose a random other individual.
                    j = int(np.random.randint(0, pop_size))
                    drift = (best_x - pop[j])
                    # Normalize drift scale to avoid too aggressive moves.
                    drift_norm = float(np.linalg.norm(drift))
                    if drift_norm > 0:
                        drift = drift / drift_norm
                    else:
                        drift = np.zeros(dim, dtype=float)
                    direction = drift
                    x_new = center + direction * (0.25 * local_sigma) + np.random.randn(dim) * local_sigma
                else:
                    x_new = center + np.random.randn(dim) * local_sigma

                x_new = clip(x_new)
                y_new = eval_obj(x_new)

                # Elitist replacement: replace current worst if improved.
                worst_idx = int(np.argmax(y))
                if y_new < y[worst_idx]:
                    pop[worst_idx] = x_new
                    y[worst_idx] = y_new
                    # Update global best if needed.
                    if y_new < best_y:
                        best_y = y_new
                        best_x = x_new.copy()
                        no_improve_steps = 0
                        # Shrink sigma on success for exploitation.
                        sigma *= 0.85
                    else:
                        no_improve_steps += 1
                else:
                    no_improve_steps += 1

            # If no improvement for a while, expand sigma to explore.
            if no_improve_steps >= 3:
                # Gentle growth, bounded to avoid exploding.
                sigma *= 1.05 + 0.02 * min(5.0, no_improve_steps)
                sigma = min(sigma, 2.0 * base_range / max(1.0, (dim ** 0.3)))
                # Cap stagnation growth pressure
                no_improve_steps = min(no_improve_steps, 50)

            # If sigma got extremely small, re-inject some exploration.
            if sigma <= 1e-14:
                sigma = sigma0

        return best_x, best_y
