# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact, budget-aware black-box minimization algorithm
# (derivative-free) using a mixture of coordinate-wise stochastic local search and
# global random restarts. It maintains a small population of candidate solutions, evaluates
# them with strict budget accounting, and iteratively refines the best solutions.
# Search state: The algorithm keeps a population of points (xs) and their objective values (ys),
# plus the current global best (best_x, best_y). It also tracks a step size (sigma) used to
# generate perturbations.
# Candidate generation: New candidates are generated by either (1) random Gaussian perturbations
# around the current best (and around some population members), (2) coordinate-wise moves
# that update one dimension at a time with adaptive magnitudes, or (3) occasional random
# restarts by sampling uniformly in bounds.
# Selection and replacement: After each batch of evaluations, it merges new candidates into the
# population, then keeps the best individuals (elitism) to form the next generation.
# Adaptation: The step size sigma is reduced on improvement (exploitation) and mildly increased
# on repeated stagnation to encourage exploration.
# Exploration mechanisms: Random perturbations, coordinate-wise exploration, and periodic
# uniform restarts provide coverage of the search space.
# Exploitation mechanisms: Strong perturbations centered at the incumbent best and smaller,
# adaptive coordinate refinements focus the search around promising regions.
# Boundary handling: Any candidate generated outside the bounds is clipped to the nearest
# valid point within [lb, ub]. This ensures feasibility for all objective evaluations.
# Budget strategy: The algorithm strictly tracks the remaining evaluation budget. Each objective
# call increments a counter; no further calls are made once the budget is exhausted. The
# internal batching adjusts to the remaining budget.
# Closest known influences: The design loosely resembles (and combines ideas from) CMA-ES-like
# restart/step adaptation and DE-style elitist replacement, while remaining much simpler and
# fully standard-library + NumPy based.
# Novelty or unusual aspects: It mixes a small elite population with coordinate-wise moves and
# a restart mechanism in a compact form, and uses deterministic evaluation counting so it
# reliably respects the budget.
# Failure modes: If the search space is extremely rugged/highly multimodal, the simple
# coordinate/local sampling may stagnate; the restart and step adaptation mitigate this but
# cannot guarantee global optimality within limited budgets.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim
        budget = self.budget

        # ---- Read bounds from func ----
        lb = None
        ub = None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds"):
            b = func.bounds
            if hasattr(b, "lb") and hasattr(b, "ub"):
                lb = np.asarray(b.lb, dtype=float)
                ub = np.asarray(b.ub, dtype=float)

        if lb is None or ub is None:
            raise AttributeError("Could not read bounds: expected func.lower/func.upper or func.bounds.lb/ub.")
        if lb.shape == ():
            lb = np.full(dim, float(lb))
        if ub.shape == ():
            ub = np.full(dim, float(ub))
        lb = lb.reshape(-1)
        ub = ub.reshape(-1)
        if lb.size != dim or ub.size != dim:
            raise ValueError("Bounds dimensionality does not match dim.")

        # Ensure lb <= ub
        lb2 = np.minimum(lb, ub)
        ub2 = np.maximum(lb, ub)
        lb, ub = lb2, ub2

        # Helper: clip to bounds
        def clip(x):
            return np.minimum(ub, np.maximum(lb, x))

        # ---- Budget accounting ----
        evals = 0

        def eval_obj(x):
            nonlocal evals
            if evals >= budget:
                # Safety: never exceed budget
                return np.inf
            evals += 1
            return float(func(x))

        # If budget is 0, return something feasible (no evals possible)
        if budget <= 0:
            # Choose mid-point
            best_x = clip((lb + ub) * 0.5)
            return best_x, float("inf")

        # ---- Initialization ----
        rng = np.random

        # Step scale: use bounds range or 1 if degenerate
        span = ub - lb
        span_safe = np.where(span > 0, span, 1.0)
        base_sigma = 0.25 * span_safe  # initial exploration radius

        # Population size: small for compactness; scale with dim but cap
        pop_size = int(np.clip(6 + dim // 2, 6, 20))
        elite_size = int(np.clip(max(2, pop_size // 2), 2, pop_size))

        # Generate initial candidates uniformly
        xs = []
        ys = []
        initial_count = min(pop_size, budget)  # evaluations used here

        for _ in range(initial_count):
            x0 = lb + rng.random(dim) * (ub - lb)
            y0 = eval_obj(x0)
            xs.append(x0)
            ys.append(y0)

        xs = np.asarray(xs, dtype=float)
        ys = np.asarray(ys, dtype=float)

        best_idx = int(np.argmin(ys))
        best_x = xs[best_idx].copy()
        best_y = float(ys[best_idx])

        # ---- Main loop ----
        # We'll do iterative generations with variable batch size based on remaining budget.
        # Heuristics:
        # - With probability, explore around best using gaussian steps
        # - Otherwise, do coordinate-wise moves
        # - Every so often do restart candidate(s)
        sigma = base_sigma.copy()
        no_improve = 0

        # Remaining budget tracker
        while evals < budget:
            remaining = budget - evals

            # Determine generation batch size
            # Aim to evaluate at least 1, at most a fraction of remaining.
            batch = int(np.clip(3, 1, min(8, remaining)))
            new_xs = []
            new_ys = []

            # Occasionally restart if stagnating
            restart_prob = 0.15 + 0.25 * (no_improve >= 3)
            gauss_prob = 0.65
            coord_prob = 0.25

            for _ in range(batch):
                r = rng.random()

                # Candidate source selection:
                # - use incumbent best as anchor mostly
                # - sometimes use random elite member for diversity
                if rng.random() < 0.75:
                    anchor = best_x
                else:
                    elite_inds = np.argsort(ys)[:elite_size]
                    anchor = xs[rng.choice(elite_inds)].copy()

                if r < restart_prob:
                    # Uniform restart in bounds
                    x = lb + rng.random(dim) * (ub - lb)
                elif r < restart_prob + gauss_prob:
                    # Gaussian perturbation around anchor and best-move bias
                    # Slightly bias toward best direction: x = anchor + noise + small pull to best
                    # The pull helps exploitation without destroying diversity.
                    noise = rng.randn(dim) * sigma
                    pull = 0.1 * rng.random() * (best_x - anchor)
                    x = anchor + noise + pull
                else:
                    # Coordinate-wise perturbation (one dimension at a time)
                    x = anchor.copy()
                    j = int(rng.randint(dim))
                    # Adaptive coordinate step: use sigma[j] and random sign
                    step = (rng.random() * 2.0 - 1.0) * sigma[j]
                    x[j] = x[j] + step
                    # Occasionally a second coordinate tweak for richer moves (still compact)
                    if dim > 1 and rng.random() < 0.3:
                        k = int(rng.randint(dim))
                        step2 = (rng.random() * 2.0 - 1.0) * (0.5 * sigma[k])
                        x[k] = x[k] + step2

                x = clip(x)
                y = eval_obj(x)
                new_xs.append(x)
                new_ys.append(y)

            # Integrate new candidates with elitist selection
            new_xs = np.asarray(new_xs, dtype=float)
            new_ys = np.asarray(new_ys, dtype=float)

            xs = np.vstack([xs, new_xs])
            ys = np.concatenate([ys, new_ys])

            # Keep best pop_size
            keep = int(min(pop_size, xs.shape[0]))
            order = np.argsort(ys)[:keep]
            xs = xs[order]
            ys = ys[order]

            cur_best_idx = int(np.argmin(ys))
            cur_best_y = float(ys[cur_best_idx])

            if cur_best_y < best_y - 1e-12:
                best_y = cur_best_y
                best_x = xs[cur_best_idx].copy()
                no_improve = 0
                # Reduce sigma to exploit around improved region
                sigma = np.maximum(1e-12, 0.85 * sigma)
            else:
                no_improve += 1
                # If stagnating, increase a bit and slightly randomize sigma per dimension
                if no_improve >= 2:
                    sigma = np.minimum(base_sigma, 1.08 * sigma) + 1e-12
                    # small per-dimension jitter
                    sigma = np.clip(sigma * (0.95 + 0.1 * rng.random(dim)), 1e-12, base_sigma)

            # If sigma becomes tiny, allow more restarts by resetting sigma softly
            if float(np.max(sigma)) <= 1e-12:
                sigma = base_sigma.copy()

            # Stop early if budget exhausted (loop condition handles it)
            # Also safeguard if objective already returned inf a lot (no further control)

        return best_x, best_y
