import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact black-box minimization algorithm
# for continuous domains. It maintains a small population of candidate points,
# repeatedly explores around the current best using anisotropic Gaussian steps,
# and also performs occasional global perturbations to avoid stagnation.
# The algorithm always respects the provided evaluation budget.
#
# Search state: A population of size pop_size is stored. The best point
# (best_x) and its objective value (best_y) are tracked. A step-size vector
# (sigma) controls how far candidates are perturbed; it is adapted online.
# The remaining evaluation budget is tracked precisely.
#
# Candidate generation: In each iteration, new points are generated by
# sampling Gaussian perturbations around either the current best or the
# current population mean. The perturbation scale uses sigma and per-dimension
# bounds. Additionally, with a small probability, the algorithm samples
# a global random point uniformly in the search box to encourage exploration.
#
# Selection and replacement: After evaluating candidates, the algorithm
# identifies the best among the newly sampled points and compares it with the
# current best. Population members are replaced by their improved versions
# when beneficial; otherwise the population is lightly refreshed toward the best.
#
# Adaptation: sigma is decreased when recent improvements occur to exploit
# and increased when progress stalls to explore. This adaptation is driven by
# whether the global best improved over the last block of evaluations.
#
# Exploration mechanisms: Global uniform re-sampling (rare) and larger
# sigma when stagnating.
#
# Exploitation mechanisms: Gaussian sampling centered at/near the best and
# shrinking sigma after improvements.
#
# Boundary handling: All sampled points are clipped to the feasible bounds
# after perturbation.
#
# Budget strategy: The number of function evaluations is capped at the given
# budget. Evaluations are accounted for exactly, including initial sampling.
# The algorithm may stop early once the budget is exhausted.
#
# Closest known influences: This resembles lightweight evolution strategies /
# CMA-like neighborhood search ideas (population + step-size adaptation),
# but implemented in a compact, dimension-robust way without advanced linear
# algebra or external libraries.
#
# Novelty or unusual aspects: Uses a simple per-dimension sigma vector scaled
# by normalized distances to bounds, combines best-centered and mean-centered
# sampling, and adapts sigma based on block-level improvement checks while
# still remaining budget-safe and deterministic under external seeding.
#
# Failure modes: If the objective is very deceptive and the budget is too small,
# the algorithm may converge prematurely to a local optimum. With extremely
# tight bounds or ill-conditioned scaling, sigma adaptation may become slow,
# but clipping prevents invalid points.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim
        budget = max(1, int(self.budget))

        # ---- Read bounds from func ----
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds"):
            b = func.bounds
            lb = np.asarray(getattr(b, "lb"), dtype=float)
            ub = np.asarray(getattr(b, "ub"), dtype=float)
        else:
            raise AttributeError("func must provide either lower/upper or bounds.lb/bounds.ub")

        lb = np.broadcast_to(lb, (dim,)).copy()
        ub = np.broadcast_to(ub, (dim,)).copy()

        if np.any(~np.isfinite(lb)) or np.any(~np.isfinite(ub)):
            raise ValueError("Bounds must be finite.")
        if np.any(ub <= lb):
            raise ValueError("Each upper bound must be greater than lower bound.")

        rng = np.random  # numpy global RNG (seeded by harness)

        # ---- Helper: clip to bounds ----
        def clip(x):
            return np.minimum(ub, np.maximum(lb, x))

        # Scale: normalized step size relative to box size
        box = ub - lb

        # Handle degenerate dimensions (box could be tiny but must be > 0)
        # We'll still use it safely.
        box_floor = np.maximum(box, 1e-300)

        # Choose population size based on budget/dimension, staying compact.
        # Each iteration evaluates k new candidates; we choose pop_size and k
        # such that we get several iterations when budget allows.
        # Roughly allocate ~1/3 to initial sampling and remainder to iterations.
        pop_size = int(np.clip(4 + dim, 6, 32))
        if budget < pop_size:
            pop_size = budget

        # Evaluate a point and update best.
        evals = 0
        best_x = None
        best_y = None

        def eval_point(x):
            nonlocal evals, best_x, best_y
            # Enforce budget
            if evals >= budget:
                return None, None
            x = clip(np.asarray(x, dtype=float))
            y = float(func(x))
            evals += 1
            if best_y is None or y < best_y:
                best_y = y
                best_x = x.copy()
            return x, y

        # ---- Initialization: random population ----
        # Use uniform sampling in the box.
        X = np.empty((pop_size, dim), dtype=float)
        yvals = np.empty(pop_size, dtype=float)

        for i in range(pop_size):
            x = lb + rng.rand(dim) * box_floor
            _, y = eval_point(x)
            X[i] = clip(x)
            yvals[i] = y if y is not None else np.inf

            if evals >= budget:
                # Budget exhausted during initialization
                return best_x, best_y

        # Current population best
        idx_best_pop = int(np.argmin(yvals))
        if best_y is None or yvals[idx_best_pop] < best_y:
            best_y = float(yvals[idx_best_pop])
            best_x = X[idx_best_pop].copy()

        # Step size vector (sigma). Start moderate, relative to box.
        # Typical ES heuristic: about 1/5 of the box.
        sigma = 0.2 * box_floor

        # Stagnation tracking
        best_y_prev_block = best_y
        block_evals_target = max(2, min(20, (budget - evals) // 3)) if budget > evals else 0
        # If budget is tiny, we'll simply exploit without many blocks.
        if block_evals_target <= 0:
            return best_x, best_y

        # ---- Main loop ----
        # Each iteration creates up to k new candidates around best and/or mean.
        # Replace population entries if improved.
        while evals < budget:
            # Determine how many evaluations we can still do in this iteration
            remaining = budget - evals
            if remaining <= 0:
                break

            # Choose k new candidates this iteration
            k = int(min(pop_size, remaining, max(2, dim + 2)))
            # Candidate centers
            mean_x = np.mean(X, axis=0)

            # Proportions: explore around best more frequently than mean
            # but include both to maintain diversity.
            p_best_center = 0.7

            # Occasionally do a global random point
            global_prob = 0.06 if dim >= 2 else 0.1

            new_X = np.empty((k, dim), dtype=float)
            new_y = np.empty(k, dtype=float)
            # Evaluate candidates one by one to remain budget-safe
            for j in range(k):
                if evals >= budget:
                    break

                if rng.rand() < global_prob:
                    # Global exploration
                    x_new = lb + rng.rand(dim) * box_floor
                else:
                    center = best_x if rng.rand() < p_best_center else mean_x

                    # Anisotropic Gaussian perturbation:
                    # Occasionally use a "directional" perturbation by scaling
                    # with random signs to diversify.
                    sign_flip = 1.0
                    if rng.rand() < 0.2:
                        sign_flip = rng.choice([-1.0, 1.0], size=dim)

                    # Gaussian step
                    z = rng.randn(dim)
                    # Step scale: occasionally larger for escape when sigma is small
                    scale = 1.0
                    if rng.rand() < 0.15:
                        scale = 2.0

                    x_new = center + sign_flip * scale * (sigma * z)

                # Clip and evaluate
                x_new = clip(x_new)
                y_new = float(func(x_new))
                evals += 1

                # Update global best
                if best_y is None or y_new < best_y:
                    best_y = y_new
                    best_x = x_new.copy()

                new_X[j] = x_new
                new_y[j] = y_new

            # If no candidates were evaluated, stop
            if evals <= budget and np.all(np.isnan(new_y)):
                break

            # ---- Selection and replacement ----
            # Replace worst individuals with better new points.
            # Map new points to indices of current population.
            # Sort new candidates by improvement potential.
            valid_count = min(k, len(new_y))
            order_new = np.argsort(new_y[:valid_count])
            order_pop_worst = np.argsort(yvals)[::-1]  # descending = worst first

            replaced = 0
            for idx_n in order_new:
                if replaced >= valid_count:
                    break
                if evals >= budget:
                    break
                # Replace if new point is better than some current population members
                idx_p = order_pop_worst[replaced % pop_size]
                if new_y[idx_n] < yvals[idx_p]:
                    X[idx_p] = new_X[idx_n]
                    yvals[idx_p] = new_y[idx_n]
                    replaced += 1
                else:
                    # Still allow occasional replacement to keep population moving
                    if rng.rand() < 0.1:
                        X[idx_p] = new_X[idx_n]
                        yvals[idx_p] = new_y[idx_n]
                        replaced += 1

            # Light refresh: pull a small fraction toward best_x if progress is limited
            if rng.rand() < 0.25:
                n_pull = 1 if dim < 8 else 2
                pull_idx = rng.choice(pop_size, size=n_pull, replace=False)
                for ii in pull_idx:
                    # Blend towards best with random weight
                    alpha = 0.3 + 0.4 * rng.rand()
                    X[ii] = clip((1 - alpha) * X[ii] + alpha * best_x)
                    # No extra evaluations to keep budget strict;
                    # We keep objective values as-is, which makes replacement purely
                    # based on earlier evaluations. (This keeps the budget safe.)
                    # If the harness expects exactness, objective changes won't be
                    # reflected; so we keep perturbations subtle and rely on
                    # evaluations already performed above.

            # ---- Adaptation (step size) ----
            # Adapt sigma based on whether best improved recently.
            # Use block target to avoid too frequent tiny updates.
            if evals >= budget:
                break

            # Check improvement window
            # We update if we have spent about block_evals_target since last check.
            if evals % max(1, block_evals_target) == 0:
                improved = best_y < best_y_prev_block
                # If improved, exploit: shrink sigma; else explore: enlarge sigma
                if improved:
                    sigma *= 0.82
                    best_y_prev_block = best_y
                else:
                    sigma *= 1.18
                    # prevent sigma from growing beyond box size
                    best_y_prev_block = best_y_prev_block

                # Keep sigma within reasonable range
                # Lower bound prevents collapse; upper bound limits jumps.
                sigma = np.clip(sigma, 1e-12 * box_floor, 0.95 * box_floor)

        return best_x, best_y
