# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact derivative-free black-box minimizer.
# It keeps a population of candidate solutions and repeatedly generates new points
# using a mix of global exploration (random sampling and mutation) and local
# exploitation (Gaussian perturbations around the current best). The algorithm is
# designed to work across different dimensions using only NumPy.
#
# Search state: A population of size ~ 6*dim (bounded by a small minimum) is kept.
# The algorithm tracks the best found point and its objective value. Each loop
# consumes a fixed number of evaluations, never exceeding the user-provided budget.
#
# Candidate generation: New candidates are generated by mutating either the best
# point (local exploitation) or random population points (global exploration). Each
# mutation uses step sizes derived from the current search scale, which is gradually
# reduced as the budget is consumed.
#
# Selection and replacement: After evaluating candidates, the population is combined
# and the best individuals are selected to form the next generation. This keeps
# promising solutions while still allowing diversity.
#
# Adaptation: The global search scale decays smoothly with the fraction of budget
# spent, tightening the search over time. Step sizes also use a population-based
# scale estimate from coordinate-wise spread.
#
# Exploration mechanisms: Random candidates drawn uniformly within bounds early on,
# plus mutations from random parents and occasional “restarts” (reinitializing some
# individuals) help avoid stagnation.
#
# Exploitation mechanisms: Many candidates are sampled from a Gaussian around the
# current best (and/or best few), with decreasing variance, focusing evaluations
# near strong performers.
#
# Boundary handling: Any generated candidate is clipped to the provided bounds.
#
# Budget strategy: The algorithm performs batches of evaluations and tracks an exact
# counter. It stops immediately when the remaining budget is insufficient for the next
# planned evaluations, ensuring it never exceeds the limit.
#
# Closest known influences: Inspired by simple evolutionary strategies / CMA-ES-like
# ask-tell ideas but implemented in a much lighter, budget-safe form without
# covariance adaptation.
#
# Novelty or unusual aspects: Uses a hybrid of best-centric local sampling and
# population spread-based step scaling with deterministic budget-aware batching, aiming
# for robustness under black-box noise-free conditions.
#
# Failure modes: If the objective has very irregular behavior or extremely narrow
# feasible basins, clipping and simple Gaussian steps may miss optima; also, with
# very small budgets (e.g., budget < population size), the algorithm reduces to a
# minimal sampling/exploitation scheme.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim
        budget_total = self.budget
        if budget_total <= 0:
            # Nothing to evaluate: return a zero vector and +inf (unknown).
            return np.zeros(dim, dtype=float), float("inf")

        # Bounds retrieval (one of: func.lower/func.upper or func.bounds.lb/ub)
        lb, ub = None, None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds"):
            b = func.bounds
            lb = np.asarray(getattr(b, "lb"), dtype=float)
            ub = np.asarray(getattr(b, "ub"), dtype=float)

        if lb is None or ub is None:
            raise AttributeError(
                "Objective function must provide bounds via func.lower/func.upper "
                "or func.bounds.lb/func.bounds.ub."
            )

        # Ensure correct shapes for broadcasting/clipping
        lb = np.broadcast_to(lb, (dim,)).astype(float, copy=False)
        ub = np.broadcast_to(ub, (dim,)).astype(float, copy=False)
        if np.any(ub < lb):
            raise ValueError("Upper bounds must be >= lower bounds for all dimensions.")
        span = ub - lb
        # Handle zero-span dimensions safely
        span_safe = np.where(span == 0.0, 1.0, span)

        def project(x):
            return np.minimum(ub, np.maximum(lb, x))

        evals = 0
        best_x = None
        best_y = float("inf")

        # Choose population size based on dimension, but respect budget.
        # Small minimum to allow selection; cap by budget.
        pop_size = max(8, min(6 * dim, budget_total))
        # At least 2 to allow evolution; if budget is tiny, we reduce.
        pop_size = max(2, min(pop_size, budget_total))

        # Helper to evaluate a batch of points (exactly tracks budget).
        def eval_points(points):
            nonlocal evals, best_x, best_y
            ys = np.empty(points.shape[0], dtype=float)
            for i in range(points.shape[0]):
                if evals >= budget_total:
                    # Should never happen if caller is budget-aware.
                    break
                y = float(func(points[i]))
                ys[i] = y
                evals += 1
                if y < best_y:
                    best_y = y
                    best_x = points[i].copy()
            return ys

        # Initial population: uniform within bounds
        rng = np.random
        pop = project(lb + rng.rand(pop_size, dim) * span_safe)

        # In case some spans are zero, project ensures correct positions.
        ys = eval_points(pop)

        # If budget was smaller than planned (shouldn't due to pop_size <= budget_total)
        if evals >= budget_total:
            return (best_x if best_x is not None else pop[0].copy()), best_y

        # Track population
        # Always keep arrays aligned; filter best later.
        # Set generation parameters
        # local_fraction: proportion of children sampled around best
        local_fraction = 0.7
        # Exploration restart fraction to mitigate stagnation
        restart_frac = 0.15
        # How many children per generation; keep small batches for budget safety.
        # We'll attempt "offspring" count but cap to remaining evaluations.
        while evals < budget_total:
            remaining = budget_total - evals
            if remaining <= 0:
                break

            # Decide offspring size for this batch.
            # Use 2*pop_size but cap by remaining.
            # If remaining is tiny, we'll just evaluate as many as possible.
            offspring = min(2 * pop_size, remaining)
            if offspring <= 0:
                break

            # Sort current population by objective
            order = np.argsort(ys)
            pop = pop[order]
            ys = ys[order]

            # Best-centric exploitation and population-scale exploration
            x_best = pop[0].copy()
            # Population spread estimate (coordinate-wise)
            # Add epsilon to prevent step collapse in flat regions.
            pop_spread = np.std(pop, axis=0)
            # Also incorporate bound span for a reasonable initial scale.
            base_scale = 0.25 * span_safe
            spread_scale = pop_spread + 0.1 * base_scale
            scale0 = np.clip(spread_scale, 1e-12, None)

            # Global decay: start large and shrink to focus near optimum
            t = evals / max(1, budget_total)
            decay = (1.0 - t) ** 2.2  # smooth, stronger towards the end

            # Local step std for exploitation
            local_std = decay * (0.5 * scale0)
            # Global step std for exploration (wider than local)
            global_std = max(1e-12, 0.9 * decay) * scale0

            # Some parents for exploitation: best few
            k_elite = min(5, pop_size)
            elite = pop[:k_elite]

            children = np.empty((offspring, dim), dtype=float)

            # Decide how many to allocate to local vs global methods
            n_local = int(round(offspring * local_fraction))
            n_global = offspring - n_local

            # Local exploitation: Gaussian around best or elite
            if n_local > 0:
                # Randomly choose elite parent for each child
                parent_idx = rng.randint(0, k_elite, size=n_local)
                parents = elite[parent_idx]
                # Gaussian noise per coordinate
                noise = rng.randn(n_local, dim) * local_std
                # With some probability, do smaller additional shrink towards best
                shrink_mask = (rng.rand(n_local, dim) < 0.25)
                # shrink_mask means reduce noise amplitude on some coordinates
                noise = np.where(shrink_mask, 0.4 * noise, noise)
                cand = parents + noise
                children[:n_local] = project(cand)

            # Global exploration: mutate random parents and sometimes uniform sampling
            if n_global > 0:
                # Mix: some uniform samples early/mid, plus Gaussian mutation
                # Probability of uniform sampling increases when decay is high.
                p_uniform = 0.35 + 0.35 * float(decay)
                uni_count = int(round(n_global * p_uniform))
                gauss_count = n_global - uni_count

                if uni_count > 0:
                    cand_u = lb + rng.rand(uni_count, dim) * span_safe
                    children[n_local:n_local + uni_count] = project(cand_u)

                if gauss_count > 0:
                    parent_idx = rng.randint(0, pop_size, size=gauss_count)
                    parents = pop[parent_idx]
                    # Wider mutation for exploration
                    noise = rng.randn(gauss_count, dim) * global_std
                    # Occasional "crossover" from best
                    cross_mask = rng.rand(gauss_count, dim) < 0.3
                    cand = parents + noise
                    cand = np.where(cross_mask, x_best, cand)
                    children[n_local + uni_count:n_local + uni_count + gauss_count] = project(cand)

            # Stagnation mitigation: occasional restart of some children
            # If we are near the end, restart probability is lower.
            if restart_frac > 0 and offspring > 0:
                t = evals / max(1, budget_total)
                p_restart = restart_frac * (0.6 + 0.4 * (1.0 - t))
                mask = rng.rand(offspring) < p_restart
                if np.any(mask):
                    cnt = int(np.sum(mask))
                    children[mask] = project(lb + rng.rand(cnt, dim) * span_safe)

            # Evaluate and update
            ys_new = eval_points(children)

            # If we exceeded budget due to rounding, trim
            if evals > budget_total:
                # Ensure we don't break invariants; but should not happen.
                ys_new = ys_new[: max(0, ys_new.shape[0] - (evals - budget_total))]
                evals = budget_total

            # Combine and select best pop_size
            # Truncate if new evaluation batch was smaller than intended.
            # We'll use the actual number of computed values in ys_new (non-empty).
            # If eval_points returned fewer due to budget, handle via finite count.
            valid = np.isfinite(ys_new)
            if not np.all(valid):
                ys_new = ys_new[valid]
                children = children[valid]

            if ys_new.size == 0:
                break

            pop_all = np.vstack([pop, children])
            ys_all = np.concatenate([ys, ys_new])

            order_all = np.argsort(ys_all)[:pop_size]
            pop = pop_all[order_all]
            ys = ys_all[order_all]

        if best_x is None:
            # Fallback: evaluate first point if possible
            x0 = project(lb.copy())
            y0 = float(func(x0))
            best_x, best_y = x0.copy(), y0
        return best_x, best_y
