# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact black-box minimization algorithm
# using a multi-stage strategy: an initial population-based exploration
# followed by iterative exploitation around the best point found so far.
# It works in any dimension given only a budget (evaluation count) and
# the search bounds from the objective function.
#
# Search state: The algorithm maintains a population of candidate points,
# their objective values, and the index of the current best candidate.
# It also tracks the current step size (mutation radius) and a counter for
# consecutive non-improving iterations to trigger stronger exploration.
#
# Candidate generation: Each iteration generates new candidates by sampling
# from a mixture of perturbations:
#   - Local Gaussian mutations around the best point
#   - Directions derived from coordinate-wise differences between the best
#     and a few other population members (a cheap covariance-like idea)
#   - Global random samples (occasionally) to avoid stagnation
# Proposals are clipped to bounds.
#
# Selection and replacement: For each generated candidate, if it improves on the
# current best value, it becomes the new best. The population is refreshed
# by replacing the worst individuals with the best new candidates seen in
# the iteration, keeping population diversity.
#
# Adaptation: The step size shrinks when improvements occur (promoting
# exploitation) and grows when the search stagnates (promoting exploration).
# A schedule based on the number of remaining evaluations is also used.
#
# Exploration mechanisms: Global random candidates are injected with a probability
# that increases when the algorithm is not improving. Additionally, coordinate
# direction perturbations provide broader search early on.
#
# Exploitation mechanisms: A majority of candidates are generated by local
# Gaussian mutations around the current best, with step size controlling
# how far the search moves.
#
# Boundary handling: Proposed points are clipped to [lb, ub] elementwise.
#
# Budget strategy: The algorithm never evaluates the objective more than the
# provided budget. It pre-allocates an evaluation budget split between an
# initialization stage and iterative refinement; if budget is very small,
# it gracefully reduces population size and iteration count.
#
# Closest known influences: The design is inspired by simple Evolution Strategies
# (population + mutation + selection) and CMA-ES-like local adaptation ideas,
# but implemented in a compact way without covariance matrix estimation.
#
# Novelty or unusual aspects: It uses a lightweight "direction bank" derived
# from population differences to bias mutations without expensive linear
# algebra or covariance updates.
#
# Failure modes: If the objective is extremely noisy or bounds are very tight,
# progress may stagnate; the algorithm responds by increasing exploration.
# With extremely small budgets, behavior degrades toward random search with
# minimal refinement.
# ALGORITHM_ANALYSIS_NOTE_END

from __future__ import annotations

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim

        # --- Bounds extraction (robust to different attribute layouts) ---
        lb = None
        ub = None
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = getattr(func, "lower")
            ub = getattr(func, "upper")
        elif hasattr(func, "bounds") and hasattr(func.bounds, "lb") and hasattr(func.bounds, "ub"):
            b = func.bounds
            lb = getattr(b, "lb")
            ub = getattr(b, "ub")
        elif hasattr(func, "bounds") and hasattr(func.bounds, "lower") and hasattr(func.bounds, "upper"):
            b = func.bounds
            lb = getattr(b, "lower")
            ub = getattr(b, "upper")

        if lb is None or ub is None:
            raise AttributeError("Objective function must provide bounds via func.lower/func.upper or func.bounds.lb/func.bounds.ub")

        lb = np.asarray(lb, dtype=float).reshape(-1)
        ub = np.asarray(ub, dtype=float).reshape(-1)
        if lb.size != dim or ub.size != dim:
            raise ValueError(f"Bounds size mismatch: expected dim={dim}, got lb={lb.size}, ub={ub.size}")
        if np.any(ub < lb):
            raise ValueError("Invalid bounds: found ub < lb")

        # Handle degenerate bounds: ensure width >= 0, use zero-width safely.
        width = ub - lb
        width_safe = np.where(width > 0, width, 1.0)

        # --- Budget accounting ---
        budget = max(0, int(self.budget))
        if budget == 0:
            # No evaluations allowed; return a legal point within bounds.
            x0 = lb.copy()
            return x0, float("inf")

        evals = 0

        def clip(x):
            return np.minimum(ub, np.maximum(lb, x))

        def uniform_sample():
            # Sample uniformly within bounds (handles zero-width).
            r = np.random.rand(dim)
            return lb + r * width_safe * (width > 0)

        def randn_like():
            return np.random.randn(dim)

        def evaluate(x):
            nonlocal evals
            if evals >= budget:
                # Safety: never exceed budget
                return float("inf")
            x = clip(x)
            y = func(x)
            evals += 1
            return float(y)

        # --- Determine population size based on budget ---
        # Keep it small to guarantee budget respect in high dimensions.
        # At least 1 individual, at most budget.
        # Initialization cost is pop_size evaluations.
        # Remaining evaluations used for refinement.
        pop_size = int(max(1, min(budget, 4 + dim // 2)))
        init_evals = min(pop_size, budget)
        pop = np.empty((init_evals, dim), dtype=float)
        vals = np.empty(init_evals, dtype=float)

        # --- Initialization: mix of bound extremes + uniform random ---
        # This improves robustness to tricky landscapes without extra evaluations.
        # Always evaluate exactly init_evals points.
        for i in range(init_evals):
            if i == 0:
                # Center point if feasible; else midpoint of bounds.
                x = (lb + ub) * 0.5
            elif i == 1 and dim > 0:
                x = lb.copy() if np.random.rand() < 0.5 else ub.copy()
            else:
                x = uniform_sample()
            pop[i] = clip(x)
            vals[i] = evaluate(pop[i])

        # Identify best
        best_idx = int(np.argmin(vals))
        best_x = pop[best_idx].copy()
        best_y = float(vals[best_idx])

        # Step size starts proportional to bound width; clamp to avoid too tiny/huge.
        # Use expected coordinate scale: mean width.
        mean_width = float(np.mean(width_safe * (width > 0) + 0.0 * (width == 0)))
        if mean_width == 0.0:
            step = 0.0
        else:
            step = 0.3 * mean_width  # initial exploration radius
        step_min = 1e-12
        step_max = max(1e-12, 0.5 * float(np.max(width_safe)))
        step = float(np.clip(step, step_min, step_max)) if step > 0 else 0.0

        # --- Refinement iterations within remaining budget ---
        remaining = budget - evals
        if remaining <= 0:
            return best_x, best_y

        # Each iteration will generate a small batch of candidates.
        # Choose batch size to spend evaluations evenly.
        # Ensure at least 1 candidate per iteration.
        batch_size = int(max(1, min(6, remaining)))
        iters = int(remaining // batch_size)
        if iters <= 0:
            iters = 1
            batch_size = max(1, remaining)

        # Track stagnation for adaptation
        no_improve = 0
        prev_best = best_y

        # Precompute indices used for direction bias
        def direction_from_population():
            # Build a direction vector as weighted sum of differences.
            # Cheap alternative to covariance estimation.
            # Returns a vector normalized to unit length (or zeros if invalid).
            # Sample other indices from population and form differences from best.
            k = min(pop_size, 3)
            if k <= 1:
                return randn_like()
            choices = np.random.choice(pop.shape[0], size=k, replace=False)
            diffs = pop[choices] - best_x  # (k, dim)
            # Weights favor directions from better-than-average individuals for exploitation bias.
            # (Still robust: uses relative improvement signals.)
            v = vals[choices]
            # If variance is small, weights become near-uniform.
            v0 = float(np.min(vals))
            # Convert to "lower is better": weights proportional to exp(-(v-v0)/scale)
            scale = float(np.std(vals) + 1e-9)
            w = np.exp(-(v - v0) / (scale + 1e-9))
            d = (w[:, None] * diffs).sum(axis=0)
            norm = float(np.linalg.norm(d))
            if not np.isfinite(norm) or norm < 1e-18:
                d = randn_like()
                norm = float(np.linalg.norm(d))
            if norm > 0 and np.isfinite(norm):
                return d / norm
            return d

        # Main loop
        for _ in range(iters):
            # Budget safety: if evaluations are near budget, shrink batch.
            if evals >= budget:
                break
            max_batch = min(batch_size, budget - evals)
            if max_batch <= 0:
                break

            # Exploration probability: higher when stagnating and early in runtime.
            progress = evals / budget
            stagnation_factor = min(1.0, no_improve / 5.0)
            p_global = float(0.15 + 0.35 * stagnation_factor + 0.2 * max(0.0, 0.5 - progress))
            p_global = min(0.7, max(0.0, p_global))

            # Generate candidates and evaluate
            candidates = np.empty((max_batch, dim), dtype=float)
            cand_vals = np.empty(max_batch, dtype=float)

            # Local mutation scale schedule (shrink with progress)
            # Shrink more strongly as we approach budget.
            shrink = float(1.0 - 0.75 * progress)
            local_step = float(step * shrink)
            if local_step < step_min:
                local_step = step_min

            # Direction bias (computed once per iteration)
            dir_bias = direction_from_population()

            for j in range(max_batch):
                if np.random.rand() < p_global or step == 0.0:
                    # Global exploration: random point in bounds
                    x = uniform_sample()
                else:
                    # Exploit: local mutation around best, with occasional direction bias
                    g1 = randn_like()
                    g2 = randn_like()
                    # Mix isotropic noise and biased direction noise.
                    # The biased term is scaled to be comparable to isotropic mutation.
                    use_bias = (np.random.rand() < 0.5)
                    if use_bias:
                        noise = 0.75 * g1 + 0.25 * (dir_bias * np.linalg.norm(g2) / (np.linalg.norm(g2) + 1e-12))
                    else:
                        noise = g1
                    # Coordinate-wise scaling based on widths (encourages respecting varying scale per dimension)
                    coord_scale = width_safe / (np.max(width_safe) + 1e-12)
                    coord_scale = np.where(width > 0, coord_scale, 0.0)
                    # Ensure non-negative
                    coord_scale = np.clip(coord_scale, 0.0, 1.0)
                    # Mutation
                    x = best_x + local_step * noise * (0.3 + 0.7 * coord_scale)

                    # Occasional larger jump to escape shallow traps
                    if no_improve >= 2 and np.random.rand() < 0.15:
                        x = best_x + (0.5 + 0.5 * np.random.rand()) * step * randn_like() * (0.5 + coord_scale)

                candidates[j] = clip(x)
                cand_vals[j] = evaluate(candidates[j])

            # Update best
            best_c_idx = int(np.argmin(cand_vals))
            cand_best_y = float(cand_vals[best_c_idx])
            if cand_best_y < best_y:
                best_y = cand_best_y
                best_x = candidates[best_c_idx].copy()
                no_improve = 0
            else:
                no_improve += 1

            # Adapt step size
            if best_y < prev_best:
                # Improved overall: shrink step to exploit
                step = float(max(step_min, 0.85 * step))
            else:
                # No improvement: cautiously expand to explore more
                step = float(min(step_max, step * (1.07 + 0.15 * no_improve)))
            prev_best = best_y

            # Population refresh: keep population_size candidates for direction sampling
            # Merge current population with new candidates but cap size at pop_size.
            if pop.shape[0] < pop_size:
                # If initial population was smaller than desired due to budget, expand gradually.
                # But keep within budget-evaluations already done.
                # We'll just replace worst elements if possible.
                pass

            # Create merged set for selection pressure
            # Note: pop size might be init_evals <= pop_size.
            merged_n = pop.shape[0] + max_batch
            # Build arrays
            merged_pop = np.empty((merged_n, dim), dtype=float)
            merged_vals = np.empty((merged_n,), dtype=float)
            merged_pop[: pop.shape[0]] = pop
            merged_vals[: pop.shape[0]] = vals
            merged_pop[pop.shape[0] :] = candidates
            merged_vals[pop.shape[0] :] = cand_vals

            # Select top pop_size individuals (smallest values)
            k = min(pop_size, merged_n)
            keep = np.argpartition(merged_vals, k - 1)[:k]
            # Update population
            pop = merged_pop[keep]
            vals = merged_vals[keep]

            # Ensure best_x stays consistent with population
            idx = int(np.argmin(vals))
            if float(vals[idx]) < best_y:
                best_y = float(vals[idx])
                best_x = pop[idx].copy()

        return best_x, best_y
