# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact black-box minimization algorithm for
# continuous domains. It maintains a small population of candidate points, uses
# coordinate-wise sampling around an evolving center, and progressively shrinks
# step sizes based on observed improvements. It is designed to be robust across
# dimensions and to respect a hard evaluation budget.
# Search state: A population of size pop_size is sampled each iteration around a
# current center (best-so-far). The algorithm tracks best_x, best_y and uses
# per-dimension step scales (sigma) to control candidate diversity.
# Candidate generation: Each candidate is generated by adding a random signed
# step to the center. Steps are drawn from a normal distribution with scale
# sigma per dimension, and are additionally clipped and reflected to remain in
# bounds. Some candidates include stronger perturbations to escape stagnation.
# Selection and replacement: After evaluating all candidates in an iteration, the
# algorithm selects the best candidate as the new center and updates best_x/best_y.
# Adaptation: If no improvement occurs, sigma is reduced to focus search; if
# improvement happens, sigma is mildly increased (capped) to keep momentum.
# Exploration mechanisms: A fraction of candidates use larger perturbations
# (sigma multiplied by an exploration factor) to explore new regions, especially
# when progress stalls.
# Exploitation mechanisms: The majority of candidates are sampled close to the
# current center using smaller sigma, enabling local refinement.
# Boundary handling: Candidates are projected back into bounds using reflection
# (mirror) and clipping to ensure feasibility without wasting evaluations.
# Budget strategy: The algorithm computes the maximum number of iterations based
# on the evaluation budget and population size, and it always stops early if the
# budget would be exceeded. Every call to func is counted and the budget is
# never surpassed.
# Closest known influences: The approach resembles simple evolution strategies /
# coordinatewise stochastic search with dynamic step-size control, adapted for a
# strict evaluation budget and a standard-box constraint.
# Novelty or unusual aspects: It mixes per-dimension adaptive sigma with a
# lightweight "stall" mechanism that triggers stronger exploration bursts without
# adding heavy machinery.
# Failure modes: In very deceptive landscapes or extremely tight budgets,
# the population may not find improving moves and sigma may shrink prematurely.
# The exploration burst mitigates but does not eliminate this risk.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        dim = self.dim
        budget = self.budget
        if budget <= 0:
            # No evaluations allowed: return a deterministic feasible point if possible
            lb, ub = self._get_bounds(func, dim)
            x0 = (lb + ub) * 0.5
            return x0, float("inf")

        lb, ub = self._get_bounds(func, dim)
        lb = np.asarray(lb, dtype=float).reshape(dim)
        ub = np.asarray(ub, dtype=float).reshape(dim)

        # Ensure well-formed bounds
        span = ub - lb
        span = np.where(span <= 0, 1.0, span)  # avoid zero span in scaling

        # Evaluation counting (never exceed budget)
        evals = 0

        def eval_obj(x):
            nonlocal evals
            if evals >= budget:
                # Should not happen, but guard for robustness.
                return float("inf")
            y = func(x)
            evals += 1
            # If func returns array-like, reduce to scalar
            y = float(np.asarray(y).reshape(-1)[0])
            return y

        # Population size and iteration planning:
        # Choose a small population to reduce overspending and remain budget-safe.
        # Make it scale mildly with dimension.
        pop_size = int(np.clip(4 + dim // 5, 4, 16))
        init_pop = min(pop_size, budget)  # evaluate until budget

        rng = np.random

        # Initialize center at a random point within bounds
        center = lb + rng.random(dim) * span
        best_x = center.copy()
        best_y = eval_obj(center)

        # Initial sigma: proportional to range, but not too large/small.
        # Keep a per-dimension sigma to help anisotropy.
        sigma = 0.3 * span
        sigma = np.where(sigma == 0, 1.0, sigma)

        # If we can, evaluate additional initial points to seed the center.
        # (This improves robustness when the initial random point is poor.)
        initial_evals_left = min(budget - evals, init_pop - 1)
        if initial_evals_left > 0:
            for _ in range(initial_evals_left):
                x = lb + rng.random(dim) * span
                y = eval_obj(x)
                if y < best_y:
                    best_y = y
                    best_x = x.copy()
            center = best_x.copy()

        # Number of full iterations we can afford, given population size.
        # Each iteration evaluates pop_size candidates. We already spent some evals.
        remaining = budget - evals
        if remaining < pop_size:
            # Not enough for another full population iteration.
            # Try a single-shot improvement step within remaining budget.
            if remaining > 0:
                # One batch of candidates up to remaining
                batch = min(remaining, pop_size)
                improved = False
                for i in range(batch):
                    # mostly small perturbations with occasional larger one
                    explore = (i == 0)  # first candidate can be larger to escape
                    step = rng.normal(size=dim) * sigma * (2.0 if explore else 1.0)
                    x = self._reflect_and_clip(center + step, lb, ub)
                    y = eval_obj(x)
                    if y < best_y:
                        best_y = y
                        best_x = x.copy()
                        center = best_x.copy()
                        improved = True
                # adjust sigma depending on improvement
                if not improved:
                    sigma *= 0.5
            return best_x, best_y

        iters = remaining // pop_size
        iters = max(1, iters)

        # Stall counter: if no improvement in several iterations, trigger stronger exploration
        stall = 0
        max_stall = 4
        sigma_min = 1e-12  # to avoid collapse to zero in floating ops

        for _ in range(iters):
            # If we're near the budget, adjust to not overshoot
            if evals + pop_size > budget:
                break

            candidates = []
            # Majority exploitation: normal steps near center
            # Minority exploration: occasional large step
            for i in range(pop_size):
                # Exploration probability with a stall boost
                explore_prob = 0.15
                if stall >= max_stall:
                    explore_prob = 0.5
                explore = rng.random() < explore_prob

                # Signed perturbations with normal noise
                scale = 2.2 if explore else 1.0
                step = rng.normal(size=dim) * sigma * scale

                x = self._reflect_and_clip(center + step, lb, ub)
                candidates.append(x)

            # Evaluate and select the best candidate
            best_iter_y = float("inf")
            best_iter_x = None

            for x in candidates:
                y = eval_obj(x)
                if y < best_iter_y:
                    best_iter_y = y
                    best_iter_x = x

            improved = best_iter_y < best_y
            if improved:
                best_y = best_iter_y
                best_x = best_iter_x.copy()
                center = best_x.copy()
                # Increase sigma a bit to keep searching wider after progress
                sigma *= 1.08
                stall = 0
            else:
                # No progress: shrink sigma to refine locally
                sigma *= 0.82
                stall += 1

            # Keep sigma within reasonable limits
            sigma = np.maximum(sigma, sigma_min)
            # Cap to a fraction of span to avoid jumping outside repeatedly
            sigma_cap = 0.75 * span
            sigma_cap = np.where(sigma_cap <= 0, 1.0, sigma_cap)
            sigma = np.minimum(sigma, sigma_cap)

        return best_x, best_y

    @staticmethod
    def _get_bounds(func, dim):
        # Read bounds from func.lower/func.upper or func.bounds.lb/ub
        if hasattr(func, "lower") and hasattr(func, "upper"):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, "bounds") and hasattr(func.bounds, "lb") and hasattr(func.bounds, "ub"):
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)
        else:
            raise AttributeError(
                "Objective must provide bounds via func.lower/func.upper "
                "or func.bounds.lb/func.bounds.ub."
            )

        lb = lb.reshape(-1)
        ub = ub.reshape(-1)
        if lb.size != dim or ub.size != dim:
            # Be tolerant: if bounds are scalars, broadcast
            if lb.size == 1:
                lb = np.full(dim, float(lb[0]))
            if ub.size == 1:
                ub = np.full(dim, float(ub[0]))
            if lb.size != dim or ub.size != dim:
                raise ValueError("Bounds dimensionality does not match 'dim'.")
        return lb, ub

    @staticmethod
    def _reflect_and_clip(x, lb, ub):
        # Reflect across bounds then clip as final safeguard.
        # This keeps points within [lb, ub] even for large steps.
        y = np.array(x, dtype=float, copy=True)
        # Reflection using modulo on the doubled interval
        # Map to [0, 2*span] then fold.
        span = ub - lb
        span_safe = np.where(span == 0, 1.0, span)
        t = (y - lb) % (2.0 * span_safe)
        folded = np.where(t <= span_safe, t, 2.0 * span_safe - t)
        y = lb + folded

        # If span was zero, y becomes lb; clip final.
        y = np.minimum(np.maximum(y, lb), ub)
        return y
