# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A hybrid optimization strategy combining Opposition-Based Learning (OBL) for initial space exploration and an adaptive (1+1)-Evolution Strategy (ES) for local refinement.
# Search state: Stores the current best solution (best_x, best_y) and a scalar step-size parameter (sigma) used for local perturbations.
# Candidate generation: During initialization, candidates are generated in pairs: a random uniform sample and its "opposite" point reflected across the center of the search space. In the refinement phase, candidates are generated by adding Gaussian noise to the current best solution.
# Selection and replacement: Uses a strictly greedy selection mechanism where a candidate replaces the current best solution only if it results in a strictly lower objective function value.
# Adaptation: The step-size (sigma) is dynamically adjusted based on success: it increases after finding an improvement to accelerate progress and decreases after a failure to focus the search locally.
# Exploration mechanisms: OBL provides a diversified initial sampling, effectively covering both random regions and their mirrored counterparts to increase the probability of landing in the global basin.
# Exploitation mechanisms: The (1+1)-ES performs a stochastic hill-climbing search with adaptive step-size reduction, allowing for precise convergence near local or global minima.
# Boundary handling: All generated candidates are explicitly clipped to the hypercube defined by the problem bounds (lb, ub).
# Budget strategy: Allocates approximately 10% of the total budget (capped by dimensionality) to the OBL initialization phase and the remaining budget to the local improvement phase.
# Closest known influences: The design is influenced by Tizhoosh's Opposition-Based Learning and Rechenberg's (1+1)-Evolution Strategy.
# Novelty or unusual aspects: The algorithm uses a simplified, zero-memory adaptation rule for sigma, ensuring robustness and low overhead in a compact implementation.
# Failure modes: May converge to a local minimum if the initial OBL phase fails to sample the basin of the global optimum, particularly in highly multimodal or discontinuous landscapes.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the algorithm with the given evaluation budget and dimensionality.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Executes the minimization search.
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and func.lower is not None:
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        else:
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)

        eval_count = 0
        best_x = None
        best_y = float('inf')

        def evaluate(x):
            nonlocal eval_count, best_x, best_y
            # Clip and evaluate
            x = np.clip(x, lb, ub)
            y = func(x)
            eval_count += 1
            if y < best_y:
                best_y = y
                best_x = x.copy()
            return y

        # 1. Opposition-Based Initialization Phase
        # Allocate a small portion of budget to OBL (e.g., 10% or 2*dim pairs)
        obl_pairs = max(1, min(self.budget // 10, 2 * self.dim) // 2)
        
        for _ in range(obl_pairs):
            if eval_count >= self.budget:
                break
            
            # Random candidate
            x_rand = lb + (ub - lb) * np.random.rand(self.dim)
            evaluate(x_rand)
            
            if eval_count >= self.budget:
                break
                
            # Opposite candidate
            x_opp = lb + ub - x_rand
            evaluate(x_opp)

        # Ensure we have at least one evaluation if OBL didn't run
        if eval_count == 0 and self.budget > 0:
            evaluate(lb + (ub - lb) * np.random.rand(self.dim))

        # 2. Local Improvement Phase ((1+1)-ES)
        # Initial relative step size
        sigma = 0.2
        domain_range = ub - lb

        while eval_count < self.budget:
            # Generate mutation
            noise = np.random.randn(self.dim) * sigma * domain_range
            candidate = best_x + noise
            
            # Evaluate improvement
            old_best_y = best_y
            val = evaluate(candidate)
            
            # Simple 1/5th-style adaptation
            if val < old_best_y:
                # Success: expand step size
                sigma *= 1.2
            else:
                # Failure: contract step size
                sigma *= 0.8
            
            # Lower bound for sigma to prevent stagnation near zero
            sigma = max(sigma, 1e-10)

        return best_x, best_y
