# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A compact Differential Evolution variant using a "current-to-best/1" mutation strategy.
# Search state: A small population of candidate vectors and their corresponding objective values.
# Candidate generation: New candidates are generated by perturbing the current individual towards the best individual in the population, plus a differential weight from two other random members.
# Selection and replacement: A simple greedy selection is used where a child replaces its parent if its objective value is lower or equal.
# Adaptation: Static parameters (F=0.5, Cr=0.8) are used to maintain simplicity while providing a balance between exploration and exploitation.
# Exploration mechanisms: Differential vectors between random population members provide search direction and scale.
# Exploitation mechanisms: The "current-to-best" component biases the search towards the current global optimum found by the population.
# Boundary handling: Candidates are clipped to the hypercube defined by the problem bounds.
# Budget strategy: The loop explicitly tracks evaluations and terminates immediately once the budget is reached.
# Closest known influences: Storn and Price's Differential Evolution (specifically the DE/current-to-best/1/bin variant).
# Novelty or unusual aspects: Extremely lightweight implementation focusing on robustness across varying dimensionalities.
# Failure modes: May converge prematurely on highly multi-modal landscapes if the population size is too small for the dimensionality.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        
        Args:
            budget: Total number of function evaluations allowed.
            dim: Dimension of the search space.
        """
        self.budget = budget
        self.dim = dim
        
        # Population size: heuristic scale based on dimension, at least 4 for DE logic
        self.pop_size = max(4, min(10 * dim, 40))
        
        # DE Hyperparameters
        self.F = 0.5   # Mutation scale factor
        self.Cr = 0.8  # Crossover probability

    def __call__(self, func):
        """
        Executes the optimization process.
        
        Args:
            func: The objective function to minimize.
            
        Returns:
            (best_x, best_y): The best solution found and its objective value.
        """
        # Determine bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Fallback for unexpected interface
            lb = np.zeros(self.dim)
            ub = np.ones(self.dim)

        eval_count = 0
        
        # Initialize population
        pop = np.random.uniform(lb, ub, (self.pop_size, self.dim))
        scores = np.full(self.pop_size, np.inf)
        
        best_y = np.inf
        best_x = None

        # Initial Evaluation
        for i in range(self.pop_size):
            if eval_count >= self.budget:
                break
            scores[i] = func(pop[i])
            eval_count += 1
            if scores[i] < best_y:
                best_y = scores[i]
                best_x = pop[i].copy()

        # Evolution Loop
        while eval_count < self.budget:
            for i in range(self.pop_size):
                if eval_count >= self.budget:
                    break
                
                # Selection of distinct indices for mutation
                idxs = [idx for idx in range(self.pop_size) if idx != i]
                r1, r2 = np.random.choice(idxs, 2, replace=False)
                
                # DE/current-to-best/1 mutation strategy
                # v = x_i + F * (best_x - x_i) + F * (x_r1 - x_r2)
                mutant = pop[i] + self.F * (best_x - pop[i]) + self.F * (pop[r1] - pop[r2])
                
                # Binomial Crossover
                cross_points = np.random.rand(self.dim) < self.Cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary handling
                trial = np.clip(trial, lb, ub)
                
                # Evaluate trial
                score_trial = func(trial)
                eval_count += 1
                
                # Selection (greedy)
                if score_trial <= scores[i]:
                    scores[i] = score_trial
                    pop[i] = trial
                    if score_trial < best_y:
                        best_y = score_trial
                        best_x = trial.copy()

        return best_x, best_y
