# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm implements an "Annealed Random Walk with Restarts" for black-box minimization. It iteratively samples a starting point (restart) and then performs a local search (annealed random walk) around that point, gradually decreasing the step size. It always keeps track of the overall best solution found.
# Search state: The search maintains `best_x` and `best_y` as the overall best solution found so far. During a local search phase (walk), it also maintains `x_current` and `y_current` as the current best solution within that walk.
# Candidate generation: Candidates are generated by adding normally distributed random noise to `x_current`, scaled by an annealing step size (`sigma`). `x_candidate = x_current + np.random.randn(dim) * sigma`.
# Selection and replacement: A candidate `x_candidate` is accepted as the new `x_current` if its objective value `y_candidate` is better than `y_current`. The overall `best_x` and `best_y` are updated whenever a new `y_candidate` (or `y_current` after an update) is globally better.
# Adaptation: The step size (`sigma`) adapts through annealing. It starts large at the beginning of each walk and gradually decreases by multiplying with an `annealing_rate` in each step. This allows for broader exploration initially within a walk and finer-grained exploitation towards the end of a walk.
# Exploration mechanisms: Random restarts provide global exploration, ensuring the search doesn't get stuck in a single basin of attraction indefinitely. The initial large step size in each annealed walk also contributes to exploration around the restart point.
# Exploitation mechanisms: The annealed random walk itself acts as an exploitation mechanism. As the step size (`sigma`) decreases, the search focuses on increasingly smaller neighborhoods around `x_current`, attempting to converge towards a local optimum. Accepting only improving moves (`y_candidate < y_current`) ensures a greedy path towards better solutions within the walk.
# Boundary handling: Candidate solutions `x_candidate` are explicitly clipped to stay within the provided `lower_bound` and `upper_bound` of the search space using `np.clip`.
# Budget strategy: The total budget is divided between restarts and the steps within each walk. The algorithm continuously cycles between a restart (one evaluation) and an annealed walk (multiple evaluations). The length of each walk is dynamically determined based on the remaining budget and a heuristic maximum walk length. This ensures the budget is never exceeded and allows for multiple restart cycles.
# Closest known influences: Random Walk, Simulated Annealing (concept of annealing step size, though acceptance is simpler here), Multi-start optimization.
# Novelty or unusual aspects: The dynamic allocation of walk length based on remaining budget and a heuristic `max_walk_steps_per_restart` ensures the algorithm adapts its search intensity to the available resources without needing a predefined number of restarts or fixed walk durations.
# Failure modes: For very high-dimensional or rugged landscapes, the greedy improvement-only acceptance rule within the walk might get easily stuck in local optima. If the annealing rate is too fast, it might converge prematurely. If too slow, it might waste budget on large steps without sufficient exploitation. The choice of initial sigma and annealing rate is heuristic and might not be optimal for all problem types or budget constraints.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    An implementation of an Annealed Random Walk with Restarts for black-box minimization.
    """

    def __init__(self, budget: int, dim: int):
        """
        Initializes the algorithm with the given budget and dimensionality.

        Args:
            budget (int): The maximum number of function evaluations allowed.
            dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func) -> (np.ndarray, float):
        """
        Executes the optimization algorithm on the given objective function.

        Args:
            func: The objective function to minimize. It must be callable and
                  provide bounds via `func.lower`/`func.upper` or `func.bounds.lb`/`func.bounds.ub`.

        Returns:
            (np.ndarray, float): A tuple containing the best found solution (x)
                                 and its corresponding objective value (y).
        """
        # --- 1. Determine bounds ---
        # Prioritize func.bounds.lb/ub if available, otherwise func.lower/upper
        if hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lower_bound = np.array(func.bounds.lb)
            upper_bound = np.array(func.bounds.ub)
        elif hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower_bound = np.array(func.lower)
            upper_bound = np.array(func.upper)
        else:
            raise AttributeError("Function must provide bounds via 'func.lower/upper' or 'func.bounds.lb/ub'.")

        search_space_range = upper_bound - lower_bound

        # --- 2. Initialize best solution found so far ---
        best_x = None
        best_y = float('inf') # Use float('inf') for initial best_y
        eval_counter = 0

        # --- 3. Algorithm Parameters (Heuristics) ---
        # Initial step size relative to the search space range for each restart's walk.
        # This controls the initial exploration radius around a restart point.
        initial_sigma_ratio = 0.1
        # Target final step size as a ratio of the initial_sigma_ratio for a walk.
        # This determines how fine-grained the exploitation becomes by the end of a walk.
        final_sigma_ratio_in_walk = 0.01
        # Heuristic for maximum number of steps in a single annealed walk phase.
        # This prevents one walk from consuming too much budget if there's a lot left,
        # ensuring multiple restarts are possible.
        max_walk_steps_per_restart = self.dim * 50
        # Ensure at least a minimum number of steps if budget is very small, to avoid division by zero.
        min_walk_steps = 1

        # --- 4. Main Optimization Loop (Restart Cycle) ---
        while eval_counter < self.budget:
            # --- Restart Phase ---
            # Sample a new starting point uniformly across the search space
            x_current = np.random.uniform(lower_bound, upper_bound, self.dim)
            y_current = func(x_current)
            eval_counter += 1

            if y_current < best_y:
                best_y = y_current
                best_x = x_current.copy() # Store a copy of the array!

            # If budget exhausted after restart evaluation, break immediately
            if eval_counter >= self.budget:
                break

            # --- Annealed Walk Phase ---
            # Determine how many steps this walk can take given remaining budget
            remaining_budget_for_walk = self.budget - eval_counter
            # Limit walk length to a heuristic max or remaining budget, ensuring at least min_walk_steps
            walk_steps_for_this_restart = max(min_walk_steps, min(max_walk_steps_per_restart, remaining_budget_for_walk))

            # Calculate annealing rate: current_sigma will decrease from its initial value to
            # initial_value * final_sigma_ratio_in_walk over `walk_steps_for_this_restart` steps.
            current_sigma = initial_sigma_ratio * search_space_range
            annealing_rate = (final_sigma_ratio_in_walk)**(1.0 / walk_steps_for_this_restart)

            for _ in range(walk_steps_for_this_restart):
                # Generate a candidate solution by adding Gaussian noise scaled by current sigma
                # `np.random.randn(self.dim)` generates standard normal samples.
                x_candidate = x_current + np.random.randn(self.dim) * current_sigma

                # Clip the candidate to ensure it stays within the defined bounds
                x_candidate = np.clip(x_candidate, lower_bound, upper_bound)

                y_candidate = func(x_candidate)
                eval_counter += 1

                # If candidate is better, update current position for this walk (greedy acceptance)
                if y_candidate < y_current:
                    x_current = x_candidate
                    y_current = y_candidate

                # Always update the global best solution if a better one is found
                if y_candidate < best_y:
                    best_y = y_candidate
                    best_x = x_candidate.copy() # Store a copy of the array!

                # Anneal the step size for the next iteration
                current_sigma *= annealing_rate

                # If budget exhausted during walk, break all loops
                if eval_counter >= self.budget:
                    break

        return best_x, best_y
