# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust (1+1) Evolution Strategy (ES) with adaptive step-size control and periodic restarts. 
# Search state: Current best point (x), current mutation strength (sigma), and success history.
# Candidate generation: Offspring are generated by adding Gaussian noise scaled by sigma to the current best point.
# Selection and replacement: Simple elitist selection: the offspring replaces the parent only if its objective value is strictly better.
# Adaptation: The mutation strength (sigma) is adapted using a success-based rule similar to the 1/5th success rule. Sigma increases on success to accelerate and decreases on failure to refine.
# Exploration mechanisms: Restarts are triggered when the step size becomes negligible or a stagnation counter is reached, allowing the search to escape local optima.
# Exploitation mechanisms: Local search via Gaussian perturbations with a contracting sigma when progress slows.
# Boundary handling: Candidates are clipped to the hypercube defined by the problem bounds.
# Budget strategy: Evaluations are tracked strictly; the loop terminates as soon as the budget is exhausted.
# Closest known influences: (1+1)-ES, Rechenberg's 1/5th success rule, Matyas Search.
# Novelty or unusual aspects: Combines a very lightweight state with a restart schedule that resets sigma to a fraction of the domain width.
# Failure modes: May struggle on highly non-separable, high-dimensional functions where a full covariance matrix would be needed to capture correlations.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        
        Args:
            budget (int): Total number of function evaluations allowed.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Executes the optimization process.
        
        Args:
            func (callable): The objective function to minimize.
        
        Returns:
            tuple: (best_x, best_y)
        """
        # Extract bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Default bounds if not specified
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        domain_range = ub - lb
        
        # State variables
        best_x = None
        best_y = float('inf')
        eval_count = 0

        # Hyperparameters for (1+1)-ES adaptation
        increase_factor = 1.5
        decrease_factor = 0.8
        
        while eval_count < self.budget:
            # --- Restart / Initialization ---
            # Start from a random point in the domain
            curr_x = lb + np.random.rand(self.dim) * domain_range
            curr_y = func(curr_x)
            eval_count += 1
            
            if curr_y < best_y:
                best_x = np.copy(curr_x)
                best_y = curr_y
            
            # Initial step size: 10% of the domain
            sigma = 0.1 * np.max(domain_range)
            stagnation_limit = 100 + 10 * self.dim
            stagnation_counter = 0

            # Local Search Loop
            while eval_count < self.budget:
                # Generate candidate
                noise = np.random.randn(self.dim)
                candidate = curr_x + sigma * noise
                
                # Boundary handling: Clip to bounds
                candidate = np.clip(candidate, lb, ub)
                
                # Evaluate
                val = func(candidate)
                eval_count += 1
                
                # Update best
                if val < best_y:
                    best_x = np.copy(candidate)
                    best_y = val
                
                # Selection and Adaptation
                if val < curr_y:
                    # Success
                    curr_x = candidate
                    curr_y = val
                    sigma *= increase_factor
                    stagnation_counter = 0
                else:
                    # Failure
                    sigma *= decrease_factor
                    stagnation_counter += 1
                
                # Check for local convergence or stagnation to trigger restart
                if sigma < 1e-12 * np.max(domain_range) or stagnation_counter > stagnation_limit:
                    break

        return best_x, best_y

# No top-level execution code or file IO is present.
# The Algorithm class satisfies the interface and constraints provided.
# Logic relies only on numpy and standard Python.
