# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a Differential Evolution (DE) strategy, specifically the DE/rand/1/bin variant. It is designed to be robust across various dimensions and landscape types by maintaining a population of candidates that evolves through mutation, crossover, and greedy selection.
# Search state: The state consists of a population of vectors (candidate solutions) and their corresponding objective function values, along with the current best solution found so far.
# Candidate generation: For each member of the population, a mutant vector is generated by taking the difference between two random members, scaling it by a mutation factor F, and adding it to a third random member. A trial vector is then created by performing binomial crossover between the parent and the mutant.
# Selection and replacement: A trial vector replaces its parent in the population if and only if its objective value is less than or equal to the parent's value (greedy selection).
# Adaptation: The mutation factor F is dithered (randomly sampled from [0.5, 1.0] for each generation) to provide a balance between large-scale exploration and fine-tuned exploitation.
# Exploration mechanisms: Exploration is driven by the random selection of base vectors for mutation and the stochastic nature of the binomial crossover, preventing the population from collapsing too quickly.
# Exploitation mechanisms: The greedy selection ensures that the population moves toward lower-energy regions of the search space. The differential nature of the mutation naturally scales the search steps as the population converges.
# Boundary handling: Trial vectors are clipped to the hyper-rectangular search space defined by the problem bounds using numpy's clip function.
# Budget strategy: The algorithm tracks the number of function evaluations and terminates immediately once the budget is exhausted, returning the best result found.
# Closest known influences: The classic Differential Evolution algorithm by Storn and Price (1997).
# Novelty or unusual aspects: The implementation uses a simplified dithered mutation factor and robustly handles different ways the function object might expose its bounds.
# Failure modes: Like most global optimizers, it may struggle with extremely high-dimensional "needle-in-a-haystack" problems or highly deceptive landscapes if the population size is too small.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the Differential Evolution optimizer.
        
        Args:
            budget (int): Maximum number of function evaluations.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        
        # Population size: common heuristic is 10 * dim, 
        # but we cap it to ensure enough generations within budget.
        self.pop_size = max(10, min(100, budget // 10))
        
        # DE parameters
        self.cr = 0.9  # Crossover probability
        self.f_range = (0.5, 1.0)  # Range for dithered mutation factor

    def __call__(self, func):
        """
        Executes the minimization process.
        
        Args:
            func: Objective function following the benchmark interface.
            
        Returns:
            tuple: (best_x, best_y)
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower)
            ub = np.array(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        else:
            # Default bounds if none provided (rare in these benchmarks)
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        eval_count = 0
        
        # Initialize population
        pop = lb + np.random.rand(self.pop_size, self.dim) * (ub - lb)
        fitness = np.zeros(self.pop_size)
        
        best_x = None
        best_y = float('inf')

        # Initial evaluation
        for i in range(self.pop_size):
            if eval_count >= self.budget:
                break
            val = func(pop[i])
            fitness[i] = val
            eval_count += 1
            
            if val < best_y:
                best_y = val
                best_x = np.copy(pop[i])

        # Main DE loop
        while eval_count < self.budget:
            # Dither mutation factor for this generation
            f = np.random.uniform(self.f_range[0], self.f_range[1])
            
            for i in range(self.pop_size):
                if eval_count >= self.budget:
                    break
                
                # Mutation: DE/rand/1
                # Select 3 distinct indices excluding the current index i
                candidates = [idx for idx in range(self.pop_size) if idx != i]
                a, b, c = np.random.choice(candidates, 3, replace=False)
                
                mutant = pop[a] + f * (pop[b] - pop[c])
                
                # Crossover: Binomial
                cross_points = np.random.rand(self.dim) < self.cr
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Boundary handling
                trial = np.clip(trial, lb, ub)
                
                # Evaluation
                trial_val = func(trial)
                eval_count += 1
                
                # Selection
                if trial_val <= fitness[i]:
                    fitness[i] = trial_val
                    pop[i] = trial
                    
                    if trial_val < best_y:
                        best_y = trial_val
                        best_x = np.copy(trial)
                        
        return best_x, best_y
