# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: An adaptive (1+lambda) Evolution Strategy (ES) featuring periodic restarts 
# and 1/5th success rule step-size control. It is designed to balance local 
# exploitation with global exploration through restarts and dynamic mutation scales.
# Search state: Stores the current parent (centroid), the current mutation scale (sigma), 
# success history for adaptation, and the global best found across all restarts.
# Candidate generation: Offspring are generated by adding Gaussian noise to the 
# current parent, scaled by the adaptive sigma and the coordinate-wise range.
# Selection and replacement: A (1+lambda) selection scheme is used where the best 
# offspring replaces the parent if it is strictly better (minimization).
# Adaptation: The mutation strength (sigma) is updated using a simplified 1/5th 
# success rule: sigma increases if the success rate is high and decreases otherwise.
# Exploration mechanisms: Restarts are triggered when the local search stagnates or 
# a fixed number of evaluations are exhausted, re-initializing the search at a 
# random point in the search space.
# Exploitation mechanisms: The (1+lambda) structure focuses search around the current 
# best, with sigma decreasing to refine the solution as progress slows.
# Boundary handling: Offspring coordinates are clipped to the hypercube defined by 
# the problem's lower and upper bounds.
# Budget strategy: The algorithm tracks evaluations strictly, exiting as soon as 
# the budget is reached or exceeded. Restarts are scheduled to allow multiple 
# independent search trajectories within the budget.
# Closest known influences: Classical Evolution Strategies, specifically (1+lambda)-ES 
# with Rechenberg's 1/5th rule and the multi-restart strategy common in BBOB benchmarks.
# Novelty or unusual aspects: Combines a very lightweight state management with 
# robust adaptation logic suitable for various black-box landscape types.
# Failure modes: May struggle with highly non-separable functions or heavy 
# dependencies between variables as it uses an isotropic mutation (diagonal covariance).
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    An adaptive (1+lambda) Evolution Strategy with restarts.
    Designed for robust black-box minimization within a fixed budget.
    """
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.eval_count = 0
        
        # Hyperparameters
        # Lambda: number of offspring per generation
        self.lam = 4 + int(3 * np.log(dim))
        # Step size adaptation parameters
        self.sigma_init = 0.2
        self.sigma_min = 1e-9
        self.c_increase = 1.22
        self.c_decrease = 0.82
        # Restart threshold (evals per restart attempt)
        self.restart_evals = max(500, 100 * dim)

    def _get_bounds(self, func):
        """Extracts bounds from the function object attributes."""
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            return np.array(func.lower), np.array(func.upper)
        if hasattr(func, 'bounds'):
            return np.array(func.bounds.lb), np.array(func.bounds.ub)
        # Fallback to standard unit hypercube if no bounds found
        return np.zeros(self.dim), np.ones(self.dim)

    def __call__(self, func):
        lb, ub = self._get_bounds(func)
        span = ub - lb
        
        global_best_x = None
        global_best_y = float('inf')
        
        while self.eval_count < self.budget:
            # Initialize a new restart
            # Current parent
            x = lb + np.random.rand(self.dim) * span
            y = func(x)
            self.eval_count += 1
            
            if y < global_best_y:
                global_best_y = y
                global_best_x = x.copy()
            
            if self.eval_count >= self.budget:
                break
                
            sigma = self.sigma_init
            restart_limit = min(self.budget, self.eval_count + self.restart_evals)
            
            # Local search loop (1+lambda) ES
            while self.eval_count < restart_limit:
                successes = 0
                best_offspring_x = None
                best_offspring_y = float('inf')
                
                # Generate offspring
                for _ in range(self.lam):
                    if self.eval_count >= self.budget:
                        break
                        
                    # Mutation: isotropic Gaussian
                    noise = np.random.randn(self.dim) * sigma * span
                    offspring_x = np.clip(x + noise, lb, ub)
                    
                    offspring_y = func(offspring_x)
                    self.eval_count += 1
                    
                    if offspring_y < best_offspring_y:
                        best_offspring_y = offspring_y
                        best_offspring_x = offspring_x
                    
                    # Track global best
                    if offspring_y < global_best_y:
                        global_best_y = offspring_y
                        global_best_x = offspring_x.copy()

                # Termination check
                if self.eval_count >= self.budget:
                    break

                # Selection: (1+lambda)
                if best_offspring_y < y:
                    x = best_offspring_x
                    y = best_offspring_y
                    successes += 1
                    # Increase step size on success (simplified 1/5th rule logic)
                    sigma = min(2.0, sigma * self.c_increase)
                else:
                    # Decrease step size on failure
                    sigma = max(self.sigma_min, sigma * self.c_decrease)
                
                # Exit local search if sigma is too small (stagnation)
                if sigma < self.sigma_min:
                    break

        return global_best_x, global_best_y

# No top-level execution per requirements.
