# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A robust (mu + lambda) Evolution Strategy (ES) with adaptive step-size control.
# Search state: A population of candidate solutions, their associated objective values, and a global mutation strength (sigma).
# Candidate generation: Offspring are generated by adding Gaussian noise to randomly selected parents from the current population.
# Selection and replacement: Truncation selection is used to maintain a population of the 'mu' best-performing individuals from the combined pool of parents and offspring.
# Adaptation: The mutation strength (sigma) is adapted using a simplified success rule, increasing when improvements are frequent and decreasing otherwise, to balance exploration and exploitation.
# Exploration mechanisms: Initial population is sampled uniformly across the search space; large initial sigma values allow broad coverage.
# Exploitation mechanisms: Selection pressure towards lower objective values and the reduction of sigma over time as the search converges.
# Boundary handling: Offspring coordinates are clipped to the hyper-rectangle defined by the lower and upper bounds.
# Budget strategy: The algorithm tracks evaluations and terminates immediately once the budget is exhausted, returning the best solution found.
# Closest known influences: Classical Evolution Strategies (Rechenberg, Schwefel) and the 1/5th success rule adaptation.
# Novelty or unusual aspects: A minimalist, self-contained implementation designed for high reliability across varying dimensions without external dependencies.
# Failure modes: May struggle with highly deceptive landscapes or extremely narrow ridges where the success rate adaptation might stall.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the Evolution Strategy optimizer.
        
        :param budget: Total number of function evaluations allowed.
        :param dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        
        # Population parameters
        self.mu = max(1, int(4 + 3 * np.log(dim)))
        self.lambd = self.mu * 4
        
        # Success rule parameters
        self.target_success_rate = 0.2
        self.factor = 0.85
        
    def __call__(self, func):
        """
        Executes the optimization process.
        
        :param func: The objective function to minimize.
        :return: (best_x, best_y) tuple.
        """
        # Boundary extraction
        try:
            lb = np.array(func.bounds.lb)
            ub = np.array(func.bounds.ub)
        except AttributeError:
            lb = np.array(func.lower)
            ub = np.array(func.upper)
            
        eval_count = 0
        best_x = None
        best_y = float('inf')
        
        # Initialization
        sigma = 0.2 * np.mean(ub - lb)
        
        # Initial population
        pop_x = np.random.uniform(lb, ub, (self.mu, self.dim))
        pop_y = np.zeros(self.mu)
        
        for i in range(self.mu):
            if eval_count >= self.budget:
                break
            pop_y[i] = func(pop_x[i])
            eval_count += 1
            if pop_y[i] < best_y:
                best_y = pop_y[i]
                best_x = pop_x[i].copy()
                
        # Main optimization loop
        while eval_count < self.budget:
            # Generate offspring
            offspring_x = np.zeros((self.lambd, self.dim))
            offspring_y = np.zeros(self.lambd)
            successes = 0
            
            for i in range(self.lambd):
                if eval_count >= self.budget:
                    offspring_x = offspring_x[:i]
                    offspring_y = offspring_y[:i]
                    break
                
                # Selection of parent
                parent_idx = np.random.randint(0, self.mu)
                parent_x = pop_x[parent_idx]
                
                # Mutation
                child_x = parent_x + sigma * np.random.standard_normal(self.dim)
                child_x = np.clip(child_x, lb, ub)
                
                # Evaluation
                child_y = func(child_x)
                eval_count += 1
                
                offspring_x[i] = child_x
                offspring_y[i] = child_y
                
                if child_y < pop_y[parent_idx]:
                    successes += 1
                
                if child_y < best_y:
                    best_y = child_y
                    best_x = child_x.copy()
            
            # Combine population and offspring
            combined_x = np.vstack([pop_x, offspring_x])
            combined_y = np.concatenate([pop_y, offspring_y])
            
            # Truncation Selection
            indices = np.argsort(combined_y)
            pop_x = combined_x[indices[:self.mu]]
            pop_y = combined_y[indices[:self.mu]]
            
            # Adapt sigma (Success Rule)
            if len(offspring_y) > 0:
                actual_success_rate = successes / len(offspring_y)
                if actual_success_rate > self.target_success_rate:
                    sigma /= self.factor
                else:
                    sigma *= self.factor
            
            # Prevent sigma from collapsing or exploding relative to bounds
            min_sigma = 1e-9 * np.mean(ub - lb)
            max_sigma = 2.0 * np.mean(ub - lb)
            sigma = np.clip(sigma, min_sigma, max_sigma)
            
        return best_x, best_y
