# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses Differential Evolution (DE), specifically the DE/rand/1/bin strategy, which is a robust global optimization algorithm.
# Search state: The state consists of a population of candidate solutions (vectors), their corresponding objective function values, and the current evaluation count.
# Candidate generation: New candidates are generated by selecting three distinct individuals from the population. A mutant vector is created by adding a scaled difference between two individuals to the third. This mutant is then combined with the current target individual using binomial crossover.
# Selection and replacement: A greedy selection mechanism is used: if the trial candidate's fitness is better than or equal to the parent's fitness, it replaces the parent in the population for the next generation.
# Adaptation: The algorithm maintains constant mutation (F=0.8) and crossover (CR=0.9) parameters, which are generally effective across a wide range of non-convex problems.
# Exploration mechanisms: Exploration is driven by the mutation process, where the difference between random population members provides a search step that automatically scales with the population diversity.
# Exploitation mechanisms: Exploitation is achieved through the greedy selection of better candidates and the binomial crossover which preserves components of successful parents.
# Boundary handling: Candidates are clipped to the hyper-rectangular search space defined by the problem's lower and upper bounds.
# Budget strategy: The algorithm tracks every call to the objective function. It initializes the population one-by-one and proceeds with evolution, terminating immediately once the evaluation budget is exhausted.
# Closest known influences: Storn and Price's original Differential Evolution (1997).
# Novelty or unusual aspects: The implementation ensures strict adherence to the budget by wrapping the evaluation and checking the counter before every call, including during population initialization.
# Failure modes: For extremely small budgets relative to the dimension, DE may not have enough iterations to converge. For very high dimensions, the population size is capped to ensure progress is made within the budget.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    A robust Differential Evolution (DE) implementation for black-box minimization.
    Designed to handle arbitrary dimensions and respect strict evaluation budgets.
    """
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        # Hyperparameters for DE/rand/1/bin
        self.F = 0.8  # Scaling factor
        self.CR = 0.9 # Crossover probability
        # Population size adaptive to dimension but constrained by budget and practicality
        self.pop_size = min(self.budget, max(10, 10 * self.dim))
        if self.pop_size > 100:
            self.pop_size = 100

    def __call__(self, func):
        # 1. Extract bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.atleast_1d(func.lower)
            ub = np.atleast_1d(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.atleast_1d(func.bounds.lb)
            ub = np.atleast_1d(func.bounds.ub)
        else:
            # Fallback if no bounds are provided, though the spec suggests they will be
            lb = np.full(self.dim, -10.0)
            ub = np.full(self.dim, 10.0)

        # Ensure bounds are float arrays of correct dimension
        if lb.shape[0] != self.dim:
            lb = np.repeat(lb, self.dim) if lb.size == 1 else lb[:self.dim]
        if ub.shape[0] != self.dim:
            ub = np.repeat(ub, self.dim) if ub.size == 1 else ub[:self.dim]

        evals_count = 0
        best_x = None
        best_y = float('inf')

        def evaluate(x):
            nonlocal evals_count, best_x, best_y
            if evals_count >= self.budget:
                return None
            
            # Clip to bounds before evaluation
            x_clipped = np.clip(x, lb, ub)
            res = func(x_clipped)
            evals_count += 1
            
            if res < best_y:
                best_y = res
                best_x = x_clipped.copy()
            return res

        # 2. Population Initialization
        pop = []
        fitness = []
        for i in range(self.pop_size):
            if evals_count >= self.budget:
                break
            # Random uniform initialization
            ind = lb + (ub - lb) * np.random.rand(self.dim)
            fit = evaluate(ind)
            if fit is not None:
                pop.append(ind)
                fitness.append(fit)

        if not pop:
            return best_x, best_y

        pop = np.array(pop)
        fitness = np.array(fitness)
        actual_pop_size = len(pop)

        # 3. Evolution Loop
        while evals_count < self.budget:
            for i in range(actual_pop_size):
                if evals_count >= self.budget:
                    break
                
                # Mutation: DE/rand/1
                idxs = [idx for idx in range(actual_pop_size) if idx != i]
                if len(idxs) < 3:
                    # Not enough individuals for mutation, break to end
                    evals_count = self.budget
                    break
                
                a_idx, b_idx, c_idx = np.random.choice(idxs, 3, replace=False)
                mutant = pop[a_idx] + self.F * (pop[b_idx] - pop[c_idx])
                
                # Crossover: Binomial
                cross_points = np.random.rand(self.dim) < self.CR
                # Ensure at least one dimension is changed
                if not np.any(cross_points):
                    cross_points[np.random.randint(0, self.dim)] = True
                
                trial = np.where(cross_points, mutant, pop[i])
                
                # Selection
                f_trial = evaluate(trial)
                if f_trial is not None:
                    if f_trial <= fitness[i]:
                        pop[i] = trial
                        fitness[i] = f_trial

        return best_x, best_y
