# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: The algorithm is a Particle Swarm Optimization (PSO) method that maintains a swarm of candidate solutions (particles). Each particle moves over the search space with a velocity influenced by its own best previous position and the best position discovered by the entire swarm. The method continuously updates personal and global bests, respects the given evaluation budget, and finally returns the best solution found.
#
# Search state: A swarm of particles, each storing its current position, velocity, personal‑best position, and personal‑best fitness. A global‑best position and its fitness represent the best solution discovered so far.
#
# Candidate generation: New positions are generated by first updating each particle’s velocity using inertia, cognitive (personal‑best) and social (global‑best) terms, then adding the velocity to the current position. The velocity is clamped to a fraction of the search range to avoid excessive displacement.
#
# Selection and replacement: After each evaluation, a particle replaces its personal‑best if the current fitness is lower. The global‑best is updated whenever any personal‑best improves.
#
# Adaptation: The balance between exploration (through inertia and random perturbations) and exploitation (through attraction to personal and global bests) is controlled by an inertia weight and random coefficients. Velocity clamping adapts to the scale of each dimension.
#
# Exploration mechanisms: Random coefficients in the velocity update, inertia term, and velocity clamping provide exploration, preventing particles from collapsing prematurely.
#
# Exploitation mechanisms: The cognitive and social acceleration terms pull particles toward promising regions identified by personal and global bests.
#
# Boundary handling: After each position update, every component is clipped to the provided lower and upper bounds, ensuring feasible solutions.
#
# Budget strategy: The algorithm first evaluates the initial swarm, then runs as many full swarm updates as the remaining budget allows, and finally spends any leftover evaluations on random sampling to make full use of the budget.
#
# Closest known influences: Classic PSO (Clerc & Kennedy, 2002) with inertia weight; similar implementations appear in many black‑box optimization benchmarks.
#
# Novelty or unusual aspects: Dynamic velocity clamping based on the bound range, a fallback to pure random sampling when the budget cannot support a full swarm, and a straightforward budget‑enforcement scheme that never exceeds the allowed evaluations.
#
# Failure modes: If the budget is too small relative to the problem dimension, the swarm cannot explore thoroughly and may converge to a suboptimal solution. Highly rugged or deceptive landscapes may cause the swarm to get stuck in local minima.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple Particle Swarm Optimization (PSO) for black‑box minimization.

    Parameters
    ----------
    budget : int
        Maximum number of function evaluations allowed.
    dim : int
        Dimensionality of the problem (number of decision variables).
    """

    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Run the optimization algorithm on the provided objective function.

        Parameters
        ----------
        func : callable
            A black‑box objective that accepts a 1‑D NumPy array of length `dim`
            and returns a scalar (the function value). The function must
            expose either a `lower` / `upper` attribute pair or a `bounds`
            attribute with `lb` and `ub` fields that define the search domain.

        Returns
        -------
        best_x : np.ndarray
            The best (lowest‑value) solution found.
        best_y : float
            The corresponding objective value.
        """
        dim = self.dim
        budget = self.budget

        # ------------------------------------------------------------------
        # Retrieve search bounds (lower and upper limits) from the function.
        # ------------------------------------------------------------------
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower, dtype=float)
            upper = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            lower = np.asarray(func.bounds.lb, dtype=float)
            upper = np.asarray(func.bounds.ub, dtype=float)
        else:
            # Fallback: unit hyper‑cube if no bounds are supplied.
            lower = np.zeros(dim, dtype=float)
            upper = np.ones(dim, dtype=float)

        # Ensure the bounds are 1‑D arrays of length `dim`.
        if lower.ndim == 0:
            lower = np.full(dim, lower.item())
        if upper.ndim == 0:
            upper = np.full(dim, upper.item())

        # ------------------------------------------------------------------
        # Early exit if no evaluations are allowed.
        # ------------------------------------------------------------------
        if budget <= 0:
            # Return a feasible point and a worst‑case value.
            x0 = (lower + upper) / 2.0
            return x0, func(x0)

        # ------------------------------------------------------------------
        # Determine swarm size. It is bounded by the budget and a
        # problem‑size dependent heuristic (10 * dim), but never smaller than 1.
        # ------------------------------------------------------------------
        max_swarm = min(10 * dim, budget)
        swarm_size = max(1, max_swarm)

        # ------------------------------------------------------------------
        # Initialise particle positions and velocities.
        # ------------------------------------------------------------------
        # Positions: uniform random within the bounds.
        X = np.random.uniform(lower, upper, size=(swarm_size, dim))
        # Velocities: small random perturbations scaled by the bound range.
        v_range = 0.1 * (upper - lower)
        V = np.random.uniform(-v_range, v_range, size=(swarm_size, dim))

        # ------------------------------------------------------------------
        # Evaluate the initial swarm.
        # ------------------------------------------------------------------
        fitness = np.empty(swarm_size, dtype=float)
        for i in range(swarm_size):
            fitness[i] = func(X[i])

        evals = swarm_size

        # Personal bests (positions and fitness).
        pbest_x = X.copy()
        pbest_y = fitness.copy()

        # Global best.
        gbest_idx = np.argmin(pbest_y)
        gbest_x = pbest_x[gbest_idx].copy()
        gbest_y = pbest_y[gbest_idx]

        # ------------------------------------------------------------------
        # Main PSO loop – run as many full swarm updates as the budget permits.
        # ------------------------------------------------------------------
        # Number of full iterations we can afford after the initial evaluation.
        remaining = budget - evals
        full_iterations = remaining // swarm_size

        # Inertia weight (often denoted w) and cognitive/social coefficients.
        w = 0.729
        c1 = 1.49445
        c2 = 1.49445

        for _ in range(full_iterations):
            # Random matrices for the velocity update.
            r1 = np.random.uniform(0.0, 1.0, size=(swarm_size, dim))
            r2 = np.random.uniform(0.0, 1.0, size=(swarm_size, dim))

            # Velocity update (standard PSO formula).
            V = (w * V
                 + c1 * r1 * (pbest_x - X)
                 + c2 * r2 * (gbest_x - X))

            # Velocity clamping to avoid excessive jumps.
            max_v = 0.2 * (upper - lower)
            V = np.clip(V, -max_v, max_v)

            # Position update.
            X = X + V
            X = np.clip(X, lower, upper)

            # Evaluate the new positions.
            for i in range(swarm_size):
                fitness[i] = func(X[i])
                evals += 1

                # Update personal best.
                if fitness[i] < pbest_y[i]:
                    pbest_x[i] = X[i].copy()
                    pbest_y[i] = fitness[i]

                    # Update global best.
                    if fitness[i] < gbest_y:
                        gbest_x = X[i].copy()
                        gbest_y = fitness[i]

        # ------------------------------------------------------------------
        # Utilise any leftover evaluations with random sampling.
        # ------------------------------------------------------------------
        leftover = budget - evals
        if leftover > 0:
            X_extra = np.random.uniform(lower, upper, size=(leftover, dim))
            for i in range(leftover):
                f_val = func(X_extra[i])
                evals += 1
                if f_val < gbest_y:
                    gbest_x = X_extra[i].copy()
                    gbest_y = f_val

        # At this point `evals` equals `budget`.
        return gbest_x, gbest_y
