import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary:
#   This module provides a simple evolutionary optimizer that follows a (1+λ)
#   strategy. A single parent (the current best point) generates λ offspring by
#   adding isotropic Gaussian noise. After evaluating the offspring, the best
#   individual among parent and offspring becomes the new parent. A single
#   step‑size (σ) controls the mutation strength and is adapted online: it is
#   increased when the best solution improves and decreased otherwise. The
#   algorithm respects the evaluation budget strictly and stops as soon as the
#   budget is exhausted.
#
# Search state:
#   - mean: the current best point (a NumPy array of dimension dim).
#   - sigma: the current step‑size (scalar) controlling the spread of the
#     Gaussian mutations.
#   - lower, upper: bound vectors defining the feasible hyper‑rectangle.
#
# Candidate generation:
#   Offspring are created as   candidate = mean + sigma * N(0, I_d)
#   where N(0, I_d) denotes a d‑dimensional standard normal draw. The
#   candidate is then projected into the bounds by component‑wise clipping.
#
# Selection and replacement:
#   The parent and all offspring are evaluated and ranked by their objective
#   values. The best μ individuals survive; in this implementation μ is set to
#   1, i.e. only the single best individual (parent or offspring) is kept as
#   the new mean for the next generation. This yields a (1+λ) strategy.
#
# Adaptation:
#   σ is multiplied by 1.2 when the new best point improves over the previous
#   best, otherwise it is multiplied by 0.8. This heuristic mirrors the 1/5‑rule
#   idea of increasing exploration when progress is being made and tightening
#   the search when no progress is observed. σ is clamped to a tiny fraction
#   (1e‑6) of the initial range and to at most half of that range to avoid
#   numerical issues.
#
# Exploration mechanisms:
#   Large σ encourages sampling far from the current mean, which helps the
#   algorithm discover new basins. Randomness is introduced via the Gaussian
#   perturbation and via the initial random mean (center of the bounds).
#
# Exploitation mechanisms:
#   As σ decreases, the sampling radius shrinks, allowing the algorithm to
#   refine the current best solution. The elitist selection guarantees that
#   the best observed point is never lost.
#
# Boundary handling:
#   After a candidate is generated, each coordinate is clipped to the
#   interval [lower_i, upper_i]. This simple projection keeps the search
#   feasible but may slightly distort the distribution near the boundaries.
#
# Budget strategy:
#   The algorithm tracks the number of performed function evaluations and
#   never exceeds the supplied budget. If the remaining budget is smaller than
#   the desired offspring count, it generates only as many candidates as can
#   still be evaluated. The first evaluation is the initial mean; thereafter
#   the main loop proceeds generation‑by‑generation until the budget is
#   exhausted.
#
# Closest known influences:
#   The implementation is inspired by classic (1+1) and (1+λ) Evolution
#   Strategies with self‑adapting step‑size, as described in
#   Bäck, Fogel, and Michalewicz (1997). It simplifies the original CMA‑ES
#   by using an isotropic Gaussian mutation and a single‑individual
#   selection, making it lightweight and easy to understand.
#
# Novelty or unusual aspects:
#   Using only a single parent and a variable‑size offspring pool keeps memory
#   usage minimal. The adaptive σ rule is a straightforward heuristic that
#   does not require covariance estimation, making the code compact and
#   dependent only on NumPy.
#
# Failure modes:
#   - Premature convergence: with a limited budget the algorithm may get stuck
#     in a local optimum, especially on highly multi‑modal landscapes.
#   - Boundary distortion: clipping can bias the search when the true optimum
#     lies near a bound.
#   - Inappropriate σ scaling: if the initial σ is set far outside the optimal
#     range, adaptation may be slow.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    """
    Simple evolutionary optimizer for black‑box minimization.

    The class follows a (1+λ) Evolution Strategy with a single parent
    (the current best point) and λ offspring generated by isotropic Gaussian
    mutations. The step‑size σ is adapted online based on improvement.
    The optimizer respects the evaluation budget strictly.

    Parameters
    ----------
    budget : int
        Maximum number of objective‑function evaluations allowed.
    dim : int
        Dimensionality of the search space.
    """

    def __init__(self, budget: int, dim: int):
        self.budget = budget
        self.dim = dim

        # Population sizes are chosen proportionally to the dimension.
        # They are later adjusted if the budget does not allow such a large
        # population.
        self.mu = max(1, int(dim * 5))
        self.lambda_ = max(2, int(dim * 20))

        # Initial step‑size; will be refined once bounds are known.
        self.sigma = 0.1

        # Internal state that will be set during a call.
        self.mean = None          # current best point (numpy array)
        self.lower = None        # lower bound vector
        self.upper = None        # upper bound vector

    def __call__(self, func):
        """
        Perform the optimization.

        Parameters
        ----------
        func : callable
            A black‑box objective function that accepts a NumPy array of shape
            (dim,) and returns a scalar (the objective value).

        Returns
        -------
        best_x : numpy.ndarray
            The best (lowest‑valued) point found.
        best_y : float
            The corresponding objective value.
        """
        # ----- obtain bounds -------------------------------------------------
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            self.lower = np.asarray(func.lower, dtype=float)
            self.upper = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            self.lower = np.asarray(func.bounds.lb, dtype=float)
            self.upper = np.asarray(func.bounds.ub, dtype=float)
        else:
            # Fallback: use a symmetric box of [-10, 10] for every dimension.
            self.lower = np.full(self.dim, -10.0)
            self.upper = np.full(self.dim, 10.0)

        if self.lower.shape[0] != self.dim or self.upper.shape[0] != self.dim:
            raise ValueError(
                f"Bounds length does not match the specified dimension "
                f"{self.dim}."
            )

        # ----- initialise search state ---------------------------------------
        # start at the centre of the feasible region
        self.mean = (self.lower + self.upper) / 2.0

        # set sigma relative to the typical range of the bounds
        range_len = (self.upper - self.lower).mean()
        self.sigma = 0.1 * range_len

        # clamp sigma to avoid trivial extremes
        self.sigma = float(np.clip(self.sigma, 1e-6 * range_len, 0.5 * range_len))

        # evaluate the initial point
        best_x = self.mean.copy()
        best_y = func(best_x)
        evals = 1

        # If the budget is exhausted after the initial evaluation, return now.
        if evals >= self.budget:
            return best_x, best_y

        # ----- main optimisation loop ----------------------------------------
        while evals < self.budget:
            # How many offspring can we still afford?
            remaining = self.budget - evals
            lam = min(self.lambda_, remaining)

            # generate λ offspring
            offspring_x = np.empty((lam, self.dim), dtype=float)
            for i in range(lam):
                # isotropic Gaussian mutation
                z = np.random.normal(0.0, 1.0, self.dim)
                cand = self.mean + self.sigma * z
                # project into the feasible box
                cand = np.clip(cand, self.lower, self.upper)
                offspring_x[i] = cand

            # evaluate offspring
            offspring_y = np.empty(lam, dtype=float)
            for i in range(lam):
                offspring_y[i] = func(offspring_x[i])
                evals += 1

            # ----- selection (including the parent) -------------------------
            # pool parent and offspring together
            all_x = np.vstack([self.mean.reshape(1, -1), offspring_x])
            all_y = np.concatenate([[best_y], offspring_y])

            # keep the best μ individuals; here μ == 1
            best_idx = int(np.argmin(all_y))
            new_mean = all_x[best_idx]
            new_best_y = all_y[best_idx]

            # ----- step‑size adaptation --------------------------------------
            if new_best_y < best_y:
                # improvement: increase exploration a bit
                self.sigma *= 1.2
                best_x = new_mean.copy()
                best_y = new_best_y
            else:
                # no improvement: tighten the search radius
                self.sigma *= 0.8

            # keep sigma within safe limits
            range_len = (self.upper - self.lower).mean()
            self.sigma = float(np.clip(self.sigma, 1e-6 * range_len, 0.5 * range_len))

            # move to the new mean
            self.mean = new_mean

            # stop if budget is now exhausted
            if evals >= self.budget:
                break

        return best_x, best_y
