# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a simple but robust evolutionary optimization
# algorithm for black-box minimization. It uses a population-based random search
# with adaptive step size control, suitable for continuous optimization problems.
#
# Search state: The algorithm maintains a current best solution (best_x, best_y),
# a population of candidate solutions, and an adaptive step size. The step size
# controls the radius of candidate generation around the current best.
#
# Candidate generation: New candidates are generated by sampling uniformly
# within [best_x - step_size, best_x + step_size] for each dimension, then
# clipped to problem bounds. This creates a "warped grid" search centered on
# the best known solution.
#
# Selection and replacement: After evaluating each candidate, only the best
# candidate replaces the current solution if it improves. Otherwise, the step
# size decreases (contraction). This ensures monotonic improvement.
#
# Adaptation: The step size adaptation uses a simple success-based rule: if
# the candidate improves the best_y, step_size *= 1.2 (expansion); otherwise,
# step_size *= 0.5 (contraction). This balances exploration vs exploitation.
#
# Exploration mechanisms: Large step size allows broad exploration; uniform
# sampling across dimensions provides diverse search directions.
#
# Exploitation mechanisms: Small step size focuses search near current best;
# monotonic selection ensures only improving moves are kept.
#
# Boundary handling: Candidates are clipped to [lower, upper] bounds per
# dimension after generation. Step size is also bounded to prevent overflow.
#
# Budget strategy: Evaluations are counted precisely; the main loop checks
# (budget - evals) >= 1 before each candidate evaluation to guarantee budget
# is never exceeded.
#
# Closest known influences: Combines elements of local random search and
# simple evolution strategies. The adaptive step size mirrors simulated
# annealing's temperature decay concept but with direct success feedback.
#
# Novelty or unusual aspects: Uses asymmetric step size adaptation (1.2 vs 0.5)
# which creates a "momentum" effect - once improving, expansion accelerates
# exploration; stagnation causes rapid contraction.
#
# Failure modes: May get stuck in local minima on highly multi-modal
# functions; poor performance on discontinuous landscapes where small steps
# cannot cross barriers; initial step size may be poorly scaled for
# differently-sized problem domains.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


class Algorithm:
    """
    A simple adaptive random search algorithm for black-box minimization.
    
    Uses a population of candidates centered on the current best solution,
    with adaptive step size to balance exploration and exploitation.
    """
    
    def __init__(self, budget, dim):
        """
        Initialize the algorithm with budget and problem dimension.
        
        Args:
            budget: Maximum number of function evaluations allowed.
            dim: Problem dimension (number of variables).
        """
        self.budget = budget
        self.dim = dim
    
    def __call__(self, func):
        """
        Minimize the objective function.
        
        Args:
            func: Objective function implementing the benchmark interface.
                Must support evaluation via func(x) and provide bounds via
                either func.lower/func.upper or func.bounds.lb/func.bounds.ub.
        
        Returns:
            tuple: (best_x, best_y) where best_x is the solution found and
                   best_y is the corresponding function value (minimized).
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower, dtype=np.float64)
            upper = np.asarray(func.upper, dtype=np.float64)
        elif hasattr(func, 'bounds'):
            lower = np.asarray(func.bounds.lb, dtype=np.float64)
            upper = np.asarray(func.bounds.ub, dtype=np.float64)
        else:
            # Fallback: assume default bounds of [0, 1] per dimension
            lower = np.zeros(self.dim, dtype=np.float64)
            upper = np.ones(self.dim, dtype=np.float64)
        
        # Calculate initial step size based on problem bounds
        # Using diagonal of the hypercube as initial radius
        range_per_dim = upper - lower
        initial_step = np.mean(range_per_dim) * 0.5
        
        # Current best solution (start with random initial point)
        best_x = np.random.uniform(lower, upper)
        best_y = func(best_x)
        evals = 1
        
        # Adaptive step size
        step_size = initial_step
        
        # Main optimization loop
        while evals < self.budget:
            # Calculate how many candidates we can still evaluate
            remaining = self.budget - evals
            if remaining <= 0:
                break
            
            # Generate one candidate: sample around current best within step_size
            # Clamp ensures candidates stay within step_size radius
            candidate_x = np.clip(
                best_x + np.random.uniform(-step_size, step_size, size=self.dim),
                lower,
                upper
            )
            
            # Evaluate candidate
            candidate_y = func(candidate_x)
            evals += 1
            
            # Selection: keep better solution
            if candidate_y < best_y:
                best_x = candidate_x
                best_y = candidate_y
                # Expand step size (exploration reward)
                step_size *= 1.2
            else:
                # Contract step size (exploitation reward)
                step_size *= 0.5
            
            # Prevent step size from becoming too small or too large
            step_size = np.clip(step_size, np.min(range_per_dim) * 1e-6, np.max(range_per_dim) * 10)
        
        return best_x, best_y
