# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A simple (1+λ) evolutionary strategy with step‑size adaptation (the 1/5‑rule) is used to minimize a black‑box function within a fixed evaluation budget.
# Search state: The algorithm maintains a single parent solution and a scalar step size σ that controls the spread of Gaussian mutations. No population covariance matrix is maintained.
# Candidate generation: Offspring are generated by adding Gaussian noise (σ·N(0,I)) to the parent vector, then clipping to the problem’s bound hyper‑rectangle.
# Selection and replacement: After each batch of λ offspring, the best among the parent and its children replaces the parent. If an offspring improves the parent’s fitness, it becomes the new parent and a success counter is incremented.
# Adaptation: σ is adjusted after every generation using the classic 1/5 rule: if the fraction of successful mutations exceeds 20 %, σ is multiplied by 1.2; otherwise it is multiplied by 0.8. σ is kept within a small minimum (1e‑6 of the bound range) and a maximum (50 % of the bound range). If σ drops below the minimum, the algorithm re‑initializes the parent randomly to escape stagnation.
# Exploration mechanisms: Large σ encourages broad exploration; the random restart also injects diversity.
# Exploitation mechanisms: When σ shrinks, mutations become finer, allowing the algorithm to exploit the current best region.
# Boundary handling: Candidate vectors are clipped element‑wise to the user‑provided lower/upper bounds, preventing evaluations outside the feasible domain.
# Budget strategy: The algorithm tracks remaining evaluations and stops as soon as the budget is exhausted, never performing more than the allowed number of func calls.
# Closest known influences: Simple (1+1)‑ES, step‑size adaptation from Rechenberg’s 1/5 rule, and restart heuristics from continuous evolutionary algorithms.
# Novelty or unusual aspects: The use of a fixed λ (scaled with dimension) and a per‑generation σ adaptation provides a balance between simplicity and robustness without external libraries.
# Failure modes: If the landscape is highly multi‑modal and the budget is small, the single‑parent strategy may get trapped; restarting mitigates this but cannot guarantee global optimum.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple (1+λ) evolutionary strategy with step‑size adaptation for black‑box minimization.
    Works with any budget and dimension, using only standard library and numpy.
    """
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        # ------------------------------------------------------------------
        # Determine search bounds (prefer func.lower/func.upper, fallback to func.bounds.lb/ub)
        # ------------------------------------------------------------------
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower, dtype=float)
            upper = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            lower = np.asarray(func.bounds.lb, dtype=float)
            upper = np.asarray(func.bounds.ub, dtype=float)
        else:
            # Fallback to unit hypercube if no bounds are provided
            lower = np.zeros(self.dim, dtype=float)
            upper = np.ones(self.dim, dtype=float)

        # Ensure lower <= upper (swap if necessary)
        if np.any(lower > upper):
            lower, upper = upper, lower

        # ------------------------------------------------------------------
        # Helper to evaluate a candidate and update the best found solution
        # ------------------------------------------------------------------
        remaining = self.budget          # evaluations left
        best_x = None
        best_y = np.inf

        def eval_and_update(x):
            nonlocal remaining, best_x, best_y
            y = func(x)
            remaining -= 1
            if best_x is None or y < best_y:
                best_y = y
                best_x = x.copy()
            return y

        # ------------------------------------------------------------------
        # Initialize parent and step size
        # ------------------------------------------------------------------
        rng = upper - lower
        x_parent = lower + rng * np.random.rand(self.dim)
        f_parent = eval_and_update(x_parent)

        sigma0 = rng * 0.1               # initial step size
        sigma_min = rng * 1e-6
        sigma_max = rng * 0.5
        sigma = sigma0.copy()

        # ------------------------------------------------------------------
        # Evolution loop: generate λ offspring per generation
        # ------------------------------------------------------------------
        offsprings = max(4, 2 * self.dim)  # λ
        success = 0

        while remaining > 0:
            # Produce a batch of λ offspring
            for _ in range(offsprings):
                if remaining == 0:
                    break
                # Mutation: add Gaussian noise scaled by σ
                x_off = x_parent + sigma * np.random.randn(self.dim)
                # Clip to feasible region
                x_off = np.clip(x_off, lower, upper)
                f_off = eval_and_update(x_off)

                # Accept if offspring improves parent
                if f_off < f_parent:
                    x_parent = x_off
                    f_parent = f_off
                    success += 1

            # ------------------------------------------------------------------
            # Step‑size adaptation (1/5 rule)
            # ------------------------------------------------------------------
            success_rate = success / offsprings
            if success_rate > 0.2:
                sigma = np.clip(sigma * 1.2, sigma_min, sigma_max)
            else:
                sigma = np.clip(sigma * 0.8, sigma_min, sigma_max)

            success = 0

            # ------------------------------------------------------------------
            # Restart if σ becomes too small (stagnation guard)
            # ------------------------------------------------------------------
            if np.any(sigma < sigma_min):
                x_parent = lower + rng * np.random.rand(self.dim)
                f_parent = eval_and_update(x_parent)
                sigma = sigma0.copy()

        return best_x, best_y
