# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a simple but robust evolutionary strategy for black-box minimization on the GNBG benchmark. It uses a (mu+lambda) evolution strategy with self-adaptive step size and restart mechanism to handle varying landscapes.
# Search state: The algorithm maintains a population of candidate solutions and a step size sigma that controls the mutation strength. The population is represented as a 2D numpy array (mu x dim). The best found solution and its fitness are tracked.
# Candidate generation: Offspring are generated by selecting a parent from the top half of the population (rank-based selection) and mutating it with a random normally distributed vector scaled by sigma. The mutated candidate is clipped to the problem bounds.
# Selection and replacement: After evaluating offspring, the algorithm combines the parent population and offspring, then selects the best mu individuals based on fitness (minimization). This is a plus-selection strategy, meaning parents can survive if they are among the top mu.
# Adaptation: The step size sigma is adapted based on whether the best fitness improved. If the best fitness decreased (improved), sigma is increased by 20%; otherwise, it is decreased by 10%. This is a simple success-based rule. Sigma is also bounded to prevent it from becoming too small or too large relative to the domain.
# Exploration mechanisms: The algorithm uses a population-based search with mutation, allowing it to explore multiple regions. The adaptive sigma helps balance exploration and exploitation.
# Exploitation mechanisms: Selection focuses on the best individuals, guiding the search toward promising areas. The adaptive sigma reduces exploration as the search converges.
# Boundary handling: Candidate solutions are clipped to the problem bounds (lower/upper) after mutation to ensure feasibility.
# Budget strategy: The algorithm strictly respects the evaluation budget. It initializes a population and then iteratively generates offspring in batches, updating the best solution. It stops when the budget is exhausted or when the step size becomes too small, triggering a restart (if evaluations remain).
# Closest known influences: This is a simplified (mu+lambda) evolution strategy with step size adaptation, reminiscent of CMA-ES but without covariance matrix adaptation. It is inspired by classical evolutionary algorithms like the (μ+λ)-EA with self-adaptation.
# Novelty or unusual aspects: The algorithm uses a rank-based parent selection and a simple success-based step size adaptation, which may be less efficient than CMA-ES but is simpler and more robust to noisy functions due to the population-based approach.
# Failure modes: If the budget is very small (e.g., less than the population size), the algorithm may only perform a few evaluations and not converge. The simple adaptation rule may cause sigma to oscillate in highly noisy environments, reducing performance. Restart logic may not be triggered if sigma is already within acceptable bounds, potentially causing premature convergence.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        # Population size: use a reasonable default that scales with dimension
        # but limit to budget/2 to ensure at least one generation if budget is small.
        self.pop_size = min(max(4, dim), max(2, budget // 2), 100)
        # If budget is smaller than pop_size, set pop_size to budget.
        if self.pop_size > budget:
            self.pop_size = budget

    def __call__(self, func):
        # Read bounds from func
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower)
            upper = np.asarray(func.upper)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lower = np.asarray(func.bounds.lb)
            upper = np.asarray(func.bounds.ub)
        else:
            # Default bounds if not provided (common for GNBG)
            lower = -np.ones(self.dim) * 10
            upper = np.ones(self.dim) * 10

        # Ensure bounds are numpy arrays of correct shape
        lower = np.asarray(lower, dtype=float)
        upper = np.asarray(upper, dtype=float)
        if lower.shape != (self.dim,):
            lower = np.full(self.dim, lower[0] if lower.size == 1 else 0.0)
        if upper.shape != (self.dim,):
            upper = np.full(self.dim, upper[0] if upper.size == 1 else 1.0)

        # Initialize population uniformly in bounds
        pop = np.random.uniform(lower, upper, (self.pop_size, self.dim))
        # Evaluate initial population
        fitness = np.array([func(x) for x in pop])
        evals = self.pop_size

        # Track best solution
        best_idx = np.argmin(fitness)
        best_x = pop[best_idx].copy()
        best_y = fitness[best_idx]

        # If budget is less than pop_size, return best from initial sample
        if evals >= self.budget:
            return best_x, best_y

        # Initialize step size (sigma) as a fraction of the domain range
        sigma = 0.5 * (upper - lower).mean()
        # Set adaptation parameters
        sigma_increase = 1.2
        sigma_decrease = 0.9
        sigma_min = 1e-6 * (upper - lower).mean()
        sigma_max = (upper - lower).mean()
        prev_best_y = best_y

        # Main evolution loop
        while evals < self.budget:
            # Generate offspring
            lambda_ = self.pop_size
            offspring = np.empty((lambda_, self.dim))
            offspring_fitness = np.empty(lambda_)

            # Determine how many offspring we can generate within budget
            remaining = self.budget - evals
            if remaining < lambda_:
                lambda_ = remaining

            for i in range(lambda_):
                # Select parent from top half of population (rank-based)
                # Use tournament selection: pick 2 random from top half and choose best
                top_half_indices = np.argsort(fitness)[:self.pop_size // 2]
                if len(top_half_indices) < 2:
                    parent_idx = top_half_indices[0]
                else:
                    candidates = np.random.choice(top_half_indices, 2, replace=False)
                    parent_idx = candidates[0] if fitness[candidates[0]] < fitness[candidates[1]] else candidates[1]
                parent = pop[parent_idx]

                # Mutate: add normally distributed vector scaled by sigma
                mutation = sigma * np.random.randn(self.dim)
                candidate = parent + mutation
                # Clip to bounds
                candidate = np.clip(candidate, lower, upper)

                # Evaluate
                fitness_val = func(candidate)
                evals += 1

                offspring[i] = candidate
                offspring_fitness[i] = fitness_val

                # Update best if improvement
                if fitness_val < best_y:
                    best_x = candidate.copy()
                    best_y = fitness_val

                # Stop if budget exhausted
                if evals >= self.budget:
                    # If we haven't filled all offspring, fill remaining with copies of best to maintain array sizes? Not needed.
                    # We can break and then select from what we have.
                    break

            # If we broke early due to budget, we might have fewer offspring
            # Adjust lambda_ to actual number generated
            actual_lambda = i + 1

            # Combine parents and offspring for selection
            combined_pop = np.vstack([pop, offspring[:actual_lambda]])
            combined_fitness = np.concatenate([fitness, offspring_fitness[:actual_lambda]])

            # Select best mu individuals (mu = pop_size)
            # If combined size is larger than pop_size, take top pop_size
            if combined_pop.shape[0] > self.pop_size:
                # Use argpartition for efficiency, but we need the top pop_size
                # Actually, we want the smallest fitness (minimization), so we can use argsort
                selected_indices = np.argsort(combined_fitness)[:self.pop_size]
            else:
                selected_indices = np.arange(combined_pop.shape[0])

            pop = combined_pop[selected_indices]
            fitness = combined_fitness[selected_indices]

            # Adapt sigma based on improvement
            if best_y < prev_best_y:
                # Improvement, increase sigma
                sigma = min(sigma * sigma_increase, sigma_max)
                prev_best_y = best_y
            else:
                # No improvement, decrease sigma
                sigma = max(sigma * sigma_decrease, sigma_min)

            # Optional: restart if sigma is too small (indicates convergence)
            # But we only restart if we have enough budget for another population evaluation
            if sigma < sigma_min and (self.budget - evals) >= self.pop_size:
                # Restart: reinitialize population
                pop = np.random.uniform(lower, upper, (self.pop_size, self.dim))
                fitness = np.array([func(x) for x in pop])
                evals += self.pop_size
                # Update best
                best_idx = np.argmin(fitness)
                if fitness[best_idx] < best_y:
                    best_x = pop[best_idx].copy()
                    best_y = fitness[best_idx]
                # Reset sigma to initial value
                sigma = 0.5 * (upper - lower).mean()
                prev_best_y = best_y

            # If budget exhausted, break
            if evals >= self.budget:
                break

        return best_x, best_y
