# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A simple (1+1) Evolution Strategy with an adaptive step size (1/5 rule) for bound-constrained black-box minimization. The algorithm starts with a random solution, then iteratively mutates it using Gaussian perturbations scaled by a step vector. If a mutant improves the current objective it is accepted; otherwise it is discarded. The step size is periodically adjusted based on the recent success rate, and the algorithm restarts from a new random point when the step size becomes too small relative to the search range.
# Search state: The optimizer maintains the current solution (vector), its objective value, the best solution found so far, the number of evaluations performed, the current step size vector (one per dimension), and counters for successes and failures used for adaptation.
# Candidate generation: A new candidate is generated by adding independent Gaussian noise to the current solution. The noise standard deviation in each dimension equals the corresponding entry of the step size vector, which is then clipped to the problem’s bounds.
# Selection and replacement: The candidate replaces the current solution only if its objective value is less than or equal to that of the current solution (minimization). The global best solution is updated whenever a better objective is encountered.
# Adaptation: Every adapt_every evaluations (at least 10 or dim*10) the algorithm computes the success rate (proportion of improvements). If the rate exceeds 0.2 the step size is multiplied by 1.2 (exploration), otherwise it is multiplied by 0.8 (exploitation). The step size is also clamped between a tiny fraction and twice the bound range to avoid runaway values.
# Exploration mechanisms: A relatively large initial step size (≈1/5 of the bound range) encourages broad sampling. Random restarts occur when the step size becomes too small, reinitializing the current solution to a fresh random point within the bounds.
# Exploitation mechanisms: As the algorithm discovers improvements, the success‑based adaptation reduces the step size, focusing the search around the current best region. Clipping to bounds prevents stepping outside the feasible region.
# Boundary handling: All candidate vectors are clipped component‑wise to the provided lower and upper bounds. If the function object supplies scalar bounds they are expanded to match the problem dimension.
# Budget strategy: The total number of function evaluations is strictly limited by the budget argument. The algorithm evaluates exactly one solution per iteration, checks the counter after each evaluation, and aborts before any extra evaluation that would exceed the budget. Any restart evaluations are also gated by the remaining budget.
# Closest known influences: The implementation is closely related to the classic (1+1) Evolution Strategy with the 1/5 success rule and to simple random search methods. It also shares ideas with re‑initialization strategies used in hybrid local search.
# Novelty or unusual aspects: The use of per‑dimension step sizes (rather than a single global sigma) combined with a simple restart trigger offers a balance between simplicity and robustness. The code is compact and relies only on NumPy and the standard library, making it easy to embed in any benchmark harness.
# Failure modes: The algorithm may become trapped in local optima, especially on rugged or highly multi‑modal landscapes. Its performance degrades in very high dimensions or when the objective is heavily stochastic, because the success‑rate adaptation can misinterpret noise. The restart mechanism mitigates some stagnation but cannot guarantee global convergence.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np


def _extract_bounds(func):
    """Extract lower and upper bounds from a function object.

    Supports two common conventions:
        func.lower / func.upper   (scalars or arrays)
        func.bounds.lb / func.bounds.ub   (objects with .lb and .ub)

    Returns
    -------
    lower, upper : numpy.ndarray
        Column vectors containing the lower and upper bounds.
    """
    if hasattr(func, 'lower') and hasattr(func, 'upper'):
        lower = np.asarray(func.lower)
        upper = np.asarray(func.upper)
    elif hasattr(func, 'bounds'):
        lower = np.asarray(func.bounds.lb)
        upper = np.asarray(func.bounds.ub)
    else:
        raise ValueError("Cannot determine bounds of the function. "
                         "Expected attributes 'lower'/'upper' or 'bounds.lb'/'bounds.ub'.")
    # Ensure 1‑D arrays
    if lower.ndim == 0:
        lower = np.atleast_1d(lower)
        upper = np.atleast_1d(upper)
    return lower, upper


class Algorithm:
    """Simple (1+1)-ES with adaptive step size for bound‑constrained minimization.

    Parameters
    ----------
    budget : int
        Maximum number of function evaluations allowed.
    dim : int
        Dimensionality of the problem (number of decision variables).
    """

    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

        # Internal state (will be set in __call__)
        self.current_x = None
        self.current_y = None
        self.best_x = None
        self.best_y = None
        self.evaluations = 0

        # Step size vector (one entry per dimension)
        self.step_size = None

        # Adaptation counters
        self.success_count = 0
        self.failure_count = 0
        self.adapt_every = None

    def __call__(self, func):
        """Run the optimizer and return (best_x, best_y)."""
        # ------------------------------------------------------------------
        # Guard against zero budget
        if self.budget <= 0:
            # Return any feasible point with infinite objective
            lower, upper = _extract_bounds(func)
            lower = np.asarray(lower, dtype=float)
            upper = np.asarray(upper, dtype=float)
            if lower.shape[0] != self.dim:
                if lower.shape[0] == 1:
                    lower = np.full(self.dim, lower[0])
                    upper = np.full(self.dim, upper[0])
                else:
                    raise ValueError("Dimension mismatch between bounds and specified dim.")
            return lower, np.inf

        # ------------------------------------------------------------------
        # Extract and validate bounds
        lower, upper = _extract_bounds(func)
        if lower.shape[0] != self.dim:
            if lower.shape[0] == 1 and self.dim > 1:
                # Expand scalar bounds to full dimensionality
                lower = np.full(self.dim, lower[0], dtype=float)
                upper = np.full(self.dim, upper[0], dtype=float)
            else:
                raise ValueError("Dimension of bounds does not match specified dim.")
        else:
            lower = lower.astype(float)
            upper = upper.astype(float)

        # ------------------------------------------------------------------
        # Initialise step size (per dimension) and adaptation parameters
        range_per_dim = upper - lower
        self.step_size = range_per_dim / 5.0
        self.adapt_every = max(10, self.dim * 10)

        # ------------------------------------------------------------------
        # Initial random solution
        self.current_x = lower + np.random.rand(self.dim) * range_per_dim
        self.current_y = func(self.current_x)
        self.evaluations = 1
        self.best_x = self.current_x.copy()
        self.best_y = self.current_y

        # ------------------------------------------------------------------
        # Main optimisation loop (1+1)-ES
        while self.evaluations < self.budget:
            # Generate candidate by Gaussian perturbation
            candidate_x = self.current_x + self.step_size * np.random.randn(self.dim)
            candidate_x = np.clip(candidate_x, lower, upper)

            # Evaluate candidate
            candidate_y = func(candidate_x)
            self.evaluations += 1

            # Selection and replacement
            if candidate_y <= self.current_y:
                self.current_x = candidate_x
                self.current_y = candidate_y
                self.success_count += 1
                if candidate_y <= self.best_y:
                    self.best_x = candidate_x.copy()
                    self.best_y = candidate_y
            else:
                self.failure_count += 1

            # ------------------------------------------------------------------
            # Adaptation of step size using the 1/5 success rule
            if self.evaluations % self.adapt_every == 0:
                total = self.success_count + self.failure_count
                if total > 0:
                    success_rate = self.success_count / total
                    if success_rate > 0.2:
                        self.step_size *= 1.2
                    else:
                        self.step_size *= 0.8

                # Reset counters
                self.success_count = 0
                self.failure_count = 0

                # Keep step size within reasonable bounds
                min_step = range_per_dim / 1e6
                max_step = range_per_dim * 2
                self.step_size = np.clip(self.step_size, min_step, max_step)

                # Restart if step size becomes negligible
                if np.all(self.step_size < min_step * 10):
                    if self.evaluations < self.budget:
                        # Re‑initialise to a new random point
                        self.current_x = lower + np.random.rand(self.dim) * range_per_dim
                        self.current_y = func(self.current_x)
                        self.evaluations += 1
                        if self.current_y <= self.best_y:
                            self.best_x = self.current_x.copy()
                            self.best_y = self.current_y
                    # If we have exhausted the budget during restart, exit
                    if self.evaluations >= self.budget:
                        break

        return self.best_x, self.best_y
