# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: The algorithm blends a lightweight global exploration phase with a
# coordinate‑wise pattern search that adapts its step size dynamically.  It
# starts by drawing a modest number of random samples to locate a promising
# region, then switches to a “Hooke‑Jeeves” style search that probes the
# neighbourhood along each axis.  Whenever an improvement is found the step
# vector is enlarged (up to the initial size) and when the whole pattern
# fails the step is shrunk.  If the step falls below a tiny fraction of the
# search range the method is restarted from a fresh random point to escape
# possible local traps.
# Search state: best_x (current best solution), best_y (its objective value),
# ev (evaluation counter), step (vector of per‑dimension step lengths), and
# a flag indicating whether a restart is required.
# Candidate generation: Uniform random samples for the initial phase;
# for the local phase a candidate is generated by moving a single coordinate
# of best_x by +step[i] or –step[i] and clipping the result into the bounds.
# Selection and replacement: Any candidate that yields a strictly smaller
# objective value replaces best_x / best_y.
# Adaptation: Step vector is multiplied by 1.2 after a successful improvement
# and by 0.5 after a full pattern with no improvement.  A restart occurs when
# any component of step falls below 1e‑5 times the corresponding bound range.
# Exploration mechanisms: Initial random sampling and forced restarts.
# Exploitation mechanisms: Axis‑parallel pattern search around the best point.
# Boundary handling: All proposed points are clipped to the supplied bounds
# (func.lower/upper or func.bounds.lb/ub).  If no bounds are supplied a
# default of [-100, 100] per dimension is used.
# Budget strategy: An evaluation counter is incremented on every call to
# func; the algorithm aborts as soon as the counter reaches the supplied
# budget, guaranteeing that the budget is never exceeded.
# Closest known influences: Pure random search for global exploration and the
# classic Hooke‑Jeeves direct search for local exploitation.
# Novelty or unusual aspects: The step vector is per‑dimension and its length
# is adapted independently; restarts are triggered automatically when the step
# becomes negligible, providing a simple escape from plateaus.
# Failure modes: If the budget is extremely small (e.g., < dim+1) the method
# may only perform random sampling and can return a sub‑optimal solution.
# In highly multi‑modal or noisy landscapes the adaptive restart may still
# get trapped, but the algorithm remains cheap and requires no parameter tuning.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple black‑box minimizer that combines random sampling with an adaptive
    coordinate‑wise pattern search (Hooke‑Jeeves style).  The implementation
    respects the supplied evaluation budget and works for any dimension.
    """

    def __init__(self, budget, dim):
        """
        Parameters
        ----------
        budget : int
            Maximum number of objective function evaluations allowed.
        dim : int
            Dimensionality of the problem (number of decision variables).
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Minimise `func` under the given evaluation budget.

        Parameters
        ----------
        func : callable
            Objective function that accepts a 1‑d NumPy array of length `dim`
            and returns a scalar (the objective value).

        Returns
        -------
        best_x : np.ndarray
            Best solution found (bound‑clipped).
        best_y : float
            Objective value at ``best_x``.
        """
        # ------------------------------------------------------------------
        # Determine search bounds (prefer func.lower/func.upper, fall back to
        # func.bounds.lb / func.bounds.ub, and finally a default [-100,100]).
        # ------------------------------------------------------------------
        lb, ub = self._get_bounds(func)

        # ------------------------------------------------------------------
        # Global exploration: a small fraction of the budget is spent on
        # uniform random sampling to locate a promising region.
        # ------------------------------------------------------------------
        n_init = max(1, int(0.05 * self.budget))   # 5 % of budget, at least 1
        best_x, best_y, ev = None, np.inf, 0

        for _ in range(n_init):
            if ev >= self.budget:
                break
            x = self._random_point(lb, ub)
            y = func(x)
            ev += 1
            if y < best_y:
                best_y, best_x = y, x

        # If the budget is already exhausted after the initial sampling, return.
        if ev >= self.budget:
            return best_x, best_y

        # ------------------------------------------------------------------
        # Local exploitation: adaptive Hooke‑Jeeves pattern search.
        # ------------------------------------------------------------------
        # Initial step = 5 % of the range in each dimension.
        range_vec = ub - lb
        step = range_vec * 0.05
        min_step = range_vec * 1e-5           # restart threshold

        while ev < self.budget:
            improved = False

            # ---- Pattern: try a move of +/- step[i] along each coordinate ----
            for i in range(self.dim):
                for sign in (1, -1):
                    if ev >= self.budget:
                        break
                    cand = best_x.copy()
                    # Clip only the perturbed coordinate to its bounds.
                    cand[i] = np.clip(cand[i] + sign * step[i], lb[i], ub[i])
                    y = func(cand)
                    ev += 1
                    if y < best_y:
                        best_y, best_x = y, cand
                        improved = True
                        break   # early exit from sign loop
                if improved:
                    break       # early exit from dimension loop

            if improved:
                # ---- Step enlargement after an improvement ----
                step = np.clip(step * 1.2, min_step, range_vec)
                continue        # go to next iteration

            # ---- No improvement in the whole pattern: shrink step ----
            step = step * 0.5

            # ---- If step has become negligible, restart from a new random point ----
            if np.any(step < min_step):
                if ev >= self.budget:
                    break
                x = self._random_point(lb, ub)
                y = func(x)
                ev += 1
                if y < best_y:
                    best_y, best_x = y, x
                # Reset step to the initial size.
                step = range_vec * 0.05

        return best_x, best_y

    # ----------------------------------------------------------------------
    # Helper methods
    # ----------------------------------------------------------------------
    def _get_bounds(self, func):
        """
        Extract lower and upper bounds from `func`.  The function may expose
        ``lower``/``upper`` attributes or a ``bounds`` object with ``lb``/``ub``.
        If neither exists, a default interval of [-100, 100] is returned.
        """
        try:
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
            return lb, ub
        except AttributeError:
            pass

        try:
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)
            return lb, ub
        except AttributeError:
            pass

        # Default bounds when nothing is provided.
        default = np.array([-100.0, 100.0])
        lb = np.full(self.dim, default[0])
        ub = np.full(self.dim, default[1])
        return lb, ub

    def _random_point(self, lb, ub):
        """
        Generate a single random point uniformly distributed within the given
        bounds.
        """
        return np.random.uniform(lb, ub)
