# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: The algorithm is a lightweight adaptive random search that starts with a batch of uniform random samples to locate a promising region and then switches to a local search phase. In the local phase a candidate is generated by adding a Gaussian perturbation (scaled by a per‑dimension step size vector) to the best solution found so far. If the candidate improves the best value the step size is enlarged, otherwise it is contracted. When the search stagnates for a predefined number of evaluations a random restart re‑samples a new point in the domain, providing a simple mechanism for escaping local optima.
#
# Search state: The optimizer stores the current best solution (best_x, best_y) and a vector of step sizes (radius) for each dimension.
#
# Candidate generation: A new point is created as best_x + radius * N(0,1), i.e., a Gaussian move with isotropic but dimension‑specific scaling.
#
# Selection and replacement: The candidate replaces the current best only if its objective value is strictly lower.
#
# Adaptation: The radius vector is multiplied by 1.2 after a successful move and by 0.8 after a failure, while being kept within a minimal (1e‑4 of the range) and maximal (0.5 of the range) bound.
#
# Exploration mechanisms: Initial uniform sampling across the whole domain and occasional random restarts when no improvement has been seen for stagnation_limit consecutive evaluations.
#
# Exploitation mechanisms: Small Gaussian steps around the best known point, with the step size shrinking when the search fails to improve, focusing on fine‑tuning a promising region.
#
# Boundary handling: All generated points are clipped to the problem’s lower and upper bounds.
#
# Budget strategy: Every call to the objective function increments an evaluation counter; the algorithm stops as soon as the counter reaches the supplied budget. No extra function calls are performed beyond the budget.
#
# Closest known influences: Classic random search, hill‑climbing, and the (1+1)‑evolutionary strategy with a 1/5‑th success rule for step‑size adaptation.
#
# Novelty or unusual aspects: The method uses a per‑dimension step size vector without maintaining an explicit population, keeping memory usage minimal. The restart trigger based on stagnation is a simple yet effective way to avoid premature convergence.
#
# Failure modes: In highly multi‑modal landscapes where the global optimum occupies an extremely small region, the random restarts may still miss it. If the step size shrinks too quickly the search can become trapped; the restart condition mitigates this but cannot guarantee global convergence. The algorithm also assumes that function evaluations are inexpensive, as it performs no surrogate modelling.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple adaptive random search for black‑box minimization.

    The optimizer starts with a set of uniform random samples and then
    iteratively perturbs the best solution found so far using Gaussian
    steps whose size adapts based on success or failure.  When no
    improvement is observed for a predefined number of evaluations,
    a random restart is performed to explore a new region of the space.
    """

    def __init__(self, budget, dim):
        """
        Parameters
        ----------
        budget : int
            Maximum number of objective‑function evaluations allowed.
        dim : int
            Dimensionality of the problem (number of variables).
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Run the optimization.

        Parameters
        ----------
        func : callable
            Objective function to be minimized.  It must accept a
            NumPy array of shape (dim,) and return a scalar.

        Returns
        -------
        best_x : np.ndarray
            Solution point that attained the lowest objective value.
        best_y : float
            The corresponding objective value.
        """
        # ------------------------------------------------------------------
        # Extract lower and upper bounds from the function object.
        # The benchmark interface is assumed to expose either
        #   func.lower / func.upper
        # or
        #   func.bounds.lb / func.bounds.ub
        # ------------------------------------------------------------------
        if hasattr(func, 'lower'):
            lb = np.asarray(func.lower, dtype=float)
            if lb.ndim == 0:
                lb
