# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a simple (1+1) Evolution Strategy (ES) for bound‑constrained black‑box minimization.
#          Starting from a uniformly sampled initial point, the algorithm repeatedly creates a mutant by adding an
#          isotropic Gaussian perturbation to the current best solution. After each fitness evaluation it performs
#          elitist selection, i.e. it keeps the better of the two points. The step size (mutation strength) is
#          continuously adapted using the classic 1/5 success rule, which aims to keep the ratio of successful
#          mutations near 20 %. Boundary violations are corrected by reflecting the offending coordinate back into
#          the allowed interval.
#
# Search state: The algorithm maintains the currently best solution (best_x) and its objective value (best_y),
#                the current mutation step size sigma, and a sliding window that records whether the last N mutations
#                improved the solution.
#
# Candidate generation: A candidate is generated by x_candidate = best_x + sigma * Z, where Z ~ N(0, I) is a
#                       standard normal vector.
#
# Selection and replacement: The candidate replaces the current best only if its objective value is strictly lower
#                            (minimization). This yields a (1+1) elitist strategy.
#
# Adaptation: After every window of N evaluations (N = max(10, 2·dim)), the fraction of successful mutations is
#             computed. If it exceeds 0.2, sigma is multiplied by 1.2 (increase step size); if it is lower than
#             0.2, sigma is multiplied by 0.8 (decrease step size). The window is then reset.
#
# Exploration mechanisms: Large sigma encourages broad exploration; Gaussian perturbations explore all dimensions
#                         independently.
#
# Exploitation mechanisms: Elitist retention of the best point guarantees monotone progress and allows fine-tuning
#                         once sigma becomes small.
#
# Boundary handling: After mutation each coordinate that lies outside [lower, upper] is reflected back into the
#                    interval by mirroring it about the bound (e.g., x = 2·lb – x for a value below the lower bound).
#                    The reflection is repeated until all coordinates are inside.
#
# Budget strategy: The main loop stops as soon as the number of performed function evaluations reaches the supplied
#                  budget. No extra evaluations are performed beyond this limit.
#
# Closest known influences: The algorithm follows the (1+1) Evolution Strategy with the 1/5 rule originally due
#                           to Rechenberg and Schwefel (1970s), a textbook method for real‑parameter optimization.
#
# Novelty or unusual aspects: The implementation uses a sliding window of successes (rather than a fixed generation
#                             count) to trigger step‑size adaptation, which makes the adaptation responsive to the
#                             current problem dimensionality.
#
# Failure modes: If the optimum lies on a very narrow ridge and sigma shrinks prematurely, the algorithm may stall.
#                It also assumes box constraints; more sophisticated handling of arbitrary constraints is not provided.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple (1+1) Evolution Strategy for bound‑constrained black‑box minimization.
    Implements the public interface:
        __init__(self, budget, dim)
        __call__(self, func) -> (best_x, best_y)
    """
    def __init__(self, budget, dim):
        """
        Parameters
        ----------
        budget : int
            Maximum number of objective function evaluations allowed.
        dim : int
            Dimensionality of the search space.
        """
        if budget < 0:
            raise ValueError("Budget must be non‑negative")
        if dim <= 0:
            raise ValueError("Dimension must be positive")
        self.budget = int(budget)
        self.dim = int(dim)

    def _get_bounds(self, func):
        """
        Retrieve lower and upper bounds for each dimension.
        Checks the common ways bounds can be supplied:
            - func.lower / func.upper
            - func.bounds.lb / func.bounds.ub
            - otherwise default to [0,1] per dimension.
        Returns
        -------
        lb, ub : numpy.ndarray
            Arrays of shape (dim,) containing lower and upper bounds.
        """
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)
        else:
            # No explicit bounds – assume unit hypercube
            lb = np.zeros(self.dim, dtype=float)
            ub = np.ones(self.dim, dtype=float)
        if lb.shape != (self.dim,) or ub.shape != (self.dim,):
            raise ValueError("Dimension of bounds does not match the declared dim")
        return lb, ub

    def __call__(self, func):
        """
        Run the optimization.

        Parameters
        ----------
        func : callable
            Black‑box objective function. Expected to accept a 1‑D numpy array of length dim
            and return a scalar (the objective value).

        Returns
        -------
        best_x : numpy.ndarray
            Best (lowest) solution found.
        best_y : float
            Objective value of best_x.
        """
        budget = self.budget
        dim = self.dim

        # If no evaluations are allowed, return a dummy solution without calling func
        if budget == 0:
            return np.zeros(dim), np.inf

        # Determine problem bounds
        lb, ub = self._get_bounds(func)

        # Sample initial solution uniformly within the bounds
        x = np.random.uniform(lb, ub)
        y = func(x)
        evals = 1

        best_x = x.copy()
        best_y = y

        # Initial mutation step size (1/6 of the average range)
        sigma = (ub - lb) / 6.0  # vector of per‑dimension step sizes

        # Sliding window for success rate (size grows with dimension)
        window = max(10, dim * 2)
        successes = []  # 1 if the last mutation improved, 0 otherwise

        # Main optimization loop
        while evals < budget:
            # Generate mutant by adding Gaussian noise scaled by sigma
            candidate = best_x + sigma * np.random.randn(dim)

            # Reflect any coordinate that fell outside the bounds
            # Repeat until all coordinates lie inside (rarely needs more than one iteration)
            while np.any(candidate < lb) or np.any(candidate > ub):
                mask_low = candidate < lb
                candidate[mask_low] = 2.0 * lb[mask_low] - candidate[mask_low]

                mask_high = candidate > ub
                candidate[mask_high] = 2.0 * ub[mask_high] - candidate[mask_high]

            # Clip remaining numerical issues (e.g., tiny round‑off)
            candidate = np.clip(candidate, lb, ub)

            # Evaluate candidate
            cand_y = func(candidate)
            evals += 1

            # Elitist selection: keep the better of the two points
            if cand_y < best_y:
                best_x = candidate.copy()
                best_y = cand_y
                successes.append(1)
            else:
                successes.append(0)

            # Adapt step size after the sliding window is full
            if len(successes) >= window:
                success_rate = sum(successes) / len(successes)
                if success_rate > 0.2:
                    sigma *= 1.2
                elif success_rate < 0.2:
                    sigma *= 0.8
                # Reset window
                successes = []

        return best_x, best_y
