# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A compact (1+1) Evolution Strategy with Rechenberg's 1/5 success rule for step‑size adaptation. It performs a simple Gaussian mutation around the current solution, accepts improvements, and periodically tunes the mutation radius to balance exploration and exploitation.
# Search state: Current point (parent), best point found so far, global step‑size factor, and a block‑wise success counter.
# Candidate generation: A new candidate is generated by adding a Gaussian perturbation whose standard deviation is the step‑size factor multiplied by a fraction (20 %) of each dimension's bound range.
# Selection and replacement: If the candidate’s objective value is not larger than the current point’s, the candidate becomes the new current point. The best solution is updated whenever the candidate improves upon the current best.
# Adaptation: After every block of 10 × dimension evaluations the algorithm computes the recent success ratio (fraction of accepted candidates). If the ratio exceeds 0.2 the step‑size factor is increased by 20 %; if it is lower, the factor is decreased by 20 %. The factor is clamped to avoid extreme steps.
# Exploration mechanisms: Large step‑size factor encourages broad search; the Gaussian perturbation is unbounded but clipped to the problem bounds.
# Exploitation mechanisms: Small step‑size factor focuses search around the current best; acceptance rule ensures only non‑worsening moves are kept.
# Boundary handling: After mutation each component of the candidate is clipped to the provided lower and upper bounds (via func.lower/upper or func.bounds.lb/ub).
# Budget strategy: Exactly one function evaluation is consumed per iteration; the algorithm stops as soon as the evaluation counter reaches the supplied budget.
# Closest known influences: Classic (1+1) evolution strategy with the 1/5 success rule (Rechenberg, 1973) and simple Gaussian mutation.
# Novelty or unusual aspects: No novel components; the implementation emphasizes simplicity, readability, and dimension‑independent robustness.
# Failure modes: On highly multi‑modal landscapes the strategy may become trapped in local minima, especially when the evaluation budget is insufficient. The fixed block size for adaptation may be suboptimal for very small budgets.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Simple (1+1) Evolution Strategy with 1/5 success rule for bound‑constrained
    black‑box minimization.  Uses only NumPy and the Python standard library.
    """

    def __init__(self, budget: int, dim: int):
        """
        Parameters
        ----------
        budget : int
            Maximum number of function evaluations allowed.
        dim : int
            Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Run the optimization and return the best solution found.

        Parameters
        ----------
        func : callable
            Black‑box objective function. Expected to accept a 1‑D NumPy array
            of length `dim` and return a scalar (the objective value).
            The function must expose either ``func.lower`` / ``func.upper`` or
            ``func.bounds.lb`` / ``func.bounds.ub`` describing the domain.

        Returns
        -------
        best_x : np.ndarray
            Best (lowest) objective vector found.
        best_y : float
            Corresponding objective value.
        """
        # ------------------------------------------------------------------
        # Retrieve problem bounds (lower, upper).  Support two common APIs.
        # ------------------------------------------------------------------
        try:
            lower = np.asarray(func.lower, dtype=float)
            upper = np.asarray(func.upper, dtype=float)
        except AttributeError:
            try:
                lower = np.asarray(func.bounds.lb, dtype=float)
                upper = np.asarray(func.bounds.ub, dtype=float)
            except AttributeError:
                # Fallback: assume unit hyper‑cube if bounds are missing.
                lower = np.zeros(self.dim, dtype=float)
                upper = np.ones(self.dim, dtype=float)

        # Ensure lower <= upper element‑wise (scalar broadcast works).
        if np.any(lower > upper):
            raise ValueError("Lower bound exceeds upper bound for some dimensions.")

        # ------------------------------------------------------------------
        # Initialisation
        # ------------------------------------------------------------------
        # Initial point drawn uniformly inside the domain.
        current_x = np.random.uniform(lower, upper)
        current_y = func(current_x)
        evals = 1

        # Keep track of the best solution seen so far.
        best_x = current_x.copy()
        best_y = current_y

        # If the budget is zero, return the (unevaluated) best point.
        if self.budget <= 0:
            return best_x, best_y

        # ------------------------------------------------------------------
        # Parameters for the (1+1) ES.
        # ------------------------------------------------------------------
        # Range of each dimension (used to scale the mutation step).
        range_vec = upper - lower                     # shape (dim,)
        # Global step‑size factor (multiplied by the 20 % fraction of the range).
        sigma_factor = 1.0
        # Minimum and maximum allowed step‑size factors (relative to the range).
        sigma_min = 1e-3
        sigma_max = 10.0

        # Block size for adaptation (Rechenberg's 1/5 rule is applied per block).
        block_size = max(10 * self.dim, 1)
        successes = 0
