# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module provides a minimal Particle Swarm Optimization (PSO) implementation for black‑box minimization. It manages a swarm of particles that explore the bounded domain guided by personal and global best positions.
# Search state: Each particle stores its current position, velocity, personal best position (pbest) and its objective value. A global best (gbest) is maintained across the swarm.
# Candidate generation: New positions are generated by updating velocities with inertia, cognitive (self‑experience) and social (swarm‑experience) components. Positions are then updated by adding velocities.
# Selection and replacement: After evaluating the objective, a particle updates its personal best if the new position is better. The global best is refreshed by taking the best personal best across the swarm.
# Adaptation: No explicit parameter adaptation is performed; inertia weight and acceleration coefficients are fixed. Velocities are clamped to prevent them from becoming too large.
# Exploration mechanisms: Random components in velocity updates and uniform initialization across the whole search space provide broad exploration.
# Exploitation mechanisms: Particles move toward promising personal and global best positions, concentrating the search around good solutions.
# Boundary handling: Positions are clipped to the lower/upper bounds after each update. Velocity clamping limits the maximum step size, further keeping particles inside the domain.
# Budget strategy: The algorithm evaluates the objective exactly `budget` times. It performs as many full swarm iterations as the budget allows and discards any remainder that cannot complete a full iteration.
# Closest known influences: Classic PSO as described by Kennedy & Eberhart (2001) with a global topology.
# Novelty or unusual aspects: The implementation is intentionally simple and uses only NumPy, without optional enhancements like constriction factors, adaptive swarm size, or local topologies.
# Failure modes: If the budget is smaller than the chosen swarm size, the algorithm reduces the swarm to fit the budget, resulting in a plain random search with no swarm dynamics. Very small dimensions may also cause the swarm to be too small for effective search.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Particle Swarm Optimization (PSO) for bounded black‑box minimization.

    Parameters
    ----------
    budget : int
        Maximum number of objective function evaluations.
    dim : int
        Dimensionality of the search space.
    """

    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

    def __call__(self, func):
        """
        Run PSO and return the best found solution and its objective value.

        Parameters
        ----------
        func : callable
            A black‑box objective function. It must accept a 1‑D array of shape (dim,)
            and return a scalar (the objective value). The function is assumed to
            provide bounds either via attributes ``lower``/``upper`` or
            ``bounds.lb``/``bounds.ub``.

        Returns
        -------
        best_x : np.ndarray
            The best solution vector found.
        best_y : float
            The corresponding objective value.
        """
        # ------------------------------------------------------------------
        # 1. Determine search bounds
        # ------------------------------------------------------------------
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower, dtype=float)
            upper = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds'):
            lower = np.asarray(func.bounds.lb, dtype=float)
            upper = np.asarray(func.bounds.ub, dtype=float)
        else:
            raise ValueError(
                "func must expose 'lower'/'upper' or 'bounds.lb'/'bounds.ub' attributes."
            )

        # Ensure bounds are column vectors of length dim
        if lower.shape[-1] != self.dim:
            raise ValueError(
                f"Lower bound dimension {lower.shape[-1]} does not match dim {self.dim}."
            )
        if upper.shape[-1] != self.dim:
            raise ValueError(
                f"Upper bound dimension {upper.shape[-1]} does not match dim {self.dim}."
            )

        # ------------------------------------------------------------------
        # 2. Swarm configuration (size limited by budget)
        # ------------------------------------------------------------------
        # Choose a reasonable swarm size; reduce it if the budget is smaller.
        desired_swarm_size = max(1, int(np.ceil(self.dim * 10)))  # 10 * dim, at least 1
        pop_size = min(desired_swarm_size, self.budget)

        # If the budget is too small to even evaluate the initial swarm, we just
        # perform random sampling without any PSO iteration.
        if pop_size == 0:
            # Edge case: budget == 0 (unlikely but handle gracefully)
            # Return a random point inside the bounds.
            x = lower + (upper - lower) * np.random.rand(self.dim)
            return x, float(func(x))

        # ------------------------------------------------------------------
        # 3. Initialize particle positions, velocities, and personal bests
        # ------------------------------------------------------------------
        # Positions: uniform random in the hyper‑rectangle
        X = lower + (upper - lower) * np.random.rand(pop_size, self.dim)

        # Velocities: small random steps (scaled by the range)
        range_vec = upper - lower
        # Guard against zero range (then set a nominal velocity)
        range_vec = np.where(range_vec == 0, 1.0, range_vec)
        V = range_vec * np.random.uniform(-0.1, 0.1, size=(pop_size, self.dim))

        # Evaluate initial positions
        evals = 0
        Y = np.empty(pop_size, dtype=float)
        for i in range(pop_size):
            Y[i] = func(X[i])
            evals += 1

        # Personal bests
        pbest_X = X.copy()
        pbest_Y = Y.copy()

        # Global best
        best_idx = int(np.argmin(Y))
        gbest_X = X[best_idx].copy()
        gbest_Y = Y[best_idx]

        # ------------------------------------------------------------------
        # 4. PSO main loop (perform full iterations while budget allows)
        # ------------------------------------------------------------------
        # PSO parameters (fixed, no adaptation)
        w = 0.7          # inertia weight
        c1 = 1.4         # cognitive coefficient
        c2 = 1.4         # social coefficient

        # Velocity clamping: limit the step size to a fraction of the search range
        v_max = 0.2 * range_vec

        # Continue as long as we can evaluate a full swarm without exceeding the budget
        while evals + pop_size <= self.budget:
            # Random factors for cognitive and social components
            r1 = np.random.rand(pop_size, self.dim)
            r2 = np.random.rand(pop_size, self.dim)

            # Update velocities
            V = (w * V
                 + c1 * r1 * (pbest_X - X)
                 + c2 * r2 * (gbest_X - X))

            # Clip velocities to the allowed range
            V = np.clip(V, -v_max, v_max)

            # Update positions
            X = X + V

            # Enforce bound constraints
            X = np.clip(X, lower, upper)

            # Evaluate the new positions
            for i in range(pop_size):
                Y[i] = func(X[i])
                evals += 1

            # Update personal bests where improvement occurred
            improved = Y < pbest_Y
            pbest_X[improved] = X[improved]
            pbest_Y[improved] = Y[improved]

            # Update global best
            min_idx = int(np.argmin(pbest_Y))
            if pbest_Y[min_idx] < gbest_Y:
                gbest_X = pbest_X[min_idx].copy()
                gbest_Y = pbest_Y[min_idx]

        # ------------------------------------------------------------------
        # 5. Return the best solution found
        # ------------------------------------------------------------------
        return gbest_X, float(gbest_Y)
