# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This module implements a compact Differential Evolution (DE) algorithm
# with a classic rand/1/bin scheme for black-box minimization. It is designed to be
# robust across different dimensions and budgets, using only numpy and the Python
# standard library.
# Search state: A population of candidate solutions (real vectors) stored in a 2D
# numpy array, with their corresponding objective values in a separate array. The
# best solution found so far and its value are tracked.
# Candidate generation: For each target vector in the population, a mutant vector
# is created by adding the scaled difference of two randomly chosen distinct
# population vectors to a third distinct vector (DE/rand/1). A trial vector is
# generated by binomial crossover between the target and mutant vectors.
# Selection and replacement: The trial vector is evaluated only if it differs from
# the target (to avoid redundant evaluations). It replaces the target if its
# objective value is less than or equal to the target's value (minimization).
# Adaptation: No online parameter adaptation is used; the scaling factor F and
# crossover probability CR are fixed at typical values (0.5 and 0.9 respectively).
# Exploration mechanisms: The differential mutation operator provides directed
# exploration by sampling the difference between random population members, which
# naturally scales with the population's spread. Crossover encourages mixing of
# components from the mutant and target.
# Exploitation mechanisms: The greedy selection (replace if better) allows the
# population to converge towards promising regions. The best solution is preserved
# across generations.
# Boundary handling: Generated trial vectors that violate box constraints are
# reflected back into the feasible space using the simple technique: for
# coordinate = 2 * bound - coordinate, with a final clamp to guarantee feasibility.
# Budget strategy: The population size is chosen dynamically based on the budget
# and dimensionality. The number of generations is computed to use the entire
# evaluation budget efficiently (every evaluation except the initial population
# evaluations is used in a generation step).
# Closest known influences: Standard Differential Evolution (Storn & Price, 1997)
# with DE/rand/1/bin and fixed parameters.
# Novelty or unusual aspects: No unusual aspects; the implementation is a vanilla
# DE with a careful budget allocation scheme.
# Failure modes: On very low budgets (e.g., budget <= population size), the
# algorithm will only evaluate the initial random population and return the best
# among them. On high-dimensional problems with limited population size, the search
# may converge prematurely to a poor local optimum. Fixed parameters may not be
# optimal for all problem landscapes.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget: int, dim: int):
        """
        Initialize the Differential Evolution optimizer.

        Args:
            budget: Maximum number of function evaluations allowed.
            dim: Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

        # Algorithm parameters
        self.F = 0.5          # scaling factor
        self.CR = 0.9         # crossover probability

        # Determine population size: try to use at least 5*dim but not too many
        # to allow enough generations. Cap at budget // 4 so that we have at
        # least 4 generations (including initial population) if possible.
        pop_base = max(5, int(dim * 2))  # minimal size 5 for very low dim
        self.pop_size = min(pop_base, budget // 4)
        if self.pop_size < 2:
            self.pop_size = max(2, budget // 2)  # at least 2 for mutation

        # Number of generations (excluding initial population evaluation)
        remaining = budget - self.pop_size
        self.max_generations = max(0, remaining // self.pop_size)

        # Store current best found by the algorithm
        self.best_x = None
        self.best_y = np.inf

    def _reflect(self, x, lb, ub):
        """Reflect out-of-bounds coordinates back into the feasible domain."""
        out_low = x < lb
        out_high = x > ub
        x[out_low] = 2.0 * lb[out_low] - x[out_low]
        x[out_high] = 2.0 * ub[out_high] - x[out_high]
        # Clamp to avoid floating-point errors during reflection
        return np.clip(x, lb, ub)

    def __call__(self, func):
        """
        Run the optimization on a given objective function.

        Args:
            func: A callable object with attributes `lower` and `upper` (or
                  `bounds.lb` and `bounds.ub`) defining the box constraints.

        Returns:
            best_x: Best solution found (numpy array of shape (dim,)).
            best_y: Best objective value (float).
        """
        # Determine bounds from func interface
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower, dtype=float)
            ub = np.array(func.upper, dtype=float)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lb = np.array(func.bounds.lb, dtype=float)
            ub = np.array(func.bounds.ub, dtype=float)
        else:
            raise AttributeError("Objective function must provide lower/upper or bounds.lb/bounds.ub")

        dim = self.dim
        pop_size = self.pop_size
        evals = 0

        # Initialize population uniformly in the search space
        population = np.random.uniform(lb, ub, size=(pop_size, dim))
        fitness = np.full(pop_size, np.inf)
        for i in range(pop_size):
            fitness[i] = func(population[i])
            evals += 1
            if fitness[i] < self.best_y:
                self.best_y = fitness[i]
                self.best_x = population[i].copy()
            if evals >= self.budget:
                break

        # Main DE loop
        for gen in range(self.max_generations):
            if evals >= self.budget:
                break
            # For each target vector
            for i in range(pop_size):
                if evals >= self.budget:
                    break
                # Mutation: select three distinct random indices different from i
                candidates = list(range(pop_size))
                candidates.remove(i)
                r1, r2, r3 = np.random.choice(candidates, size=3, replace=False)
                mutant = population[r1] + self.F * (population[r2] - population[r3])

                # Crossover: binomial
                trial = population[i].copy()
                # Ensure at least one component comes from mutant
                j_rand = np.random.randint(0, dim)
                for j in range(dim):
                    if np.random.rand() < self.CR or j == j_rand:
                        trial[j] = mutant[j]

                # Boundary handling
                trial = self._reflect(trial, lb, ub)

                # Evaluate trial (skip if identical to target to save evaluation)
                if np.allclose(trial, population[i]):
                    continue
                trial_fitness = func(trial)
                evals += 1

                # Selection
                if trial_fitness <= fitness[i]:
                    population[i] = trial
                    fitness[i] = trial_fitness
                    if trial_fitness < self.best_y:
                        self.best_y = trial_fitness
                        self.best_x = trial.copy()

            # Update best if any improvement occurred during generation
            # (already tracked per trial)

        return self.best_x, self.best_y
