import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: Classic Differential Evolution (DE/rand/1/bin) with fixed scaling factor and crossover probability, applied to black-box minimization.
# Search state: Population of candidate solutions (NP vectors) and their fitness values.
# Candidate generation: For each target vector, a mutant is generated by adding scaled difference of two other random population vectors to a base vector (rand/1). Then binomial crossover creates a trial vector by mixing mutant and target components with probability CR.
# Selection and replacement: Greedy selection: trial replaces target if its fitness is better (minimization).
# Adaptation: No adaptation of parameters (F and CR are fixed).
# Exploration mechanisms: The differential mutation with random selection encourages exploration, especially when population diversity is high.
# Exploitation mechanisms: As population converges, differences become small, leading to local search. Also, selection pressures towards better solutions.
# Boundary handling: Components exceeding bounds are reflected back (or clamped) using a simple clamping to bound.
# Budget strategy: Stopping when total function evaluations reach budget. Population size is set dynamically based on dim and budget (e.g., NP = min(10*dim, budget//2, 200)), ensures at least a few generations.
# Closest known influences: Standard DE (Storn and Price, 1997).
# Novelty or unusual aspects: Minimal modifications; simple fixed parameters (F=0.8, CR=0.9). Population size scaled to budget/dim.
# Failure modes: On high-dimensional or deceptive landscapes, may converge prematurely if population loses diversity; fixed parameters may not suit all problems.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Read bounds (support both attribute naming conventions)
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.atleast_1d(np.asarray(func.lower, dtype=float))
            ub = np.atleast_1d(np.asarray(func.upper, dtype=float))
        elif hasattr(func, 'bounds'):
            lb = np.atleast_1d(np.asarray(func.bounds.lb, dtype=float))
            ub = np.atleast_1d(np.asarray(func.bounds.ub, dtype=float))
        else:
            raise AttributeError("Cannot determine bounds from func object")

        dim = self.dim
        if lb.shape[0] != dim or ub.shape[0] != dim:
            # If scalar bounds, broadcast
            lb = np.full(dim, lb.item()) if lb.size == 1 else lb
            ub = np.full(dim, ub.item()) if ub.size == 1 else ub

        # Population size: ensure at least 4, at most budget//2 (so we can have generations),
        # and try to keep it proportional to dimension but not too large.
        NP = max(4, min(10 * dim, self.budget // 2))
        # But if budget is tiny, NP may be larger than budget. Cap it.
        NP = min(NP, self.budget)

        # DE parameters
        F = 0.8          # mutation factor
        CR = 0.9         # crossover probability

        # Initialize population uniformly in [lb, ub]
        pop = np.random.uniform(low=lb, high=ub, size=(NP, dim))
        # Evaluate initial population
        fitness = np.array([func(x) for x in pop])
        evals = NP
        best_idx = np.argmin(fitness)
        best_x = pop[best_idx].copy()
        best_y = fitness[best_idx]

        # Main loop
        while evals < self.budget:
            # Generate one generation of trial vectors
            for i in range(NP):
                # Mutation: select three distinct random indices != i
                r = np.random.permutation(NP)
                # Find indices not equal to i
                candidates = r[r != i]
                if len(candidates) < 3:
                    # Not enough individuals, skip mutation for this target
                    continue
                a, b, c = candidates[:3]
                mutant = pop[a] + F * (pop[b] - pop[c])

                # Crossover binomial
                trial = np.empty(dim)
                j_rand = np.random.randint(dim)
                for j in range(dim):
                    if np.random.rand() < CR or j == j_rand:
                        trial[j] = mutant[j]
                    else:
                        trial[j] = pop[i, j]

                # Boundary handling: simple clamping to bounds
                trial = np.clip(trial, lb, ub)

                # Evaluate trial only if budget remains
                if evals >= self.budget:
                    break
                trial_fit = func(trial)
                evals += 1

                # Selection: greedy
                if trial_fit < fitness[i]:
                    pop[i] = trial
                    fitness[i] = trial_fit
                    if trial_fit < best_y:
                        best_y = trial_fit
                        best_x = trial.copy()

            # Early stop if budget exhausted during generation
            if evals >= self.budget:
                break

        return best_x, best_y
