import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: Implements a (1+1)-Evolution Strategy with global step-size adaptation
# using the classic 1/5 success rule. It iteratively perturbs the current best
# solution with a multivariate normal distribution scaled by the step size.
# The step size is periodically adjusted based on the observed success rate
# of recent mutations.
#
# Search state: A single candidate solution (position vector) and a global
# step size (scalar). Also maintains a success counter over a sliding window.
#
# Candidate generation: A new candidate is generated by adding
# sigma * N(0, I) to the current position, then clamping to the variable bounds.
#
# Selection and replacement: Greedy selection: the new candidate replaces the
# current solution if it achieves a lower objective value (minimization).
# The best-ever solution is tracked separately.
#
# Adaptation: Every 10 evaluations, the global step size is updated according
# to the 1/5 success rule: if more than 20% of the last 10 mutations were
# successful, step size is increased (multiplied by 1.2); if fewer than 20%,
# it is decreased (multiplied by 0.8). This aims to maintain a reasonable
# acceptance rate.
#
# Exploration mechanisms: Gaussian mutation with adjustable isotropic step size.
# The adaptation rule promotes larger steps when successful mutations are
# frequent (exploration) and smaller steps when failures dominate (exploitation).
#
# Exploitation mechanisms: Greedy acceptance of any improving move; the step
# size shrinks when successes become rare, focusing on a local region.
#
# Boundary handling: Mutated coordinates are clipped to the lower and upper
# bounds defined by the objective function interface.
#
# Budget strategy: The algorithm exactly consumes the prescribed evaluation
# budget by performing one function evaluation per iteration. For budgets
# smaller than the adaptation window (10), a pure random search fallback is used.
#
# Closest known influences: (1+1)-Evolution Strategy with Rechenberg’s 1/5 rule
# (Rechenberg, 1973; Schwefel, 1981).
#
# Novelty or unusual aspects: None; this is a textbook implementation intended
# to be compact and understandable.
#
# Failure modes:
# - May stagnate on highly non-separable or ill-conditioned functions because
#   the isotropic mutation does not capture correlations between dimensions.
# - The fixed window size (10) may be suboptimal for very high-dimensional or
#   extremely rugged landscapes.
# - The fixed multiplication factors (1.2, 0.8) may not be optimal for all
#   problem scales.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    """(1+1)-ES with 1/5 success rule for black-box minimization."""

    def __init__(self, budget: int, dim: int):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Determine variable bounds
        try:
            lb = np.array(func.lower, dtype=float)
            ub = np.array(func.upper, dtype=float)
        except AttributeError:
            lb = np.array(func.bounds.lb, dtype=float)
            ub = np.array(func.bounds.ub, dtype=float)

        budget = self.budget
        dim = self.dim

        # Fallback: pure random search for extremely small budgets
        if budget < 10:
            best_x = None
            best_y = np.inf
            for _ in range(budget):
                x = np.random.uniform(lb, ub, dim)
                y = func(x)
                if y < best_y:
                    best_y = y
                    best_x = x.copy()
            return best_x, best_y

        # Initial point
        x = np.random.uniform(lb, ub, dim)
        y = func(x)
        evals = 1
        best_x = x.copy()
        best_y = y

        # Global step size (isotropic)
        sigma = (ub - lb).mean() / 5.0

        # Adaption parameters
        window = 10          # evaluations between step-size updates
        success_counter = 0  # successes within current window
        step = 0             # total evaluations since start of window

        while evals < budget:
            # Generate candidate by mutating current point
            x_candidate = x + sigma * np.random.randn(dim)
            x_candidate = np.clip(x_candidate, lb, ub)
            y_candidate = func(x_candidate)
            evals += 1

            # Greedy selection
            if y_candidate < y:
                x = x_candidate
                y = y_candidate
                success_counter += 1
                if y_candidate < best_y:
                    best_y = y_candidate
                    best_x = x_candidate.copy()

            step += 1

            # Adapt step size at the end of each window
            if step % window == 0:
                success_rate = success_counter / window
                if success_rate > 0.2:
                    sigma *= 1.2
                elif success_rate < 0.2:
                    sigma *= 0.8
                success_counter = 0  # reset for next window

        return best_x, best_y
