import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: The algorithm is a (1+1)-Evolution Strategy with step size adaptation using Rechenberg's 1/5th rule and occasional random restarts to escape local minima. It is designed for black-box minimization under a strict evaluation budget.
# Search state: The algorithm maintains a single current best solution (best_x) and its objective value (best_y), along with a step size (sigma) controlling the mutation magnitude, and a success counter for adaptive step size control. Additionally, it tracks stagnation to trigger restarts.
# Candidate generation: A candidate solution is generated by adding isotropic Gaussian noise scaled by sigma to the current best solution: candidate = best_x + sigma * np.random.randn(dim). The candidate is then clipped to the domain bounds.
# Selection and replacement: The candidate replaces the current best if its objective value (minimization) is lower than best_y. Only the best solution is retained (elitist selection).
# Adaptation: Step size sigma is updated every 'update_period' evaluations (set to max(1, dim)) using the empirical success rate in that window. If success_rate > 1/5, sigma is increased (exp(1/dim)); if <1/5, sigma is decreased (exp(-1/dim)). This implements Rechenberg's 1/5 rule. sigma is also clamped to avoid extreme values. Additionally, if no improvement is observed for a stagnation threshold (5*dim) and sigma is below a small fraction of domain, the algorithm performs a random restart: best_x is drawn uniformly anew, evaluated, sigma reset to initial value, and success counter cleared.
# Exploration mechanisms: Exploration is facilitated by relatively large sigma early on and after restarts. Gaussian mutations provide isotropic exploration.
# Exploitation mechanisms: Exploitation occurs as sigma decreases when success rate is low, focusing search near the current best. The elitist selection ensures the best solution is never lost.
# Boundary handling: Candidate solutions are clipped to the [lb, ub] bounds element-wise.
# Budget strategy: The algorithm strictly respects the evaluation budget by checking evals < budget before each evaluation. The initial evaluation counts toward the budget. No function evaluations are wasted.
# Closest known influences: The algorithm is a straightforward implementation of the (1+1)-ES with Rechenberg's 1/5th rule, which is a classic in evolutionary computation. The restart mechanism is inspired by the IPOP-CMA-ES restart scheme, but simplified.
# Novelty or unusual aspects: No particular novelty; the algorithm is standard. The restart condition (stagnation + small sigma) is designed to improve robustness on multimodal functions.
# Failure modes: The algorithm may fail on high-dimensional, non-separable, or highly multimodal landscapes because it relies on isotropic Gaussian mutations and does not adapt the covariance matrix. For functions with strong variable interactions or narrow valleys, convergence may be slow or premature. Restarts help but may not be sufficient under strict budgets. The step size adaptation may also be misled by flat regions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    """Minimizer based on a (1+1)-ES with Rechenberg's 1/5 rule and restarts."""

    def __init__(self, budget: int, dim: int):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Determine bounds from func
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower, dtype=float)
            ub = np.asarray(func.upper, dtype=float)
        elif hasattr(func, 'bounds') and func.bounds is not None:
            lb = np.asarray(func.bounds.lb, dtype=float)
            ub = np.asarray(func.bounds.ub, dtype=float)
        else:
            raise AttributeError("Cannot find bounds from func")

        dim = self.dim
        budget = self.budget

        # Validate dimension
        if lb.shape[0] != dim or ub.shape[0] != dim:
            raise ValueError("Dimension mismatch between bounds and Algorithm dim")

        # Initialize best solution uniformly
        best_x = lb + np.random.rand(dim) * (ub - lb)
        best_y = func(best_x)
        evals = 1

        domain_scale = np.mean(ub - lb)
        sigma = 0.2 * domain_scale
        min_sigma = 1e-8 * domain_scale
        max_sigma = 0.5 * domain_scale

        update_period = max(1, dim)
        success_counter = 0

        stagnation_threshold = max(10, 5 * dim)
        stagnation_counter = 0

        restart_sigma = 0.2 * domain_scale

        while evals < budget:
            # Generate candidate by isotropic Gaussian mutation
            candidate = best_x + sigma * np.random.randn(dim)
            candidate = np.clip(candidate, lb, ub)

            # Evaluate the candidate
            candidate_y = func(candidate)
            evals += 1

            # Selection (minimization)
            if candidate_y < best_y:
                best_x, best_y = candidate, candidate_y
                success_counter += 1
                stagnation_counter = 0
            else:
                stagnation_counter += 1

            # Step size adaptation (Rechenberg's 1/5 rule)
            if evals % update_period == 0:
                success_rate = success_counter / update_period
                if success_rate > 0.2:
                    sigma *= np.exp(1.0 / dim)
                elif success_rate < 0.2:
                    sigma *= np.exp(-1.0 / dim)
                success_counter = 0

            # Clamp sigma
            sigma = np.clip(sigma, min_sigma, max_sigma)

            # Restart if stagnation with small sigma
            if stagnation_counter >= stagnation_threshold and sigma < 0.01 * domain_scale:
                if evals >= budget:
                    break
                best_x = lb + np.random.rand(dim) * (ub - lb)
                best_y = func(best_x)
                evals += 1
                sigma = restart_sigma
                success_counter = 0
                stagnation_counter = 0

        return best_x, best_y
