# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: Implementation of a global Particle Swarm Optimization (PSO) algorithm for black-box minimization.
# Search state: Population of candidate positions (pos), velocities (vel), personal best positions and fitnesses, and a global best position.
# Candidate generation: New positions are generated by updating velocities using inertia, cognitive component (attraction to personal best), and social component (attraction to global best), then adding velocities to current positions.
# Selection and replacement: Each candidate is evaluated; if its fitness is better than its personal best, personal best is updated; if better than global best, global best is updated. No other selection mechanism; all particles survive to next generation.
# Adaptation: Inertia weight w, cognitive c1, and social c2 are fixed (no adaptation). Population size is fixed based on budget and dimension.
# Exploration mechanisms: Random initialization of positions and velocities; stochastic coefficients r1, r2; velocities can overshoot and cause exploration; boundary clipping may cause loss of exploration; inertia weight provides some exploration.
# Exploitation mechanisms: Attraction to global best and personal best focuses search around found minima; decreasing inertia weight could improve exploitation but not implemented here (constant).
# Boundary handling: Positions are clipped to bounds after update. Velocities are not modified; particles hitting boundary may have velocity carrying them back inside next step.
# Budget strategy: Evaluations are counted strictly; loop stops exactly when budget is reached. Population size chosen to allow multiple generations.
# Closest known influences: Standard PSO (Kennedy & Eberhart 1995) with inertia weight (Shi & Eberhart 1998).
# Novelty or unusual aspects: None; straightforward implementation.
# Failure modes: May converge prematurely to local optimum if population size too small or dimensionality high; constant inertia may lead to poor exploitation in later generations; can struggle with highly multimodal or ill-conditioned functions.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Determine bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower = np.asarray(func.lower).reshape(1, -1)
            upper = np.asarray(func.upper).reshape(1, -1)
        elif hasattr(func, 'bounds'):
            lower = np.asarray(func.bounds.lb).reshape(1, -1)
            upper = np.asarray(func.bounds.ub).reshape(1, -1)
        else:
            raise ValueError("Cannot determine domain bounds")

        # Population size – keep at least 4, at most 40, and never exceed budget
        pop_size = max(4, min(40, self.budget // 10))
        pop_size = min(pop_size, self.budget)

        # Number of full generations (remaining evaluations after first generation)
        max_iters = self.budget // pop_size

        # PSO parameters (fixed)
        w = 0.7   # inertia weight
        c1 = 1.5  # cognitive coefficient
        c2 = 1.5  # social coefficient

        rng = np.random.default_rng()

        # Initialise positions uniformly inside domain
        pos = lower + rng.uniform(0, 1, size=(pop_size, self.dim)) * (upper - lower)
        # Initialise velocities scaled to a fraction of the domain size
        vel = rng.uniform(-1, 1, size=(pop_size, self.dim)) * (upper - lower) / 10.0

        # Evaluate initial population
        fitness = np.array([func(p) for p in pos])   # pop_size evaluations
        evals = pop_size

        # Personal bests
        pbest_pos = pos.copy()
        pbest_fit = fitness.copy()

        # Global best
        best_idx = np.argmin(pbest_fit)
        gbest_pos = pbest_pos[best_idx].copy()
        gbest_fit = pbest_fit[best_idx]

        best_x = gbest_pos.copy()
        best_y = gbest_fit

        # Main PSO loop
        for _ in range(max_iters):
            if evals >= self.budget:
                break

            # Generate random numbers once per iteration
            r1 = rng.uniform(0, 1, size=(pop_size, self.dim))
            r2 = rng.uniform(0, 1, size=(pop_size, self.dim))

            # Update velocities and positions
            vel = w * vel + c1 * r1 * (pbest_pos - pos) + c2 * r2 * (gbest_pos - pos)
            pos = pos + vel
            pos = np.clip(pos, lower, upper)   # boundary handling: clip

            # Evaluate new positions
            for i in range(pop_size):
                if evals >= self.budget:
                    break
                fit = func(pos[i])
                evals += 1

                # Update personal best
                if fit < pbest_fit[i]:
                    pbest_fit[i] = fit
                    pbest_pos[i] = pos[i].copy()

                # Update global best
                if fit < gbest_fit:
                    gbest_fit = fit
                    gbest_pos = pos[i].copy()

            # Update overall best found so far
            if gbest_fit < best_y:
                best_y = gbest_fit
                best_x = gbest_pos.copy()

        return best_x, best_y
