import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: Particle Swarm Optimization (PSO) with adaptive inertia weight.
# Search state: The algorithm maintains a swarm of particles, each with position, velocity, personal best, and global best.
# Candidate generation: New candidate positions are generated by updating particle velocities using standard PSO update rule with inertia and acceleration coefficients, then adding velocity to position.
# Selection and replacement: Each particle compares its new function value to its personal best; the global best is updated if a new global optimum is found.
# Adaptation: Inertia weight linearly decreases from 0.9 to 0.4 over the number of generations, balancing exploration and exploitation.
# Exploration mechanisms: Random weights (r1, r2) in velocity update and initial random positions and velocities.
# Exploitation mechanisms: Attraction to personal best and global best drives convergence.
# Boundary handling: Positions that exit the search domain are reflected back inside, and velocity is reversed to keep particles within bounds.
# Budget strategy: A fixed population size is chosen based on dimension and budget. Evaluations are performed in generations; any leftover evaluations are spent iterating through particles one by one.
# Closest known influences: Standard PSO (Kennedy and Eberhart). Inertia weight variant.
# Novelty or unusual aspects: Simple reflection boundary handling.
# Failure modes: May converge prematurely to local optima in high-dimensional multimodal landscapes. Fixed parameters may not suit all problems.
# ALGORITHM_ANALYSIS_NOTE_END


class Algorithm:
    def __init__(self, budget, dim):
        self.budget = int(budget)
        self.dim = int(dim)

        # Choose a population size that scales logarithmically with dimension,
        # but never larger than the budget so that at least one generation can run.
        raw_pop = max(2, int(4 + 3 * np.log(self.dim + 1)))
        self.pop_size = min(raw_pop, self.budget)

        # PSO parameters (fixed)
        self.w_start = 0.9         # initial inertia weight
        self.w_end = 0.4           # final inertia weight
        self.c1 = 2.0              # cognitive coefficient
        self.c2 = 2.0              # social coefficient

    def __call__(self, func):
        # Extract search bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.array(func.lower, dtype=float)
            ub = np.array(func.upper, dtype=float)
        else:
            lb = np.array(func.bounds.lb, dtype=float)
            ub = np.array(func.bounds.ub, dtype=float)

        dim = self.dim
        pop = self.pop_size
        budget = self.budget

        # Initialise particles uniformly in the search space
        particles = np.random.uniform(lb, ub, (pop, dim))
        # Velocities initialised to a small fraction of the domain range
        velocity_scale = (ub - lb) * 0.1
        velocities = np.random.uniform(-velocity_scale, velocity_scale, (pop, dim))

        # Personal bests
        personal_best = particles.copy()
        personal_best_val = np.full(pop, np.inf)

        # Global best
        global_best = np.zeros(dim)
        global_best_val = np.inf

        evals = 0

        # Evaluate the initial population
        for i in range(pop):
            y = func(particles[i])
            evals += 1
            personal_best_val[i] = y
            if y < global_best_val:
                global_best_val = y
                global_best = particles[i].copy()

        # Number of complete generations we can run (initial pop already evaluated)
        remaining_evals = budget - evals
        if remaining_evals <= 0:
            return global_best, global_best_val

        max_generations = remaining_evals // pop   # full generations
        leftover = remaining_evals % pop           # extra individual updates

        # Full generations
        for gen in range(max_generations):
            w = self.w_start - (self.w_start - self.w_end) * gen / max_generations
            for i in range(pop):
                r1 = np.random.random(dim)
                r2 = np.random.random(dim)

                # Velocity update
                velocities[i] = (w * velocities[i]
                                 + self.c1 * r1 * (personal_best[i] - particles[i])
                                 + self.c2 * r2 * (global_best - particles[i]))

                # Position update
                particles[i] = particles[i] + velocities[i]

                # Reflect boundaries
                for d in range(dim):
                    if particles[i, d] < lb[d]:
                        particles[i, d] = 2 * lb[d] - particles[i, d]
                        velocities[i, d] = -velocities[i, d]
                    elif particles[i, d] > ub[d]:
                        particles[i, d] = 2 * ub[d] - particles[i, d]
                        velocities[i, d] = -velocities[i, d]

                # Evaluate
                y = func(particles[i])
                evals += 1

                # Update personal best
                if y < personal_best_val[i]:
                    personal_best_val[i] = y
                    personal_best[i] = particles[i].copy()

                # Update global best
                if y < global_best_val:
                    global_best_val = y
                    global_best = particles[i].copy()

        # Leftover evaluations – cycle through particles one at a time
        if leftover > 0:
            # Use the inertia weight from the last complete generation
            if max_generations > 0:
                last_w = self.w_start - (self.w_start - self.w_end) * (max_generations - 1) / max_generations
            else:
                last_w = self.w_start  # no generation completed

            for idx in range(leftover):
                i = idx % pop
                r1 = np.random.random(dim)
                r2 = np.random.random(dim)

                velocities[i] = (last_w * velocities[i]
                                 + self.c1 * r1 * (personal_best[i] - particles[i])
                                 + self.c2 * r2 * (global_best - particles[i]))

                particles[i] = particles[i] + velocities[i]

                # Reflect boundaries
                for d in range(dim):
                    if particles[i, d] < lb[d]:
                        particles[i, d] = 2 * lb[d] - particles[i, d]
                        velocities[i, d] = -velocities[i, d]
                    elif particles[i, d] > ub[d]:
                        particles[i, d] = 2 * ub[d] - particles[i, d]
                        velocities[i, d] = -velocities[i, d]

                y = func(particles[i])
                evals += 1

                if y < personal_best_val[i]:
                    personal_best_val[i] = y
                    personal_best[i] = particles[i].copy()

                if y < global_best_val:
                    global_best_val = y
                    global_best = particles[i].copy()

        # Ensure we never exceed the budget (safety check, should be exact)
        # return best found
        return global_best, global_best_val
