# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A (1+1) Evolution Strategy using adaptive diagonal step sizes and a directional evolution path.
# Search state: Current best solution (mean), a scalar step-size (sigma), a diagonal scaling vector (stds), and an evolution path (path).
# Candidate generation: Samples are generated by adding a combination of isotropic Gaussian noise and a directional bias (evolution path) to the current best point, scaled by the diagonal step sizes.
# Selection and replacement: Greedy (1+1) selection; the candidate replaces the current best if its objective value is lower or equal.
# Adaptation: The global step size (sigma) and the evolution path are updated based on success. On success, the path accumulates the successful direction and sigma increases; on failure, sigma decreases.
# Exploration mechanisms: Stochastic Gaussian sampling and expansion of the search radius (sigma) upon finding improvements.
# Exploitation mechanisms: Contraction of the search radius (sigma) upon failure to localize the search, and directional bias to follow successful descent trajectories.
# Boundary handling: Candidates are clipped to the hyper-rectangular bounds provided by the function interface.
# Budget strategy: The algorithm tracks evaluations and terminates immediately before exceeding the provided budget.
# Closest known influences: (1+1)-ES, simplified Diagonal CMA-ES, and Matyas' adaptive step-size control.
# Novelty or unusual aspects: Combines diagonal scaling with a simplified evolution path in a 1+1 framework without expensive matrix operations.
# Failure modes: May converge prematurely on highly multi-modal landscapes or struggle with extremely non-separable, rotated functions due to the lack of a full covariance matrix.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        
        Args:
            budget (int): Total number of function evaluations allowed.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Runs the minimization process.
        
        Args:
            func (callable): The objective function to minimize.
        
        Returns:
            tuple: (best_x, best_y) representing the best solution found.
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        elif hasattr(func, 'bounds'):
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        else:
            # Fallback if no bounds are provided (though benchmark usually provides them)
            lb = np.full(self.dim, -5.0)
            ub = np.full(self.dim, 5.0)

        # Initialization
        center = 0.5 * (lb + ub)
        span = ub - lb
        
        # Search parameters
        sigma = 0.1  # Global step-size factor
        stds = 0.2 * span  # Diagonal scaling
        path = np.zeros(self.dim)  # Evolution path (momentum)
        
        # Initial evaluation
        best_x = np.clip(center, lb, ub)
        best_y = func(best_x)
        eval_count = 1
        
        # Hyperparameters for adaptation
        c_p = 0.2  # Path decay constant
        sigma_up = 1.2
        sigma_down = 0.85
        path_influence = 0.4  # How much the path affects new samples
        
        while eval_count < self.budget:
            # Generate a new candidate
            # Combine random white noise with the accumulated evolution path
            z = np.random.standard_normal(self.dim)
            direction = z + path_influence * path
            
            candidate = best_x + sigma * stds * direction
            
            # Boundary handling: clip to search space
            candidate = np.clip(candidate, lb, ub)
            
            # Evaluation
            y = func(candidate)
            eval_count += 1
            
            if y <= best_y:
                # Success: Move to new point and update search state
                best_y = y
                best_x = candidate
                
                # Update evolution path (exponential moving average of successful steps)
                path = (1 - c_p) * path + c_p * z
                
                # Expand search radius
                sigma = min(sigma * sigma_up, 1e2)
            else:
                # Failure: Contract search radius and decay path
                sigma = max(sigma * sigma_down, 1e-12)
                path *= (1 - c_p)
            
            # Periodically check if sigma is becoming too small relative to bounds
            # but keep going until budget is exhausted.
            
        return best_x, best_y

# Optimization module implementation complete.
