# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm implements a variant of restart hill climbing using coordinate masks for perturbation. It repeatedly initializes at random points in the search space and then performs a local search. The local search perturbs a randomly chosen subset of dimensions (a "mask") using Gaussian noise. If an improvement is found, the current solution is updated; otherwise, an unsuccessful step counter increments. Once a maximum number of unsuccessful steps is reached, the local search terminates, and a new random restart point is chosen (if budget allows). The best solution found across all restarts and local searches is maintained and returned.
# Search state: The primary search state consists of the `best_x` (the best solution found globally) and `best_y` (its objective value). During a local search phase, `current_x` and `current_y` represent the current best solution within that particular hill climbing run. The algorithm also tracks the remaining `budget`.
# Candidate generation: Candidates are generated by perturbing `current_x`. A random subset of dimensions (a "coordinate mask") is chosen. For these masked dimensions, Gaussian noise scaled by the dimension's search range is added. Dimensions not in the mask remain unchanged.
# Selection and replacement: In the local search phase, a candidate `candidate_x` is generated from `current_x`. If `candidate_y` (the objective value of `candidate_x`) is strictly better than `current_y`, then `candidate_x` replaces `current_x`. If `current_y` (the new local best) is better than `best_y`, then `best_x` and `best_y` are updated.
# Adaptation: The algorithm does not have explicit online adaptation of parameters like step size or mask size during a run. The perturbation scale factor is static but scales relative to the problem's bounds. The local search implicitly adapts by stopping after `hc_max_unsuccessful_steps`, effectively shifting focus or restarting if no immediate improvements are found, which can be seen as an adaptive restart mechanism.
# Exploration mechanisms:
# - Random Restarts: The algorithm frequently restarts the local search from a new, randomly sampled point within the entire search space. This helps escape local optima and explore different regions.
# - Coordinate Masks: By randomly selecting subsets of dimensions to perturb, the algorithm explores directions that are not strictly axis-aligned (as in simple coordinate ascent/descent) but also not completely random in all dimensions simultaneously. This balances focused movement with directional diversity.
# Exploitation mechanisms:
# - Hill Climbing: The core local search mechanism is greedy hill climbing. It always moves towards improved solutions.
# - Step Size: The Gaussian perturbation with a fixed standard deviation (relative to the search range) allows for fine-tuning movements in promising areas, leveraging the local gradient information implicitly.
# Boundary handling: When generating candidate points, `numpy.clip` is used to ensure that all coordinate values remain within the `lower_bound` and `upper_bound` of the search space. This handles boundaries by projecting points back onto the feasible region.
# Budget strategy: The budget is strictly managed. Each call to `func` decrements the internal budget counter. All loops and operations check `self.budget > 0` to ensure no evaluations occur beyond the allotted budget. The algorithm stops immediately once the budget is exhausted.
# Closest known influences: This algorithm draws inspiration from:
# - Random Restart Hill Climbing (RRHC): The overall meta-strategy of restarting local searches from new random points.
# - Stochastic Local Search: Generally falls under this category due to the use of randomness in candidate generation.
# Novelty or unusual aspects: The specific combination of random restarts with a coordinate-masked Gaussian perturbation strategy within the local search phase. The `max_mask_size` being `dim // 2` is a heuristic choice balancing exploration of subspaces versus single-dimension changes, particularly effective for dimensions greater than 3.
# Failure modes:
# - Premature convergence: If `hc_max_unsuccessful_steps` is too high, it might spend too much time in a poor local optimum, reducing the number of restarts and overall exploration.
# - Insufficient exploitation: If `perturbation_scale_factor` is too large or `hc_max_unsuccessful_steps` is too low, the local search might be too "jumpy" or too short-lived to properly converge to local optima.
# - Suboptimal hyperparameter tuning: The fixed hyperparameters might not be optimal for all problem types or dimensions, as they are not adaptive.
# - High dimensionality: In very high dimensions, randomly sampling an effective coordinate mask might become less efficient, and `dim // 2` might still be too large a mask size for effective local search without more sophisticated step size adaptation.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    A GNBG black-box minimization benchmark algorithm implementing restart hill climbing
    with coordinate masks.
    """

    def __init__(self, budget: int, dim: int):
        """
        Initializes the algorithm with a total budget and problem dimension.

        Args:
            budget: The maximum number of function evaluations allowed.
            dim: The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.lower_bound = None
        self.upper_bound = None

        # Hyperparameters for the algorithm
        # Maximum number of steps without improvement before a local search restarts
        self.hc_max_unsuccessful_steps = 10
        # Factor for Gaussian perturbation std dev relative to the search range
        self.perturbation_scale_factor = 0.1
        # Minimum number of dimensions to perturb in a coordinate mask
        self.min_mask_size = 1
        # Maximum number of dimensions to perturb in a coordinate mask.
        # Set to max(1, dim // 2) to allow for multi-dimensional perturbations
        # while ensuring it's at least 1 for low dimensions.
        self.max_mask_size = max(1, dim // 2)

    def _get_bounds(self, func) -> None:
        """
        Determines the lower and upper bounds of the search space from the function object.
        Supports func.lower/upper or func.bounds.lb/ub.
        """
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            self.lower_bound = np.asarray(func.lower)
            self.upper_bound = np.asarray(func.upper)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            self.lower_bound = np.asarray(func.bounds.lb)
            self.upper_bound = np.asarray(func.bounds.ub)
        else:
            # Fallback if bounds are not explicitly provided in expected formats.
            # This should ideally not happen in GNBG benchmarks.
            self.lower_bound = np.full(self.dim, -5.0)
            self.upper_bound = np.full(self.dim, 5.0)

        # Ensure bounds are correctly shaped (1D array of dim elements)
        if self.lower_bound.shape != (self.dim,) or self.upper_bound.shape != (self.dim,):
            # Try to flatten if they are (dim, 1) or scalar
            self.lower_bound = self.lower_bound.flatten()
            self.upper_bound = self.upper_bound.flatten()
            if self.lower_bound.shape != (self.dim,) or self.upper_bound.shape != (self.dim,):
                raise ValueError(f"Bounds shape mismatch: expected ({self.dim},), got {self.lower_bound.shape} and {self.upper_bound.shape}.")

        if np.any(self.lower_bound >= self.upper_bound):
            raise ValueError("Lower bounds must be strictly less than upper bounds for all dimensions.")

    def __call__(self, func) -> tuple[np.ndarray, float]:
        """
        Executes the optimization process.

        Args:
            func: The objective function to minimize. It takes a numpy array (x)
                  and returns a float (y).

        Returns:
            A tuple (best_x, best_y) representing the best solution found
            and its objective value.
        """
        self._get_bounds(func)

        # Calculate the search range for each dimension, used for scaling perturbations
        search_range = self.upper_bound - self.lower_bound
        perturbation_std = self.perturbation_scale_factor * search_range

        # Initialize with a random point and evaluate
        initial_x = np.random.uniform(self.lower_bound, self.upper_bound, self.dim)
        best_x = initial_x
        best_y = func(best_x)
        self.budget -= 1

        # If budget exhausted after initial evaluation, return immediately
        if self.budget <= 0:
            return best_x, best_y

        # Main loop: Continuously restart hill climbing as long as budget allows
        while self.budget > 0:
            # Start a new hill climbing attempt from a new random point
            current_x = np.random.uniform(self.lower_bound, self.upper_bound, self.dim)
            current_y = func(current_x)
            self.budget -= 1

            # Update global best if the new restart point is better
            if current_y < best_y:
                best_y = current_y
                best_x = current_x

            if self.budget <= 0:
                break

            # Local search (hill climbing) phase
            unsuccessful_steps = 0
            while self.budget > 0 and unsuccessful_steps < self.hc_max_unsuccessful_steps:
                # Generate a candidate point by perturbing current_x
                candidate_x = np.copy(current_x)

                # Generate a coordinate mask: randomly choose a subset of dimensions to perturb
                mask_size = np.random.randint(self.min_mask_size, self.max_mask_size + 1)
                mask_indices = np.random.choice(self.dim, mask_size, replace=False)

                # Perturb only the masked dimensions using Gaussian noise
                # The std dev is scaled per dimension based on its search_range
                perturbation = np.random.normal(0, perturbation_std[mask_indices], mask_size)
                candidate_x[mask_indices] += perturbation

                # Apply bounds to ensure the candidate stays within the search space
                candidate_x = np.clip(candidate_x, self.lower_bound, self.upper_bound)

                # Evaluate the candidate point
                candidate_y = func(candidate_x)
                self.budget -= 1

                # Check for improvement
                if candidate_y < current_y:
                    # Improvement found: update current point and reset unsuccessful counter
                    current_x = candidate_x
                    current_y = candidate_y
                    unsuccessful_steps = 0
                    # Update global best if current_y is better
                    if current_y < best_y:
                        best_y = current_y
                        best_x = current_x
                else:
                    # No improvement: increment unsuccessful steps
                    unsuccessful_steps += 1

                if self.budget <= 0:
                    break
            # The inner loop exits either when budget runs out or
            # when hc_max_unsuccessful_steps is reached, triggering a restart.

        return best_x, best_y
