# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm implements an "Annealed Random Walk with Restarts" (ARWR) for black-box minimization. It maintains a current solution and iteratively perturbs it with a decreasing step size, accepting improvements greedily. To escape local optima, it periodically restarts the search from a new random location in the search space, either based on a fixed evaluation interval or when the local search stagnates.
# Search state: The primary search state consists of `best_x` (the best solution found globally) and `best_y` (its objective value), along with `current_x` and `current_y` (the best solution found within the current random walk segment).
# Candidate generation: New candidate solutions are generated by adding a random perturbation (`delta`) to `current_x`. The `delta` components are drawn from a uniform distribution, with their maximum magnitude scaled by an annealing factor and the search space range for each dimension.
# Selection and replacement: A candidate `x_candidate` is evaluated. If `func(x_candidate)` is better (lower) than `current_y`, `x_candidate` replaces `current_x`. If `current_y` is better than `best_y`, then `best_x` and `best_y` are updated. The algorithm is greedy in accepting steps to update `current_x`.
# Adaptation: The main adaptation mechanism is the "annealing" of the step size. The maximum perturbation magnitude for each dimension linearly decreases from an initial ratio (e.g., 10% of the dimension's range) down to a minimum ratio (e.g., 0.1% of the range) as the total budget is consumed. This encourages broader exploration early on and finer exploitation later.
# Exploration mechanisms:
#   1. Random Walk: The generation of `delta` allows movement in any direction, covering the local neighborhood.
#   2. Restarts: Periodically, the algorithm discards its `current_x` and jumps to a new, randomly sampled point in the search space. This helps in escaping local minima and exploring diverse regions. Restarts occur either after a fixed number of evaluations or if the `current_x` has not improved for a set number of steps.
# Exploitation mechanisms:
#   1. Greedy Acceptance: Steps are only accepted if they improve the `current_y` value, driving the search towards local optima.
#   2. Annealed Step Size: The shrinking step size allows the algorithm to focus its search more narrowly around promising regions as the budget depletes, refining the current best solution.
# Boundary handling: When a new candidate `x_candidate` is generated, its components are clipped to the `lower_bounds` and `upper_bounds` of the search space.
# Budget strategy: The algorithm strictly adheres to the provided `budget`. Each call to `func` increments an evaluation counter, and the main loop terminates once the budget is exhausted. The annealing schedule and restart intervals are proportional to the remaining budget.
# Closest known influences: Random Walk, Simulated Annealing (without probabilistic acceptance, but with step size annealing), Multi-start algorithms.
# Novelty or unusual aspects: The combination of fixed-interval restarts and stagnation-based restarts, alongside a simple linear annealing schedule for uniform random walk steps, provides a straightforward and robust approach. The per-dimension scaling of step size based on `range_bounds` is also a common and robust practice.
# Failure modes:
#   1. Premature convergence: If restarts are too infrequent or the initial step size shrinks too quickly, the algorithm might get stuck in a poor local optimum, especially on highly multimodal functions.
#   2. Slow convergence: If the step size shrinks too slowly or restarts are too frequent, the algorithm might spend too much time exploring and not enough time refining, potentially failing to find precise optima.
#   3. Flat landscapes: On completely flat or very noisy landscapes, the greedy acceptance criteria might struggle to make progress.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    Implements an Annealed Random Walk with Restarts (ARWR) for black-box minimization.
    """

    def __init__(self, budget: int, dim: int):
        """
        Initializes the optimization algorithm.

        Args:
            budget (int): The maximum number of function evaluations allowed.
            dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func) -> tuple[np.ndarray, float]:
        """
        Executes the Annealed Random Walk with Restarts optimization algorithm.

        Args:
            func: The objective function to minimize. It must have 'lower' and 'upper'
                  attributes (or 'bounds.lb' and 'bounds.ub') defining the search space.

        Returns:
            tuple[np.ndarray, float]: A tuple containing (best_x, best_y), where best_x is
                                      the best solution found and best_y is its objective value.
        """
        # --- Algorithm Parameters ---
        # Initial step size as a fraction of the total range of a dimension.
        # Controls initial exploration amplitude.
        INITIAL_MAX_STEP_RATIO = 0.1 # e.g., 10%
