# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm, named GNBG (Guess-and-Check for Numerical Black-box Global), employs a hybrid strategy combining initial broad exploration with an iterative cycle of exploitation and controlled exploration. It starts by sampling a few points uniformly across the search space to establish an initial best candidate. In the main loop, it primarily attempts to improve the current best solution by perturbing it with Gaussian noise (exploitation). Periodically, it introduces fully uniform random samples (exploration) to mitigate premature convergence and discover new promising regions. All candidate solutions are evaluated against the current budget and clipped to stay within problem bounds.
# Search state: The algorithm maintains the `best_x` (the candidate input vector that yielded the lowest objective value found so far) and `best_y` (its corresponding objective value). It also tracks `current_budget_used` to ensure the total budget is not exceeded.
# Candidate generation: Candidates are generated using two primary mechanisms:
# 1. Uniform Exploration: A new candidate `x` is drawn from a uniform distribution across the entire search space, `U(lower_bound, upper_bound)`.
# 2. Incumbent-Centered Perturbation (Exploitation): A new candidate `x'` is generated by adding Gaussian noise to the current `best_x`. The standard deviation of this noise is a fixed fraction (`perturbation_scale_factor`) of the total range of each dimension. `x' = best_x + N(0, perturbation_scale_factor * (upper_bound - lower_bound))`.
# Selection and replacement: A greedy selection strategy is used. Any newly generated and evaluated candidate `x_candidate` replaces the current `best_x` if its objective value `y_candidate` is strictly lower than `best_y`. Otherwise, the incumbent `best_x` is retained.
# Adaptation: The algorithm does not feature explicit adaptation mechanisms for its parameters (e.g., `exploration_probability` or `perturbation_scale_factor`). These parameters remain constant throughout the optimization process. However, the search implicitly adapts by narrowing its exploitation focus around a progressively better `best_x` as the optimization proceeds.
# Exploration mechanisms:
# 1. Initial Random Sampling: A small number of points are sampled uniformly at the very beginning to quickly cover the search space and find an initial good starting point.
# 2. Periodic Uniform Exploration: During the main loop, with a fixed `exploration_probability`, the algorithm generates entirely new candidates uniformly at random across the entire search domain. This helps prevent premature convergence to local optima and facilitates discovery of globally better regions.
# Exploitation mechanisms:
# 1. Incumbent-Centered Perturbation: The primary exploitation mechanism involves generating new candidates by perturbing the current `best_x` with Gaussian noise. This focuses the search on the vicinity of the best-known solution, attempting to find improvements nearby.
# 2. Greedy Selection: Only improvements are accepted, directly driving the search towards lower objective values.
# Boundary handling: All generated candidate points, whether from uniform sampling or perturbation, are explicitly clipped to ensure they remain within the `lower_bound` and `upper_bound` of the search space. `x_clipped = np.clip(x_candidate, lower_bound, upper_bound)`.
# Budget strategy: The algorithm strictly adheres to the provided `budget`. Every call to the objective function `func` increments `current_budget_used`. The optimization loop terminates as soon as `current_budget_used` reaches `budget`. If `budget` is 0, it returns a default neutral point without any evaluation. If `budget` is 1, it performs a single evaluation and returns that result.
# Closest known influences: This algorithm shares conceptual similarities with basic Random Search for its exploration phases and with simple Evolutionary Strategies (like (1+1)-ES) or hill-climbing for its exploitation via perturbation and greedy selection. The fixed probability of switching between exploration and exploitation is a common heuristic in hybrid algorithms.
# Novelty or unusual aspects: The algorithm's design is intentionally straightforward, combining well-established heuristics without introducing complex novel mechanisms. Its balance between fixed-probability uniform exploration and incumbent-centered Gaussian perturbation is a practical compromise for black-box problems where no gradient information is available.
# Failure modes:
# 1. Stagnation: If `perturbation_scale_factor` is too small, the algorithm might get stuck in local optima, especially if the `exploration_probability` is also low or if the global optimum is far from any initially sampled points.
# 2. Slow convergence: If `perturbation_scale_factor` is too large, the search might be too "jumpy" and fail to fine-tune solutions effectively, resembling more of a pure random search.
# 3. Inefficient for high dimensions: In very high-dimensional spaces, both uniform random sampling and small-step perturbations can become inefficient for finding improvements due to the curse of dimensionality.
# 4. No adaptive step size: The fixed `perturbation_scale_factor` might not be optimal throughout the search; a dynamic adaptation could improve performance.
# 5. Sensitive to parameter tuning: The performance is sensitive to `exploration_probability` and `perturbation_scale_factor`.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    GNBG (Guess-and-Check for Numerical Black-box Global) minimization benchmark algorithm.

    This algorithm employs a hybrid strategy, combining initial broad exploration
    with an iterative cycle of exploitation (incumbent-centered perturbation)
    and controlled exploration (uniform random sampling).
    """

    def __init__(self, budget: int, dim: int):
        """
        Initializes the algorithm with the total evaluation budget and problem dimension.

        Args:
            budget (int): The maximum number of function evaluations allowed.
            dim (int): The dimensionality of the problem's search space.
        """
        if not isinstance(budget, int) or budget < 0:
            raise ValueError("Budget must be a non-negative integer.")
        if not isinstance(dim, int) or dim <= 0:
            raise ValueError("Dimension must be a positive integer.")

        self.budget = budget
        self.dim = dim
        self.current_budget_used = 0

    def _read_bounds(self, func):
        """
        Reads the lower and upper bounds for each dimension from the function object.
        Prioritizes `func.lower`/`func.upper`, falls back to `func.bounds.lb`/`func.bounds.ub`.

        Args:
            func: The objective function object.

        Returns:
            tuple[np.ndarray, np.ndarray]: A tuple containing (lower_bound, upper_bound)
                                           as numpy arrays of shape (self.dim,).
        Raises:
            AttributeError: If bounds cannot be found on the function object.
            ValueError: If the bounds' shape does not match the problem dimension.
        """
        lower_bound = None
        upper_bound = None

        # Try func.lower / func.upper first
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lower_bound = np.asarray(func.lower, dtype=float)
            upper_bound = np.asarray(func.upper, dtype=float)
        # Fallback to func.bounds.lb / func.bounds.ub
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            lower_bound = np.asarray(func.bounds.lb, dtype=float)
            upper_bound = np.asarray(func.bounds.ub, dtype=float)
        else:
            raise AttributeError(
                "Function object must have 'lower'/'upper' or 'bounds.lb'/'bounds.ub' attributes."
            )

        # Ensure bounds are correctly shaped for the dimension
        if lower_bound.ndim == 0:  # Scalar bound, apply to all dimensions
            lower_bound = np.full(self.dim, lower_bound)
        if upper_bound.ndim == 0:  # Scalar bound, apply to all dimensions
            upper_bound = np.full(self.dim, upper_bound)

        if lower_bound.shape != (self.dim,) or upper_bound.shape != (self.dim,):
            raise ValueError(
                f"Bounds shape mismatch. Expected ({self.dim},), "
                f"got {lower_bound.shape} and {upper_bound.shape}."
            )
            
        return lower_bound, upper_bound

    def _evaluate(self, func, x):
        """
        Evaluates the objective function for a given candidate solution 'x',
        respecting the total budget.

        Args:
            func: The objective function.
            x (np.ndarray): The candidate solution to evaluate.

        Returns:
            float: The objective value of x, or np.inf if budget is exhausted.
        """
        if self.current_budget_used >= self.budget:
            return np.inf  # Return infinity if budget is exhausted to prevent further evaluations
        
        self.current_budget_used += 1
        return func(x)

    def __call__(self, func) -> tuple[np.ndarray, float]:
        """
        Executes the optimization process to find the minimum of the given function.

        Args:
            func: The objective function to minimize. It must accept a numpy array
                  of shape (self.dim,) and return a float. It must also have
                  attributes for lower and upper bounds (e.g., `func.lower`, `func.upper`).

        Returns:
            tuple[np.ndarray, float]: A tuple containing the best found solution
                                      (best_x) and its corresponding objective value (best_y).
        """
        lower_bound, upper_bound = self._read_bounds(func)
        search_range = upper_bound - lower_bound

        best_x = None
        best_y = np.inf

        # Handle zero budget explicitly: no evaluations possible
        if self.budget == 0:
            # Return a neutral point within bounds and infinity, as no evaluations can be made.
            return lower_bound + 0.5 * search_range, np.inf

        # 1. Initialization: Evaluate at least one point to set initial best_x, best_y
        initial_x = lower_bound + np.random.rand(self.dim) * search_range
        best_x = initial_x
        best_y = self._evaluate(func, initial_x)

        # If budget was 1, we are done after the first evaluation.
        if self.current_budget_used >= self.budget:
            return best_x, best_y

        # Continue with more initial exploratory samples if budget allows.
        # This helps quickly cover the search space before focusing.
        num_initial_exploratory_samples = max(1, min(self.budget - self.current_budget_used, self.dim * 2))
        
        for _ in range(num_initial_exploratory_samples):
            if self.current_budget_used >= self.budget:
                break # Stop if budget runs out during initial sampling
            x_candidate = lower_bound + np.random.rand(self.dim) * search_range
            y_candidate = self._evaluate(func, x_candidate)
            
            if y_candidate < best_y:
                best_y = y_candidate
                best_x = x_candidate

        # 2. Main Optimization Loop: Mixed uniform exploration and incumbent-centered perturbation
        # Parameters for the algorithm's behavior
        exploration_probability = 0.15      # Probability of performing a global uniform exploration step
        perturbation_scale_factor = 0.1     # Scales the standard deviation of Gaussian perturbation relative to search range

        while self.current_budget_used < self.budget:
            x_candidate = None

            # Decide between exploration (uniform random) or exploitation (perturb incumbent)
            if np.random.rand() < exploration_probability:
                # Exploration: Generate a new candidate uniformly across the entire search space
                x_candidate = lower_bound + np.random.rand(self.dim) * search_range
            else:
                # Exploitation: Perturb the current best solution with Gaussian noise
                # The standard deviation for perturbation is proportional to the search range for each dimension.
                perturbation_std_dev = perturbation_scale_factor * search_range
                x_candidate = best_x + np.random.normal(loc=0, scale=perturbation_std_dev, size=self.dim)
                
                # Boundary handling: Clip the perturbed candidate to ensure it stays within bounds
                x_candidate = np.clip(x_candidate, lower_bound, upper_bound)
            
            # Evaluate the new candidate
            y_candidate = self._evaluate(func, x_candidate)

            # Update the best found solution if the new candidate is better
            if y_candidate < best_y:
                best_y = y_candidate
                best_x = x_candidate
        
        return best_x, best_y
