# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm, named GNBG (Guided Neighborhood Based Gradient-free), combines opposition-based initialization with a decaying-step local random perturbation search. It aims for a balance between initial exploration and subsequent exploitation of promising regions.
# Search state: The primary search state maintained is `best_x` (the best found solution vector) and `best_y` (its corresponding objective value). During local search, new candidate solutions are generated around `best_x`.
# Candidate generation:
#   1. Initialization: Random candidate solutions are generated uniformly within the search bounds. For each random solution `x_rand`, an 'opposite' solution `x_opp = lower + upper - x_rand` is also generated.
#   2. Local Improvement: Candidates are generated by adding Gaussian noise (normal distribution) centered at the `best_x` with a standard deviation determined by a decaying `step_size`.
# Selection and replacement: A simple greedy selection strategy is used. If a newly generated candidate `x_candidate` yields a better objective value (`y_candidate < best_y`), it replaces the current `best_x` and `best_y`.
# Adaptation: The `step_size` for the local search phase decays over time. It starts relatively large (1/10th of the search space range) and decreases quadratically as the budget is consumed, encouraging broader steps early on and finer tuning later.
# Exploration mechanisms:
#   1. Opposition-based initialization: Provides initial diversity by sampling points and their reflections, potentially finding good regions quickly by covering opposite sides of the search space.
#   2. Random perturbation: The local search itself uses random (Gaussian) perturbations, allowing it to explore the neighborhood around the current best solution.
# Exploitation mechanisms:
#   1. Greedy selection: Always moves towards better solutions, directly exploiting found improvements.
#   2. Decaying step size: Gradually reduces the search radius around `best_x`, enabling finer exploitation of the local optimum as the search progresses and budget diminishes.
# Boundary handling: All generated candidate solutions are clipped to ensure they remain within the specified `lower` and `upper` bounds using `numpy.clip`.
# Budget strategy: The algorithm strictly adheres to the `budget` constraint. Evaluations are counted, and the search terminates as soon as the budget is exhausted or an evaluation would exceed it. A portion of the budget is allocated to initialization (approximately `2 * max(1, dim)` evaluations, capped by half the total budget), with the remainder for local improvement.
# Closest known influences: Opposition-Based Learning (OBL) for initialization, simple random walk/hill climbing for local search. It shares concepts with basic Evolutionary Algorithms or Swarm Intelligence algorithms that use a best-to-far solution and local perturbations, but without complex population dynamics.
# Novelty or unusual aspects: The specific combination of opposition-based initialization with a quadratically decaying Gaussian perturbation step size for local improvement in a compact, budget-aware manner.
# Failure modes:
#   1. Premature convergence: The algorithm might get stuck in a local optimum, especially in multimodal landscapes, due to its greedy nature and reliance on local perturbations around a single `best_x`.
#   2. Inefficient for very high dimensions: The random perturbation might become inefficient in very high-dimensional spaces without more sophisticated direction-finding mechanisms.
#   3. Limited exploration for small budgets: With very small budgets, most evaluations might go into initialization, leaving little for effective local search.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    """
    GNBG (Guided Neighborhood Based Gradient-free) black-box minimization benchmark algorithm.

    Combines opposition-based initialization with a decaying-step local random perturbation search.
    """

    def __init__(self, budget: int, dim: int):
        """
        Initializes the algorithm with a total evaluation budget and problem dimension.

        Args:
            budget (int): The maximum number of function evaluations allowed.
            dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.eval_count = 0
        self.lower = None
        self.upper = None

    def _get_bounds(self, func):
        """
        Extracts lower and upper bounds from the objective function.
        Prioritizes func.lower/upper, falls back to func.bounds.lb/ub.
        """
        try:
            # Check for direct lower/upper attributes
            if hasattr(func, 'lower') and hasattr(func, 'upper'):
                self.lower = np.asarray(func.lower, dtype=float)
                self.upper = np.asarray(func.upper, dtype=float)
            # Check for func.bounds.lb/ub
            elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
                self.lower = np.asarray(func.bounds.lb, dtype=float)
                self.upper = np.asarray(func.bounds.ub, dtype=float)
            else:
                raise AttributeError("Function object must have 'lower'/'upper' or 'bounds.lb'/'bounds.ub' attributes.")

            # Ensure bounds are correctly shaped (e.g., if func.lower/upper are scalars for all dimensions)
            if self.lower.ndim == 0:
                self.lower = np.full(self.dim, self.lower)
            if self.upper.ndim == 0:
                self.upper = np.full(self.dim, self.upper)

            if not (self.lower.shape == (self.dim,) and self.upper.shape == (self.dim,)):
                raise ValueError(f"Bounds must be 1D arrays of shape ({self.dim},), "
                                 f"got lower shape {self.lower.shape}, upper shape {self.upper.shape}")

        except Exception as e:
            raise ValueError(f"Failed to retrieve bounds from function object: {e}")

    def __call__(self, func) -> tuple[np.ndarray, float]:
        """
        Executes the optimization algorithm.

        Args:
            func: The objective function to minimize. It takes a numpy array (solution vector)
                  and returns a float (objective value).

        Returns:
            tuple[np.ndarray, float]: A tuple containing the best found solution vector (best_x)
                                      and its corresponding objective value (best_y).
        """
        self.eval_count = 0
        self._get_bounds(func)
        lower, upper = self.lower, self.upper

        best_x = None
        best_y = float('inf')

        # --- Phase 1: Opposition-Based Initialization ---
        # Generate initial samples and their opposite points to get a good spread.
        # Allocate a portion of the budget, ensuring at least one pair if possible.
        # Aim for `max(1, self.dim)` pairs, but cap by half the total budget.
        num_opposition_pairs = min(self.budget // 2, max(1, self.dim))

        for _ in range(num_opposition_pairs):
            if self.eval_count >= self.budget:
                break

            # Generate a random point within bounds
            x_rand = np.random.uniform(lower, upper, self.dim)
            y_rand = func(x_rand)
            self.eval_count += 1

            if y_rand < best_y:
                best_y = y_rand
                best_x = x_rand

            if self.eval_count >= self.budget:
                break

            # Generate the opposite point
            # x_opp = lower + upper - x_rand reflects x_rand across the center of the bounds
            x_opp = lower + upper - x_rand
            # Ensure opposite point is within bounds (should be if x_rand is)
            x_opp = np.clip(x_opp, lower, upper)
            y_opp = func(x_opp)
            self.eval_count += 1

            if y_opp < best_y:
                best_y = y_opp
                best_x = x_opp

        # Handle the edge case where budget is 1 and no opposition pairs were generated.
        # Ensure best_x is initialized with at least one evaluation if budget > 0.
        if best_x is None and self.eval_count < self.budget:
            x_initial = np.random.uniform(lower, upper, self.dim)
            best_y = func(x_initial)
            best_x = x_initial
            self.eval_count += 1

        # If budget is 0 or initial calls exhausted it completely without finding a point
        if best_x is None:
            # This case should only occur if budget was 0 from the start.
            return np.full(self.dim, np.nan), float('inf') # Return a placeholder for no evaluations.

        # --- Phase 2: Local Improvement (Decaying Step Random Perturbation) ---
        # Start with a step size proportional to the search space range.
        # It decays over the remaining budget.
        initial_step_size_range = np.mean(upper - lower) / 10.0
        
        while self.eval_count < self.budget:
            # Calculate current step size based on remaining budget
            # Uses a quadratic decay to reduce step size faster towards the end.
            # Adds a small epsilon to prevent step size from becoming exactly zero too early,
            # allowing for minimal perturbations even at the very end.
            remaining_budget_ratio = (self.budget - self.eval_count) / self.budget
            current_step_size = initial_step_size_range * (remaining_budget_ratio**2) + 1e-9

            # Generate a candidate by perturbing the current best_x
            # The perturbation is a Gaussian noise with std_dev = current_step_size
            perturbation = np.random.normal(0, current_step_size, self.dim)
            x_candidate = best_x + perturbation

            # Clip the candidate solution to ensure it stays within bounds
            x_candidate = np.clip(x_candidate, lower, upper)

            # Evaluate the candidate solution
            y_candidate = func(x_candidate)
            self.eval_count += 1

            # If a better solution is found, update best_x and best_y
            if y_candidate < best_y:
                best_y = y_candidate
                best_x = x_candidate

        return best_x, best_y
