# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: A (1+1) Evolution Strategy (ES) that employs a success-based step-size adaptation, 
#          traditionally known as the 1/5th success rule.
# Search state: The current best solution vector (best_x), its objective value (best_y), 
#               and a global mutation strength (sigma).
# Candidate generation: Candidates are generated by adding Gaussian noise to the current 
#                        best point. This noise is scaled by the current sigma and the 
#                        width of the search space in each dimension.
# Selection and replacement: A greedy (1+1) selection strategy is used; a new candidate 
#                            replaces the current best if its objective value is less 
#                            than or equal to the current best.
# Adaptation: The mutation strength sigma is adjusted exponentially after every evaluation. 
#             An improvement (success) increases sigma to expand the search, while a 
#             failure decreases it to refine the search.
# Exploration mechanisms: The algorithm starts with a large mutation radius (10% of the 
#                          search range) and expands sigma upon finding improvements.
# Exploitation mechanisms: Exponential decay of sigma during failures allows the search 
#                          to converge precisely on local or global optima.
# Boundary handling: Generated candidates are clipped to the feasible region defined by 
#                    the lower and upper bounds of the objective function.
# Budget strategy: The algorithm tracks evaluations in a simple loop and terminates 
#                  exactly when the provided budget is exhausted.
# Closest known influences: Rechenberg's (1+1)-ES and the 1/5th success rule for 
#                            evolutionary parameter control.
# Novelty or unusual aspects: Provides a compact, window-free implementation of 
#                             success-rate adaptation using continuous exponential updates.
# Failure modes: May converge to local optima in highly multi-modal landscapes due 
#                to the local nature of (1+1) search.
# ALGORITHM_ANALYSIS_NOTE_END

import numpy as np

class Algorithm:
    def __init__(self, budget, dim):
        """
        Initializes the optimization algorithm.
        
        Args:
            budget (int): Total number of function evaluations allowed.
            dim (int): Dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        """
        Runs the minimization process.
        
        Args:
            func (callable): The objective function to minimize.
            
        Returns:
            tuple: (best_x, best_y) found during the search.
        """
        # Extract bounds from the function object
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            lb = np.asarray(func.lower)
            ub = np.asarray(func.upper)
        else:
            lb = np.asarray(func.bounds.lb)
            ub = np.asarray(func.bounds.ub)
        
        range_vec = ub - lb
        best_x = None
        best_y = float('inf')
        
        # Mutation strength (sigma) relative to the range of the search space
        sigma = 0.1
        
        evals = 0
        while evals < self.budget:
            if evals == 0:
                # Start with a random point within bounds
                candidate = lb + range_vec * np.random.rand(self.dim)
            else:
                # Generate a mutated candidate using Gaussian noise
                noise = np.random.randn(self.dim)
                candidate = np.clip(best_x + sigma * range_vec * noise, lb, ub)
            
            # Evaluate the candidate
            y_cand = func(candidate)
            evals += 1
            
            # Selection: Update best point if candidate is better or equal
            if evals == 1 or y_cand <= best_y:
                # Success: update point and increase search radius
                best_y = y_cand
                best_x = candidate
                
                # Adaptation: Continuous version of 1/5th rule update
                # Success increases sigma: exp(0.8/d)
                if evals > 1:
                    sigma *= np.exp(0.8 / self.dim)
            else:
                # Failure: decrease search radius
                # Failure decreases sigma: exp(-0.2/d)
                # This ensures sigma stays stable if success rate is 1/5 (0.8 - 0.2 * 4 = 0)
                sigma *= np.exp(-0.2 / self.dim)
            
            # Clamp sigma to prevent numerical issues or excessive expansion
            sigma = min(sigma, 2.0)
            
        return best_x, best_y
