import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates new candidate
# solutions by sampling uniformly within the search space.
# Search state: The algorithm maintains the current best solution found so far.
# Candidate generation: Candidates are generated by sampling uniformly within
# the search space.
# Selection and replacement: The best candidate is selected and replaces the
# current best solution if it has a lower objective value.
# Adaptation: There is no adaptation in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
# sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the search space by selecting
# the best candidate solution found so far.
# Boundary handling: Candidate solutions that fall outside the search space
# are discarded and a new candidate is generated.
# Budget strategy: The algorithm uses the entire evaluation budget.
# Closest known influences: This algorithm is a basic random search
# implementation.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
# algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
# high-dimensional or multimodal problems, as it does not have any advanced
# exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Get the search space bounds
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            lb = func.lower
            ub = func.upper

        for _ in range(self.budget):
            # Generate a new candidate solution
            x = lb + (ub - lb) * np.random.rand(self.dim)

            # Evaluate the candidate solution
            y = func(x)

            # Update the best solution if the candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
