import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact and robust implementation of a black-box optimization algorithm that uses a random search strategy to find the global minimum of a given objective function within a specified evaluation budget. The algorithm samples candidate solutions uniformly from the search space, evaluates them, and updates the best solution found so far.
# Search state: The algorithm maintains a single best solution, represented by the (best_x, best_y) tuple.
# Candidate generation: Candidate solutions are generated by sampling uniformly from the search space defined by the function's bounds.
# Selection and replacement: The algorithm selects the best candidate solution found so far and replaces the current best solution if the new candidate is better.
# Adaptation: The algorithm does not adapt during the search process, as it uses a fixed random sampling strategy.
# Exploration mechanisms: The algorithm explores the search space by generating random candidate solutions uniformly across the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution by replacing it with a better candidate if found.
# Boundary handling: The algorithm ensures that all candidate solutions are within the search space bounds by clamping the values to the bounds if necessary.
# Budget strategy: The algorithm stops the search when the evaluation budget is exhausted.
# Closest known influences: This implementation is similar to a simple random search algorithm, which is a common baseline for black-box optimization problems.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust, and easy to understand, making it suitable for use in a wide range of black-box optimization benchmarks.
# Failure modes: The algorithm may struggle to find the global minimum in high-dimensional, multimodal, or deceptive objective functions, as it relies solely on random sampling without any advanced search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
