import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple, gradient-free optimization method that uses
#          a population of candidate solutions and applies mutation and selection
#          to generate new candidates and converge towards the optimum.
# Search state: The algorithm maintains a population of candidate solutions,
#               represented as a 2D numpy array. Each row in the array
#               corresponds to a candidate solution.
# Candidate generation: New candidate solutions are generated by applying
#                       Gaussian mutation to the current population. The
#                       mutation step size is adapted based on the current
#                       population's performance.
# Selection and replacement: The population is sorted based on the objective
#                            function values, and the best candidates are
#                            selected to form the next generation.
# Adaptation: The mutation step size is adapted based on the current population's
#             performance. If the population is improving, the step size is
#             increased; otherwise, it is decreased.
# Exploration mechanisms: The Gaussian mutation provides a balance of exploration
#                         and exploitation, allowing the algorithm to search
#                         the space broadly while also focusing on promising
#                         regions.
# Exploitation mechanisms: The selection of the best candidates in the population
#                          allows the algorithm to exploit the most promising
#                          regions of the search space.
# Boundary handling: Candidate solutions that violate the problem's bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget to
#                  perform a single run.
# Closest known influences: This algorithm is similar to a simple Evolutionary
#                           Strategy (ES) with adaptive step size.
# Novelty or unusual aspects: The algorithm does not use any problem-specific
#                             knowledge or additional external resources.
# Failure modes: The algorithm may struggle with highly multimodal or
#                deceptive objective functions, where the Gaussian mutation
#                is not sufficient to escape local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.pop_size = 10 * dim
        self.pop = np.random.uniform(0, 1, (self.pop_size, self.dim))
        self.step_size = 0.1

    def __call__(self, func):
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        evals = 0
        best_x = None
        best_y = float('inf')

        while evals < self.budget:
            # Evaluate the current population
            y = np.array([func(x) for x in self.pop])
            evals += self.pop_size

            # Update the best solution
            idx = np.argmin(y)
            if y[idx] < best_y:
                best_x = self.pop[idx]
                best_y = y[idx]

            # Select the best candidates
            sorted_idx = np.argsort(y)
            self.pop = self.pop[sorted_idx[:self.pop_size // 2]]

            # Apply Gaussian mutation
            self.pop += np.random.normal(0, self.step_size, self.pop.shape)

            # Bound handling
            self.pop = np.clip(self.pop, self.lower, self.upper)

            # Adapt the step size
            if np.mean(y[sorted_idx[:self.pop_size // 2]]) < np.mean(y[sorted_idx[self.pop_size // 2:]]):
                self.step_size *= 1.2
            else:
                self.step_size *= 0.8

        return best_x, best_y
