import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a random restart strategy to search for the global minimum of the objective function. It samples a candidate solution from a uniform random distribution within the bounds of the search space, evaluates the objective function, and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x) and its corresponding objective function value (best_y).
# Candidate generation: Candidates are generated by sampling a point from a uniform random distribution within the bounds of the search space.
# Selection and replacement: The candidate solution is compared to the current best solution, and the better of the two is retained as the new best solution.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling new candidate solutions from a uniform random distribution.
# Exploitation mechanisms: The algorithm exploits the search space by keeping track of the best solution found so far and using it as a starting point for subsequent iterations.
# Boundary handling: The algorithm ensures that the candidate solution is within the bounds of the search space by clamping the values if necessary.
# Budget strategy: The algorithm uses the entire evaluation budget before terminating.
# Closest known influences: This algorithm is a simple random restart strategy, which is a commonly used approach for global optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may fail to find the global minimum if the objective function is highly multimodal or if the evaluation budget is too small.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the objective function
            y = func(x)

            # Update the best solution if necessary
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
