import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that samples points uniformly within the provided bounds and keeps track of the best solution found so far.
# Search state: The search state is simply the best solution found so far, represented by the best_x and best_y variables.
# Candidate generation: Candidates are generated by sampling points uniformly within the provided bounds.
# Selection and replacement: The best candidate replaces the current best solution if it has a lower objective function value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by uniformly sampling points within the provided bounds.
# Exploitation mechanisms: The algorithm exploits the current best solution by sampling points around it, but this is not implemented in this simple version.
# Boundary handling: Boundary handling is performed by clamping the sampled points to the provided bounds.
# Budget strategy: The algorithm simply uses the provided evaluation budget and stops when the budget is exhausted.
# Closest known influences: This algorithm is a basic random search algorithm, which is a common starting point for black-box optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in highly multimodal or high-dimensional problems, as it relies solely on random sampling without any sophisticated exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        evaluations = 0
        while evaluations < self.budget:
            # Generate a candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the candidate solution
            y = func(x)
            evaluations += 1

            # Update the best solution if the candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
