import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a black-box optimization algorithm based on Nelder-Mead simplex method.
# Search state: The search state is represented by a simplex of N+1 points, where N is the problem dimension.
# Candidate generation: New candidate points are generated by performing Nelder-Mead reflections, expansions, and contractions on the simplex.
# Selection and replacement: The worst point in the simplex is replaced by the new candidate, if it improves the objective value.
# Adaptation: The simplex size and shape adapts based on the Nelder-Mead update rules, which depend on the relative objective values of the simplex vertices.
# Exploration mechanisms: The simplex explores the search space by expanding, contracting, and reflecting, allowing it to navigate rugged and multimodal landscapes.
# Exploitation mechanisms: The simplex converges towards the local minimum by gradually shrinking its size.
# Boundary handling: If a candidate point goes outside the feasible domain, it is projected back onto the nearest boundary.
# Budget strategy: The algorithm terminates when the evaluation budget is exhausted.
# Closest known influences: This implementation is based on the Nelder-Mead simplex method, a classic gradient-free optimization algorithm.
# Novelty or unusual aspects: None, this is a standard implementation of the Nelder-Mead algorithm.
# Failure modes: The algorithm may converge to a local minimum, especially on highly multimodal functions. It may also struggle with very high-dimensional problems or functions with many local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x = np.zeros((self.dim + 1, self.dim))
        y = np.zeros(self.dim + 1)
        for i in range(self.dim + 1):
            if hasattr(func, 'bounds'):
                x[i] = func.bounds.lb + (func.bounds.ub - func.bounds.lb) * np.random.rand(self.dim)
            else:
                x[i] = func.lower + (func.upper - func.lower) * np.random.rand(self.dim)
            y[i] = func(x[i])
            self.evaluations += 1

        # Nelder-Mead simplex optimization
        while self.evaluations < self.budget:
            # Order the simplex vertices
            order = np.argsort(y)
            x = x[order]
            y = y[order]

            # Compute the centroid of the best N points
            xbar = np.mean(x[:-1], axis=0)

            # Reflection
            xr = xbar + (xbar - x[-1])
            yr = func(xr)
            self.evaluations += 1
            if y[0] <= yr < y[-2]:
                x[-1] = xr
                y[-1] = yr
                continue

            # Expansion
            if yr < y[0]:
                xe = xbar + 2 * (xbar - x[-1])
                ye = func(xe)
                self.evaluations += 1
                if ye < yr:
                    x[-1] = xe
                    y[-1] = ye
                    continue
                else:
                    x[-1] = xr
                    y[-1] = yr
                    continue

            # Contraction
            xc = xbar + 0.5 * (x[-1] - xbar)
            yc = func(xc)
            self.evaluations += 1
            if yc < y[-1]:
                x[-1] = xc
                y[-1] = yc
                continue

            # Shrink
            x[1:] = x[0] + 0.5 * (x[1:] - x[0])
            for i in range(1, self.dim + 1):
                y[i] = func(x[i])
                self.evaluations += 1

        # Return the best solution found
        best_idx = np.argmin(y)
        return x[best_idx], y[best_idx]
