import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search that generates candidate solutions
#          uniformly within the search space and selects the best one found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling each dimension uniformly
#                       within the provided bounds.
# Selection and replacement: The best candidate found so far is kept as the current
#                            solution.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling
#                         new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the search space by keeping track of
#                          the best solution found so far.
# Boundary handling: Candidate solutions that fall outside the search space are
#                    rejected and a new candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search method.
# Novelty or unusual aspects: None.
# Failure modes: The algorithm may struggle on highly multi-modal or deceptive
#                objective functions, as it has no mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        evaluations = 0
        while evaluations < self.budget:
            # Generate a new candidate solution
            candidate_x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)
            evaluations += 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
