import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This Python module implements a simple, compact, and robust black-box
#          optimization algorithm for the GNBG benchmark. The algorithm uses a
#          random search strategy, sampling candidate solutions uniformly
#          within the search space defined by the problem bounds.
# Search state: The search state is represented by the current best solution
#               (best_x, best_y).
# Candidate generation: Candidates are generated by sampling uniformly within
#                      the search space defined by the problem bounds.
# Selection and replacement: The best candidate solution found so far is
#                           stored and updated as the search progresses.
# Adaptation: The algorithm does not adapt during the search, it simply
#             samples new candidates uniformly.
# Exploration mechanisms: The algorithm explores the search space by
#                        sampling new candidate solutions randomly.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                         by biasing the sampling towards the best known
#                         solution.
# Boundary handling: The algorithm handles boundary constraints by
#                   rejecting any candidate solutions that fall outside
#                   the search space defined by the problem bounds.
# Budget strategy: The algorithm spends the entire evaluation budget
#                  sampling new candidate solutions.
# Closest known influences: The algorithm is a simple random search
#                         strategy, which is a common baseline for
#                         black-box optimization problems.
# Novelty or unusual aspects: The algorithm is a straightforward
#                            implementation of a random search
#                            strategy, with no unusual or novel
#                            aspects.
# Failure modes: The algorithm may struggle to solve problems with
#               highly multimodal or deceptive objective functions,
#               as it does not employ any advanced exploration or
#               exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            lb = func.lower
            ub = func.upper

        # Perform random search
        for _ in range(self.budget):
            x = np.random.uniform(lb, ub, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
