import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: The algorithm is a simple random search algorithm that samples points
#          uniformly within the bounded search space and keeps track of the best
#          solution found so far.
# Search state: The search state is simply the current best solution (best_x,
#               best_y).
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the bounded search space.
# Selection and replacement: The best candidate (if any) replaces the current
#                           best solution.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The algorithm explores the search space uniformly
#                         by randomly sampling points.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          keeping track of it and returning it as the final
#                          result.
# Boundary handling: Boundary handling is performed by clamping the sampled
#                    points to the search space bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to sample
#                  points and find the best solution.
# Closest known influences: This algorithm is a basic random search algorithm,
#                          which is a simple and robust optimization technique.
# Novelty or unusual aspects: The algorithm is very simple and straightforward,
#                            without any advanced features or mechanisms.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it relies solely
#                on random sampling without any directed search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
