import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a black-box
#          optimization algorithm that uses a randomized search strategy to
#          minimize an objective function. It leverages the NumPy library for
#          core functionality and is designed to work within the provided
#          evaluation budget.
# Search state: The search state is represented by the current best solution
#               (best_x, best_y), which is updated as the algorithm progresses.
# Candidate generation: New candidate solutions are generated by sampling from
#                      a normal distribution centered around the current best
#                      solution, with a standard deviation that adapts based on
#                      the evaluation budget.
# Selection and replacement: The algorithm selects the new candidate solution
#                           if it improves the current best solution, and
#                           replaces the best solution accordingly.
# Adaptation: The standard deviation of the normal distribution used for
#             candidate generation is adapted based on the remaining evaluation
#             budget, allowing for more exploration early on and more
#             exploitation towards the end of the budget.
# Exploration mechanisms: The algorithm explores the search space by generating
#                        new candidate solutions using a normal distribution
#                        centered around the current best solution.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                         generating new candidates in its vicinity, with the
#                         standard deviation of the normal distribution
#                         decreasing as the budget is consumed.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                   within the provided bounds by clipping the values if
#                   necessary.
# Budget strategy: The algorithm aims to use the entire evaluation budget by
#                  adapting the standard deviation of the normal distribution
#                  used for candidate generation.
# Closest known influences: This algorithm is inspired by simple randomized
#                          search techniques, such as Gaussian mutation in
#                          evolutionary algorithms.
# Novelty or unusual aspects: The adaptive nature of the standard deviation
#                            based on the remaining budget is a novel aspect
#                            of this implementation.
# Failure modes: The algorithm may struggle with highly multimodal or
#               deceptive objective functions, as it relies on a simple
#               randomized search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        if self.best_x is None:
            # Initialize the search by sampling a random starting point
            self.best_x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
            self.best_y = func(self.best_x)
            self.budget -= 1

        # Adapt the standard deviation based on the remaining budget
        std_dev = (func.bounds.ub - func.bounds.lb) / (2 * np.sqrt(self.budget))

        while self.budget > 0:
            # Generate a new candidate solution
            candidate_x = self.best_x + std_dev * np.random.normal(size=self.dim)

            # Ensure the candidate is within the bounds
            candidate_x = np.clip(candidate_x, func.bounds.lb, func.bounds.ub)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)
            self.budget -= 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
