import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple implementation of the Nelder-Mead simplex
#          method, a direct search optimization technique for unconstrained
#          minimization problems.
# Search state: The search state is represented by a simplex, which is a
#                geometric figure with N+1 vertices in N-dimensional space.
# Candidate generation: New candidate solutions are generated by performing
#                      reflections, expansions, and contractions of the current
#                      simplex.
# Selection and replacement: The vertex with the highest function value is
#                           replaced by the new candidate solution if it
#                           improves the objective function.
# Adaptation: The size and shape of the simplex are adapted based on the
#             relative function values at the vertices, allowing the algorithm
#             to explore the search space efficiently.
# Exploration mechanisms: The algorithm explores the search space by reflecting
#                        the simplex through the centroid of the other vertices,
#                        and by expanding or contracting the simplex based on
#                        the success of the reflection.
# Exploitation mechanisms: The algorithm exploits the current search region by
#                         performing contractions of the simplex towards the
#                         best vertex.
# Boundary handling: The algorithm handles boundary constraints by reflecting
#                   any vertex that goes outside the bounds back onto the
#                   boundary.
# Budget strategy: The algorithm terminates when the evaluation budget is
#                  exhausted.
# Closest known influences: The Nelder-Mead simplex method.
# Novelty or unusual aspects: None.
# Failure modes: The algorithm may converge to a local minimum if the objective
#                function is multi-modal or has many local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.bounds.lb, func.bounds.ub, size=self.dim)
        vertices = [x0 + 0.05 * (func.bounds.ub - func.bounds.lb) * np.random.randn(self.dim) for _ in range(self.dim + 1)]
        function_values = [func(x) for x in vertices]
        self.evaluations += self.dim + 1

        # Nelder-Mead simplex algorithm
        while self.evaluations < self.budget:
            # Order the vertices from best to worst
            vertices = [x for _, x in sorted(zip(function_values, vertices))]
            function_values = sorted(function_values)

            # Calculate the centroid of the best vertices
            centroid = np.mean(vertices[:-1], axis=0)

            # Reflect the worst vertex through the centroid
            reflected = centroid + (centroid - vertices[-1])
            reflected_value = func(reflected)
            self.evaluations += 1

            if reflected_value < function_values[0]:
                # Expand the simplex
                expanded = centroid + 2 * (reflected - centroid)
                expanded_value = func(expanded)
                self.evaluations += 1
                if expanded_value < reflected_value:
                    vertices[-1] = expanded
                    function_values[-1] = expanded_value
                else:
                    vertices[-1] = reflected
                    function_values[-1] = reflected_value
            elif reflected_value < function_values[-2]:
                # Accept the reflected vertex
                vertices[-1] = reflected
                function_values[-1] = reflected_value
            else:
                # Contract the simplex
                if reflected_value < function_values[-1]:
                    contracted = centroid + 0.5 * (reflected - centroid)
                else:
                    contracted = centroid - 0.5 * (vertices[-1] - centroid)
                contracted_value = func(contracted)
                self.evaluations += 1
                if contracted_value < function_values[-1]:
                    vertices[-1] = contracted
                    function_values[-1] = contracted_value
                else:
                    # Shrink the simplex
                    vertices = [vertices[0] + 0.5 * (x - vertices[0]) for x in vertices]
                    function_values = [func(x) for x in vertices]
                    self.evaluations += self.dim

        # Return the best solution found
        best_idx = np.argmin(function_values)
        best_x = vertices[best_idx]
        best_y = function_values[best_idx]
        return best_x, best_y
