import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized search algorithm for black-box minimization. It uses a purely random search within the given bounds, with no specific adaptation or search state.
# Search state: The algorithm maintains no explicit search state.
# Candidate generation: New candidate solutions are generated by sampling uniformly random points within the given bounds.
# Selection and replacement: The best candidate solution found so far is always kept, and is returned as the result.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling uniformly random points.
# Exploitation mechanisms: The algorithm does not have any exploitation mechanisms.
# Boundary handling: The algorithm samples points uniformly within the given bounds, and simply returns the best point found within the evaluation budget.
# Budget strategy: The algorithm uses the full evaluation budget, without any early stopping or budget management.
# Closest known influences: This algorithm is a basic random search, similar to the 'Uniform Random Search' method.
# Novelty or unusual aspects: This implementation is designed to be compact, robust, and self-contained, without any external dependencies or complex mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex, multi-modal landscapes, as it has no mechanisms to efficiently explore or exploit the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
