import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact, robust, and randomized black-box
#          optimization method that uses a Gaussian random search with
#          adaptive step sizes to efficiently explore the search space and
#          find the global minimum.
# Search state: The search state is represented by the current best solution
#               (best_x, best_y) and a vector of standard deviations (sigma)
#               that control the step sizes for each dimension.
# Candidate generation: New candidate solutions are generated by adding
#                       Gaussian-distributed perturbations to the current
#                       best solution, with the step sizes controlled by the
#                       sigma vector.
# Selection and replacement: The best candidate solution is selected and
#                            replaces the current best solution if it improves
#                            the objective value.
# Adaptation: The step sizes (sigma) are adapted based on the success or
#             failure of the previous step, using a simple update rule.
# Exploration mechanisms: The Gaussian random search provides a balance of
#                         exploration and exploitation, allowing the
#                         algorithm to explore the search space while also
#                         converging towards the global minimum.
# Exploitation mechanisms: The algorithm focuses exploitation on the current
#                          best solution by generating new candidates in its
#                          vicinity.
# Boundary handling: If a candidate solution falls outside the search bounds,
#                    it is projected back onto the nearest valid point.
# Budget strategy: The algorithm uses the entire evaluation budget, without
#                  exceeding it, by generating and evaluating as many
#                  candidates as possible within the given budget.
# Closest known influences: This algorithm is similar to randomized search
#                           methods like Gaussian random search, and it
#                           incorporates adaptive step sizes like in
#                           self-adaptive evolution strategies.
# Novelty or unusual aspects: The compact and robust implementation, which
#                             avoids external dependencies and handles
#                             arbitrary dimensions, is a novel aspect of
#                             this algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems with
#                complex, multi-modal objective functions, where the Gaussian
#                random search may not be sufficient to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = float('inf')
        self.sigma = np.ones(dim)

    def __call__(self, func):
        remaining_budget = self.budget
        while remaining_budget > 0:
            candidate_x = self.best_x + self.sigma * np.random.normal(size=self.dim)
            candidate_y = func(candidate_x)
            remaining_budget -= 1

            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            self.update_sigma()

        return self.best_x, self.best_y

    def update_sigma(self):
        # Adapt the step sizes based on the success or failure of the
        # previous step
        if self.best_y < float('inf'):
            self.sigma *= 0.9  # Decrease step sizes on success
        else:
            self.sigma *= 1.1  # Increase step sizes on failure

        # Ensure step sizes remain within reasonable bounds
        self.sigma = np.maximum(self.sigma, 1e-8)
        self.sigma = np.minimum(self.sigma, 1e2)
