import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple, compact implementation of a black-box optimization
# algorithm based on randomized search. It initializes a population of candidate
# solutions, evaluates them, and then iteratively generates and evaluates new
# candidates, keeping track of the best solution found so far.
# Search state: The search state consists of a population of candidate solutions,
# represented as a 2D numpy array, along with the corresponding objective values.
# Candidate generation: New candidate solutions are generated by sampling
# uniformly within the search space bounds.
# Selection and replacement: The best candidate solution from the current
# population is always kept, and the remaining candidates are replaced by new
# randomly generated solutions.
# Adaptation: There is no adaptation mechanism in this implementation; the search
# process is entirely driven by random sampling.
# Exploration mechanisms: The exploration mechanism is based on uniform random
# sampling within the search space bounds.
# Exploitation mechanisms: There are no explicit exploitation mechanisms; the
# algorithm relies on the stochastic nature of the random sampling to eventually
# find good solutions.
# Boundary handling: Candidate solutions that fall outside the search space
# bounds are simply discarded and replaced with new random solutions.
# Budget strategy: The algorithm simply evaluates the maximum number of
# candidates allowed by the provided budget.
# Closest known influences: This algorithm is similar to a basic evolutionary
# strategy or a random search algorithm.
# Novelty or unusual aspects: This implementation is designed to be as compact
# and simple as possible, while still meeting the requirements of the GNBG
# black-box minimization benchmark.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive
# functions, as it relies solely on random sampling without any more advanced
# exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 10 * self.dim
        self.population = None
        self.population_values = None
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        if self.population is None:
            self.initialize_population(func)

        for _ in range(self.budget // self.population_size):
            self.update_population(func)

        return self.best_x, self.best_y

    def initialize_population(self, func):
        self.population = np.random.uniform(
            func.lower if hasattr(func, 'lower') else func.bounds.lb,
            func.upper if hasattr(func, 'upper') else func.bounds.ub,
            (self.population_size, self.dim)
        )
        self.population_values = np.array([func(x) for x in self.population])
        self.best_x = self.population[np.argmin(self.population_values)]
        self.best_y = np.min(self.population_values)

    def update_population(self, func):
        new_population = np.random.uniform(
            func.lower if hasattr(func, 'lower') else func.bounds.lb,
            func.upper if hasattr(func, 'upper') else func.bounds.ub,
            (self.population_size, self.dim)
        )
        new_population_values = np.array([func(x) for x in new_population])
        self.population = np.vstack((self.best_x[None, :], new_population[1:]))
        self.population_values = np.concatenate((
            [self.best_y], new_population_values[1:]
        ))
        self.best_x = self.population[np.argmin(self.population_values)]
        self.best_y = np.min(self.population_values)
