import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is an implementation of a simple stochastic gradient descent (SGD) algorithm for
#          the GNBG black-box minimization benchmark. The algorithm iteratively updates the
#          search point by taking a step in the direction of the negative gradient, subject to
#          the problem bounds.
# Search state: The search state is represented by the current point x and the best point found so far.
# Candidate generation: New candidates are generated by taking a step in the direction of the
#                       negative gradient, with a step size that decreases over time.
# Selection and replacement: The new candidate replaces the current point if it has a lower
#                            objective function value.
# Adaptation: The step size is adapted over time using a simple schedule that decreases the
#             step size as the number of function evaluations increases.
# Exploration mechanisms: The algorithm relies on the stochastic nature of the gradient estimates
#                         to explore the search space.
# Exploitation mechanisms: The algorithm focuses on exploiting the local gradient information to
#                          move towards the minimum.
# Boundary handling: If a candidate point goes outside the bounds, it is projected back onto the
#                    feasible region.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This implementation is inspired by basic stochastic gradient descent
#                           algorithms used in machine learning and optimization.
# Novelty or unusual aspects: The algorithm is designed to be simple, compact, and robust across
#                             different problem dimensions.
# Failure modes: The algorithm may struggle in highly multimodal or non-differentiable problems,
#                where the gradient information is not reliable.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.step_size = 1.0
        self.best_x = np.zeros(self.dim)
        self.best_y = np.inf

    def __call__(self, func):
        x = np.zeros(self.dim)
        evals = 0

        while evals < self.budget:
            # Compute the gradient estimate
            grad = self.__gradient(func, x)

            # Update the step size
            self.step_size = max(1e-4, self.step_size * 0.99)

            # Take a step in the direction of the negative gradient
            new_x = x - self.step_size * grad

            # Project the new point onto the feasible region
            new_x = self.__project(new_x, func)

            # Evaluate the new point
            new_y = func(new_x)
            evals += 1

            # Update the best point if necessary
            if new_y < self.best_y:
                self.best_x = new_x
                self.best_y = new_y

            # Update the current point
            x = new_x

        return self.best_x, self.best_y

    def __gradient(self, func, x):
        # Compute the gradient estimate using finite differences
        eps = 1e-8
        grad = np.zeros_like(x)
        for i in range(self.dim):
            x_plus = x.copy()
            x_plus[i] += eps
            x_minus = x.copy()
            x_minus[i] -= eps
            grad[i] = (func(x_plus) - func(x_minus)) / (2 * eps)
        return grad

    def __project(self, x, func):
        # Project the point onto the feasible region
        lb = getattr(func, 'lower', func.bounds.lb)
        ub = getattr(func, 'upper', func.bounds.ub)
        return np.clip(x, lb, ub)
