import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a simple randomized search algorithm for black-box optimization problems. It generates candidate solutions uniformly within the search space, evaluates them, and keeps track of the best solution found so far.
# Search state: The algorithm maintains a single best solution, represented by its input coordinates (best_x) and objective function value (best_y).
# Candidate generation: Candidates are generated by sampling uniformly within the search space defined by the bounds of the objective function.
# Selection and replacement: The best candidate found so far replaces the current best solution if it has a lower objective function value.
# Adaptation: The algorithm does not adapt during the optimization process; it uses a fixed sampling strategy throughout the entire budget.
# Exploration mechanisms: The uniform random sampling explores the search space in a fairly unbiased manner.
# Exploitation mechanisms: The algorithm exploits the best solution found so far by always updating to a better candidate if one is found.
# Boundary handling: The algorithm ensures that candidate solutions stay within the bounds of the search space by sampling uniformly within those bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided, evaluating as many candidates as possible within the given budget.
# Closest known influences: This algorithm is a simple, classic randomized search approach, similar to pure random search or uniform random sampling.
# Novelty or unusual aspects: The algorithm is designed to be compact, readable, and robust across dimensions, without relying on any external libraries or techniques.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with highly complex or deceptive landscapes, as it does not employ any advanced exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
