import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that generates
#          new candidate solutions by sampling from a uniform distribution
#          within the given bounds. It keeps track of the best solution found
#          so far and returns it at the end of the budget.
# Search state: The search state is the current best solution found so far.
# Candidate generation: New candidate solutions are generated by sampling from
#                      a uniform distribution within the given bounds.
# Selection and replacement: The best solution found so far is always kept
#                            and returned at the end of the budget.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in
#                          this algorithm.
# Boundary handling: Candidate solutions that fall outside the given bounds
#                    are discarded and a new candidate is generated.
# Budget strategy: The algorithm simply uses up the entire evaluation budget
#                  and returns the best solution found.
# Closest known influences: This algorithm is a basic random search algorithm
#                          without any additional optimization mechanisms.
# Novelty or unusual aspects: There are no unusual aspects to this algorithm.
# Failure modes: The algorithm may fail to find a good solution if the search
#                space is very large or the objective function is highly
#                multimodal.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
