import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search approach to find the
#          minimum of the provided function. It generates random candidate
#          solutions within the provided bounds and evaluates them, keeping
#          track of the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling random points
#                      uniformly within the provided bounds.
# Selection and replacement: The best candidate found so far is always kept.
# Adaptation: The algorithm does not adapt during the search.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                        generating new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the best solution found so far.
# Boundary handling: The algorithm ensures that candidate solutions are always
#                   within the provided bounds.
# Budget strategy: The algorithm uses the entire evaluation budget provided.
# Closest known influences: This algorithm is a basic random search method,
#                          which is a commonly used approach for black-box
#                          optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it relies solely
#                on random exploration.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Read the function bounds
        lb = func.lower if hasattr(func, 'lower') else func.bounds.lb
        ub = func.upper if hasattr(func, 'upper') else func.bounds.ub

        # Initialize the best solution
        self.best_x = np.random.uniform(lb, ub, size=self.dim)
        self.best_y = func(self.best_x)

        # Perform the optimization
        for _ in range(self.budget - 1):
            # Generate a new candidate solution
            candidate_x = np.random.uniform(lb, ub, size=self.dim)
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
