import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized black-box optimization algorithm
#          that uses a gradient-free search to explore the objective function and find the
#          minimum value within the given budget and dimensionality.
# Search state: The search state is represented by the current best position (best_x) and
#               its corresponding function value (best_y).
# Candidate generation: New candidate solutions are generated by sampling from a normal
#                       distribution centered at the current best position, with a
#                       covariance matrix that adapts based on the search progress.
# Selection and replacement: The new candidate is always accepted if it improves the
#                            current best solution. Otherwise, it is discarded.
# Adaptation: The covariance matrix of the sampling distribution is updated at each
#             iteration based on the success or failure of the previous candidate.
# Exploration mechanisms: The algorithm explores the search space by generating new
#                         candidate solutions with a covariance matrix that is
#                         initialized to be large, allowing for broad exploration.
# Exploitation mechanisms: As the search progresses, the covariance matrix is
#                          gradually reduced, focusing the search around the
#                          current best solution.
# Boundary handling: Candidate solutions that fall outside the search bounds are
#                    rejected and a new candidate is generated.
# Budget strategy: The algorithm attempts to make the most efficient use of the
#                  available evaluation budget by continuously updating the
#                  search state and adapting the sampling distribution.
# Closest known influences: This algorithm is loosely inspired by evolutionary
#                           strategies, with a focus on simplicity and robustness.
# Novelty or unusual aspects: The algorithm does not use any external libraries
#                             beyond the Python standard library and NumPy, making
#                             it a self-contained and lightweight solution.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive
#                objective functions, as it relies on a relatively simple
#                adaptation mechanism without any explicit mechanisms for
#                escaping local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.cov = np.eye(self.dim) * 1.0

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = self.best_x + np.random.multivariate_normal(np.zeros(self.dim), self.cov) if self.best_x is not None else np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the new candidate
            y = func(x)

            # Update the best solution if the new candidate is better
            if y < self.best_y:
                self.best_x, self.best_y = x, y

            # Adapt the covariance matrix
            if self.best_x is not None:
                self.cov = np.cov(np.array([self.best_x, x]).T) * 0.9 + np.eye(self.dim) * 0.1

        return self.best_x, self.best_y
