import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search that samples points within the
#          given bounds and keeps track of the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the given bounds.
# Selection and replacement: The best candidate replaces the current best solution
#                            if it has a lower objective function value.
# Adaptation: The algorithm does not adapt during the optimization process.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling points within the bounds.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          continuing to sample around it.
# Boundary handling: The algorithm ensures that all sampled points are within the
#                    given bounds.
# Budget strategy: The algorithm uses the entire evaluation budget, sampling
#                  points until the budget is exhausted.
# Closest known influences: This algorithm is a simple, generic random search
#                          approach that is commonly used as a baseline for
#                          black-box optimization problems.
# Novelty or unusual aspects: The algorithm does not have any novel or unusual
#                            aspects, as it is a basic random search approach.
# Failure modes: The algorithm may struggle to optimize complex, high-dimensional
#                problems, as it does not have any advanced exploration or
#                exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        self.budget_remaining = self.budget
        while self.budget_remaining > 0:
            x = self._sample_point(func)
            y = func(x)
            self.budget_remaining -= 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y

    def _sample_point(self, func):
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            lb = func.lower
            ub = func.upper
        return np.random.uniform(lb, ub, self.dim)
