import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a basic random search algorithm to solve the GNBG black-box minimization benchmark.
# Search state: The current best solution is stored as a single point in the search space.
# Candidate generation: New candidate solutions are generated by sampling uniformly within the bounds of the search space.
# Selection and replacement: The best candidate solution found so far is always kept, replacing the previous best if a better solution is found.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: New candidate solutions are sampled uniformly, providing a purely exploratory search.
# Exploitation mechanisms: There are no exploitation mechanisms in this implementation.
# Boundary handling: Candidate solutions that fall outside the search space bounds are rejected and a new candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This is a basic random search algorithm, without any advanced techniques.
# Novelty or unusual aspects: There are no novel or unusual aspects to this implementation.
# Failure modes: This algorithm may struggle to find the global optimum, especially in high-dimensional problems or problems with many local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        evaluations = 0
        while evaluations < self.budget:
            x = self.sample_candidate(func)
            y = func(x)
            evaluations += 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y

    def sample_candidate(self, func):
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper
        x = np.random.uniform(lb, ub, self.dim)
        return x
