import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact implementation of a gradient-free blackbox
#          optimization algorithm that uses a multivariate normal distribution
#          to sample candidate solutions and updates the distribution parameters
#          based on the performance of the samples.
# Search state: The search state is represented by the mean and covariance matrix
#               of the multivariate normal distribution used to sample candidate
#               solutions.
# Candidate generation: Candidate solutions are generated by sampling from the
#                       multivariate normal distribution.
# Selection and replacement: The best candidate solution observed so far is
#                            kept as the current best solution.
# Adaptation: The mean and covariance matrix of the multivariate normal
#             distribution are updated based on the performance of the
#             candidate solutions.
# Exploration mechanisms: The covariance matrix is used to control the
#                         exploration behavior of the algorithm.
# Exploitation mechanisms: The mean of the multivariate normal distribution
#                          is used to guide the search towards promising regions
#                          of the search space.
# Boundary handling: Candidate solutions that violate the problem bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm attempts to use the entire evaluation budget
#                  provided, but stops early if the optimum is found.
# Closest known influences: This algorithm is based on the CMA-ES (Covariance
#                           Matrix Adaptation Evolution Strategy) algorithm.
# Novelty or unusual aspects: The implementation is very compact and uses only
#                             the Python standard library and NumPy.
# Failure modes: The algorithm may struggle with high-dimensional problems or
#                problems with complex, multimodal, or discontinuous objective
#                functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_mean = np.zeros(dim)
        self.sigma = 1.0
        self.C = np.eye(dim)

    def __call__(self, func):
        best_x = None
        best_y = np.inf
        evals = 0

        while evals < self.budget:
            x = self.x_mean + self.sigma * np.random.multivariate_normal(np.zeros(self.dim), self.C)

            # Bound handling
            if hasattr(func, 'bounds'):
                x = np.clip(x, func.bounds.lb, func.bounds.ub)
            else:
                x = np.clip(x, func.lower, func.upper)

            y = func(x)
            evals += 1

            if y < best_y:
                best_x = x
                best_y = y

            # Update distribution parameters
            delta = (x - self.x_mean) / self.sigma
            self.x_mean += (1 / (evals + 1)) * delta
            self.C += (1 / (evals + 1)) * (np.outer(delta, delta) - self.C)

        return best_x, best_y
