import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple stochastic search algorithm that generates new candidate solutions by
#          perturbing the current best solution, and selects the new best solution based on the
#          objective function value. The algorithm uses adaptive step sizes to balance exploration
#          and exploitation, and handles boundary constraints by reflecting solutions that go
#          outside the search space.
# Search state: The algorithm maintains a single current best solution.
# Candidate generation: New candidate solutions are generated by perturbing the current best
#                       solution with a Gaussian noise vector, with an adaptive step size.
# Selection and replacement: The new candidate solution replaces the current best solution if it
#                            has a lower objective function value.
# Adaptation: The step size for generating new candidates is adapted based on the success rate of
#             the previous iterations, using a simple rule to increase or decrease the step size.
# Exploration mechanisms: The Gaussian noise added to the current best solution encourages
#                         exploration of the search space.
# Exploitation mechanisms: The selection of the new best solution based on the objective function
#                          value encourages exploitation of promising regions of the search space.
# Boundary handling: Solutions that go outside the search space are reflected back into the
#                    search space.
# Budget strategy: The algorithm simply uses all the available evaluation budget.
# Closest known influences: This algorithm is similar to a basic (1+1)-Evolutionary Strategy,
#                           with some additional features like adaptive step size and boundary
#                           handling.
# Novelty or unusual aspects: The algorithm is quite simple and straightforward, without any
#                             unusual or novel aspects.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex
#                multimodal landscapes, as it relies on a single current best solution and
#                Gaussian perturbations.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf
        self.step_size = 1.0

    def __call__(self, func):
        if self.x_best is None:
            self.x_best = np.random.uniform(func.lower, func.upper, self.dim)
            self.f_best = func(self.x_best)
            self.budget -= 1

        success_count = 0
        while self.budget > 0:
            x = self.x_best + self.step_size * np.random.randn(self.dim)
            x = np.clip(x, func.lower, func.upper)
            f = func(x)
            self.budget -= 1

            if f < self.f_best:
                self.x_best = x
                self.f_best = f
                success_count += 1
            else:
                success_count = 0

            self.step_size *= 1.1 if success_count > 0 else 0.9

        return self.x_best, self.f_best
