import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a gradient-free numerical optimization approach based on the Nelder-Mead simplex method.
# Search state: The search state is represented by a simplex of points in the search space, which is iteratively updated.
# Candidate generation: New candidate solutions are generated by performing various operations on the simplex, such as reflection, expansion, and contraction.
# Selection and replacement: The best candidate solution is selected based on the function values at the simplex vertices, and the simplex is updated accordingly.
# Adaptation: The simplex adapts its size and shape during the optimization process to efficiently explore the search space.
# Exploration mechanisms: The algorithm explores the search space by generating new candidates through the simplex operations, which can lead to both exploration and exploitation.
# Exploitation mechanisms: The algorithm exploits the search space by preferentially selecting candidate solutions that improve the current best solution.
# Boundary handling: If a candidate solution falls outside the feasible region, it is projected back onto the boundary of the feasible region.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: The Nelder-Mead simplex method, a classic gradient-free optimization algorithm.
# Novelty or unusual aspects: None, this is a standard implementation of the Nelder-Mead simplex method.
# Failure modes: The algorithm may converge to a local minimum, especially for multimodal or highly irregular objective functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0
        self.simplex = None
        self.simplex_values = None

    def __call__(self, func):
        if self.simplex is None:
            self.initialize_simplex(func)

        while self.evaluations < self.budget:
            self.update_simplex(func)

        best_idx = np.argmin(self.simplex_values)
        best_x = self.simplex[best_idx]
        best_y = self.simplex_values[best_idx]
        return best_x, best_y

    def initialize_simplex(self, func):
        # Initialize a simplex of n+1 points in the n-dimensional search space
        self.simplex = np.zeros((self.dim + 1, self.dim))
        self.simplex_values = np.zeros(self.dim + 1)

        # Set the first vertex of the simplex to a random point within the bounds
        self.simplex[0] = self.generate_initial_point(func)
        self.simplex_values[0] = func(self.simplex[0])
        self.evaluations += 1

        # Set the remaining vertices of the simplex
        for i in range(1, self.dim + 1):
            self.simplex[i] = self.simplex[0].copy()
            self.simplex[i, i-1] += 1.0
            self.simplex_values[i] = func(self.simplex[i])
            self.evaluations += 1

    def update_simplex(self, func):
        # Sort the simplex vertices by their function values
        sort_idx = np.argsort(self.simplex_values)
        self.simplex = self.simplex[sort_idx]
        self.simplex_values = self.simplex_values[sort_idx]

        # Compute the centroid of the best n vertices
        centroid = np.mean(self.simplex[:-1], axis=0)

        # Reflect the worst vertex through the centroid
        reflected = centroid + (centroid - self.simplex[-1])
        reflected_value = func(reflected)
        self.evaluations += 1

        if reflected_value < self.simplex_values[0]:
            # Expansion: If the reflected point is better than the best, try expanding further
            expanded = centroid + 2 * (reflected - centroid)
            expanded_value = func(expanded)
            self.evaluations += 1
            if expanded_value < reflected_value:
                self.simplex[-1] = expanded
                self.simplex_values[-1] = expanded_value
            else:
                self.simplex[-1] = reflected
                self.simplex_values[-1] = reflected_value
        elif reflected_value < self.simplex_values[-2]:
            # Acceptance: If the reflected point is better than the second-worst, accept it
            self.simplex[-1] = reflected
            self.simplex_values[-1] = reflected_value
        else:
            # Contraction: If the reflected point is not better than the second-worst, contract towards the best
            contracted = centroid + 0.5 * (self.simplex[-1] - centroid)
            contracted_value = func(contracted)
            self.evaluations += 1
            if contracted_value < self.simplex_values[-1]:
                self.simplex[-1] = contracted
                self.simplex_values[-1] = contracted_value
            else:
                # Shrink: If the contracted point is not better, shrink the simplex towards the best vertex
                self.simplex[1:] = self.simplex[0] + 0.5 * (self.simplex[1:] - self.simplex[0])
                for i in range(1, self.dim + 1):
                    self.simplex_values[i] = func(self.simplex[i])
                    self.evaluations += 1

    def generate_initial_point(self, func):
        # Generate a random initial point within the bounds of the objective function
        if hasattr(func, 'bounds'):
            lower, upper = func.bounds.lb, func.bounds.ub
        else:
            lower, upper = func.lower, func.upper
        return np.random.uniform(lower, upper, self.dim)
