import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a stochastic gradient descent (SGD) method with momentum and adaptive step sizes.
# Search state: The search state is represented by the current position (x) and the current velocity (v).
# Candidate generation: New candidates are generated by updating the current position using the momentum and the gradient.
# Selection and replacement: The best candidate is selected and replaces the current position if it has a lower objective function value.
# Adaptation: The step size is adapted using an exponential moving average of the gradient magnitude.
# Exploration mechanisms: The momentum term encourages exploration by allowing the search to escape local minima.
# Exploitation mechanisms: The adaptive step size allows the algorithm to focus on promising regions of the search space.
# Boundary handling: If a candidate exceeds the bounds, it is projected back onto the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget to explore the search space.
# Closest known influences: This algorithm is inspired by the ADAM optimization method, but with a different step size adaptation rule.
# Novelty or unusual aspects: The use of an exponential moving average for the step size adaptation is a novel aspect of this algorithm.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive functions, where the gradient information is not a reliable guide to the global minimum.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.v = np.zeros(dim)
        self.step_size = 0.1
        self.beta1 = 0.9
        self.beta2 = 0.999
        self.eps = 1e-8

    def __call__(self, func):
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        self.best_x = self.x.copy()
        self.best_y = func(self.best_x)
        self.evaluations = 1

        while self.evaluations <= self.budget:
            gradient = self.gradient(func, self.x)
            self.v = self.beta1 * self.v + (1 - self.beta1) * gradient
            self.x = self.x - self.step_size * self.v / (np.sqrt(self.eps + np.sum(self.v**2)))

            self.x = np.clip(self.x, self.lower, self.upper)
            y = func(self.x)
            self.evaluations += 1

            if y < self.best_y:
                self.best_x = self.x.copy()
                self.best_y = y

        return self.best_x, self.best_y

    def gradient(self, func, x):
        h = 1e-8
        gradient = np.zeros(self.dim)
        for i in range(self.dim):
            x_plus = x.copy()
            x_plus[i] += h
            x_minus = x.copy()
            x_minus[i] -= h
            gradient[i] = (func(x_plus) - func(x_minus)) / (2 * h)
        return gradient
