import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that samples
#          candidate solutions uniformly within the given search bounds and
#          keeps track of the best solution found so far.
# Search state: The search state is represented by the best solution found so
#                far, which is initialized to a random point within the search
#                bounds.
# Candidate generation: Candidates are generated by sampling a new point
#                       uniformly within the search bounds.
# Selection and replacement: The best candidate solution is compared to the
#                            current best solution, and if the new solution
#                            is better, it replaces the current best solution.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by
#                         uniformly sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                          by comparing new candidates to it.
# Boundary handling: The algorithm samples new candidates within the given
#                    search bounds, ensuring that the solution stays within
#                    the search space.
# Budget strategy: The algorithm uses the full evaluation budget provided,
#                  evaluating as many candidate solutions as possible within
#                  the budget.
# Closest known influences: This algorithm is a basic random search, which
#                           is a common baseline for black-box optimization
#                           problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             algorithm.
# Failure modes: The algorithm may struggle with problems that have a
#                highly multimodal or rugged objective function, as it
#                has no mechanisms to escape local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.random.uniform(low=-5, high=5, size=self.dim)
        self.best_y = np.inf

    def __call__(self, func):
        remaining_budget = self.budget
        while remaining_budget > 0:
            x = np.random.uniform(low=func.lower, high=func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
            remaining_budget -= 1
        return self.best_x, self.best_y
