import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, randomized search algorithm that is robust across dimensions. It maintains a population of candidate solutions and iteratively updates them using a combination of mutation and selection strategies.
# Search state: The search state is represented by a population of candidate solutions, where each solution is a vector of real-valued parameters.
# Candidate generation: New candidate solutions are generated by applying random Gaussian mutations to the current population. The mutation step size is adapted based on the objective function values of the current population.
# Selection and replacement: The best candidate solution from the current population is selected to be the next iterate. The remaining population members are replaced by the newly generated candidates.
# Adaptation: The mutation step size is adapted based on the objective function values of the current population, using a simple heuristic that aims to maintain a target acceptance rate.
# Exploration mechanisms: The algorithm relies on the randomness of the Gaussian mutations to explore the search space.
# Exploitation mechanisms: The selection of the best candidate solution from the current population allows the algorithm to exploit promising regions of the search space.
# Boundary handling: Candidate solutions that violate the box constraints are projected back onto the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget provided, without any early stopping or budget allocation strategies.
# Closest known influences: This algorithm is similar in spirit to Evolution Strategies, a family of randomized search algorithms that have been widely used for black-box optimization.
# Novelty or unusual aspects: The algorithm is designed to be compact, readable, and robust across dimensions, without relying on any advanced techniques or external libraries.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex, multimodal objective functions, where the simple mutation and selection strategies may not be sufficient to efficiently explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 20
        self.step_size = 1.0
        self.target_acceptance_rate = 0.2

    def __call__(self, func):
        # Initialize the population
        self.population = np.random.uniform(
            func.lower, func.upper, (self.population_size, self.dim)
        )
        self.population_values = np.array([func(x) for x in self.population])

        # Optimize
        best_idx = np.argmin(self.population_values)
        best_x, best_y = self.population[best_idx], self.population_values[best_idx]
        for _ in range(self.budget - self.population_size):
            # Generate new candidates
            new_candidates = self.population + self.step_size * np.random.normal(
                scale=1.0, size=(self.population_size, self.dim)
            )

            # Evaluate new candidates
            new_values = np.array([func(x) for x in new_candidates])

            # Select the best candidate
            best_idx = np.argmin(np.concatenate([self.population_values, new_values]))
            if best_idx < self.population_size:
                # Keep the best from the current population
                best_x, best_y = self.population[best_idx], self.population_values[best_idx]
            else:
                # Replace the population with the new candidates
                best_x, best_y = new_candidates[best_idx - self.population_size], new_values[
                    best_idx - self.population_size
                ]
                self.population = new_candidates
                self.population_values = new_values

            # Adapt the step size
            acceptance_rate = np.mean(new_values < self.population_values)
            self.step_size *= np.exp(
                (acceptance_rate - self.target_acceptance_rate) / self.target_acceptance_rate
            )

        return best_x, best_y
