import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search method that samples
#          points uniformly within the search space and keeps track of the
#          best solution found so far.
# Search state: The search state is represented by the current best solution
#               (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the search space.
# Selection and replacement: The best candidate found so far replaces the
#                            current best solution if it has a lower objective
#                            function value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         points uniformly.
# Exploitation mechanisms: The algorithm exploits the best solution found so far.
# Boundary handling: Boundary handling is performed by clamping the candidate
#                    solution to the search space bounds.
# Budget strategy: The algorithm uses the entire evaluation budget, sampling
#                  as many points as possible within the budget.
# Closest known influences: This algorithm is a basic random search method,
#                          similar to the "Uniform Random Search" technique.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it relies solely
#                on random sampling without any more sophisticated search
#                mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a candidate solution by sampling uniformly within the search space
            candidate_x = np.random.uniform(func.lower, func.upper, size=self.dim)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
