import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of the Nelder-Mead simplex algorithm,
#          a classic direct search method for derivative-free optimization.
# Search state: The search state is represented by a simplex, which is a set of
#               n+1 points in the n-dimensional search space.
# Candidate generation: New candidate points are generated by reflecting, expanding,
#                       contracting, or shrinking the current simplex.
# Selection and replacement: The point with the highest function value is replaced
#                            by the new candidate point.
# Adaptation: The size and shape of the simplex are adapted based on the function
#             values at the vertices.
# Exploration mechanisms: The simplex can expand or shrink to explore different
#                         regions of the search space.
# Exploitation mechanisms: The simplex can contract around the current best point
#                          to refine the search.
# Boundary handling: Points that violate the variable bounds are projected back
#                    onto the feasible region.
# Budget strategy: The algorithm runs for the full evaluation budget.
# Closest known influences: The Nelder-Mead algorithm was originally proposed by
#                           John Nelder and Roger Mead in 1965.
# Novelty or unusual aspects: This is a standard implementation of the Nelder-Mead
#                             algorithm, without any unusual aspects.
# Failure modes: The algorithm may struggle with high-dimensional problems or
#                problems with many local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.bounds.lb, func.bounds.ub, size=self.dim)
        simplex = [x0]
        for i in range(self.dim):
            x = x0.copy()
            x[i] += 0.05 * (func.bounds.ub[i] - func.bounds.lb[i])
            simplex.append(x)

        # Evaluate the initial simplex
        fvals = [func(x) for x in simplex]
        best_idx = np.argmin(fvals)
        best_x, best_y = simplex[best_idx], fvals[best_idx]
        evals_used = self.dim + 1

        # Iterate until the budget is exhausted
        while evals_used < self.budget:
            # Compute the centroid of the simplex
            centroid = np.mean(simplex[:-1], axis=0)

            # Reflect the worst point through the centroid
            worst_idx = np.argmax(fvals)
            reflected = centroid + (centroid - simplex[worst_idx])
            reflected = np.clip(reflected, func.bounds.lb, func.bounds.ub)
            reflected_val = func(reflected)
            evals_used += 1

            # Decide whether to accept the reflection or not
            if reflected_val < fvals[best_idx]:
                # Expand the simplex if the reflection is good
                expanded = centroid + 2 * (reflected - centroid)
                expanded = np.clip(expanded, func.bounds.lb, func.bounds.ub)
                expanded_val = func(expanded)
                evals_used += 1
                if expanded_val < reflected_val:
                    simplex[worst_idx] = expanded
                    fvals[worst_idx] = expanded_val
                else:
                    simplex[worst_idx] = reflected
                    fvals[worst_idx] = reflected_val
            elif reflected_val < fvals[worst_idx]:
                # Accept the reflection
                simplex[worst_idx] = reflected
                fvals[worst_idx] = reflected_val
            else:
                # Contract the simplex
                contracted = centroid + 0.5 * (simplex[worst_idx] - centroid)
                contracted = np.clip(contracted, func.bounds.lb, func.bounds.ub)
                contracted_val = func(contracted)
                evals_used += 1
                if contracted_val < fvals[worst_idx]:
                    simplex[worst_idx] = contracted
                    fvals[worst_idx] = contracted_val
                else:
                    # Shrink the simplex
                    for i in range(len(simplex)):
                        if i != best_idx:
                            simplex[i] = best_x + 0.5 * (simplex[i] - best_x)
                            fvals[i] = func(simplex[i])
                            evals_used += 1

            # Update the best point
            new_best_idx = np.argmin(fvals)
            if fvals[new_best_idx] < best_y:
                best_x, best_y = simplex[new_best_idx], fvals[new_best_idx]

        return best_x, best_y
