import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that samples points within the
#          search space and keeps track of the best solution found so far. It does not
#          use any sophisticated search strategies or adaptation mechanisms.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling uniformly within the
#                       search space defined by the function's bounds.
# Selection and replacement: The best candidate found so far is always kept as the
#                            current best solution.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling new
#                         points randomly.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          continuing to sample around it.
# Boundary handling: The algorithm ensures that sampled points are within the
#                    function's bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search approach,
#                           similar to a "blind" optimization method.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             algorithm.
# Failure modes: The algorithm may struggle with multimodal or highly
#                constrained functions, as it lacks any sophisticated
#                search strategies.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
