import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust implementation of a blackbox
#          minimization algorithm using the Nelder-Mead simplex method.
# Search state: The search state is represented by a simplex of points in the
#               search space, along with their corresponding function values.
# Candidate generation: New candidate points are generated by reflection,
#                       expansion, contraction, or shrinkage of the simplex.
# Selection and replacement: The worst point in the simplex is replaced with
#                            the new candidate, if it improves the objective.
# Adaptation: The simplex adapts its size and shape to the local landscape
#             through the Nelder-Mead update rules.
# Exploration mechanisms: The simplex explores the search space through
#                         reflection, expansion, and shrinkage operations.
# Exploitation mechanisms: The simplex exploits the local landscape through
#                          contraction operations.
# Boundary handling: If a candidate point falls outside the search bounds, it
#                    is projected back onto the nearest valid point.
# Budget strategy: The algorithm terminates when the evaluation budget is
#                  exhausted.
# Closest known influences: This implementation is based on the Nelder-Mead
#                          simplex method, a classic derivative-free
#                          optimization algorithm.
# Novelty or unusual aspects: The algorithm is designed to be compact and
#                             robust across dimensions, using only the Python
#                             standard library and NumPy.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with many local minima, as the Nelder-Mead method
#                can converge to non-global minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.n_evals = 0

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.lower, func.upper, self.dim)
        X = np.zeros((self.dim + 1, self.dim))
        X[0] = x0
        for i in range(1, self.dim + 1):
            X[i] = x0 + 0.05 * (func.upper - func.lower) * (np.eye(self.dim)[i-1])
        y = np.array([func(x) for x in X])
        self.n_evals += self.dim + 1

        # Run the Nelder-Mead algorithm
        while self.n_evals < self.budget:
            # Order the simplex
            order = np.argsort(y)
            X = X[order]
            y = y[order]

            # Compute the centroid of the best (n) points
            xbar = np.mean(X[:-1], axis=0)

            # Reflection
            xr = xbar + 1 * (xbar - X[-1])
            yr = func(xr)
            self.n_evals += 1
            if y[0] <= yr < y[-2]:
                X[-1] = xr
                y[-1] = yr
                continue

            # Expansion
            if yr < y[0]:
                xe = xbar + 2 * (xr - xbar)
                ye = func(xe)
                self.n_evals += 1
                if ye < yr:
                    X[-1] = xe
                    y[-1] = ye
                    continue
                else:
                    X[-1] = xr
                    y[-1] = yr
                    continue

            # Contraction
            xc = xbar + 0.5 * (X[-1] - xbar)
            yc = func(xc)
            self.n_evals += 1
            if yc < y[-1]:
                X[-1] = xc
                y[-1] = yc
                continue

            # Shrinkage
            X[1:] = X[0] + 0.5 * (X[1:] - X[0])
            y[1:] = [func(x) for x in X[1:]]
            self.n_evals += self.dim

        # Return the best point found
        best_idx = np.argmin(y)
        return X[best_idx], y[best_idx]
