import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a random search strategy to minimize the objective function within the given evaluation budget. It generates candidate solutions by sampling from a uniform distribution within the specified bounds, and selects the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y) and the evaluation budget.
# Candidate generation: Candidates are generated by sampling from a uniform distribution within the specified bounds.
# Selection and replacement: The algorithm selects the best candidate found so far and replaces the current best solution if the new candidate is better.
# Adaptation: The algorithm does not adapt during the optimization process.
# Exploration mechanisms: The algorithm explores the search space by randomly generating candidates within the bounds.
# Exploitation mechanisms: The algorithm exploits the best solution found so far by replacing it with a better candidate if one is found.
# Boundary handling: The algorithm generates candidates within the specified bounds and does not handle boundary cases explicitly.
# Budget strategy: The algorithm uses the provided evaluation budget and stops when the budget is exhausted.
# Closest known influences: This algorithm is a basic random search strategy, which is a common approach for black-box optimization problems.
# Novelty or unusual aspects: The algorithm is designed to be compact, readable, and robust across dimensions, using only the Python standard library and NumPy.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional or multimodal problems, as it relies solely on random sampling without any more advanced search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
