import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm to minimize the given
#          black-box function within the provided evaluation budget. It generates new
#          candidate solutions by sampling from a multivariate normal distribution centered
#          at the current best solution, and selects the best solution found so far.
# Search state: The algorithm maintains a single best solution (best_x, best_y) found so far.
# Candidate generation: New candidate solutions are generated by sampling from a multivariate
#                       normal distribution centered at the current best solution. The
#                       standard deviation of the distribution is adaptively scaled based
#                       on the problem dimensionality.
# Selection and replacement: The best candidate solution found so far is always kept as the
#                            current best solution.
# Adaptation: The standard deviation of the multivariate normal distribution used for
#             candidate generation is adapted based on the problem dimensionality.
# Exploration mechanisms: The random sampling of new candidate solutions provides a
#                         mechanism for exploring the search space.
# Exploitation mechanisms: The algorithm focuses the search around the current best solution,
#                          which provides a mechanism for exploitation.
# Boundary handling: If a candidate solution falls outside the bounds defined by the
#                    objective function, it is projected back onto the nearest valid point
#                    within the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided, without any
#                  specific budget management strategy.
# Closest known influences: This implementation is inspired by simple random search
#                          algorithms commonly used for black-box optimization problems.
# Novelty or unusual aspects: The adaptive scaling of the standard deviation based on the
#                             problem dimensionality is a relatively simple but effective
#                             technique to balance exploration and exploitation.
# Failure modes: The algorithm may struggle with highly multimodal or deceptive objective
#                functions, as it relies on a simple random search strategy without any
#                advanced mechanisms for escaping local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.std_dev = 1.0 / np.sqrt(self.dim)

    def __call__(self, func):
        # Initialize the best solution
        best_x = np.zeros(self.dim)
        best_y = func(best_x)

        # Perform the optimization
        for _ in range(self.budget):
            # Generate a new candidate solution
            candidate_x = best_x + self.std_dev * np.random.normal(size=self.dim)

            # Ensure the candidate solution is within the bounds
            if hasattr(func, 'bounds'):
                candidate_x = np.clip(candidate_x, func.bounds.lb, func.bounds.ub)
            else:
                candidate_x = np.clip(candidate_x, func.lower, func.upper)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < best_y:
                best_x = candidate_x
                best_y = candidate_y

        return best_x, best_y
