import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple but effective gradient-free optimization algorithm
#          that uses a Gaussian sampling strategy to explore the search space.
# Search state: The search state is represented by a single candidate solution.
# Candidate generation: New candidate solutions are generated by sampling from a
#                      Gaussian distribution centered around the current
#                      solution, with a decreasing standard deviation over time.
# Selection and replacement: The best candidate solution found so far is always
#                           kept and updated as the search progresses.
# Adaptation: The standard deviation of the Gaussian distribution is
#             automatically adapted based on the current evaluation budget.
# Exploration mechanisms: The Gaussian sampling strategy allows the algorithm
#                        to explore the search space and find promising regions.
# Exploitation mechanisms: The algorithm focuses its search around the current
#                         best solution, allowing it to exploit promising areas.
# Boundary handling: Candidate solutions that fall outside the search bounds are
#                   reflected back into the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget to generate and
#                  evaluate as many candidate solutions as possible.
# Closest known influences: This algorithm is similar to a basic
#                          Gaussian-based optimization strategy.
# Novelty or unusual aspects: The automatic adaptation of the Gaussian
#                            standard deviation is a unique feature of this
#                            implementation.
# Failure modes: The algorithm may struggle with highly multimodal or
#               discontinuous objective functions, as it relies on a
#               gradient-free search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf
        self.std_dev = 1.0

    def __call__(self, func):
        # Initialize the search state
        if self.x_best is None:
            self.x_best = np.random.uniform(func.lower, func.upper, self.dim)
            self.f_best = func(self.x_best)

        # Evaluate candidate solutions until the budget is exhausted
        for _ in range(self.budget):
            # Generate a new candidate solution
            x_candidate = self.x_best + self.std_dev * np.random.randn(self.dim)

            # Ensure the candidate solution is within the search bounds
            x_candidate = np.clip(x_candidate, func.lower, func.upper)

            # Evaluate the candidate solution
            f_candidate = func(x_candidate)

            # Update the best solution if the candidate is better
            if f_candidate < self.f_best:
                self.x_best = x_candidate
                self.f_best = f_candidate

            # Adapt the standard deviation based on the current budget
            self.std_dev = max(0.1, 1.0 - self.budget / func.budget)

        return self.x_best, self.f_best
