import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates new candidate
#          solutions by sampling from the given input bounds. It selects the
#          best-so-far solution and returns it as the final result.
# Search state: The algorithm maintains a single best solution found so far.
# Candidate generation: New candidate solutions are generated by randomly
#                       sampling from the input bounds.
# Selection and replacement: The best solution found so far is replaced if a
#                            better solution is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the best solution found so
#                          far by returning it as the final result.
# Boundary handling: The algorithm ensures that all candidate solutions are
#                    within the input bounds.
# Budget strategy: The algorithm uses the provided evaluation budget and never
#                  exceeds it.
# Closest known influences: This algorithm is a basic random search technique,
#                          similar to a uniform random sampling approach.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                highly multi-modal or high-dimensional problems, as it relies
#                solely on random sampling.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
