import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized gradient-free
#          optimization algorithm for the GNBG black-box minimization benchmark.
# Search state: The search state consists of a single candidate solution,
#               represented as a numpy array of real values.
# Candidate generation: New candidate solutions are generated by adding a
#                       Gaussian-distributed random perturbation to the
#                       current best solution.
# Selection and replacement: The candidate solution is compared to the
#                            current best solution, and the better one is kept.
# Adaptation: The standard deviation of the Gaussian perturbation is adapted
#             based on the quality of the candidate solution.
# Exploration mechanisms: The Gaussian perturbation provides a balance of
#                         exploration and exploitation.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates around it.
# Boundary handling: Candidate solutions that violate the search space bounds
#                    are reflected back into the feasible region.
# Budget strategy: The algorithm consumes the provided evaluation budget
#                  gradually, without exceeding it.
# Closest known influences: This algorithm is inspired by the Covariance
#                           Matrix Adaptation Evolution Strategy (CMA-ES).
# Novelty or unusual aspects: The compact implementation and the absence of
#                             explicit parameter tuning are unusual aspects.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                in the presence of multimodal or deceptive objective functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.sigma = 1.0

    def __call__(self, func):
        # Read bounds from the function object
        self.lb = func.lower if hasattr(func, 'lower') else func.bounds.lb
        self.ub = func.upper if hasattr(func, 'upper') else func.bounds.ub

        # Initialize the best solution
        self.best_x = self.x.copy()
        self.best_y = func(self.best_x)
        self.evaluations = 1

        while self.evaluations < self.budget:
            # Generate a new candidate solution
            candidate = self.best_x + self.sigma * np.random.normal(size=self.dim)

            # Reflect the candidate if it violates the bounds
            candidate = np.clip(candidate, self.lb, self.ub)

            # Evaluate the candidate
            candidate_y = func(candidate)
            self.evaluations += 1

            # Update the best solution
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            # Adapt the step size
            self.sigma *= np.exp((candidate_y - self.best_y) / self.best_y)

        return self.best_x, self.best_y
