import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple stochastic search algorithm to
#          minimize the given black-box function. It generates new candidate
#          solutions by sampling from a normal distribution centered on the
#          current best solution, and selects the best candidate to replace the
#          current best if it improves the objective.
# Search state: The algorithm maintains a single current best solution.
# Candidate generation: New candidates are generated by sampling from a normal
#                       distribution with a fixed standard deviation, centered
#                       on the current best solution.
# Selection and replacement: The best candidate is selected and replaces the
#                            current best solution if it improves the objective.
# Adaptation: The algorithm does not adapt its search parameters during the
#             optimization process.
# Exploration mechanisms: The normal distribution used to generate new
#                         candidates provides a balance of exploration and
#                         exploitation.
# Exploitation mechanisms: The algorithm focuses on improving the current best
#                          solution.
# Boundary handling: If a candidate solution falls outside the specified
#                    bounds, it is projected back onto the nearest valid point.
# Budget strategy: The algorithm uses the entire evaluation budget, without
#                  any specific budget management strategy.
# Closest known influences: This algorithm is similar to a simple Gaussian
#                           mutation-based evolutionary strategy.
# Novelty or unusual aspects: The algorithm is extremely simple and compact,
#                             relying only on the standard Python library and
#                             NumPy.
# Failure modes: The algorithm may struggle with highly multimodal or
#                discontinuous objective functions, as it does not have any
#                mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf

    def __call__(self, func):
        bounds = (func.lower, func.upper) if hasattr(func, 'lower') else func.bounds
        self.x_best = np.random.uniform(bounds[0], bounds[1], size=self.dim)
        self.f_best = func(self.x_best)

        for _ in range(self.budget - 1):
            x_candidate = self.x_best + np.random.normal(scale=1.0, size=self.dim)
            x_candidate = np.clip(x_candidate, bounds[0], bounds[1])
            f_candidate = func(x_candidate)

            if f_candidate < self.f_best:
                self.x_best = x_candidate
                self.f_best = f_candidate

        return self.x_best, self.f_best
