import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple randomized search algorithm to solve the GNBG black-box minimization benchmark.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling from the search space uniformly at random.
# Selection and replacement: The best candidate solution replaces the current best solution if it improves the objective function value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The algorithm explores the search space by generating new candidate solutions uniformly at random.
# Exploitation mechanisms: The algorithm exploits the current best solution by continuing to search in its vicinity.
# Boundary handling: The algorithm ensures that candidate solutions stay within the specified bounds by clipping the values to the bounds if necessary.
# Budget strategy: The algorithm uses the entire evaluation budget to search for the best solution.
# Closest known influences: This implementation is a basic random search algorithm, which is a common starting point for black-box optimization.
# Novelty or unusual aspects: There are no novel or unusual aspects to this implementation.
# Failure modes: The algorithm may struggle to solve problems with complex objective functions or high-dimensional search spaces, as it relies solely on random sampling without any advanced search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
