import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a random search strategy to explore the search space
#          and find the minimum of the objective function.
# Search state: The search state is represented by the current best solution (best_x)
#               and its corresponding objective value (best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                       from the search space defined by the function bounds.
# Selection and replacement: The best candidate solution is selected and replaces
#                            the current best solution if it has a lower objective
#                            value.
# Adaptation: The algorithm does not adapt during the search.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          replacing it with a better candidate if one is found.
# Boundary handling: The algorithm handles boundary constraints by sampling
#                    candidate solutions within the specified bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to perform
#                  the random search.
# Closest known influences: This algorithm is a basic random search, which is
#                          a common starting point for black-box optimization.
# Novelty or unusual aspects: The algorithm is simple and straightforward, with
#                             no unusual aspects.
# Failure modes: The algorithm may struggle to find the global minimum if the
#                objective function has many local minima or is highly multimodal.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Read function bounds
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper

        # Initialize best solution
        self.best_x = np.random.uniform(lb, ub, size=self.dim)
        self.best_y = func(self.best_x)

        # Perform random search
        for _ in range(self.budget - 1):
            x = np.random.uniform(lb, ub, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
