import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search approach to find the
#          minimum of a black-box function within a given budget.
# Search state: The search state is represented by the current best solution
#                (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling
#                       uniformly within the search space bounds.
# Selection and replacement: The best candidate solution found so far is
#                            always kept, replacing the previous best.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by
#                         sampling new points randomly.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                          by comparing new candidates to it.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                    within the search space bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a simple random search, which
#                           is a fundamental optimization technique.
# Novelty or unusual aspects: This algorithm does not have any unusual
#                             aspects.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with narrow optima, as the random search may not
#                be able to find the global optimum within the given budget.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
