import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, randomized, derivative-free optimization algorithm
#          based on a combination of grid search and random sampling.
# Search state: The algorithm maintains a single current best candidate solution.
# Candidate generation: New candidate solutions are generated by randomly sampling
#                      within the search bounds.
# Selection and replacement: The current best candidate is replaced if a new
#                           solution with a lower objective value is found.
# Adaptation: The algorithm does not adapt during the optimization process.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                        sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                         focusing the random sampling around it.
# Boundary handling: The algorithm respects the search bounds by clipping
#                    candidate solutions that fall outside the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is similar to a basic random search
#                          algorithm, with some elements of grid search.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust,
#                            and easy to understand, with a focus on simplicity
#                            and reliability rather than advanced techniques.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex, multimodal objective functions, as it
#                relies on simple random sampling without any more sophisticated
#                exploration mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Initialize the search state
        if self.best_x is None:
            self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
            self.best_y = func(self.best_x)

        # Iterate until the budget is exhausted
        for _ in range(self.budget):
            # Generate a new candidate solution by random sampling
            candidate_x = np.random.uniform(func.lower, func.upper, self.dim)
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
