import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of an evolutionary algorithm for
#          black-box optimization. It uses a population of candidate solutions,
#          and iteratively applies mutation, selection, and replacement to
#          explore the search space and find the global optimum.
# Search state: The algorithm maintains a population of candidate solutions,
#               represented as numpy arrays.
# Candidate generation: New candidates are generated by applying Gaussian
#                       mutation to the current population.
# Selection and replacement: The best candidates (in terms of objective function
#                            value) are selected to survive to the next
#                            generation. The remaining slots in the population
#                            are filled with new mutated candidates.
# Adaptation: The mutation step size is adapted based on the progress of the
#             search, using a simple self-adaptive mechanism.
# Exploration mechanisms: Mutation with a fixed initial step size provides
#                         exploration, while the self-adaptive step size
#                         adjusts the exploration-exploitation balance over
#                         the course of the search.
# Exploitation mechanisms: The selection of the best candidates from the
#                          population provides an exploitation mechanism.
# Boundary handling: Candidate solutions that fall outside the feasible
#                    region are projected back onto the boundary.
# Budget strategy: The algorithm uses the full evaluation budget, without
#                  exceeding it.
# Closest known influences: This implementation is inspired by classic
#                           evolutionary algorithms, such as Evolutionary
#                           Strategies and Differential Evolution.
# Novelty or unusual aspects: The use of a self-adaptive mutation step size
#                             is a relatively simple but effective mechanism
#                             for adjusting the exploration-exploitation
#                             balance.
# Failure modes: The algorithm may struggle with highly multimodal or
#                deceptive objective functions, where the initial population
#                and mutation process are unable to effectively explore the
#                search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 20
        self.initial_step_size = 0.5
        self.step_size_decay = 0.999
        self.population = np.random.uniform(-1, 1, (self.population_size, self.dim))

    def __call__(self, func):
        self.evaluations = 0
        self.best_x = None
        self.best_y = float('inf')

        while self.evaluations < self.budget:
            # Generate new candidates by mutating the population
            candidates = self.population + self.initial_step_size * np.random.normal(0, 1, (self.population_size, self.dim))

            # Evaluate the candidates and update the best solution
            for candidate in candidates:
                # Ensure the candidate is within the feasible bounds
                candidate = np.clip(candidate, func.lower, func.upper)
                y = func(candidate)
                self.evaluations += 1
                if y < self.best_y:
                    self.best_x, self.best_y = candidate, y

            # Select the best candidates to survive to the next generation
            self.population = candidates[np.argsort(np.array([func(c) for c in candidates]))[:self.population_size]]

            # Adapt the mutation step size
            self.initial_step_size *= self.step_size_decay

        return self.best_x, self.best_y
