import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm to minimize the objective function. It generates candidate solutions by randomly sampling within the search domain, evaluates the objective function, and keeps track of the best solution found so far.
# Search state: The search state is represented by the best solution found so far, which is updated whenever a better solution is discovered.
# Candidate generation: Candidates are generated by randomly sampling the search domain, with each dimension independently sampled from a uniform distribution between the lower and upper bounds.
# Selection and replacement: The best candidate solution is selected by evaluating the objective function and comparing the result to the current best solution. If the new solution is better, it replaces the current best solution.
# Adaptation: The algorithm does not have any adaptation mechanisms. The search process is purely random without any learning or adjustment of the search strategy.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling new candidate solutions. This provides a uniform exploration of the search domain.
# Exploitation mechanisms: The algorithm does not have any explicit exploitation mechanisms. The best solution found so far is used as the starting point for the next iteration, but there is no active exploitation beyond this.
# Boundary handling: Candidate solutions that fall outside the search domain are automatically clipped to the nearest valid value within the bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to explore the search space. It does not have a specific budget strategy, other than stopping when the budget is exhausted.
# Closest known influences: This implementation is based on a simple random search algorithm, which is a common baseline for black-box optimization problems.
# Novelty or unusual aspects: The algorithm is straightforward and does not employ any advanced techniques. Its simplicity and reliance on random sampling are its main characteristics.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex, multimodal objective functions, as it does not have any mechanisms to escape local minima or efficiently explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the objective function
            y = func(x)

            # Update the best solution if the new candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
