import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust, and randomized black-box optimization algorithm that uses a random search strategy with mutation and elitism.
# Search state: The search state is represented by a population of candidate solutions (x) and their corresponding objective values (y).
# Candidate generation: New candidate solutions are generated by mutating the current best solution, with the mutation step size adaptively scaled based on the search progress.
# Selection and replacement: The population is replaced at each iteration by the best candidates, with elitism ensuring that the current best solution is always retained.
# Adaptation: The mutation step size is adapted based on the search progress, decreasing as the algorithm converges.
# Exploration mechanisms: Mutation of the current best solution provides the primary exploration mechanism, with the mutation step size controlling the balance between exploration and exploitation.
# Exploitation mechanisms: Elitism and the focus on the current best solution drive exploitation.
# Boundary handling: Candidate solutions that violate the problem bounds are reflected back within the bounds.
# Budget strategy: The algorithm aims to make the most of the provided evaluation budget by focusing on the current best solution and adaptively scaling the mutation step size.
# Closest known influences: This algorithm is inspired by simple randomized search strategies, such as Gaussian mutation and (1+1)-ES.
# Novelty or unusual aspects: The adaptive scaling of the mutation step size and the use of elitism are notable features of this algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex, multi-modal objective functions, as the random search strategy may not be able to efficiently explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.y_best = np.inf
        self.step_size = 1.0

    def __call__(self, func):
        self.x_best = np.random.uniform(func.lower, func.upper, self.dim)
        self.y_best = func(self.x_best)
        self.budget -= 1

        for _ in range(self.budget):
            x_candidate = self.x_best + self.step_size * np.random.normal(0, 1, self.dim)
            x_candidate = np.clip(x_candidate, func.lower, func.upper)
            y_candidate = func(x_candidate)
            self.budget -= 1

            if y_candidate < self.y_best:
                self.x_best = x_candidate
                self.y_best = y_candidate

            self.step_size *= 0.99

        return self.x_best, self.y_best
