import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of the Nelder-Mead (Simplex) algorithm for
#          black-box minimization. It maintains a simplex of candidate solutions and
#          iteratively updates the simplex to move towards the minimum.
# Search state: The search state is represented by the vertices of the simplex, which
#               are stored as rows in a 2D numpy array.
# Candidate generation: New candidate points are generated by reflecting, expanding,
#                       or contracting the simplex.
# Selection and replacement: The worst point in the simplex is replaced with a new
#                            candidate point.
# Adaptation: The simplex size and shape are adapted based on the function values
#             at the vertices.
# Exploration mechanisms: The simplex expands and contracts to explore the search space.
# Exploitation mechanisms: The simplex moves towards the minimum by reflecting and
#                          contracting around the best point.
# Boundary handling: If a candidate point falls outside the bounds, it is projected
#                    back onto the nearest valid point.
# Budget strategy: The algorithm runs until the evaluation budget is exhausted.
# Closest known influences: The Nelder-Mead algorithm is a well-known direct search
#                          method for derivative-free optimization.
# Novelty or unusual aspects: This is a standard implementation of the Nelder-Mead
#                            algorithm, without any unusual or novel aspects.
# Failure modes: The algorithm may converge to a local minimum, depending on the
#                starting simplex and the objective function landscape.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.lower, func.upper, size=(self.dim + 1, self.dim))
        y = np.array([func(x) for x in x0])
        self.evaluations += self.dim + 1

        # Nelder-Mead algorithm
        while self.evaluations < self.budget:
            # Sort the simplex
            idx = np.argsort(y)
            x0, y = x0[idx], y[idx]

            # Reflect the worst point
            xr = x0[0] + 1.0 * (x0[0] - x0[-1])
            yr = func(xr)
            self.evaluations += 1

            if yr < y[0]:
                # Expand the simplex
                xe = x0[0] + 2.0 * (xr - x0[0])
                ye = func(xe)
                self.evaluations += 1
                if ye < yr:
                    x0[-1] = xe
                    y[-1] = ye
                else:
                    x0[-1] = xr
                    y[-1] = yr
            elif yr < y[-2]:
                # Accept the reflected point
                x0[-1] = xr
                y[-1] = yr
            else:
                # Contract the simplex
                xc = x0[-1] + 0.5 * (x0[0] - x0[-1])
                yc = func(xc)
                self.evaluations += 1
                if yc < y[-1]:
                    x0[-1] = xc
                    y[-1] = yc
                else:
                    # Shrink the simplex
                    x0[1:] = x0[0] + 0.5 * (x0[1:] - x0[0])
                    y[1:] = [func(x) for x in x0[1:]]
                    self.evaluations += self.dim

        # Return the best solution
        best_idx = np.argmin(y)
        return x0[best_idx], y[best_idx]
