import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search that generates new candidate
#          solutions by sampling from a uniform distribution within the provided
#          bounds, and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x)
#               and its corresponding objective value (best_y).
# Candidate generation: New candidate solutions are generated by sampling from a
#                       uniform distribution within the provided bounds.
# Selection and replacement: The current best solution is replaced if a new
#                            candidate solution has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          remembering and returning it.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                    within the provided bounds by sampling from a uniform
#                    distribution within those bounds.
# Budget strategy: The algorithm uses the provided evaluation budget, and stops
#                  when the budget is exhausted.
# Closest known influences: This algorithm is a basic random search technique,
#                          which is a common baseline for black-box
#                          optimization problems.
# Novelty or unusual aspects: This algorithm does not have any novel or unusual
#                             aspects. It is a simple and straightforward
#                             random search algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                complex, highly multimodal, or high-dimensional problems,
#                as it relies solely on random sampling without any advanced
#                exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')
        self.evaluations = 0

    def __call__(self, func):
        while self.evaluations < self.budget:
            # Generate a new candidate solution
            x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)

            # Evaluate the candidate solution
            y = func(x)
            self.evaluations += 1

            # Update the best solution if the new candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
