import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a randomized search approach with a simple coordinate-wise adaptation mechanism.
# Search state: The algorithm maintains a current best solution and a set of candidate solutions generated around it.
# Candidate generation: Candidate solutions are generated by perturbing the current best solution along each dimension, using a Gaussian distribution with a fixed standard deviation.
# Selection and replacement: The best candidate solution is selected and replaces the current best solution if it is better.
# Adaptation: The standard deviation of the Gaussian distribution is adapted based on the improvement in the objective function value.
# Exploration mechanisms: The randomized candidate generation provides exploration, while the adaptation mechanism adjusts the step size.
# Exploitation mechanisms: The algorithm focuses on the current best solution and its immediate neighborhood.
# Boundary handling: If a candidate solution goes out of bounds, it is projected back onto the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget and stops when the budget is exhausted.
# Closest known influences: This algorithm is inspired by simple randomized search and coordinate descent methods.
# Novelty or unusual aspects: The adaptation mechanism is relatively simple and straightforward.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive functions, as it does not have explicit mechanisms to escape local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.y_best = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        if self.x_best is None:
            # Initialize the best solution randomly within the bounds
            self.x_best = np.random.uniform(func.bounds.lb, func.bounds.ub, size=self.dim)
            self.y_best = func(self.x_best)

        for _ in range(self.budget):
            # Generate candidate solutions by perturbing the current best solution
            candidates = self.x_best + self.sigma * np.random.normal(0, 1, size=(self.dim, self.dim))

            # Evaluate the candidates and update the best solution
            for i in range(self.dim):
                x_candidate = candidates[i]
                if np.all(x_candidate >= func.bounds.lb) and np.all(x_candidate <= func.bounds.ub):
                    y_candidate = func(x_candidate)
                    if y_candidate < self.y_best:
                        self.x_best = x_candidate
                        self.y_best = y_candidate

            # Adapt the standard deviation based on the improvement
            if self.y_best < func(self.x_best):
                self.sigma *= 0.9
            else:
                self.sigma *= 1.1

        return self.x_best, self.y_best
