import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple randomized search that samples points
#          within the provided bounds and keeps track of the best solution
#          found so far.
# Search state: The algorithm maintains a single best solution, represented
#               by the best_x and best_y variables.
# Candidate generation: Candidates are generated by sampling uniformly random
#                       points within the provided bounds.
# Selection and replacement: The best candidate found so far is always kept.
#                            Worse candidates are discarded.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The random sampling of points within the bounds
#                         provides the exploration mechanism.
# Exploitation mechanisms: The algorithm exploits by keeping track of the
#                          best solution found so far.
# Boundary handling: Candidates are sampled uniformly within the provided
#                    bounds, so no special boundary handling is required.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search, which
#                           is a common baseline for black-box optimization.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             simple random search algorithm.
# Failure modes: The algorithm may struggle on highly multimodal or
#                high-dimensional problems, as it has no mechanisms for
#                exploiting structure in the objective function.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
