import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized direct search algorithm for black-box
#          function optimization. It generates new candidate solutions by
#          sampling from a multivariate normal distribution, and selects the
#          best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x,
#                best_y) and a covariance matrix that governs the search.
# Candidate generation: New candidates are generated by sampling from a
#                       multivariate normal distribution centered on the best
#                       solution, with a covariance matrix that is adapted
#                       during the search.
# Selection and replacement: The best candidate solution found so far is
#                            always retained.
# Adaptation: The covariance matrix is adapted by scaling it by a factor that
#             depends on the number of function evaluations remaining.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         from a broad covariance matrix early in the search,
#                         and gradually focuses the search by adapting the
#                         covariance matrix.
# Exploitation mechanisms: The algorithm exploits the best solution found so
#                          far by centering the search distribution around it.
# Boundary handling: The algorithm reflects candidates that fall outside the
#                    feasible region back inside the bounds.
# Budget strategy: The algorithm uses the full evaluation budget, adjusting
#                  the search behavior as the budget is depleted.
# Closest known influences: This algorithm is inspired by the Covariance Matrix
#                           Adaptation Evolution Strategy (CMA-ES), a well-known
#                           black-box optimization algorithm.
# Novelty or unusual aspects: The algorithm does not use any problem-specific
#                            information or assumptions, making it a
#                            general-purpose black-box optimizer.
# Failure modes: The algorithm may struggle with highly multimodal or
#                discontinuous objective functions, as it relies on a
#                Gaussian search distribution.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = np.inf
        self.cov = np.eye(dim)

    def __call__(self, func):
        for _ in range(self.budget):
            x = self.generate_candidate(func)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
            self.adapt_covariance()
        return self.best_x, self.best_y

    def generate_candidate(self, func):
        """Generate a new candidate solution by sampling from a multivariate
        normal distribution centered on the current best solution."""
        candidate = self.best_x + np.random.multivariate_normal(np.zeros(self.dim), self.cov)
        # Reflect the candidate back into the feasible region if it falls outside the bounds
        candidate = np.clip(candidate, func.lower, func.upper)
        return candidate

    def adapt_covariance(self):
        """Adapt the covariance matrix of the search distribution based on the
        remaining evaluation budget."""
        scale = (self.budget / self.budget) ** 0.25
        self.cov *= scale
