import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple gradient-free optimization algorithm based on the
#          Nelder-Mead simplex method. It starts with a simplex in the
#          search space and iteratively updates the simplex to move
#          towards the optimum.
# Search state: The search state is represented by the vertices of the simplex,
#               which are stored as a 2D numpy array.
# Candidate generation: New candidates are generated by performing reflection,
#                       expansion, contraction, or shrinkage operations on the
#                       simplex.
# Selection and replacement: The worst vertex of the simplex is replaced by
#                            the new candidate.
# Adaptation: The size and shape of the simplex are adapted based on the
#             objective function values at the vertices.
# Exploration mechanisms: The simplex method explores the search space by
#                         generating new candidates in different directions.
# Exploitation mechanisms: The simplex method exploits the search space by
#                          moving the simplex towards the optimum.
# Boundary handling: Candidates that go outside the search space are
#                    projected back onto the boundary.
# Budget strategy: The algorithm stops when the evaluation budget is
#                  exhausted.
# Closest known influences: The Nelder-Mead simplex method.
# Novelty or unusual aspects: None.
# Failure modes: The algorithm may get stuck in a local optimum, especially
#                for multimodal functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0
        self.simplex = None
        self.simplex_values = None

    def __call__(self, func):
        if self.simplex is None:
            self.initialize_simplex(func)
        
        while self.evaluations < self.budget:
            self.step(func)
        
        best_idx = np.argmin(self.simplex_values)
        best_x = self.simplex[best_idx]
        best_y = self.simplex_values[best_idx]
        return best_x, best_y

    def initialize_simplex(self, func):
        """Initialize the simplex in the search space."""
        self.simplex = np.zeros((self.dim + 1, self.dim))
        self.simplex_values = np.zeros(self.dim + 1)
        
        # Create an initial simplex
        for i in range(self.dim + 1):
            x = np.zeros(self.dim)
            for j in range(self.dim):
                if j == i:
                    x[j] = 1.0
            self.simplex[i] = x
            self.simplex_values[i] = func(x)
            self.evaluations += 1
        
        # Sort the simplex vertices by function value
        order = np.argsort(self.simplex_values)
        self.simplex = self.simplex[order]
        self.simplex_values = self.simplex_values[order]

    def step(self, func):
        """Perform one iteration of the Nelder-Mead algorithm."""
        # Compute the centroid of the simplex, excluding the worst vertex
        centroid = np.mean(self.simplex[:-1], axis=0)
        
        # Reflect the worst vertex through the centroid
        reflected = centroid + (centroid - self.simplex[-1])
        reflected_value = func(reflected)
        self.evaluations += 1
        
        if reflected_value < self.simplex_values[0]:
            # Expansion step
            expanded = centroid + 2 * (reflected - centroid)
            expanded_value = func(expanded)
            self.evaluations += 1
            if expanded_value < reflected_value:
                self.simplex[-1] = expanded
                self.simplex_values[-1] = expanded_value
            else:
                self.simplex[-1] = reflected
                self.simplex_values[-1] = reflected_value
        elif reflected_value < self.simplex_values[-2]:
            # Acceptance of reflected
            self.simplex[-1] = reflected
            self.simplex_values[-1] = reflected_value
        else:
            # Contraction or shrinkage
            if reflected_value < self.simplex_values[-1]:
                # Outer contraction
                contracted = centroid + 0.5 * (reflected - centroid)
            else:
                # Inner contraction
                contracted = centroid - 0.5 * (self.simplex[-1] - centroid)
            contracted_value = func(contracted)
            self.evaluations += 1
            if contracted_value < self.simplex_values[-1]:
                self.simplex[-1] = contracted
                self.simplex_values[-1] = contracted_value
            else:
                # Shrinkage
                for i in range(1, self.dim + 1):
                    self.simplex[i] = self.simplex[0] + 0.5 * (self.simplex[i] - self.simplex[0])
                    self.simplex_values[i] = func(self.simplex[i])
                    self.evaluations += 1
        
        # Sort the simplex vertices by function value
        order = np.argsort(self.simplex_values)
        self.simplex = self.simplex[order]
        self.simplex_values = self.simplex_values[order]
