import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search that samples points within the
#          given bounds and keeps track of the best point found so far.
# Search state: The search state is simply the current best point and its objective value.
# Candidate generation: Candidates are generated by sampling uniformly within the
#                       given bounds.
# Selection and replacement: The best candidate found so far replaces the current
#                            best point if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new points.
# Exploitation mechanisms: The algorithm exploits the best point found so far by
#                          continuing to sample around it.
# Boundary handling: Candidates that fall outside the given bounds are rejected.
# Budget strategy: The algorithm uses the full evaluation budget, sampling new
#                  points until the budget is exhausted.
# Closest known influences: This algorithm is a basic random search method, similar
#                          to pure random search or random restarts of a local
#                          optimization method.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may struggle to find the global optimum if the
#                objective function is multimodal or the search space is high-dimensional.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
