import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a randomized search strategy to
# minimize the objective function within the given budget. It generates
# candidate solutions by sampling from a multivariate normal distribution
# centered at the current best solution, and selects the best candidate
# to replace the current best if it improves the objective value.
# Search state: The algorithm maintains the current best solution (best_x)
# and its objective value (best_y).
# Candidate generation: Candidates are generated by sampling from a
# multivariate normal distribution centered at the current best solution,
# with a covariance matrix that scales with the dimensionality of the
# problem.
# Selection and replacement: The generated candidates are evaluated, and
# the best candidate replaces the current best solution if it improves
# the objective value.
# Adaptation: The covariance matrix used to generate candidates is
# adapted based on the quality of the current best solution, with
# a larger covariance matrix used when the best solution is far from
# the optimum.
# Exploration mechanisms: The randomized candidate generation
# provides exploration of the search space.
# Exploitation mechanisms: The selection of the best candidate
# provides exploitation of promising regions of the search space.
# Boundary handling: Candidate solutions that fall outside the
# feasible region are reflected back within the bounds.
# Budget strategy: The algorithm uses the entire evaluation budget
# provided, without any explicit budget management.
# Closest known influences: This algorithm is inspired by the
# Covariance Matrix Adaptation Evolution Strategy (CMA-ES).
# Novelty or unusual aspects: The algorithm does not use any
# problem-specific knowledge or tuning, and is designed to be
# as robust and general-purpose as possible.
# Failure modes: The algorithm may struggle in high-dimensional
# problems with complex or multimodal objective functions, as the
# randomized search strategy may not be able to effectively
# explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Initialize the search state
        if self.best_x is None:
            self.best_x = np.random.uniform(func.bounds.lb, func.bounds.ub, size=self.dim)
            self.best_y = func(self.best_x)

        # Adapt the covariance matrix based on the current best solution
        sigma = 1.0 + np.linalg.norm(self.best_x - func.bounds.lb) / np.linalg.norm(func.bounds.ub - func.bounds.lb)
        cov = sigma**2 * np.eye(self.dim)

        # Evaluate the budget
        for _ in range(self.budget):
            # Generate a new candidate solution
            candidate = np.random.multivariate_normal(self.best_x, cov)

            # Ensure the candidate is within the bounds
            candidate = np.maximum(func.bounds.lb, np.minimum(func.bounds.ub, candidate))

            # Evaluate the candidate
            candidate_y = func(candidate)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

        return self.best_x, self.best_y
