import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a black-box optimization algorithm
#          that uses a random search strategy with a uniform sampling distribution.
# Search state: The search state consists of the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                       from the search space bounded by the provided lower and upper
#                       bounds.
# Selection and replacement: The current best solution is replaced if a new candidate
#                            solution has a lower objective function value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The random sampling of candidate solutions provides a purely
#                         explorative search strategy.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidate solutions that fall outside the search space are
#                    projected back onto the boundary.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This implementation is a basic random search algorithm.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            implementation.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it has no mechanisms
#                for exploiting information about the objective function.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        while self.evaluations < self.budget:
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the objective function and update the best solution
            y = func(x)
            self.evaluations += 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
