import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search strategy to minimize
#          the given black-box function. It generates random candidate solutions
#          within the provided bounds, evaluates them, and keeps track of the
#          best solution found so far.
# Search state: The search state consists of the current best solution (best_x)
#               and its corresponding objective value (best_y).
# Candidate generation: Candidates are generated by sampling random points
#                       uniformly within the search space defined by the
#                       function's bounds.
# Selection and replacement: The best candidate solution found so far is
#                            selected and replaces the previous best solution
#                            if the new one has a lower objective value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The random sampling of candidates promotes exploration
#                         of the search space.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidate solutions that fall outside the search space
#                    bounds are rejected and a new candidate is generated.
# Budget strategy: The implementation strictly adheres to the provided
#                  evaluation budget and never exceeds it.
# Closest known influences: This implementation is a basic random search
#                          algorithm, which is a common baseline for
#                          black-box optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            implementation.
# Failure modes: This implementation may struggle to find the global optimum
#                in high-dimensional or multimodal problems, as it relies solely
#                on random sampling without any additional mechanisms to
#                enhance the search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Initialize the best solution
        self.best_x = np.zeros(self.dim)
        self.best_y = func(self.best_x)

        # Iterate until the evaluation budget is exhausted
        while self.budget > 0:
            # Generate a new candidate solution
            candidate = self._generate_candidate(func)

            # Evaluate the candidate
            candidate_y = func(candidate)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            self.budget -= 1

        return self.best_x, self.best_y

    def _generate_candidate(self, func):
        """Generate a new candidate solution within the function's bounds."""
        if hasattr(func, 'bounds'):
            # Use func.bounds.lb and func.bounds.ub if available
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            # Use func.lower and func.upper if available
            lb = func.lower
            ub = func.upper

        # Generate a new candidate solution within the bounds
        candidate = np.random.uniform(lb, ub, size=self.dim)
        return candidate
