import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of the Nelder-Mead simplex algorithm for
#          black-box optimization. It maintains a simplex of points and iteratively
#          updates it to move towards the optimum. The algorithm is well-suited for
#          low-dimensional problems and does not require gradient information.
# Search state: The search state is represented by the current simplex, which is a
#               set of points in the search space.
# Candidate generation: New candidate points are generated by performing reflections,
#                       expansions, and contractions of the simplex.
# Selection and replacement: The worst point in the simplex is replaced by a new
#                            candidate point based on the simplex update rules.
# Adaptation: The size and shape of the simplex are adapted based on the objective
#              function values at the simplex vertices.
# Exploration mechanisms: The simplex updates provide a balance of exploration and
#                         exploitation, with the ability to escape local minima.
# Exploitation mechanisms: The simplex updates focus the search around the current
#                          best point.
# Boundary handling: If a candidate point falls outside the bounds, it is projected
#                    back onto the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget, without early
#                  termination.
# Closest known influences: The Nelder-Mead simplex algorithm.
# Novelty or unusual aspects: The algorithm is a standard optimization method and
#                            does not have any unusual aspects.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems
#                with many local minima, as it does not have a systematic way to
#                escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x = np.zeros((self.dim + 1, self.dim))
        f = np.zeros(self.dim + 1)
        for i in range(self.dim + 1):
            x[i] = np.random.uniform(func.bounds.lb, func.bounds.ub)
            f[i] = func(x[i])
            self.evaluations += 1

        while self.evaluations < self.budget:
            # Order the simplex vertices by function value
            order = np.argsort(f)
            x = x[order]
            f = f[order]

            # Compute the centroid of the simplex (excluding the worst point)
            x_c = np.mean(x[:-1], axis=0)

            # Reflection
            x_r = x_c + 1.0 * (x_c - x[-1])
            if np.all(func.bounds.lb <= x_r) and np.all(x_r <= func.bounds.ub):
                f_r = func(x_r)
                self.evaluations += 1
                if f_r < f[0]:
                    # Expansion
                    x_e = x_c + 2.0 * (x_r - x_c)
                    if np.all(func.bounds.lb <= x_e) and np.all(x_e <= func.bounds.ub):
                        f_e = func(x_e)
                        self.evaluations += 1
                        if f_e < f_r:
                            x[-1] = x_e
                            f[-1] = f_e
                        else:
                            x[-1] = x_r
                            f[-1] = f_r
                    else:
                        x[-1] = x_r
                        f[-1] = f_r
                elif f[0] <= f_r < f[-2]:
                    x[-1] = x_r
                    f[-1] = f_r
                else:
                    # Contraction
                    x_c = x_c + 0.5 * (x[-1] - x_c)
                    if np.all(func.bounds.lb <= x_c) and np.all(x_c <= func.bounds.ub):
                        f_c = func(x_c)
                        self.evaluations += 1
                        if f_c <= f[-1]:
                            x[-1] = x_c
                            f[-1] = f_c
                        else:
                            # Shrink
                            for i in range(1, self.dim + 1):
                                x[i] = x[0] + 0.5 * (x[i] - x[0])
                                f[i] = func(x[i])
                                self.evaluations += 1
            else:
                # Boundary violation, project back onto the feasible region
                x[-1] = np.clip(x_r, func.bounds.lb, func.bounds.ub)
                f[-1] = func(x[-1])
                self.evaluations += 1

            # Update the best solution
            if f[0] < self.f_best:
                self.x_best = x[0]
                self.f_best = f[0]

        return self.x_best, self.f_best
