import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm for the GNBG black-box
#          minimization benchmark. It generates candidate solutions by sampling
#          uniformly from the bounded search space, and returns the best
#          solution found within the provided evaluation budget.
# Search state: The algorithm maintains the current best solution and its
#                corresponding objective function value.
# Candidate generation: Candidates are generated by sampling uniformly from the
#                       bounded search space.
# Selection and replacement: The best candidate solution found so far is
#                            selected and replaces the current best solution
#                            if it is an improvement.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling candidate solutions.
# Exploitation mechanisms: The algorithm exploits the search space by selecting
#                          and retaining the best solution found so far.
# Boundary handling: Candidate solutions that fall outside the bounded search
#                    space are rejected.
# Budget strategy: The algorithm uses the entire evaluation budget to explore
#                  the search space and find the best solution.
# Closest known influences: This algorithm is a basic random search technique
#                           that has been used in many optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it relies solely
#                on random sampling without any more advanced search strategies.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
