import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm that samples candidate
#          solutions uniformly within the given search bounds and returns the best one found
#          within the evaluation budget.
# Search state: The algorithm maintains a single current best solution and its objective value.
# Candidate generation: Candidates are generated by sampling uniform random points within the
#                       search bounds.
# Selection and replacement: At each iteration, the current best solution is replaced if a
#                            better candidate is found.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The random sampling provides a purely exploratory search.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidates are sampled uniformly within the search bounds, and any
#                    out-of-bounds solutions are discarded.
# Budget strategy: The algorithm simply evaluates candidate solutions until the budget is
#                  exhausted.
# Closest known influences: This is a basic random search algorithm, which is a common
#                          baseline for black-box optimization problems.
# Novelty or unusual aspects: This implementation is intentionally kept simple and
#                             straightforward, without any advanced techniques.
# Failure modes: This algorithm may struggle to find the global optimum, especially for
#                multimodal or highly constrained problems, due to its lack of exploitation
#                and adaptation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        self.budget_left = self.budget
        self.best_x = None
        self.best_y = np.inf

        while self.budget_left > 0:
            candidate = self._sample_candidate(func)
            candidate_y = func(candidate)
            self.budget_left -= 1

            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

        return self.best_x, self.best_y

    def _sample_candidate(self, func):
        lb, ub = self._get_bounds(func)
        return np.random.uniform(lb, ub, size=self.dim)

    def _get_bounds(self, func):
        try:
            lb = func.lower
            ub = func.upper
        except AttributeError:
            lb = func.bounds.lb
            ub = func.bounds.ub
        return lb, ub
