import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a Gaussian Mixture-based black-box
#          optimization algorithm that uses a fixed number of candidate solutions
#          and a simplified candidate generation and selection process.
# Search state: The search state is represented by a set of weighted Gaussian
#               distributions, where each distribution represents a candidate
#               solution. The weights determine the relative importance of each
#               candidate.
# Candidate generation: New candidate solutions are generated by sampling from the
#                       Gaussian distributions. The means and variances of the
#                       distributions are updated based on the performance of the
#                       previous candidates.
# Selection and replacement: The best candidate solution is selected and returned.
#                            The search state is updated by adjusting the weights
#                            of the Gaussian distributions based on the performance
#                            of the candidates.
# Adaptation: The algorithm adapts by updating the means and variances of the
#             Gaussian distributions based on the performance of the candidates.
# Exploration mechanisms: The algorithm explores the search space by sampling from
#                         the Gaussian distributions, which encourages the
#                         exploration of different regions of the search space.
# Exploitation mechanisms: The algorithm exploits the search space by focusing
#                          on the most promising regions, as indicated by the
#                          weights of the Gaussian distributions.
# Boundary handling: The algorithm handles boundary constraints by reflecting
#                    the candidate solutions that fall outside the bounds back
#                    into the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget for each
#                  function call, without any additional budget management.
# Closest known influences: This algorithm is inspired by Gaussian Mixture Models
#                          and Estimation of Distribution Algorithms, which are
#                          common approaches for black-box optimization.
# Novelty or unusual aspects: The algorithm uses a simplified candidate generation
#                            and selection process, which may make it less
#                            powerful than more sophisticated algorithms, but
#                            also more compact and easier to understand.
# Failure modes: The algorithm may struggle with highly multimodal or
#                discontinuous objective functions, as the Gaussian distributions
#                may not be able to adequately model the search space in these
#                cases.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.num_candidates = 20
        self.means = np.zeros((self.num_candidates, self.dim))
        self.stdevs = np.ones((self.num_candidates, self.dim))
        self.weights = np.ones(self.num_candidates) / self.num_candidates

    def __call__(self, func):
        best_x = None
        best_y = float('inf')

        for _ in range(self.budget):
            candidate_xs = []
            candidate_ys = []

            for _ in range(self.num_candidates):
                candidate_x = self.sample_candidate()
                candidate_y = func(candidate_x)
                candidate_xs.append(candidate_x)
                candidate_ys.append(candidate_y)

                if candidate_y < best_y:
                    best_x = candidate_x
                    best_y = candidate_y

            self.update_search_state(candidate_xs, candidate_ys)

        return best_x, best_y

    def sample_candidate(self):
        index = np.random.choice(self.num_candidates, p=self.weights)
        candidate_x = np.random.normal(self.means[index], self.stdevs[index])

        # Reflect the candidate back into the feasible region if it goes out of bounds
        if hasattr(self.sample_candidate, 'lower'):
            candidate_x = np.maximum(candidate_x, self.sample_candidate.lower)
        if hasattr(self.sample_candidate, 'upper'):
            candidate_x = np.minimum(candidate_x, self.sample_candidate.upper)
        if hasattr(self.sample_candidate, 'bounds'):
            candidate_x = np.maximum(candidate_x, self.sample_candidate.bounds.lb)
            candidate_x = np.minimum(candidate_x, self.sample_candidate.bounds.ub)

        return candidate_x

    def update_search_state(self, candidate_xs, candidate_ys):
        # Update the means and standard deviations of the Gaussian distributions
        for i in range(self.num_candidates):
            self.means[i] = np.average([x[i] for x in candidate_xs], weights=[y for y in candidate_ys], axis=0)
            self.stdevs[i] = np.sqrt(np.average([(x[i] - self.means[i])**2 for x in candidate_xs], weights=[y for y in candidate_ys], axis=0))

        # Update the weights of the Gaussian distributions
        self.weights = [y / sum(candidate_ys) for y in candidate_ys]
