import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized search algorithm for
#          the GNBG black-box minimization benchmark. The algorithm maintains a
#          population of candidate solutions, which are iteratively updated
#          using a combination of random sampling and gradient-based updates.
# Search state: The search state consists of a population of candidate
#                solutions, represented as a 2D numpy array.
# Candidate generation: New candidates are generated by randomly sampling from
#                      the current population, and applying a gradient-based
#                      update step.
# Selection and replacement: The best candidate from the updated population is
#                           selected as the new population. Worse candidates
#                           are replaced.
# Adaptation: The algorithm does not explicitly adapt its search strategy.
# Exploration mechanisms: Exploration is achieved through random sampling of
#                        the search space.
# Exploitation mechanisms: Exploitation is achieved through the gradient-based
#                         update step.
# Boundary handling: Boundary constraints are handled by projecting candidate
#                   solutions back into the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget, without
#                  any specific budget management strategy.
# Closest known influences: The algorithm is inspired by evolution strategies
#                          and gradient-based optimization methods.
# Novelty or unusual aspects: The algorithm combines random sampling and
#                            gradient-based updates in a compact and robust
#                            way, without any external dependencies.
# Failure modes: The algorithm may struggle on highly multimodal or
#               discontinuous functions, where the gradient-based update
#               may not be effective.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 20
        self.population = None
        self.step_size = 0.1

    def __call__(self, func):
        if self.population is None:
            self.population = np.random.uniform(func.lower, func.upper, (self.population_size, self.dim))

        for _ in range(self.budget):
            # Sample a random individual from the population
            idx = np.random.randint(0, self.population_size)
            x = self.population[idx]

            # Compute the gradient of the objective function
            grad = self.compute_gradient(func, x)

            # Update the individual using the gradient
            new_x = x - self.step_size * grad
            new_x = np.clip(new_x, func.lower, func.upper)

            # Replace the current individual with the new one if it's better
            y = func(x)
            new_y = func(new_x)
            if new_y < y:
                self.population[idx] = new_x

        # Return the best individual found
        best_idx = np.argmin([func(x) for x in self.population])
        best_x = self.population[best_idx]
        best_y = func(best_x)
        return best_x, best_y

    def compute_gradient(self, func, x):
        """Compute the gradient of the objective function using finite differences."""
        eps = 1e-6
        grad = np.zeros(self.dim)
        for i in range(self.dim):
            x_plus = x.copy()
            x_plus[i] += eps
            x_minus = x.copy()
            x_minus[i] -= eps
            grad[i] = (func(x_plus) - func(x_minus)) / (2 * eps)
        return grad
