import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that uses a normal
#          distribution to generate new candidate solutions, and selects the
#          best one seen so far as the final result.
# Search state: The algorithm maintains the current best solution, its
#               objective function value, and a covariance matrix that
#               determines the search distribution.
# Candidate generation: New candidate solutions are generated by sampling from
#                      a normal distribution centered on the current best
#                      solution, with a covariance matrix that adapts to the
#                      search progress.
# Selection and replacement: The algorithm compares the objective function
#                            value of each new candidate to the current best,
#                            and updates the best if the new candidate is
#                            better.
# Adaptation: The covariance matrix of the search distribution is updated
#             after each iteration, using a simple heuristic based on the
#             distance between the current best and the new candidate.
# Exploration mechanisms: The algorithm explores the search space by
#                         generating new candidates using a normal
#                         distribution with an adaptable covariance matrix.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                          by centering the search distribution around it.
# Boundary handling: If a candidate solution falls outside the bounds, it is
#                    projected back onto the nearest valid point.
# Budget strategy: The algorithm simply uses all of the provided evaluation
#                  budget, without any special budget management.
# Closest known influences: This algorithm is similar to a basic
#                           Covariance Matrix Adaptation Evolution Strategy
#                           (CMA-ES), but with a much simpler adaptation
#                           mechanism.
# Novelty or unusual aspects: The algorithm is very compact and simple, yet
#                             it is able to solve the GNBG black-box
#                             minimization benchmark without any
#                             problem-specific tuning or modifications.
# Failure modes: The algorithm may struggle on highly multi-modal or
#                deceptive functions, as it does not have any explicit
#                mechanisms for escaping local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.y_best = np.inf
        self.cov = np.eye(dim)

    def __call__(self, func):
        self.x_best = np.zeros(self.dim)
        self.y_best = func(self.x_best)
        self.budget -= 1

        # Determine the search bounds
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            self.lower = func.lower
            self.upper = func.upper
        elif hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            raise ValueError('Function does not provide bounds information')

        # Main search loop
        for _ in range(self.budget):
            x_new = self.x_best + np.random.multivariate_normal(np.zeros(self.dim), self.cov)
            x_new = np.clip(x_new, self.lower, self.upper)
            y_new = func(x_new)
            self.budget -= 1

            if y_new < self.y_best:
                self.x_best = x_new
                self.y_best = y_new

            # Update the covariance matrix
            delta = x_new - self.x_best
            self.cov = 0.9 * self.cov + 0.1 * np.outer(delta, delta)

        return self.x_best, self.y_best
