import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a randomized search algorithm that samples points within the
#          bounded domain and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x,
#               best_y) and the remaining evaluation budget.
# Candidate generation: Candidates are generated by sampling uniformly within
#                       the bounded domain.
# Selection and replacement: The best candidate is selected and replaces the
#                            current best solution if it improves the objective.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The uniform random sampling provides exploration across
#                         the entire domain.
# Exploitation mechanisms: The algorithm exploits by focusing the search around
#                          the current best solution.
# Boundary handling: Candidates that fall outside the bounded domain are
#                    rejected.
# Budget strategy: The algorithm uses the provided evaluation budget and stops
#                  when the budget is exhausted.
# Closest known influences: This algorithm is similar to a simple random search.
# Novelty or unusual aspects: The algorithm is very simple and does not include
#                             any advanced mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with highly multimodal objective functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        while self.budget > 0:
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            self.budget -= 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
