import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple gradient-free optimization method that
#          uses a population of candidate solutions and iteratively updates
#          them based on the objective function values.
# Search state: The search state consists of a population of candidate
#                solutions, represented as a 2D numpy array.
# Candidate generation: New candidate solutions are generated by adding Gaussian
#                       noise to the current population.
# Selection and replacement: The best candidate solution from the population
#                            is selected as the new best solution. The population
#                            is then updated by replacing the worst candidate
#                            solution with the new candidate.
# Adaptation: The standard deviation of the Gaussian noise used to generate new
#             candidates is adapted based on the current best objective function
#             value.
# Exploration mechanisms: The Gaussian noise used to generate new candidates
#                         provides exploration of the search space.
# Exploitation mechanisms: The selection of the best candidate solution as the
#                          new best solution provides exploitation of the
#                          current search region.
# Boundary handling: Candidate solutions that fall outside the bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm attempts to use the entire evaluation budget
#                  by generating new candidates until the budget is exhausted.
# Closest known influences: This algorithm is similar to a basic evolutionary
#                           strategy optimization method.
# Novelty or unusual aspects: The adaptation of the standard deviation of the
#                             Gaussian noise is a relatively simple but
#                             effective way to balance exploration and
#                             exploitation.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex multimodal or deceptive landscapes,
#                as the Gaussian mutation may not be sufficient to escape
#                local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 10
        self.sigma = 1.0

        # Initialize the population
        self.population = np.random.uniform(low=-5, high=5, size=(self.population_size, self.dim))
        self.population_fitness = np.full(self.population_size, np.inf)

    def __call__(self, func):
        # Evaluate the initial population
        for i in range(self.population_size):
            self.population_fitness[i] = func(self.population[i])
            self.budget -= 1

        # Optimize the population
        while self.budget > 0:
            # Generate new candidates
            new_candidates = self.population + np.random.normal(loc=0, scale=self.sigma, size=(self.population_size, self.dim))

            # Evaluate new candidates and update the population
            for i in range(self.population_size):
                new_fitness = func(new_candidates[i])
                self.budget -= 1

                if new_fitness < self.population_fitness[i]:
                    self.population[i] = new_candidates[i]
                    self.population_fitness[i] = new_fitness

            # Adapt the standard deviation
            self.sigma *= np.exp(-0.05 * (self.population_fitness.min() - self.population_fitness.mean()))

            # Clip the population to the bounds
            self.population = np.clip(self.population, func.lower, func.upper)

        # Return the best solution
        best_idx = np.argmin(self.population_fitness)
        return self.population[best_idx], self.population_fitness[best_idx]
