import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the given bounds and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points uniformly within the given bounds.
# Selection and replacement: The best candidate replaces the current best solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling points uniformly at random.
# Exploitation mechanisms: The algorithm exploits the best solution found so far by sampling around it.
# Boundary handling: Candidates that fall outside the given bounds are discarded and a new candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is similar to a simple random search or Monte Carlo method.
# Novelty or unusual aspects: The algorithm is very simple and does not use any advanced techniques.
# Failure modes: The algorithm may struggle to find good solutions in high-dimensional or multimodal problems, as it relies solely on random sampling.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Sample a candidate point uniformly within the bounds
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the candidate
            y = func(x)

            # Update the best solution if the candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
