import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust, and randomized black-box optimization
#          algorithm that uses Gaussian sampling to explore the search space.
# Search state: The search state is represented by the current best solution,
#               the current standard deviation of the search distribution,
#               and the remaining evaluation budget.
# Candidate generation: New candidates are generated by sampling from a
#                       Gaussian distribution centered on the current best
#                       solution, with the standard deviation adapted during
#                       the search.
# Selection and replacement: The best candidate from the current generation
#                            replaces the current best solution if it has a
#                            lower objective value.
# Adaptation: The standard deviation of the search distribution is adapted
#             based on the progress of the search, increasing when the search
#             is stagnant and decreasing when the search is making progress.
# Exploration mechanisms: The Gaussian sampling provides a balance of
#                         exploration and exploitation, with the standard
#                         deviation controlling the amount of exploration.
# Exploitation mechanisms: The search is biased towards the current best
#                          solution, with new candidates generated close to
#                          it.
# Boundary handling: Candidates that fall outside the search bounds are
#                    reflected back into the feasible region.
# Budget strategy: The algorithm aims to use the entire evaluation budget,
#                  but will return the current best solution if the budget
#                  is exhausted.
# Closest known influences: This algorithm is inspired by evolution strategies
#                          and Gaussian sampling-based optimization methods.
# Novelty or unusual aspects: The adaptive standard deviation and boundary
#                            handling are relatively simple but effective
#                            mechanisms for this black-box optimization task.
# Failure modes: The algorithm may struggle with highly multimodal or
#                discontinuous objective functions, as the Gaussian sampling
#                may not be able to effectively explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.std = 1.0

    def __call__(self, func):
        # Read bounds from the function
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Initialize the search with a random starting point
        self.best_x = np.random.uniform(self.lb, self.ub, size=self.dim)
        self.best_y = func(self.best_x)
        self.budget -= 1

        # Optimize until the budget is exhausted
        while self.budget > 0:
            # Generate a new candidate by sampling from a Gaussian distribution
            candidate = self.best_x + np.random.normal(0, self.std, size=self.dim)

            # Reflect the candidate back into the feasible region if necessary
            candidate = np.clip(candidate, self.lb, self.ub)

            # Evaluate the candidate
            candidate_y = func(candidate)
            self.budget -= 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            # Adapt the standard deviation based on the search progress
            if self.budget > 0.1 * self.budget:
                self.std *= 0.99
            else:
                self.std *= 1.01

        return self.best_x, self.best_y
