import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a Gaussian Smoothed Local Search algorithm
#          for black-box optimization problems. It maintains a search distribution centered
#          on the current best solution, and samples new candidate solutions from this
#          distribution, accepting the best ones.
# Search state: The algorithm maintains a current best solution and its objective function
#               value, as well as a search distribution (mean and covariance matrix).
# Candidate generation: New candidate solutions are generated by sampling from a Gaussian
#                       distribution centered on the current best solution, with a
#                       covariance matrix that adapts based on the progress of the search.
# Selection and replacement: The best candidate solution is compared to the current best
#                            and replaces it if the new solution is better.
# Adaptation: The covariance matrix of the search distribution is adapted based on the
#             progress of the search, becoming more narrow in successful directions and
#             wider in unsuccessful directions.
# Exploration mechanisms: The initial search distribution has a large covariance matrix
#                         to enable broad exploration of the search space. Over time, the
#                         covariance matrix adapts to focus the search on promising regions.
# Exploitation mechanisms: The search distribution is centered on the current best solution,
#                          allowing the algorithm to exploit the surrounding region.
# Boundary handling: The algorithm checks if candidate solutions are within the bounds of
#                    the search space, and rejects any that are outside.
# Budget strategy: The algorithm uses the full evaluation budget provided, without any
#                  explicit budget management strategy.
# Closest known influences: This algorithm is similar to Gaussian Smoothed Local Search
#                          and Covariance Matrix Adaptation Evolution Strategies.
# Novelty or unusual aspects: The compact, self-contained implementation without any
#                             external dependencies is a novel aspect of this code.
# Failure modes: The algorithm may struggle in high-dimensional problems or those with
#                many local minima, as the Gaussian search distribution may not be
#                flexible enough to navigate such landscapes effectively.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf
        self.cov = np.eye(dim) * 1.0

    def __call__(self, func):
        # Initialize the search distribution
        self.x_best = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
        self.f_best = func(self.x_best)
        self.budget -= 1

        while self.budget > 0:
            # Generate a new candidate solution
            x_candidate = np.random.multivariate_normal(self.x_best, self.cov)

            # Check if the candidate is within the bounds
            if np.all(x_candidate >= func.bounds.lb) and np.all(x_candidate <= func.bounds.ub):
                f_candidate = func(x_candidate)
                self.budget -= 1

                # Update the best solution if the candidate is better
                if f_candidate < self.f_best:
                    self.x_best = x_candidate
                    self.f_best = f_candidate

            # Adapt the search distribution
            self.cov *= 0.95  # Decay the covariance matrix
            self.cov += np.eye(self.dim) * 0.05  # Add a small constant to ensure positive definiteness

        return self.x_best, self.f_best
