import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust implementation of a derivative-free optimization
#          algorithm for the GNBG black-box minimization benchmark. It uses a simple
#          random search strategy with some adaptive features.
# Search state: The search state is represented by a single current candidate solution.
# Candidate generation: New candidate solutions are generated by sampling from a normal
#                      distribution centered on the current solution, with adaptive
#                      standard deviations.
# Selection and replacement: The current solution is replaced if a better candidate is
#                            found, otherwise it is kept.
# Adaptation: The standard deviations used for generating new candidates are adapted
#             based on the success rate of the search.
# Exploration mechanisms: The algorithm explores the search space by sampling new
#                         candidate solutions from a distribution centered on the
#                         current solution.
# Exploitation mechanisms: The algorithm exploits the search space by reducing the
#                          standard deviations of the sampling distribution when the
#                          search is successful.
# Boundary handling: Candidate solutions that fall outside the search bounds are
#                    reflected back inside the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget, without any
#                  special budget management strategies.
# Closest known influences: This algorithm is inspired by simple random search
#                          strategies, with some adaptive features similar to
#                          evolution strategies.
# Novelty or unusual aspects: The combination of a simple random search with
#                            adaptive standard deviations is a relatively
#                            straightforward but effective approach for
#                            black-box optimization.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex, multimodal objective functions, as
#                it relies on a relatively simple search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.random.uniform(low=-5, high=5, size=dim)
        self.std_devs = np.ones(dim) * 2.0
        self.success_count = 0

    def __call__(self, func):
        best_x = self.x.copy()
        best_y = func(best_x)
        self.budget -= 1

        while self.budget > 0:
            candidate = self.x + np.random.normal(loc=0, scale=self.std_devs, size=self.dim)
            
            # Reflect candidate back into feasible region if it's out of bounds
            if hasattr(func, 'bounds'):
                candidate = np.clip(candidate, func.bounds.lb, func.bounds.ub)
            else:
                candidate = np.clip(candidate, func.lower, func.upper)
            
            candidate_y = func(candidate)
            self.budget -= 1

            if candidate_y < best_y:
                best_x = candidate
                best_y = candidate_y
                self.x = candidate
                self.success_count += 1
                self.std_devs *= 0.98  # Reduce standard deviations on success
            else:
                self.std_devs *= 1.01  # Increase standard deviations on failure

        return best_x, best_y
