import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a black-box minimization algorithm that uses a random
#          search strategy to explore the search space efficiently while respecting the provided
#          evaluation budget.
# Search state: The algorithm maintains a single best candidate solution, which is updated as better
#               solutions are found.
# Candidate generation: New candidate solutions are generated by sampling uniformly within the
#                       search space defined by the function bounds.
# Selection and replacement: The best candidate solution is always kept, and it is replaced only
#                            if a better solution is found.
# Adaptation: The algorithm does not adapt its search strategy during the optimization process.
# Exploration mechanisms: The algorithm explores the search space by generating new random
#                         candidate solutions within the function bounds.
# Exploitation mechanisms: The algorithm exploits the search space by keeping track of the best
#                          solution found so far and biasing the search towards that region.
# Boundary handling: The algorithm ensures that all candidate solutions are within the function
#                    bounds by sampling uniformly within the bounds.
# Budget strategy: The algorithm stops when the provided evaluation budget is exhausted.
# Closest known influences: This algorithm is a simple, randomized search strategy that is
#                           commonly used as a baseline for more sophisticated optimization
#                           algorithms.
# Novelty or unusual aspects: The algorithm is intentionally kept simple and compact to
#                             demonstrate a robust, no-frills approach to black-box
#                             optimization.
# Failure modes: The algorithm may struggle to solve problems with complex or highly
#                multimodal objective functions, as it does not employ any advanced
#                exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
