import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that samples points uniformly within the given bounds and keeps track of the best point found so far.
# Search state: The algorithm maintains a single best point and its corresponding objective value.
# Candidate generation: Candidates are generated by sampling points uniformly within the given bounds.
# Selection and replacement: The best candidate replaces the current best point if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: Exploration is achieved through uniform random sampling within the bounds.
# Exploitation mechanisms: Exploitation is achieved by keeping track of the best point found so far and replacing it with better candidates.
# Boundary handling: Boundary handling is achieved by sampling points within the given bounds.
# Budget strategy: The algorithm uses the full evaluation budget, sampling the maximum number of points allowed.
# Closest known influences: This algorithm is similar to a simple random search or a Monte Carlo method for global optimization.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex or deceptive objective functions, as it does not incorporate any sophisticated search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
