import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a basic implementation of random search. It generates
# candidate solutions by sampling from a uniform distribution within the given
# bounds, and keeps track of the best solution found so far.
# Search state: The search state is represented by the best_x and best_y variables,
# which store the coordinates and function value of the best solution found so far.
# Candidate generation: Candidates are generated by sampling from a uniform
# distribution within the given bounds.
# Selection and replacement: The best candidate replaces the current best solution
# if it has a lower function value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The random sampling of candidates provides exploration.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidates outside the bounds are discarded and replaced with
# new samples.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This is a basic random search algorithm.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
# implementation.
# Failure modes: The algorithm may struggle to find the global optimum, especially
# in high-dimensional or multimodal problems, due to the lack of more sophisticated
# search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        evaluations = 0
        while evaluations < self.budget:
            candidate = np.random.uniform(func.lower, func.upper, size=self.dim)
            candidate_y = func(candidate)
            evaluations += 1
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y
        return self.best_x, self.best_y
