import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that generates candidate solutions uniformly within the search
#          bounds, evaluates them, and keeps track of the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y) and the remaining evaluation budget.
# Candidate generation: Candidates are generated by sampling uniformly within the given search bounds.
# Selection and replacement: The best candidate solution found so far is always kept, and replaces the current best if a better
#                            solution is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The uniform random sampling provides a simple exploration mechanism.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidate solutions that fall outside the search bounds are re-sampled until a valid solution is found.
# Budget strategy: The algorithm strictly adheres to the given evaluation budget, and stops when the budget is exhausted.
# Closest known influences: This algorithm is a basic randomized search, similar to pure random search or evolutionary
#                          strategies with uniform mutation.
# Novelty or unusual aspects: The algorithm is intentionally kept simple and compact, without any advanced mechanisms.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive functions, where random sampling is unlikely
#                to find the global optimum within the given budget.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        while self.budget > 0:
            # Generate a candidate solution uniformly within the search bounds
            x = self._generate_candidate(func)

            # Evaluate the candidate and update the best solution if necessary
            y = func(x)
            self.budget -= 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y

    def _generate_candidate(self, func):
        """Generate a candidate solution uniformly within the search bounds"""
        lb = getattr(func, 'lower', func.bounds.lb)
        ub = getattr(func, 'upper', func.bounds.ub)
        x = np.random.uniform(lb, ub, size=self.dim)
        return x
