import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search strategy that samples points
#          uniformly within the search space and keeps track of the current
#          best solution. It is a robust and easy-to-implement approach that
#          makes no assumptions about the objective function.
# Search state: The algorithm maintains the current best solution (best_x, best_y)
#               as the search state.
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the search space.
# Selection and replacement: The current best solution is replaced if a better
#                            candidate is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         points uniformly.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          continuing to sample around it.
# Boundary handling: The algorithm handles boundary constraints by sampling
#                    points within the provided bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search strategy,
#                           which is a common baseline for black-box
#                           optimization problems.
# Novelty or unusual aspects: There are no particularly novel or unusual
#                             aspects to this algorithm.
# Failure modes: The algorithm may struggle on objective functions with
#                complex or highly multimodal landscapes, as it does not
#                incorporate any advanced exploration or exploitation
#                mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
