import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust random search algorithm that maintains
# a single current best solution and updates it through a series of
# random perturbations. It reads the problem bounds from the objective
# function and never exceeds the provided evaluation budget.
# Search state: The algorithm maintains a single current best solution x
# and its corresponding objective value y.
# Candidate generation: New candidate solutions are generated by adding
# Gaussian noise to the current best solution, with the noise scale
# adaptively adjusted based on the success rate of recent steps.
# Selection and replacement: If a new candidate solution has a better
# objective value than the current best, it replaces the current best.
# Adaptation: The scale of the Gaussian noise used to generate new
# candidates is adapted based on the success rate of recent steps, to
# balance exploration and exploitation.
# Exploration mechanisms: The algorithm explores the search space by
# generating new random candidates around the current best solution.
# Exploitation mechanisms: The algorithm exploits the current best solution
# by generating new candidates in its vicinity and accepting improvements.
# Boundary handling: The algorithm ensures that new candidate solutions
# always remain within the problem bounds by clipping values that fall
# outside the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided,
# without any early stopping.
# Closest known influences: This algorithm is a basic random search
# approach, similar to the "1+1 Evolution Strategy" and "Random Search"
# algorithms commonly used as baseline methods in black-box optimization.
# Novelty or unusual aspects: The adaptive noise scaling is a relatively
# simple but effective technique to balance exploration and exploitation.
# Failure modes: This algorithm may struggle on highly multimodal or
# deceptive objective functions, as it does not have any mechanisms to
# escape local optima. Its performance is also likely to degrade as the
# problem dimensionality increases.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = None
        self.y = float('inf')
        self.noise_scale = 1.0
        self.success_count = 0
        self.trial_count = 0

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper

        # Initialize current best solution
        self.x = np.random.uniform(lb, ub, self.dim)
        self.y = func(self.x)

        # Optimize within the budget
        for _ in range(self.budget):
            # Generate new candidate
            candidate = self.x + self.noise_scale * np.random.normal(size=self.dim)
            candidate = np.clip(candidate, lb, ub)
            y_candidate = func(candidate)

            # Update current best
            if y_candidate < self.y:
                self.x, self.y = candidate, y_candidate
                self.success_count += 1
            self.trial_count += 1

            # Adapt noise scale
            self.noise_scale *= 0.9 ** (1 - 0.1 * (self.success_count / self.trial_count))

        return self.x, self.y
