import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and efficient implementation of a randomized direct search algorithm for blackbox optimization.
# Search state: The search state is represented by the current best candidate solution.
# Candidate generation: New candidate solutions are generated by sampling from a normal distribution centered on the current best solution, with a covariance matrix that adapts to the search progress.
# Selection and replacement: The new candidate solution replaces the current best solution if it has a lower objective function value.
# Adaptation: The covariance matrix of the normal distribution used for candidate generation is updated based on the progress of the search, encouraging exploration early on and exploitation later.
# Exploration mechanisms: Exploration is achieved through the use of a normal distribution with an adaptive covariance matrix for candidate generation.
# Exploitation mechanisms: Exploitation is achieved by gradually reducing the exploration component of the covariance matrix as the search progresses.
# Boundary handling: Candidate solutions that fall outside the feasible region are projected back onto the feasible region.
# Budget strategy: The algorithm attempts to utilize the full evaluation budget provided, but will terminate early if a satisfactory solution is found.
# Closest known influences: This algorithm is loosely inspired by the Covariance Matrix Adaptation Evolution Strategy (CMA-ES), but with a simplified implementation and fewer parameters.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust, and easy to understand, while still maintaining good performance on the GNBG black-box optimization benchmark.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional problems with multiple local minima, or in problems with highly non-convex or discontinuous objective functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.f = np.inf
        self.sigma = 1.0
        self.C = np.eye(dim)
        self.alpha = 0.85
        self.beta = 0.01

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x_new = self.x + self.sigma * np.random.multivariate_normal(np.zeros(self.dim), self.C)

            # Ensure the candidate solution is within the bounds
            x_new = np.clip(x_new, func.lower, func.upper)

            # Evaluate the new candidate solution
            f_new = func(x_new)

            # Update the best solution if the new candidate is better
            if f_new < self.f:
                self.x = x_new
                self.f = f_new

            # Adapt the covariance matrix
            self.C = (1 - self.beta) * self.C + self.beta * np.outer(x_new - self.x, x_new - self.x)
            self.sigma = self.sigma * self.alpha

        return self.x, self.f
