import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the search space and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points uniformly within the search space.
# Selection and replacement: The best candidate found so far replaces the current best solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: Exploration is achieved through the uniform random sampling of the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution by sampling new candidates around it.
# Boundary handling: Boundary handling is achieved by sampling new candidates within the search space bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to sample new candidates.
# Closest known influences: This algorithm is similar to a basic random search algorithm.
# Novelty or unusual aspects: The algorithm is very simple and does not have any advanced mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with complex landscapes, as it relies solely on random sampling.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
