import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates new candidates
#          by sampling from a uniform distribution within the search bounds.
# Search state: The search state consists of the current best solution (best_x, best_y).
# Candidate generation: New candidates are generated by sampling from a uniform
#                       distribution within the search bounds.
# Selection and replacement: The best candidate found so far is always kept.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         generating new candidates.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in this
#                          algorithm.
# Boundary handling: Candidates that fall outside the search bounds are rejected.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This algorithm is a basic random search method.
# Novelty or unusual aspects: This algorithm is very simple and straightforward.
# Failure modes: The algorithm may struggle to find good solutions in high-dimensional
#                or multimodal problems, as it relies solely on random sampling.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')
        self.evaluations = 0

    def __call__(self, func):
        while self.evaluations < self.budget:
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            self.evaluations += 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
