import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple gradient-free optimization algorithm that uses a combination of random sampling and gradient-based local search to find the minimum of the objective function.
# Search state: The algorithm maintains a single candidate solution and its corresponding objective value.
# Candidate generation: New candidate solutions are generated by perturbing the current solution with a Gaussian random vector.
# Selection and replacement: The new candidate solution replaces the current solution if it has a lower objective value.
# Adaptation: The standard deviation of the Gaussian perturbation is adapted based on the success or failure of the previous step.
# Exploration mechanisms: The algorithm uses random sampling to explore the search space.
# Exploitation mechanisms: The algorithm uses gradient-based local search to exploit the local structure of the objective function.
# Boundary handling: If a candidate solution goes outside the bounds of the search space, it is projected back onto the nearest valid point.
# Budget strategy: The algorithm uses the entire evaluation budget, with no early stopping.
# Closest known influences: This algorithm is similar to the Adaptive Metropolis Algorithm and the Differential Evolution algorithm.
# Novelty or unusual aspects: The algorithm combines random sampling and gradient-based local search in a simple and robust manner.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive objective functions, where the local search can get stuck in a poor local minimum.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.random.uniform(low=-5, high=5, size=dim)
        self.f = None
        self.sigma = 1.0

    def __call__(self, func):
        self.f = func
        best_x = self.x.copy()
        best_y = self.f(best_x)
        num_evals = 1

        while num_evals < self.budget:
            # Generate a new candidate solution
            candidate = self.x + self.sigma * np.random.normal(size=self.dim)

            # Check if the candidate is within the bounds
            if hasattr(self.f, 'bounds'):
                lb, ub = self.f.bounds.lb, self.f.bounds.ub
            else:
                lb, ub = self.f.lower, self.f.upper
            candidate = np.clip(candidate, lb, ub)

            # Evaluate the candidate solution
            candidate_y = self.f(candidate)
            num_evals += 1

            # Update the best solution if the candidate is better
            if candidate_y < best_y:
                best_x, best_y = candidate, candidate_y

            # Adapt the step size
            if candidate_y < self.f(self.x):
                self.sigma *= 1.01
            else:
                self.sigma *= 0.99

            # Update the current solution
            self.x = candidate

        return best_x, best_y
