import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a simplex-based direct search algorithm for
#          the GNBG black-box minimization benchmark. It starts with a simplex around the
#          origin, and iteratively reflects, expands, or contracts the simplex to find
#          better points, while staying within the provided search bounds.
# Search state: The search state is represented by the vertices of the simplex, which are
#               stored as the rows of a 2D numpy array.
# Candidate generation: New candidate points are generated by reflecting, expanding, or
#                       contracting the current simplex.
# Selection and replacement: The candidate with the lowest function value replaces the
#                            worst point in the simplex.
# Adaptation: The size and shape of the simplex are adapted based on the function values
#             at the vertices.
# Exploration mechanisms: The initial simplex size and the reflection, expansion, and
#                         contraction factors control the exploration of the search space.
# Exploitation mechanisms: The simplex-based search focuses on exploiting the local
#                          structure of the objective function.
# Boundary handling: The search is confined within the provided bounds by reflecting
#                    points that go outside the bounds.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This implementation is based on the Nelder-Mead simplex
#                           algorithm, a classic direct search method for unconstrained
#                           optimization.
# Novelty or unusual aspects: The algorithm is designed to be compact and robust across
#                             dimensions, without using any external libraries or
#                           advanced techniques.
# Failure modes: The algorithm may struggle with highly multimodal or discontinuous
#                objective functions, as the simplex-based search is mainly suited for
#                smooth, unimodal problems.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros((dim + 1, dim))  # Simplex vertices
        self.y = np.zeros(dim + 1)  # Function values at vertices
        self.init_simplex()

    def init_simplex(self):
        """Initialize the simplex around the origin."""
        self.x[:] = 0
        self.x[1:] = np.eye(self.dim) * 0.5

    def __call__(self, func):
        """Optimize the given function within the evaluation budget."""
        while self.budget > 0:
            # Reflect the worst point through the centroid of the other points
            xr = self.centroid() + (self.centroid() - self.x[-1])
            yr = func(xr)
            self.budget -= 1

            if yr < self.y[0]:
                # Expand the simplex
                xe = self.centroid() + 2 * (xr - self.centroid())
                ye = func(xe)
                self.budget -= 1
                if ye < yr:
                    self.replace(-1, xe, ye)
                else:
                    self.replace(-1, xr, yr)
            elif yr < self.y[-2]:
                # Accept the reflected point
                self.replace(-1, xr, yr)
            else:
                # Contract the simplex
                xc = self.centroid() + 0.5 * (self.x[-1] - self.centroid())
                yc = func(xc)
                self.budget -= 1
                if yc < self.y[-1]:
                    self.replace(-1, xc, yc)
                else:
                    # Shrink the simplex towards the best point
                    self.x[1:] = self.x[0] + 0.5 * (self.x[1:] - self.x[0])
                    for i in range(1, self.dim + 1):
                        self.y[i] = func(self.x[i])
                        self.budget -= 1

        # Return the best point found
        best_idx = np.argmin(self.y)
        return self.x[best_idx], self.y[best_idx]

    def centroid(self):
        """Calculate the centroid of the simplex, excluding the worst point."""
        return np.mean(self.x[:-1], axis=0)

    def replace(self, idx, x, y):
        """Replace a simplex vertex with a new point."""
        self.x[idx] = x
        self.y[idx] = y
