import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple downhill simplex method to iteratively
#          minimize the objective function within the given budget.
# Search state: The search state consists of a simplex of points in the
#                parameter space, represented as a (dim+1) x dim numpy array.
# Candidate generation: New candidate points are generated by reflecting,
#                       expanding, or contracting the simplex.
# Selection and replacement: The worst point in the simplex is replaced by the
#                            new candidate point if it improves the objective.
# Adaptation: The size and shape of the simplex are adapted based on the
#              objective function values at the simplex vertices.
# Exploration mechanisms: The initial simplex is constructed using random
#                         points within the parameter bounds.
# Exploitation mechanisms: The simplex method gradually contracts around the
#                          current best point.
# Boundary handling: If a candidate point falls outside the parameter bounds,
#                    it is projected back onto the nearest valid point.
# Budget strategy: The algorithm terminates when the evaluation budget is
#                  exhausted.
# Closest known influences: The Nelder-Mead simplex method.
# Novelty or unusual aspects: None.
# Failure modes: The algorithm may get stuck in local minima, especially for
#                multi-modal or high-dimensional problems.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Read parameter bounds
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            lb = func.lower
            ub = func.upper

        # Initialize simplex
        x = np.random.uniform(lb, ub, size=(self.dim + 1, self.dim))
        y = np.array([func(xi) for xi in x])
        self.evaluations += self.dim + 1

        # Optimize using Nelder-Mead simplex method
        while self.evaluations < self.budget:
            # Find best, worst, and second-worst points
            i_best = np.argmin(y)
            i_worst = np.argmax(y)
            i_second_worst = (np.arange(self.dim + 1) != i_worst).argmax()

            # Compute centroid of best points
            x_centroid = x[np.arange(self.dim + 1) != i_worst].mean(axis=0)

            # Reflect worst point through centroid
            x_reflect = x_centroid + (x_centroid - x[i_worst])
            x_reflect = np.clip(x_reflect, lb, ub)
            y_reflect = func(x_reflect)
            self.evaluations += 1

            if y_reflect < y[i_best]:
                # Expand in reflection direction
                x_expand = x_centroid + 2 * (x_reflect - x_centroid)
                x_expand = np.clip(x_expand, lb, ub)
                y_expand = func(x_expand)
                self.evaluations += 1
                if y_expand < y_reflect:
                    x[i_worst] = x_expand
                    y[i_worst] = y_expand
                else:
                    x[i_worst] = x_reflect
                    y[i_worst] = y_reflect
            elif y_reflect < y[i_second_worst]:
                # Accept reflected point
                x[i_worst] = x_reflect
                y[i_worst] = y_reflect
            else:
                # Contract towards best point
                x_contract = x_centroid + 0.5 * (x[i_worst] - x_centroid)
                x_contract = np.clip(x_contract, lb, ub)
                y_contract = func(x_contract)
                self.evaluations += 1
                if y_contract < y[i_worst]:
                    x[i_worst] = x_contract
                    y[i_worst] = y_contract
                else:
                    # Shrink simplex towards best point
                    x[np.arange(self.dim + 1) != i_best] = \
                        x[i_best] + 0.5 * (x[np.arange(self.dim + 1) != i_best] - x[i_best])
                    y[np.arange(self.dim + 1) != i_best] = \
                        [func(xi) for xi in x[np.arange(self.dim + 1) != i_best]]
                    self.evaluations += self.dim

        # Return best point found
        return x[i_best], y[i_best]
