import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple, randomized direct search method that
#          generates candidate solutions using a normal distribution centered
#          on the current best solution. It selects the best of the candidates
#          and replaces the current best if the new solution is better.
# Search state: The algorithm maintains a single best solution, represented
#               as a NumPy array.
# Candidate generation: Candidates are generated by adding Gaussian noise to
#                       the current best solution. The standard deviation of
#                       the noise is adapted based on the number of function
#                       evaluations used.
# Selection and replacement: The algorithm selects the best of the generated
#                            candidates and replaces the current best solution
#                            if the new solution is better.
# Adaptation: The standard deviation of the Gaussian noise used to generate
#             candidates is adapted based on the number of function evaluations
#             used. The standard deviation decreases as more evaluations are
#             used.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         new candidates using Gaussian noise around the current
#                         best solution.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates close to it.
# Boundary handling: The algorithm checks if the generated candidate solutions
#                    are within the provided bounds and rejects any that are
#                    outside the bounds.
# Budget strategy: The algorithm uses the entire provided evaluation budget
#                  and does not exceed it.
# Closest known influences: This algorithm is similar to a randomized direct
#                          search method, such as the Nelder-Mead simplex
#                          algorithm or a variant of the Covariance Matrix
#                          Adaptation Evolution Strategy (CMA-ES).
# Novelty or unusual aspects: The algorithm does not have any particularly
#                             novel or unusual aspects. It is a straightforward
#                             randomized direct search method.
# Failure modes: The algorithm may struggle to solve problems with many local
#                minima or highly multimodal objective functions, as it relies
#                on a simple Gaussian sampling around the current best solution.
#                It may also struggle with problems that require more complex
#                exploration and exploitation strategies.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(self.dim)
        self.best_y = np.inf
        self.evaluations = 0

    def __call__(self, func):
        bounds = self._get_bounds(func)
        while self.evaluations < self.budget:
            candidate = self._generate_candidate(self.best_x, bounds)
            candidate_y = func(candidate)
            self.evaluations += 1
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y
        return self.best_x, self.best_y

    def _get_bounds(self, func):
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            return np.array([func.lower, func.upper]).T
        elif hasattr(func, 'bounds'):
            return np.array([func.bounds.lb, func.bounds.ub]).T
        else:
            raise ValueError('Could not determine bounds from the function.')

    def _generate_candidate(self, x, bounds):
        sigma = 1.0 / np.sqrt(1 + self.evaluations / self.budget)
        candidate = x + sigma * np.random.normal(size=self.dim)
        return np.clip(candidate, bounds[:, 0], bounds[:, 1])
