import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a randomized
#          search method for black-box minimization. It leverages a combination
#          of random sampling and gradient-free local search to efficiently
#          explore the search space and locate the optimum.
# Search state: The search state consists of the current best solution (best_x,
#               best_y) and a history of past evaluations.
# Candidate generation: New candidate solutions are generated by randomly
#                       sampling within the search bounds, using a normal
#                       distribution centered on the current best solution.
# Selection and replacement: The best candidate solution is selected and
#                            replaces the current best solution if it has a
#                            lower objective value.
# Adaptation: The algorithm does not explicitly adapt its search strategy
#             during the optimization process.
# Exploration mechanisms: The algorithm primarily explores the search space
#                         through random sampling, which allows it to discover
#                         potentially promising regions.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates in its vicinity, allowing
#                          it to refine the search around potentially optimal
#                          regions.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                    generated within the specified search bounds by clipping
#                    any out-of-bounds values.
# Budget strategy: The algorithm keeps track of the evaluation budget and
#                  ensures that it never exceeds the provided budget.
# Closest known influences: This algorithm is inspired by simple randomized
#                           search methods, such as Pure Random Search and
#                           Nelder-Mead.
# Novelty or unusual aspects: The algorithm's compact and robust implementation,
#                             without relying on external libraries or
#                             techniques, is a novel aspect.
# Failure modes: The algorithm may struggle in high-dimensional search spaces
#                or with highly multimodal objective functions, where the
#                random sampling approach may not be able to efficiently
#                explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the search with a random starting point
        self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
        self.best_y = func(self.best_x)
        self.evaluations += 1

        # Perform the search
        while self.evaluations < self.budget:
            # Generate a new candidate solution
            candidate_x = np.clip(self.best_x + np.random.normal(0, 1, self.dim),
                                  func.lower, func.upper)
            candidate_y = func(candidate_x)
            self.evaluations += 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
