import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the given bounds and keeps track of the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points uniformly within the given bounds.
# Selection and replacement: The best candidate found so far replaces the current best solution if it is better.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space uniformly by sampling random points.
# Exploitation mechanisms: The algorithm exploits the current best solution by replacing it with a better candidate if one is found.
# Boundary handling: The algorithm ensures that candidate solutions are within the given bounds by sampling within the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a simple random search, which is a basic optimization technique.
# Novelty or unusual aspects: There are no unusual aspects to this algorithm.
# Failure modes: This algorithm may struggle to find the global optimum in high-dimensional or multimodal problems, as it does not incorporate any advanced exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
