import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact implementation of a randomized search algorithm
#          for the GNBG black-box minimization benchmark. It uses a simple random
#          sampling approach with some basic mechanisms to handle the search space
#          boundaries.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly within
#                       the search space bounds.
# Selection and replacement: The new candidate is compared to the current best solution,
#                            and the better one is kept as the new best solution.
# Adaptation: There is no explicit adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm relies on random sampling to explore the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution by keeping track
#                          of the best seen objective value.
# Boundary handling: Candidate solutions that fall outside the search space bounds are
#                    projected back onto the boundary.
# Budget strategy: The algorithm uses the entire evaluation budget, sampling new candidates
#                  until the budget is exhausted.
# Closest known influences: This algorithm is a simple implementation of a randomized
#                          search algorithm, with some basic boundary handling.
# Novelty or unusual aspects: The algorithm is quite compact and straightforward, without
#                            any advanced mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with
#                complex landscapes, as it relies solely on random sampling without any
#                more sophisticated exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
