import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of the Nelder-Mead simplex algorithm for
#          black-box optimization. It maintains a simplex of candidate solutions and
#          iteratively updates the simplex to move towards the optimum.
# Search state: The search state is represented by the simplex, which is a set of
#               n+1 points in the n-dimensional search space, where n is the
#               dimensionality of the problem.
# Candidate generation: New candidate points are generated by reflecting, expanding,
#                       or contracting the current simplex.
# Selection and replacement: The worst point in the simplex is replaced by a new
#                            candidate point.
# Adaptation: The algorithm adapts the size and shape of the simplex based on the
#             objective function values at the vertices.
# Exploration mechanisms: The algorithm explores the search space by generating new
#                         candidate points that are distributed around the current
#                         simplex.
# Exploitation mechanisms: The algorithm exploits the best regions of the search
#                          space by contracting the simplex towards the best point.
# Boundary handling: If a candidate point falls outside the search bounds, it is
#                    projected back onto the boundary.
# Budget strategy: The algorithm terminates when the evaluation budget is exhausted.
# Closest known influences: This implementation is based on the Nelder-Mead simplex
#                           algorithm, which is a well-known derivative-free
#                           optimization method.
# Novelty or unusual aspects: This implementation is designed to be compact, robust,
#                             and suitable for the GNBG black-box minimization
#                             benchmark.
# Failure modes: The algorithm may converge to a local minimum, especially if the
#                objective function is multimodal or has a complex landscape.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(low=func.lower, high=func.upper, size=(self.dim + 1, self.dim))
        y = np.array([func(x) for x in x0])
        self.evaluations += self.dim + 1

        # Nelder-Mead iterations
        while self.evaluations < self.budget:
            # Order the simplex
            idx = np.argsort(y)
            x0, y = x0[idx], y[idx]

            # Reflect the worst point
            xr = x0[:-1].mean(axis=0) + (x0[:-1].mean(axis=0) - x0[-1])
            yr = func(xr)
            self.evaluations += 1

            # Update the simplex
            if yr < y[0]:
                # Expand the simplex
                xe = x0[:-1].mean(axis=0) + 2 * (xr - x0[:-1].mean(axis=0))
                ye = func(xe)
                self.evaluations += 1
                if ye < yr:
                    x0[-1], y[-1] = xe, ye
                else:
                    x0[-1], y[-1] = xr, yr
            elif yr < y[-2]:
                # Accept the reflected point
                x0[-1], y[-1] = xr, yr
            else:
                # Contract the simplex
                xc = x0[:-1].mean(axis=0) + 0.5 * (x0[-1] - x0[:-1].mean(axis=0))
                yc = func(xc)
                self.evaluations += 1
                if yc < y[-1]:
                    x0[-1], y[-1] = xc, yc
                else:
                    # Shrink the simplex
                    x0[1:], y[1:] = (x0[0] + 0.5 * (x0[1:] - x0[0])), [func(x) for x in (x0[0] + 0.5 * (x0[1:] - x0[0]))]
                    self.evaluations += self.dim

        # Return the best solution found
        best_idx = np.argmin(y)
        return x0[best_idx], y[best_idx]
