import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact implementation of a randomized search
#          strategy for black-box optimization problems. It generates candidate
#          solutions by sampling from a multivariate normal distribution,
#          centered at the current best solution. The variance of the
#          distribution is adapted based on the observed function values.
# Search state: The algorithm maintains a single current best solution.
# Candidate generation: Candidates are generated by sampling from a multivariate
#                      normal distribution centered at the current best
#                      solution, with a covariance matrix that is adapted
#                      during the search.
# Selection and replacement: The best candidate solution is always accepted as
#                           the new current best.
# Adaptation: The covariance matrix of the candidate generation distribution is
#             adapted based on the observed function values, using a simple
#             heuristic that increases the variance along dimensions where
#             improvements have been observed.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                        from a multivariate normal distribution, which
#                        inherently balances exploration and exploitation.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                         centering the candidate generation distribution
#                         around it.
# Boundary handling: Candidate solutions that violate the problem bounds are
#                   projected back onto the feasible region.
# Budget strategy: The algorithm consumes the entire evaluation budget
#                  provided, without any explicit budget management.
# Closest known influences: This algorithm is similar to the Gaussian Adaptation
#                          Evolution Strategy (GAES), a well-known
#                          gradient-free optimization algorithm.
# Novelty or unusual aspects: The algorithm is highly compact and uses a simple
#                            adaptation heuristic, making it easy to understand
#                            and implement.
# Failure modes: The algorithm may perform poorly on multimodal or highly
#                rugged objective functions, as it relies on a single-point
#                search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.sigma = np.ones(dim)

    def __call__(self, func):
        best_x = self.x.copy()
        best_y = func(best_x)
        self.budget -= 1

        while self.budget > 0:
            # Generate a new candidate solution
            candidate = self.x + self.sigma * np.random.randn(self.dim)

            # Ensure the candidate is within the problem bounds
            candidate = np.clip(candidate, func.lower, func.upper)

            # Evaluate the candidate and update the best solution if necessary
            y = func(candidate)
            self.budget -= 1
            if y < best_y:
                best_x = candidate.copy()
                best_y = y

            # Adapt the step size based on the function values
            self.sigma *= np.exp(0.01 * (y - best_y) / np.linalg.norm(self.sigma))

        return best_x, best_y
