import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search strategy that samples points
#          uniformly within the bounded search space and keeps track of the
#          current best solution found so far.
# Search state: The search state consists of the current best solution (best_x,
#               best_y) and the remaining evaluation budget.
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the bounded search space.
# Selection and replacement: The current best solution is replaced if a
#                           better candidate is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space uniformly by
#                         sampling random points.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          continuing to search around it.
# Boundary handling: Boundary handling is performed by clamping the sampled
#                    points to the bounded search space.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search strategy,
#                           which is a common baseline for black-box
#                           optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or highly multimodal problems, as it relies
#                solely on random sampling without any more sophisticated
#                search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
