import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact and robust implementation of a random search algorithm
#          for the GNBG black-box minimization benchmark.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                       random points within the search bounds.
# Selection and replacement: The best solution found so far is always kept, replacing
#                            it only if a better solution is found.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The uniform random sampling of candidates encourages exploration
#                         of the search space.
# Exploitation mechanisms: None. The algorithm relies solely on exploration.
# Boundary handling: Candidate solutions that fall outside the search bounds are
#                    projected back onto the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This implementation is inspired by simple random search
#                          algorithms commonly used as baseline methods.
# Novelty or unusual aspects: There are no novel or unusual aspects to this implementation.
# Failure modes: The algorithm may struggle to efficiently solve problems with
#                strong dependencies or structure, as it does not incorporate
#                any problem-specific knowledge or adaptive mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Read search bounds
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper

        # Initialize search
        self.best_x = np.random.uniform(lb, ub, self.dim)
        self.best_y = func(self.best_x)
        budget_used = 1

        # Search loop
        while budget_used < self.budget:
            # Generate new candidate
            x = np.random.uniform(lb, ub, self.dim)

            # Evaluate candidate
            y = func(x)
            budget_used += 1

            # Update best solution
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
