import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple Nelder-Mead simplex method to
#          optimize the given black-box function within the provided budget.
# Search state: The search state is represented by a simplex, which is a set
#               of (dim+1) points in the search space.
# Candidate generation: New candidate points are generated by performing
#                       standard Nelder-Mead simplex operations, such as
#                       reflection, expansion, and contraction.
# Selection and replacement: The best point in the simplex is selected as the
#                            next iteration's starting point. The worst point
#                            is replaced with the new candidate.
# Adaptation: The simplex adapts its size and shape based on the function
#             values at the vertices, following the Nelder-Mead algorithm.
# Exploration mechanisms: The simplex explores the search space by moving
#                         towards promising regions and expanding or
#                         contracting the simplex size.
# Exploitation mechanisms: The simplex exploits the local information by
#                          performing simplex operations to converge towards
#                          the optimum.
# Boundary handling: Boundary violations are handled by projecting the
#                    out-of-bounds points back onto the feasible region.
# Budget strategy: The algorithm stops when the evaluation budget is
#                  exhausted.
# Closest known influences: The Nelder-Mead simplex method is a classic
#                           gradient-free optimization algorithm.
# Novelty or unusual aspects: This implementation is a straightforward
#                             application of the Nelder-Mead method to the
#                             given black-box optimization problem.
# Failure modes: The algorithm may struggle with multimodal or highly
#                rugged functions, as the simplex can get stuck in local
#                minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.simplex = None
        self.function_values = None
        self.evaluations = 0

    def __call__(self, func):
        if self.simplex is None:
            self.initialize_simplex(func)
        else:
            self.update_simplex(func)

        best_x = self.simplex[0]
        best_y = self.function_values[0]
        return best_x, best_y

    def initialize_simplex(self, func):
        """Initialize the simplex with (dim+1) random points."""
        self.simplex = np.random.uniform(func.lower, func.upper, (self.dim + 1, self.dim))
        self.function_values = np.array([func(x) for x in self.simplex])
        self.evaluations = self.dim + 1

    def update_simplex(self, func):
        """Update the simplex using the Nelder-Mead algorithm."""
        while self.evaluations < self.budget:
            # Order the simplex vertices by their function values
            order = np.argsort(self.function_values)
            self.simplex = self.simplex[order]
            self.function_values = self.function_values[order]

            # Compute the centroid of the best (dim) points
            centroid = np.mean(self.simplex[:-1], axis=0)

            # Reflect the worst point through the centroid
            reflected = centroid + (centroid - self.simplex[-1])
            reflected = np.clip(reflected, func.lower, func.upper)
            reflected_value = func(reflected)
            self.evaluations += 1

            if reflected_value < self.function_values[0]:
                # Expansion step
                expanded = centroid + 2 * (reflected - centroid)
                expanded = np.clip(expanded, func.lower, func.upper)
                expanded_value = func(expanded)
                self.evaluations += 1
                if expanded_value < reflected_value:
                    self.simplex[-1] = expanded
                    self.function_values[-1] = expanded_value
                else:
                    self.simplex[-1] = reflected
                    self.function_values[-1] = reflected_value
            elif reflected_value < self.function_values[-2]:
                # Accept the reflected point
                self.simplex[-1] = reflected
                self.function_values[-1] = reflected_value
            else:
                # Contraction step
                contracted = centroid + 0.5 * (self.simplex[-1] - centroid)
                contracted = np.clip(contracted, func.lower, func.upper)
                contracted_value = func(contracted)
                self.evaluations += 1
                if contracted_value < self.function_values[-1]:
                    self.simplex[-1] = contracted
                    self.function_values[-1] = contracted_value
                else:
                    # Shrink the simplex
                    self.simplex = self.simplex[0] + 0.5 * (self.simplex[1:] - self.simplex[0])
                    self.function_values = [func(x) for x in self.simplex]
                    self.evaluations += self.dim

        best_x = self.simplex[0]
        best_y = self.function_values[0]
        return best_x, best_y
