import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search strategy to find the
#          minimum of the black-box objective function. It samples points
#          uniformly within the search space and keeps track of the best
#          point found so far.
# Search state: The algorithm maintains the current best solution (best_x,
#               best_y) found during the search.
# Candidate generation: New candidate solutions are generated by sampling
#                       uniformly within the search space.
# Selection and replacement: The best candidate solution is compared to the
#                            current best solution, and replaces it if the
#                            new solution is better.
# Adaptation: There is no adaptation in this algorithm; the search strategy
#             remains the same throughout the optimization.
# Exploration mechanisms: The uniform random sampling provides exploration
#                         of the search space.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in
#                          this algorithm.
# Boundary handling: Candidate solutions that fall outside the search space
#                    are discarded and a new candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided.
# Closest known influences: This algorithm is a basic random search strategy,
#                           similar to the "Ball-Dropping" algorithm.
# Novelty or unusual aspects: This algorithm is intentionally simple and
#                             straightforward, without any advanced
#                             optimization techniques.
# Failure modes: The algorithm may struggle to find the global minimum if the
#                objective function is highly multimodal or has a very narrow
#                global minimum.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
