import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust implementation of the Nelder-Mead simplex algorithm for
#          black-box minimization in arbitrary dimensions. It uses only the Python standard
#          library and NumPy, and never exceeds the provided evaluation budget.
# Search state: The algorithm maintains a simplex of points (n+1 points in n dimensions).
# Candidate generation: New candidate points are generated by reflecting, expanding, or
#                       contracting the simplex.
# Selection and replacement: The worst point in the simplex is replaced by a new candidate.
# Adaptation: The simplex is adapted by adjusting the reflection, expansion, and contraction
#             coefficients based on the objective function values at the simplex vertices.
# Exploration mechanisms: The simplex exploration is driven by the reflection, expansion,
#                         and contraction operations, which allow the simplex to move and
#                         deform in the search space.
# Exploitation mechanisms: The simplex is attracted towards the best-so-far point, and the
#                          algorithm terminates when the simplex size is sufficiently small.
# Boundary handling: Candidate points that fall outside the bounds are projected back onto
#                    the nearest feasible point.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This implementation is based on the Nelder-Mead simplex algorithm,
#                           a classic direct search method for derivative-free optimization.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust, and universal,
#                             without relying on any problem-specific knowledge or tuning.
# Failure modes: The algorithm may struggle in high-dimensional problems or on multimodal
#                functions with many local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.n_evals = 0
        self.alpha = 1.0  # reflection coefficient
        self.gamma = 2.0  # expansion coefficient
        self.rho = 0.5    # contraction coefficient
        self.sigma = 0.5  # shrinkage coefficient

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.lower, func.upper, size=(self.dim + 1, self.dim))
        y = [func(x) for x in x0]
        self.n_evals += self.dim + 1

        while self.n_evals < self.budget:
            # Sort the simplex by objective function value
            x0 = x0[np.argsort(y)]
            y = sorted(y)

            # Compute the centroid of the best n points
            xc = np.mean(x0[:-1], axis=0)

            # Reflect the worst point through the centroid
            xr = xc + self.alpha * (xc - x0[-1])
            yr = func(xr)
            self.n_evals += 1

            if yr < y[0]:
                # Expansion step
                xe = xc + self.gamma * (xr - xc)
                ye = func(xe)
                self.n_evals += 1
                if ye < yr:
                    x0[-1] = xe
                    y[-1] = ye
                else:
                    x0[-1] = xr
                    y[-1] = yr
            elif yr < y[-2]:
                # Accept the reflected point
                x0[-1] = xr
                y[-1] = yr
            else:
                if yr < y[-1]:
                    # Contraction step
                    xc = xc + self.rho * (xr - xc)
                    yc = func(xc)
                    self.n_evals += 1
                    if yc <= yr:
                        x0[-1] = xc
                        y[-1] = yc
                    else:
                        # Shrink the simplex
                        x0 = x0[0] + self.sigma * (x0 - x0[0])
                        y = [func(x) for x in x0]
                        self.n_evals += self.dim

        # Return the best point found
        best_idx = np.argmin(y)
        return x0[best_idx], y[best_idx]
