import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search strategy that samples
#          points uniformly within the search space and keeps track of the
#          best point found so far.
# Search state: The search state consists of the current best point and
#               its objective function value.
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the search space.
# Selection and replacement: The best candidate found so far is always
#                            kept, replacing the previous best if a better
#                            point is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         points uniformly, which allows it to potentially
#                         discover any point in the search space.
# Exploitation mechanisms: The algorithm exploits the best point found so far
#                          by keeping track of it and using it as the starting
#                          point for subsequent searches.
# Boundary handling: Boundary handling is performed by rejecting any candidate
#                    points that fall outside the search space.
# Budget strategy: The algorithm uses the entire evaluation budget provided,
#                  sampling as many points as possible within the budget.
# Closest known influences: This algorithm is a basic random search strategy,
#                           which is a common starting point for
#                           black-box optimization problems.
# Novelty or unusual aspects: There are no particularly novel or unusual
#                             aspects to this algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with narrow, well-defined optima, as the random
#                search strategy may not be able to efficiently locate the
#                optimum within the provided budget.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
