import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact and robust implementation of a randomized derivative-free
#          optimization algorithm for the GNBG black-box minimization benchmark.
# Search state: The search state consists of a single candidate solution, which is
#               iteratively updated.
# Candidate generation: New candidate solutions are generated by adding Gaussian
#                       noise to the current best solution.
# Selection and replacement: The new candidate replaces the current best solution
#                            if it has a better objective function value.
# Adaptation: The standard deviation of the Gaussian noise is adapted based on the
#             progress of the search.
# Exploration mechanisms: The randomized candidate generation promotes exploration
#                         of the search space.
# Exploitation mechanisms: The selection of the new best solution promotes
#                          exploitation of promising regions.
# Boundary handling: Candidate solutions that violate the box constraints are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm makes efficient use of the evaluation budget by
#                  terminating when the budget is exhausted.
# Closest known influences: This algorithm is inspired by simple randomized
#                           derivative-free optimization methods.
# Novelty or unusual aspects: The adaptation of the search step size is a relatively
#                             common technique, but the specific implementation here
#                             is tailored to the GNBG benchmark.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex, multi-modal objective functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.f = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        self.budget_spent = 0
        while self.budget_spent < self.budget:
            candidate = self.x + self.sigma * np.random.normal(size=self.dim)
            candidate = np.clip(candidate, func.bounds.lb, func.bounds.ub)
            candidate_f = func(candidate)
            self.budget_spent += 1
            if candidate_f < self.f:
                self.x = candidate
                self.f = candidate_f
            self.sigma *= 0.99  # Adapt the search step size
        return self.x, self.f
