import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple and robust implementation of a black-box minimization
#          algorithm for the GNBG benchmark. It uses a random search strategy
#          with adaptive step sizes.
# Search state: The algorithm maintains the current best solution (best_x, best_y)
#               and a set of candidate solutions.
# Candidate generation: New candidate solutions are generated by adding Gaussian
#                       noise to the current best solution, with an adaptive
#                       step size that decreases as the budget is consumed.
# Selection and replacement: The best candidate solution is selected and replaces
#                            the current best solution if it improves the
#                            objective value.
# Adaptation: The step size for generating new candidates is adapted based on
#             the success rate of the previous candidates.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         new candidates with Gaussian noise.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates in its vicinity.
# Boundary handling: The algorithm ensures that new candidate solutions stay
#                    within the problem bounds by clipping the values if
#                    necessary.
# Budget strategy: The algorithm consumes the evaluation budget evenly over the
#                  course of the search.
# Closest known influences: This algorithm is similar to a basic random search
#                           with adaptive step sizes, which is a common
#                           approach for black-box optimization problems.
# Novelty or unusual aspects: The algorithm does not have any unusual aspects
#                             and follows a standard random search strategy.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex multimodal landscapes, as the random
#                search strategy may not be able to efficiently explore the
#                search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.step_size = 1.0

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        # Initialize the search
        self.best_x = np.random.uniform(self.lower, self.upper, size=self.dim)
        self.best_y = func(self.best_x)
        self.budget -= 1

        # Perform the search
        while self.budget > 0:
            # Generate a new candidate solution
            candidate_x = self.best_x + self.step_size * np.random.normal(size=self.dim)
            candidate_x = np.clip(candidate_x, self.lower, self.upper)
            candidate_y = func(candidate_x)
            self.budget -= 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            # Adapt the step size based on the success rate
            self.step_size *= 0.9 if candidate_y < self.best_y else 1.1

        return self.best_x, self.best_y
