import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the given
#          search bounds, evaluates the objective function, and keeps track of the best point found
#          so far.
# Search state: The search state consists of the current best point and its corresponding function value.
# Candidate generation: Candidates are generated by sampling points uniformly within the search bounds.
# Selection and replacement: The best candidate replaces the current best point if it has a lower
#                            function value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling points uniformly.
# Exploitation mechanisms: The algorithm exploits the search space by keeping track of the best
#                          point found so far and using it to guide the search.
# Boundary handling: The algorithm ensures that all candidate points are within the search bounds by
#                    clipping the values to the bounds if necessary.
# Budget strategy: The algorithm uses the entire evaluation budget to sample as many points as possible
#                  within the given budget.
# Closest known influences: This algorithm is a basic random search algorithm, which is a common
#                          baseline for black-box optimization problems.
# Novelty or unusual aspects: This algorithm does not have any novel or unusual aspects, as it is a
#                            straightforward implementation of a random search.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional or
#                multimodal problems, as it relies solely on random sampling without any
#                additional mechanisms to guide the search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
