import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple and compact implementation of a black-box optimization
#          algorithm for the GNBG benchmark. It uses a random search strategy with
#          Gaussian perturbations to explore the search space, and keeps track of
#          the best solution found so far.
# Search state: The search state is represented by the current best solution (best_x)
#               and its corresponding objective value (best_y).
# Candidate generation: New candidates are generated by adding Gaussian noise to the
#                       current best solution, with the standard deviation of the
#                       noise decreasing as the budget is consumed.
# Selection and replacement: The new candidate is always compared to the current
#                           best solution, and replaces it if the new solution is
#                           better.
# Adaptation: The standard deviation of the Gaussian noise is adapted based on the
#             remaining evaluation budget, decreasing as the budget is consumed.
# Exploration mechanisms: The algorithm uses random Gaussian perturbations to
#                         explore the search space.
# Exploitation mechanisms: The algorithm focuses on the current best solution, using
#                          it as the center of the Gaussian distribution for
#                          generating new candidates.
# Boundary handling: The algorithm ensures that new candidates stay within the
#                    specified bounds by clamping the values to the bounds if
#                    necessary.
# Budget strategy: The algorithm consumes the evaluation budget at a constant rate,
#                  using the remaining budget to adapt the Gaussian noise standard
#                  deviation.
# Closest known influences: This algorithm is inspired by simple randomized search
#                           methods, such as the COBRA algorithm.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust, and
#                             easy to understand, with a focus on simplicity and
#                             generality.
# Failure modes: The algorithm may struggle with highly multimodal or deceptive
#                landscapes, as it relies on a simple random search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        if self.best_x is None:
            # Initialize the search by sampling a random point within the bounds
            self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
            self.best_y = func(self.best_x)
            self.budget -= 1

        # Iterate until the budget is exhausted
        while self.budget > 0:
            # Generate a new candidate by perturbing the current best solution
            std = max(0.1, 1.0 - self.budget / func.budget)
            candidate = self.best_x + np.random.normal(0, std, self.dim)

            # Ensure the candidate is within the bounds
            candidate = np.clip(candidate, func.lower, func.upper)

            # Evaluate the candidate and update the best solution if it's better
            candidate_y = func(candidate)
            self.budget -= 1
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

        return self.best_x, self.best_y
