import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact implementation of a randomized search strategy
#          for black-box optimization problems. It uses a simple random sampling
#          approach to explore the search space and keep track of the best solution
#          found so far.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling uniformly within the
#                       provided bounds for each dimension.
# Selection and replacement: The best candidate found during the budget is selected
#                            and replaces the current best solution if it is better.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         random samples within the provided bounds.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          sampling around it, but this is not a major component.
# Boundary handling: The algorithm respects the provided bounds by clamping
#                    candidate solutions to the valid range.
# Budget strategy: The algorithm uses the entire budget for exploration, without
#                  any budget allocation strategies.
# Closest known influences: This algorithm is a basic random search strategy,
#                          similar to Randomized Search or Pure Random Search.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             implementation.
# Failure modes: This algorithm may struggle in high-dimensional problems or
#                problems with complex, multimodal landscapes, as it lacks
#                more advanced exploration and exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
