import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized search algorithm for
#          black-box function optimization. It uses a multivariate Gaussian
#          distribution to sample candidate solutions, and selects the best
#          candidate from each batch.
# Search state: The search state is represented by the mean and covariance
#               matrix of the Gaussian distribution used to sample candidates.
# Candidate generation: Candidates are generated by sampling from a multivariate
#                      Gaussian distribution centered at the current search mean,
#                      with a covariance matrix that adapts based on the success
#                      of previous iterations.
# Selection and replacement: The best candidate from each batch is selected and
#                           used to update the search state.
# Adaptation: The covariance matrix of the Gaussian distribution is adapted
#             based on the success of previous iterations, using a simple rank-
#             one update.
# Exploration mechanisms: The search explores the space by sampling from a
#                        Gaussian distribution with a covariance matrix that
#                        adapts to the landscape.
# Exploitation mechanisms: The search exploits the best solutions found so far
#                         by centering the Gaussian distribution around the
#                         current best solution.
# Boundary handling: Boundary handling is performed by clamping candidate
#                   solutions to the provided bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided, and
#                  does not exceed it.
# Closest known influences: This algorithm is inspired by the Covariance Matrix
#                          Adaptation Evolution Strategy (CMA-ES).
# Novelty or unusual aspects: The implementation is compact and self-contained,
#                            using only the Python standard library and NumPy.
# Failure modes: The algorithm may struggle on highly multimodal or
#                discontinuous functions, or in cases where the provided
#                evaluation budget is extremely limited.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.mean = np.zeros(dim)
        self.cov = np.eye(dim)
        self.num_evals = 0

    def __call__(self, func):
        bounds = self._get_bounds(func)
        best_x = np.zeros(self.dim)
        best_y = float('inf')

        for _ in range(self.budget):
            candidate = self._sample_candidate(bounds)
            y = func(candidate)
            self.num_evals += 1

            if y < best_y:
                best_x = candidate
                best_y = y

            self._update_search_state(candidate, y)

        return best_x, best_y

    def _get_bounds(self, func):
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            return func.lower, func.upper
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            return func.bounds.lb, func.bounds.ub
        else:
            raise ValueError('Could not determine function bounds')

    def _sample_candidate(self, bounds):
        candidate = np.random.multivariate_normal(self.mean, self.cov)
        return np.clip(candidate, bounds[0], bounds[1])

    def _update_search_state(self, candidate, y):
        self.mean = (1 - 1 / self.num_evals) * self.mean + 1 / self.num_evals * candidate
        delta = candidate - self.mean
        self.cov = (1 - 1 / self.num_evals) * self.cov + 1 / self.num_evals * np.outer(delta, delta)
