import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a basic gradient-based optimization approach to minimize the objective function within the given budget.
# Search state: The search state is represented by the current best solution (best_x) and its corresponding objective value (best_y).
# Candidate generation: Candidates are generated by perturbing the current best solution using a normal distribution with a decreasing standard deviation.
# Selection and replacement: The new candidate solution is accepted if it improves the current best solution.
# Adaptation: The standard deviation of the normal distribution used for candidate generation is decreased over time to focus the search on the promising regions.
# Exploration mechanisms: The initial exploration is facilitated by the larger standard deviation, which allows the search to cover a wider range of the search space.
# Exploitation mechanisms: As the search progresses, the smaller standard deviation forces the search to focus on the promising regions around the current best solution.
# Boundary handling: The candidate solution is clipped to the provided bounds to ensure feasibility.
# Budget strategy: The algorithm uses the entire evaluation budget to perform the optimization.
# Closest known influences: This algorithm is inspired by the basic gradient-based optimization approach, with adaptive step size control.
# Novelty or unusual aspects: The algorithm does not use any specialized techniques or advanced optimization methods, but rather relies on a simple and robust gradient-based approach.
# Failure modes: The algorithm may struggle in cases where the objective function is highly multimodal or non-convex, as the gradient-based approach may get stuck in local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.std_dev = 1.0  # Initial standard deviation for candidate generation
        self.std_dev_decay = 0.99  # Decay rate for standard deviation
        self.best_x = np.zeros(dim)
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            candidate_x = self.best_x + self.std_dev * np.random.normal(size=self.dim)

            # Clip the candidate solution to the bounds
            candidate_x = np.clip(candidate_x, func.lower, func.upper)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            # Decrease the standard deviation for the next iteration
            self.std_dev *= self.std_dev_decay

        return self.best_x, self.best_y
