import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that generates new
# candidate solutions by adding Gaussian noise to the current best solution.
# Search state: The algorithm maintains a single best solution, which is
# updated whenever a better solution is found.
# Candidate generation: New candidate solutions are generated by adding
# Gaussian noise to the current best solution. The standard deviation of the
# noise is adaptively reduced as the search progresses.
# Selection and replacement: The new candidate solution replaces the current
# best solution if it is better (has a lower objective function value).
# Adaptation: The standard deviation of the Gaussian noise is reduced as the
# search progresses, to focus the search around the current best solution.
# Exploration mechanisms: The initial Gaussian noise allows for broad
# exploration of the search space.
# Exploitation mechanisms: As the search progresses, the reduced noise
# standard deviation focuses the search around the current best solution.
# Boundary handling: If a candidate solution falls outside the search bounds,
# it is reflected back inside the bounds.
# Budget strategy: The algorithm uses the full evaluation budget, with no
# early stopping.
# Closest known influences: This algorithm is similar to a simple
# implementation of a (1+1)-Evolutionary Strategy.
# Novelty or unusual aspects: The boundary handling mechanism is a simple
# reflection approach, which may not be optimal for all problems.
# Failure modes: The algorithm may struggle on multimodal or highly
# non-convex functions, as it does not have any explicit mechanisms for
# escaping local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Read the search bounds from the function
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        # Initialize the search with a random solution
        self.best_x = np.random.uniform(self.lower, self.upper, self.dim)
        self.best_y = func(self.best_x)

        # Adaptive step size parameter
        sigma = 1.0

        # Search loop
        for _ in range(self.budget):
            # Generate a new candidate solution
            candidate_x = self.best_x + np.random.normal(0, sigma, self.dim)

            # Reflect the candidate back into the search bounds
            candidate_x = np.clip(candidate_x, self.lower, self.upper)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            # Reduce the step size
            sigma *= 0.999

        return self.best_x, self.best_y
