import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a simple random search algorithm
#          for the GNBG black-box minimization benchmark.
# Search state: The search maintains a single current best candidate solution.
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                      within the search space bounds.
# Selection and replacement: The current best candidate is updated whenever a
#                           better solution is found.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                        sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the search space by updating
#                         the current best candidate whenever a better solution
#                         is found.
# Boundary handling: The algorithm samples candidate solutions uniformly within
#                   the search space bounds, and automatically handles any
#                   out-of-bounds values.
# Budget strategy: The algorithm simply evaluates the maximum number of function
#                 evaluations allowed by the provided budget.
# Closest known influences: This algorithm is a basic random search, which is
#                          a common and simple baseline for black-box
#                          optimization problems.
# Novelty or unusual aspects: There are no particularly novel or unusual aspects
#                            to this implementation.
# Failure modes: The algorithm may struggle to find the global optimum in
#               high-dimensional or multimodal problems, as it has no
#               mechanisms for exploiting problem structure or escaping
#               local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
