import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a randomized search strategy to find the minimum of the objective function within the provided evaluation budget.
# Search state: The search state is represented by a single candidate solution, which is updated iteratively.
# Candidate generation: New candidate solutions are generated by adding Gaussian-distributed random offsets to the current solution.
# Selection and replacement: The new candidate solution replaces the current solution if it has a lower objective function value.
# Adaptation: The step size of the Gaussian offsets is adapted based on the success or failure of the previous step.
# Exploration mechanisms: The algorithm relies on the randomized nature of the Gaussian offsets to explore the search space.
# Exploitation mechanisms: The algorithm focuses the search around the current best solution by adjusting the step size.
# Boundary handling: If a candidate solution falls outside the bounds, it is projected back onto the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget to search for the minimum.
# Closest known influences: This algorithm is similar to a simple stochastic hill-climbing or evolutionary optimization approach.
# Novelty or unusual aspects: The algorithm does not use any advanced techniques and is kept relatively simple.
# Failure modes: The algorithm may struggle to find the global minimum if the objective function is highly multimodal or has narrow, steep minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.y = np.inf
        self.step_size = 1.0

    def __call__(self, func):
        for _ in range(self.budget):
            candidate = self.x + self.step_size * np.random.normal(size=self.dim)
            if hasattr(func, 'bounds'):
                candidate = np.clip(candidate, func.bounds.lb, func.bounds.ub)
            else:
                candidate = np.clip(candidate, func.lower, func.upper)
            candidate_y = func(candidate)
            if candidate_y < self.y:
                self.x = candidate
                self.y = candidate_y
                self.step_size *= 1.1
            else:
                self.step_size *= 0.9
        return self.x, self.y
