import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple implementation of the Nelder-Mead simplex method for
#          unconstrained black-box optimization. It maintains a simplex of points in the
#          search space and iteratively updates the simplex by reflecting, expanding, or
#          contracting the worst point.
# Search state: The search state is represented by the current simplex of points in the
#                search space.
# Candidate generation: New candidate points are generated by reflecting, expanding, or
#                       contracting the worst point in the current simplex.
# Selection and replacement: The new candidate point replaces the worst point in the
#                            current simplex if it has a lower function value.
# Adaptation: The algorithm adapts the size and shape of the simplex based on the
#             function values at the simplex vertices.
# Exploration mechanisms: The algorithm explores the search space by reflecting, expanding,
#                         and contracting the simplex.
# Exploitation mechanisms: The algorithm exploits the search space by shrinking the simplex
#                          around the current best point.
# Boundary handling: The algorithm handles boundary constraints by projecting points that
#                    exceed the bounds back onto the boundary.
# Budget strategy: The algorithm uses the entire evaluation budget, never exceeding it.
# Closest known influences: This algorithm is based on the Nelder-Mead simplex method, a
#                           classic algorithm for unconstrained optimization.
# Novelty or unusual aspects: This implementation is quite compact and simple, while still
#                             being robust across dimensions.
# Failure modes: The algorithm may struggle with highly multimodal or discontinuous
#                objective functions, as the simplex-based approach may get stuck in local
#                minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.bounds.lb, func.bounds.ub, size=(self.dim + 1, self.dim))
        y = [func(x) for x in x0]
        idx = np.argsort(y)
        self.simplex = x0[idx]
        self.function_values = np.array(y)[idx]

        # Main optimization loop
        for _ in range(self.budget):
            # Compute the centroid of the simplex
            centroid = np.mean(self.simplex[:-1], axis=0)

            # Reflect the worst point
            reflected = centroid + (centroid - self.simplex[-1])
            reflected = np.clip(reflected, func.bounds.lb, func.bounds.ub)
            reflected_value = func(reflected)

            if reflected_value < self.function_values[-2]:
                # Expand the simplex
                expanded = centroid + 2 * (reflected - centroid)
                expanded = np.clip(expanded, func.bounds.lb, func.bounds.ub)
                expanded_value = func(expanded)
                if expanded_value < reflected_value:
                    self.simplex[-1] = expanded
                    self.function_values[-1] = expanded_value
                else:
                    self.simplex[-1] = reflected
                    self.function_values[-1] = reflected_value
            elif reflected_value < self.function_values[-1]:
                # Accept the reflection
                self.simplex[-1] = reflected
                self.function_values[-1] = reflected_value
            else:
                # Contract the simplex
                contracted = centroid + 0.5 * (self.simplex[-1] - centroid)
                contracted = np.clip(contracted, func.bounds.lb, func.bounds.ub)
                contracted_value = func(contracted)
                if contracted_value < self.function_values[-1]:
                    self.simplex[-1] = contracted
                    self.function_values[-1] = contracted_value
                else:
                    # Shrink the simplex
                    self.simplex = self.simplex[0] + 0.5 * (self.simplex[1:] - self.simplex[0])
                    self.function_values = [func(x) for x in self.simplex]

            # Update the best solution
            idx = np.argsort(self.function_values)
            self.simplex = self.simplex[idx]
            self.function_values = self.function_values[idx]
            if self.function_values[0] < self.best_y:
                self.best_x = self.simplex[0]
                self.best_y = self.function_values[0]

        return self.best_x, self.best_y
