import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact and robust implementation of a randomized search
#          algorithm for black-box optimization problems. It uses a simple
#          random sampling approach to explore the search space, with some
#          basic mechanisms to encourage exploration and handle search
#          boundaries.
# Search state: The search state is kept minimal, consisting only of the
#          current best solution found so far. The search does not maintain
#          any additional state, such as a population of candidate solutions.
# Candidate generation: Candidate solutions are generated by sampling random
#          points within the search bounds.
# Selection and replacement: The best candidate solution found so far is
#          updated after each function evaluation.
# Adaptation: The algorithm does not adapt its search parameters or strategies
#          during the optimization process.
# Exploration mechanisms: Exploration is encouraged by generating random
#          samples across the entire search space.
# Exploitation mechanisms: The algorithm focuses on exploitation by keeping
#          track of the best solution found so far and using that as the
#          starting point for further search.
# Boundary handling: Candidate solutions that fall outside the search bounds
#          are automatically adjusted to the nearest valid point within the
#          bounds.
# Budget strategy: The algorithm will not exceed the provided evaluation
#          budget, and will return the best solution found within the budget.
# Closest known influences: This implementation is inspired by simple random
#          search algorithms, such as Pure Random Search (PRS) and Uniform
#          Random Search (URS).
# Novelty or unusual aspects: The algorithm is designed to be particularly
#          compact and robust, with a minimal set of features and no
#          specialized tuning or adaptation.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#          problems with complex, multimodal objective functions, as its
#          simple random sampling approach may not be able to effectively
#          explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        """
        Minimize the given black-box function `func`.

        Args:
            func (callable): The black-box function to minimize. The function
                should take a numpy array of shape (dim,) as input and return
                a scalar value.

        Returns:
            tuple: The best solution found (best_x, best_y), where best_x is a
                numpy array of shape (dim,) and best_y is a scalar value.
        """
        # Read the search bounds from the function
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            bounds = np.column_stack((func.lower, func.upper))
        elif hasattr(func, 'bounds'):
            bounds = np.array([func.bounds.lb, func.bounds.ub]).T
        else:
            raise ValueError('Could not determine the search bounds')

        # Optimize the function
        for _ in range(self.budget):
            # Generate a random candidate solution
            x = np.random.uniform(bounds[:, 0], bounds[:, 1], size=self.dim)

            # Evaluate the function
            y = func(x)

            # Update the best solution found so far
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
