import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a simple
#          randomized search algorithm for black-box optimization. It uses a
#          random sampling approach to explore the search space and gradually
#          improve the best solution found.
# Search state: The algorithm maintains a single best solution, represented by
#               the current best x and y values.
# Candidate generation: New candidate solutions are generated by sampling
#                       uniformly from the search space defined by the problem
#                       bounds.
# Selection and replacement: The new candidate solution replaces the current
#                            best solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The uniform random sampling provides exploration of
#                         the search space.
# Exploitation mechanisms: The replacement of the best solution with better
#                          candidates provides a simple exploitation mechanism.
# Boundary handling: The algorithm checks the bounds of the search space and
#                    rejects any candidate solutions that fall outside the
#                    bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to perform
#                  as many function evaluations as possible.
# Closest known influences: This algorithm is a simple, generic randomized
#                           search approach, similar to random search or
#                           random restart hill climbing.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust,
#                             and easy to understand, without any advanced
#                             mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex, multi-modal landscapes, as it relies
#                solely on random sampling without any more sophisticated
#                search strategies.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Read bounds from the function
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        # Perform random search within the budget
        for _ in range(self.budget):
            x = np.random.uniform(self.lower, self.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
