import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that samples points
#          uniformly within the given bounds and keeps track of the best
#          solution found so far.
# Search state: The search state consists of the best solution found so far,
#               represented by the best_x and best_y variables.
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the given bounds.
# Selection and replacement: The best candidate found so far is always kept.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: Exploration is achieved through the uniform random
#                         sampling of points within the given bounds.
# Exploitation mechanisms: There are no dedicated exploitation mechanisms in
#                          this algorithm.
# Boundary handling: Boundary handling is not required, as the algorithm
#                    samples points directly within the given bounds.
# Budget strategy: The algorithm uses the entire evaluation budget, sampling
#                  as many points as possible within the given budget.
# Closest known influences: This algorithm is a simple baseline, similar to a
#                           pure random search.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex, multimodal objective functions, as it
#                has no dedicated exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
