import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized hill-climbing algorithm for
#          the GNBG black-box minimization benchmark. It uses a Gaussian sampling process
#          to generate candidate solutions, and a deterministic selection mechanism to
#          choose the best candidate at each step.
# Search state: The algorithm maintains the current best solution (best_x, best_y) and
#               the evaluation budget remaining.
# Candidate generation: Candidates are generated by adding Gaussian noise to the current
#                       best solution, with the standard deviation decreasing as the
#                       budget is consumed.
# Selection and replacement: The best candidate solution is selected and becomes the
#                            new current best if it improves on the previous best.
# Adaptation: The standard deviation of the Gaussian noise decreases linearly with the
#             remaining evaluation budget.
# Exploration mechanisms: The Gaussian sampling process provides a balance of exploration
#                         and exploitation, with more exploration early on and more
#                         exploitation towards the end of the budget.
# Exploitation mechanisms: The deterministic selection of the best candidate solution
#                          at each step focuses the search on promising regions of the
#                          search space.
# Boundary handling: The algorithm ensures that candidate solutions always remain within
#                    the provided bounds, by clipping values that exceed the bounds.
# Budget strategy: The algorithm consumes the evaluation budget linearly, decreasing the
#                  standard deviation of the Gaussian noise as the budget is consumed.
# Closest known influences: This algorithm is inspired by classic randomized hill-climbing
#                           techniques, with some similarities to Simulated Annealing.
# Novelty or unusual aspects: The compact, self-contained nature of the implementation,
#                             and the way it handles the decreasing standard deviation
#                             and budget consumption, are somewhat unusual aspects.
# Failure modes: The algorithm may struggle in high-dimensional problems with complex
#                multi-modal landscapes, as the Gaussian sampling process may not be
#                able to effectively explore the search space in those cases.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = float('inf')

    def __call__(self, func):
        # Read bounds from the function
        self.lb = func.lower if hasattr(func, 'lower') else func.bounds.lb
        self.ub = func.upper if hasattr(func, 'upper') else func.bounds.ub

        # Initialize the search
        self.x = np.random.uniform(self.lb, self.ub, self.dim)
        self.y = func(self.x)
        self.best_x = self.x.copy()
        self.best_y = self.y

        # Run the search
        while self.budget > 0:
            # Generate a new candidate solution
            std = self.budget / self.budget  # Decrease std dev linearly with budget
            self.x = self.best_x + np.random.normal(0, std, self.dim)
            self.x = np.clip(self.x, self.lb, self.ub)  # Ensure feasibility
            self.y = func(self.x)

            # Update the best solution if the new candidate is better
            if self.y < self.best_y:
                self.best_x = self.x.copy()
                self.best_y = self.y

            self.budget -= 1

        return self.best_x, self.best_y
