import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized search algorithm for black-box
#          minimization problems, using the standard Python library and NumPy.
# Search state: The algorithm maintains a single candidate solution, and generates new
#               candidates by perturbing the current one.
# Candidate generation: New candidates are generated by adding Gaussian noise to the current
#                      solution, with a dynamically adjusted step size.
# Selection and replacement: The new candidate replaces the current solution if it has a
#                           lower objective function value.
# Adaptation: The step size for generating new candidates is adjusted based on the
#             progress of the search, becoming smaller as the optimum is approached.
# Exploration mechanisms: The initial step size and the amount of Gaussian noise are
#                        the main exploration mechanisms.
# Exploitation mechanisms: The algorithm focuses the search around the current best
#                         solution, with the step size decreasing over time.
# Boundary handling: The algorithm ensures that new candidates stay within the
#                   feasible region defined by the problem bounds.
# Budget strategy: The algorithm uses the entire evaluation budget, without any
#                  explicit budget management.
# Closest known influences: This algorithm is similar to a basic random search or
#                          stochastic hill-climbing approach.
# Novelty or unusual aspects: The dynamic step size adjustment is a relatively
#                            simple but effective adaptation mechanism.
# Failure modes: The algorithm may struggle to escape local optima, especially in
#                high-dimensional problems with complex landscapes.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.step_size = 1.0

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Initialize current solution
        x = np.random.uniform(self.lb, self.ub, size=self.dim)
        y = func(x)
        self.best_x, self.best_y = x, y

        # Optimize within the budget
        for _ in range(self.budget):
            # Generate a new candidate
            new_x = x + self.step_size * np.random.normal(size=self.dim)
            new_x = np.clip(new_x, self.lb, self.ub)
            new_y = func(new_x)

            # Update the best solution
            if new_y < self.best_y:
                self.best_x, self.best_y = new_x, new_y
                x, y = new_x, new_y

            # Adapt the step size
            self.step_size *= 0.999

        return self.best_x, self.best_y
