import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search implementation that samples points
#          from the feasible region uniformly at random and keeps track of the
#          best solution found so far.
# Search state: The search state consists of the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling points from the feasible
#                       region uniformly at random.
# Selection and replacement: The best solution found so far is always maintained.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling points
#                         uniformly at random.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          returning it as the final result.
# Boundary handling: Boundary handling is performed by sampling points that are
#                    guaranteed to be within the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget to sample as
#                  many points as possible.
# Closest known influences: This algorithm is a basic random search approach, which
#                          is a common baseline for comparison in optimization
#                          problems.
# Novelty or unusual aspects: This algorithm does not have any novel or unusual
#                            aspects and is a straightforward implementation of
#                            random search.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with a complex objective function landscape, as it
#                does not have any sophisticated exploration or exploitation
#                mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        num_evals = 0
        while num_evals < self.budget:
            # Sample a point from the feasible region
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            num_evals += 1

            # Update the best solution if necessary
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
