import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple randomized search algorithm
#          to minimize the provided objective function.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                       within the given bounds.
# Selection and replacement: If a new candidate solution has a lower objective
#                            value than the current best, it replaces the best.
# Adaptation: There is no adaptation; the search is entirely randomized.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         new random candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          replacing it with better candidates.
# Boundary handling: Candidate solutions that fall outside the given bounds are
#                    simply discarded and a new candidate is generated.
# Budget strategy: The algorithm uses the entire evaluation budget, generating
#                  as many candidate solutions as possible within the budget.
# Closest known influences: This implementation is a simple, pure random search
#                           algorithm without any advanced features.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             implementation.
# Failure modes: The algorithm may struggle on highly multimodal, deceptive,
#                or high-dimensional problems where pure random search is
#                ineffective.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
