import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that samples points
#          within the provided bounds and keeps track of the best point found so far.
# Search state: The algorithm maintains the current best point and its corresponding
#               function value.
# Candidate generation: Candidates are generated by sampling points uniformly within
#                       the provided bounds.
# Selection and replacement: The current best point is replaced if a better point is found.
# Adaptation: The algorithm does not adapt its search strategy during the optimization.
# Exploration mechanisms: The algorithm explores the search space by sampling points
#                         uniformly within the provided bounds.
# Exploitation mechanisms: The algorithm does not have any explicit exploitation mechanisms.
# Boundary handling: The algorithm handles boundary constraints by generating candidates
#                    within the provided bounds.
# Budget strategy: The algorithm uses the entire evaluation budget during the optimization.
# Closest known influences: This algorithm is a basic random search algorithm, which is a
#                           common baseline for black-box optimization problems.
# Novelty or unusual aspects: The algorithm is simple and straightforward, with no
#                             unusual aspects.
# Failure modes: The algorithm may struggle on problems with complex objective functions
#                or high-dimensional search spaces, as it lacks more advanced search
#                mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            lower, upper = func.bounds.lb, func.bounds.ub
        else:
            lower, upper = func.lower, func.upper

        # Optimize
        for _ in range(self.budget):
            # Generate a candidate solution
            x = np.random.uniform(lower, upper, size=self.dim)

            # Evaluate the candidate
            y = func(x)

            # Update the best solution
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
