import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a Gaussian Sampling Algorithm (GSA) to perform the black-box minimization task.
# Search state: The search state is represented by a population of candidate solutions, each with an associated function value.
# Candidate generation: New candidates are generated by sampling from a Gaussian distribution centered on the current best solution, with a decreasing standard deviation over time.
# Selection and replacement: The best candidate from the current population is selected to be the new best solution. The population is then updated by replacing the worst candidate with the new best solution.
# Adaptation: The standard deviation of the Gaussian distribution used to generate new candidates decreases over time, allowing for more exploitation of the search space as the algorithm progresses.
# Exploration mechanisms: The initial standard deviation of the Gaussian distribution allows for broad exploration of the search space, while the decreasing standard deviation over time encourages exploitation of promising regions.
# Exploitation mechanisms: The selection of the best candidate from the current population and the replacement of the worst candidate with the new best solution allows the algorithm to exploit promising regions of the search space.
# Boundary handling: If a generated candidate solution falls outside the specified bounds, it is projected back into the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget provided, with no early stopping.
# Closest known influences: The Gaussian Sampling Algorithm (GSA) is inspired by evolution strategies and other population-based optimization methods.
# Novelty or unusual aspects: The use of a Gaussian distribution for candidate generation and the decreasing standard deviation over time are common features of evolution strategies, but the specific implementation and parameter choices may be novel.
# Failure modes: The algorithm may struggle in highly multimodal or deceptive landscapes, where the Gaussian sampling approach may not be able to efficiently explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 10
        self.init_sigma = 1.0
        self.sigma_decay = 0.99

        # Initialize the population
        self.population = np.random.uniform(low=-5, high=5, size=(self.population_size, self.dim))
        self.function_values = np.inf * np.ones(self.population_size)

    def __call__(self, func):
        # Get the function bounds
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Optimize
        for _ in range(self.budget):
            # Generate new candidates
            new_candidates = self.population[np.argmin(self.function_values)] + self.init_sigma * np.random.normal(size=(self.population_size, self.dim))

            # Evaluate the new candidates
            new_function_values = np.array([func(x) for x in new_candidates])

            # Update the population
            worst_idx = np.argmax(self.function_values)
            self.population[worst_idx] = new_candidates[np.argmin(new_function_values)]
            self.function_values[worst_idx] = np.min(new_function_values)

            # Decay the standard deviation
            self.init_sigma *= self.sigma_decay

        # Return the best solution found
        best_idx = np.argmin(self.function_values)
        best_x = self.population[best_idx]
        best_y = self.function_values[best_idx]
        return best_x, best_y
