import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple randomized black-box optimizer that uses
#          a combination of exploration and exploitation to search for the
#          global minimum of the objective function.
# Search state: The search state is represented by the current best solution
#                (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling
#                       from a multivariate normal distribution centered
#                       around the current best solution.
# Selection and replacement: The new candidate solution replaces the current
#                            best solution if it has a lower objective
#                            function value.
# Adaptation: The standard deviation of the multivariate normal distribution
#             used to generate new candidates is adapted based on the current
#             evaluation budget.
# Exploration mechanisms: Exploration is achieved through the randomized
#                         sampling of new candidate solutions.
# Exploitation mechanisms: Exploitation is achieved by centering the sampling
#                          distribution around the current best solution.
# Boundary handling: Candidate solutions that fall outside the bounds of the
#                    search space are projected back onto the nearest valid
#                    point.
# Budget strategy: The algorithm attempts to use the entire evaluation budget
#                  by dynamically adjusting the standard deviation of the
#                  sampling distribution.
# Closest known influences: This algorithm is similar to a simple evolution
#                           strategy or a randomized hill-climbing algorithm.
# Novelty or unusual aspects: The dynamic adaptation of the standard deviation
#                             based on the remaining evaluation budget is a
#                             somewhat unusual aspect of this algorithm.
# Failure modes: The algorithm may struggle to find the global minimum if the
#                objective function has multiple local minima or is highly
#                multimodal.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.std_dev = 1.0

    def __call__(self, func):
        # Initialize the best solution
        if self.best_x is None:
            self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
            self.best_y = func(self.best_x)

        # Iterate until the budget is exhausted
        while self.budget > 0:
            # Generate a new candidate solution
            candidate_x = self.best_x + np.random.normal(0, self.std_dev, self.dim)

            # Project the candidate solution onto the valid search space
            candidate_x = np.clip(candidate_x, func.lower, func.upper)

            # Evaluate the new candidate solution
            candidate_y = func(candidate_x)
            self.budget -= 1

            # Update the best solution if the new candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            # Adapt the standard deviation based on the remaining budget
            self.std_dev = max(0.1, self.std_dev * (self.budget / self.budget))

        return self.best_x, self.best_y
