import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm implements a compact, randomized search strategy for
#          black-box optimization problems. It uses a simple gradient-free
#          approach to explore the search space, with randomized candidate
#          generation and selection.
# Search state: The algorithm maintains a single candidate solution,
#               representing the current best point found so far.
# Candidate generation: New candidate solutions are generated by adding
#                       a random perturbation to the current best point.
#                       The perturbation magnitude is adapted based on the
#                       search progress.
# Selection and replacement: The new candidate is accepted if it improves
#                            on the current best solution.
# Adaptation: The perturbation magnitude is adjusted using a simple
#             1/sqrt(iteration) schedule, to balance exploration and
#             exploitation over the course of the optimization.
# Exploration mechanisms: The randomized candidate generation provides
#                         a simple exploration mechanism, allowing the
#                         algorithm to search broadly across the feasible
#                         region.
# Exploitation mechanisms: The selection of improved candidates and the
#                          adaptive perturbation magnitude allow the
#                          algorithm to focus search effort on promising
#                          regions of the search space.
# Boundary handling: The algorithm ensures that candidate solutions
#                    remain within the feasible region by clamping
#                    out-of-bounds values to the nearest valid bound.
# Budget strategy: The algorithm aims to use the full evaluation budget
#                  by adaptively scaling the perturbation magnitude.
# Closest known influences: This algorithm draws inspiration from
#                           randomized gradient-free optimization
#                           methods, such as direct search and
#                           evolutionary algorithms.
# Novelty or unusual aspects: The compact, self-contained nature of
#                            the implementation is somewhat unusual
#                            for black-box optimization algorithms.
# Failure modes: The algorithm may struggle with highly multimodal
#                or deceptive objective functions, where the simple
#                gradient-free approach may not be able to efficiently
#                locate the global optimum.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.f = np.inf
        self.iter = 0
        self.step_size = 1.0

    def __call__(self, func):
        bounds = (func.lower, func.upper) if hasattr(func, 'lower') else func.bounds
        while self.iter < self.budget:
            self.iter += 1
            candidate = self.x + self.step_size * np.random.normal(size=self.dim)
            candidate = np.clip(candidate, bounds[0], bounds[1])
            candidate_f = func(candidate)
            if candidate_f < self.f:
                self.x = candidate
                self.f = candidate_f
            self.step_size = 1.0 / np.sqrt(self.iter)
        return self.x, self.f
