import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search with uniform sampling within the
#          given bounds to find the minimum of the objective function.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidates are generated by sampling uniformly within the
#                       given bounds.
# Selection and replacement: The best candidate found so far is always kept as the current
#                            best solution.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by uniformly sampling
#                         new candidates within the given bounds.
# Exploitation mechanisms: There is no explicit exploitation mechanism in this algorithm.
#                          The best solution found so far is used as the result.
# Boundary handling: The algorithm ensures that all candidates are within the given bounds
#                    by clamping the values to the bounds if necessary.
# Budget strategy: The algorithm uses the entire evaluation budget to perform the random
#                  search.
# Closest known influences: This algorithm is a simple, baseline random search method.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may struggle to find the global optimum, especially in
#                high-dimensional problems or problems with complex, multi-modal
#                landscapes.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
