import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search approach to minimize the given objective function. It generates new candidate solutions by sampling from a uniform distribution within the specified bounds, and selects the best solution found within the given evaluation budget.
# Search state: The algorithm maintains the current best solution (best_x, best_y) found so far.
# Candidate generation: New candidate solutions are generated by sampling from a uniform distribution within the specified bounds.
# Selection and replacement: The algorithm compares the objective value of the new candidate solution with the current best solution, and updates the best solution if the new one is better.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The random sampling of new candidate solutions provides exploration of the search space.
# Exploitation mechanisms: The algorithm selects the best solution found so far, which provides a form of exploitation.
# Boundary handling: The algorithm ensures that the generated candidate solutions are within the specified bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to search for the best solution.
# Closest known influences: This algorithm is a simple implementation of a random search method, which is a common baseline approach for black-box optimization problems.
# Novelty or unusual aspects: The algorithm does not have any novel or unusual aspects, as it is a straightforward implementation of a random search method.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional problems or problems with complex landscapes, as it relies solely on random sampling without any additional mechanisms to guide the search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the objective function
            y = func(x)

            # Update the best solution if the new one is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
