import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a Nelder-Mead simplex algorithm for
#          black-box optimization. It constructs a simplex in the search space,
#          and iteratively reflects, expands, contracts, or shrinks the simplex
#          to find the optimum.
# Search state: The search state is represented by the simplex, which is a set
#                of N+1 points in the N-dimensional search space, where N is the
#                dimensionality of the problem.
# Candidate generation: New candidate points are generated by reflecting,
#                       expanding, contracting, or shrinking the current simplex.
# Selection and replacement: The best point in the current simplex is selected
#                            as the next iterate. The worst point is replaced
#                            by the new candidate.
# Adaptation: The size and shape of the simplex adapts based on the function
#             values at the vertices, using standard Nelder-Mead update rules.
# Exploration mechanisms: The simplex exploration is driven by the reflection,
#                         expansion, and contraction operations, which allow the
#                         algorithm to traverse the search space.
# Exploitation mechanisms: The shrinkage operation allows the algorithm to
#                          focus in on promising regions of the search space.
# Boundary handling: Boundary violations are handled by clamping the out-of-bounds
#                    coordinates to the feasible range.
# Budget strategy: The algorithm consumes one function evaluation per iteration,
#                  and terminates when the budget is exhausted.
# Closest known influences: This implementation is based on the standard Nelder-Mead
#                           simplex algorithm, which is a well-known derivative-free
#                           optimization method.
# Novelty or unusual aspects: The compactness and simplicity of the implementation
#                             is unusual for a black-box optimization algorithm.
# Failure modes: The algorithm may struggle with highly multimodal or discontinuous
#                objective functions, as it relies on the simplex shape to guide the
#                search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x0 = np.random.uniform(func.lower, func.upper, size=self.dim)
        simplex = [x0]
        for i in range(self.dim):
            x = x0.copy()
            x[i] += 0.05 * (func.upper[i] - func.lower[i])
            simplex.append(x)

        # Evaluate the initial simplex
        for x in simplex:
            self.evaluations += 1
            if self.evaluations > self.budget:
                break

        # Optimization loop
        while self.evaluations <= self.budget:
            # Order the simplex
            simplex = sorted(simplex, key=lambda x: func(x))
            best_x, best_y = simplex[0], func(simplex[0])

            # Reflection
            xr = simplex[0] + 1.0 * (simplex[0] - simplex[-1])
            xr = np.clip(xr, func.lower, func.upper)
            yr = func(xr)
            self.evaluations += 1
            if yr < best_y:
                # Expansion
                xe = simplex[0] + 2.0 * (xr - simplex[0])
                xe = np.clip(xe, func.lower, func.upper)
                ye = func(xe)
                self.evaluations += 1
                if ye < yr:
                    simplex[-1] = xe
                else:
                    simplex[-1] = xr
            else:
                if yr < func(simplex[-1]):
                    # Accepted reflection
                    simplex[-1] = xr
                else:
                    # Contraction
                    xc = simplex[0] + 0.5 * (simplex[-1] - simplex[0])
                    xc = np.clip(xc, func.lower, func.upper)
                    yc = func(xc)
                    self.evaluations += 1
                    if yc < func(simplex[-1]):
                        simplex[-1] = xc
                    else:
                        # Shrink
                        for i in range(1, len(simplex)):
                            simplex[i] = simplex[0] + 0.5 * (simplex[i] - simplex[0])
                            self.evaluations += 1

        return best_x, best_y
