import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, robust, and easy-to-understand implementation of a global black-box optimization algorithm. It uses a combination of random search and gradient-based local search to efficiently explore the search space and find the global minimum.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling from a multivariate normal distribution centered around the current best solution, with a covariance matrix that adapts to the scaling of the problem.
# Selection and replacement: The new candidate solution is compared to the current best solution, and replaces it if the new solution is better.
# Adaptation: The covariance matrix of the multivariate normal distribution is adapted based on the success or failure of the previous candidate solutions.
# Exploration mechanisms: The algorithm uses a combination of random search and gradient-based local search to explore the search space. The random search component ensures that the algorithm can escape from local minima, while the gradient-based local search component helps to refine the search around promising regions.
# Exploitation mechanisms: The algorithm focuses its search around the current best solution, by sampling new candidates from a multivariate normal distribution centered on the best solution.
# Boundary handling: The algorithm ensures that the new candidate solutions are within the bounds of the search space by projecting any out-of-bounds solutions onto the boundary.
# Budget strategy: The algorithm continuously updates the best solution found so far, and returns the best solution when the evaluation budget is exhausted.
# Closest known influences: This algorithm is inspired by the CMA-ES (Covariance Matrix Adaptation Evolution Strategy) algorithm, which is a widely used global optimization algorithm.
# Novelty or unusual aspects: The algorithm uses a simple and compact implementation, without any external dependencies beyond the Python standard library and NumPy.
# Failure modes: The algorithm may struggle to optimize functions with very complex, multi-modal, or highly deceptive landscapes, where the random search and gradient-based local search components may not be sufficient to find the global minimum.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.cov = np.eye(dim)
        self.step_size = 1.0

    def __call__(self, func):
        evaluations = 0
        while evaluations < self.budget:
            # Generate a new candidate solution
            candidate = self.best_x + self.step_size * np.random.multivariate_normal(np.zeros(self.dim), self.cov) if self.best_x is not None else np.random.uniform(func.bounds.lb, func.bounds.ub)

            # Evaluate the candidate solution
            candidate_y = func(candidate)
            evaluations += 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            # Adapt the step size and covariance matrix
            self.step_size *= np.exp(0.1 * (candidate_y - self.best_y) / self.best_y)
            self.cov = (1 - 1 / self.dim) * self.cov + (1 / self.dim) * np.outer(candidate - self.best_x, candidate - self.best_x)

        return self.best_x, self.best_y
