import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the search space and keeps track of the best solution found so far.
# Search state: The search state consists of the current best solution (best_x, best_y) and the remaining evaluation budget.
# Candidate generation: Candidates are generated by sampling points uniformly within the search space.
# Selection and replacement: The best candidate found so far is always kept, and the best solution is updated whenever a better candidate is found.
# Adaptation: There is no adaptation mechanism in this algorithm, as it is a simple random search.
# Exploration mechanisms: The algorithm explores the search space by sampling points uniformly.
# Exploitation mechanisms: The algorithm exploits the current best solution by biasing the sampling towards that region, but only implicitly through the random sampling.
# Boundary handling: Boundary handling is performed by clamping the sampled points to the search space bounds.
# Budget strategy: The algorithm uses the full evaluation budget, without any specific strategy.
# Closest known influences: This algorithm is a basic random search, which is a well-known baseline for black-box optimization.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm, as it is a simple and common approach to black-box optimization.
# Failure modes: The algorithm may struggle on high-dimensional problems or problems with highly multimodal or rugged landscapes, as it has no mechanism to efficiently explore or exploit the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
