import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that uniformly samples the search space
#          and keeps track of the best solution found so far.
# Search state: The algorithm maintains the best solution found so far, represented by
#               the best_x and best_y variables.
# Candidate generation: Candidates are generated by uniformly sampling the search space
#                       within the given bounds.
# Selection and replacement: The best candidate solution is compared to the current
#                            best solution, and the better one is kept.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by uniformly sampling
#                         new candidate solutions.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in this
#                          algorithm. The best solution found so far is used as the
#                          final result.
# Boundary handling: Candidate solutions that fall outside the search space bounds
#                    are discarded and a new candidate is generated.
# Budget strategy: The algorithm strictly adheres to the provided evaluation budget
#                  and does not exceed it.
# Closest known influences: This algorithm is a basic random search approach, which
#                           is a simple and robust optimization technique.
# Novelty or unusual aspects: This implementation is designed to be compact, readable,
#                             and robust across dimensions, while fulfilling the
#                             specified public interface requirements.
# Failure modes: The algorithm may struggle to find the global optimum in highly
#                multimodal or high-dimensional problems, as it relies solely on
#                random sampling without any advanced exploration or exploitation
#                mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
