import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates new candidate solutions
# by sampling from a uniform distribution within the given bounds. The best solution found
# so far is kept and returned at the end of the search.
# Search state: The algorithm keeps track of the best solution found so far, including
# the decision variables (best_x) and the corresponding objective function value (best_y).
# Candidate generation: New candidate solutions are generated by sampling from a uniform
# distribution within the given bounds for each decision variable.
# Selection and replacement: The best solution found so far is always kept and replaced
# only if a better solution is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling
# new candidate solutions within the given bounds.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in this algorithm.
# Boundary handling: The algorithm samples new candidate solutions within the given
# bounds, so no special boundary handling is required.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This algorithm is a simple random search, which is a common
# baseline for black-box optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may fail to find the global optimum if the evaluation
# budget is not sufficient, or if the objective function has multiple local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = np.inf

    def __call__(self, func):
        used_budget = 0
        while used_budget < self.budget:
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            used_budget += 1

            # Update the best solution if the new solution is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
