import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a multivariate normal distribution to sample
#          candidate solutions, and updates the mean and covariance of the
#          distribution based on the performance of the sampled solutions.
# Search state: The search state is represented by the mean and covariance of
#               the multivariate normal distribution used to sample candidates.
# Candidate generation: Candidates are generated by sampling from the
#                       multivariate normal distribution.
# Selection and replacement: The best candidate solution is selected and
#                            replaces the current mean of the distribution.
# Adaptation: The mean and covariance of the distribution are updated based
#             on the performance of the sampled candidates.
# Exploration mechanisms: The exploration is controlled by the covariance of
#                         the multivariate normal distribution.
# Exploitation mechanisms: The exploitation is controlled by the mean of the
#                          multivariate normal distribution.
# Boundary handling: Candidates that fall outside the search bounds are
#                    rejected and a new candidate is sampled.
# Budget strategy: The algorithm uses the entire evaluation budget to sample
#                  and update the search distribution.
# Closest known influences: This algorithm is similar to the Covariance Matrix
#                           Adaptation Evolution Strategy (CMA-ES) algorithm.
# Novelty or unusual aspects: The algorithm does not use any specialized
#                             techniques or modifications, and relies solely
#                             on the standard multivariate normal distribution.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                when the objective function is highly multimodal.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.mean = np.zeros(dim)
        self.cov = np.eye(dim)
        self.evals = 0

    def __call__(self, func):
        best_x = None
        best_y = np.inf

        while self.evals < self.budget:
            # Sample a new candidate solution
            x = np.random.multivariate_normal(self.mean, self.cov)

            # Evaluate the candidate solution
            y = func(x)
            self.evals += 1

            # Update the best solution
            if y < best_y:
                best_x = x
                best_y = y

            # Update the search distribution
            self.mean = (1 - 1 / (self.evals + 1)) * self.mean + x / (self.evals + 1)
            self.cov = (1 - 1 / (self.evals + 1)) * self.cov + np.outer(x - self.mean, x - self.mean) / (self.evals + 1)

        return best_x, best_y
