import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a combination of random sampling and gradient-based optimization
#          to find the minimum of a black-box function within a given budget.
# Search state: The algorithm maintains the current best solution (best_x, best_y) and a population
#               of candidate solutions.
# Candidate generation: New candidates are generated by either random sampling within the bounds
#                       or by perturbing the current best solution using a small gradient step.
# Selection and replacement: At each iteration, the best candidate solution is selected and replaces
#                            the current best solution if it is an improvement.
# Adaptation: The algorithm does not explicitly adapt its parameters during the search.
# Exploration mechanisms: The random sampling of new candidates provides exploration of the search space.
# Exploitation mechanisms: The gradient-based optimization of the best solution provides exploitation
#                          of promising regions of the search space.
# Boundary handling: Candidate solutions that go outside the bounds are projected back onto the
#                    feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget, without early termination.
# Closest known influences: This algorithm combines ideas from random search and gradient-based
#                           optimization, which are common techniques in black-box optimization.
# Novelty or unusual aspects: The combination of random sampling and gradient-based optimization
#                             in a compact implementation for the GNBG benchmark is novel.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with
#                many local minima, as the gradient-based optimization component may get
#                stuck in local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')
        self.population = None

    def __call__(self, func):
        # Initialize the population
        self.population = np.random.uniform(func.lower, func.upper, (10, self.dim))

        # Evaluate the initial population
        population_y = [func(x) for x in self.population]

        # Find the initial best solution
        best_idx = np.argmin(population_y)
        self.best_x = self.population[best_idx]
        self.best_y = population_y[best_idx]

        # Consume the remaining budget
        budget_remaining = self.budget - len(self.population)
        while budget_remaining > 0:
            # Generate new candidates
            new_candidates = self.generate_candidates(func)

            # Evaluate the new candidates
            new_candidate_y = [func(x) for x in new_candidates]

            # Update the best solution
            for x, y in zip(new_candidates, new_candidate_y):
                if y < self.best_y:
                    self.best_x = x
                    self.best_y = y

            # Add the new candidates to the population
            self.population = np.concatenate((self.population, new_candidates), axis=0)

            # Consume the evaluation budget
            budget_remaining -= len(new_candidates)

        return self.best_x, self.best_y

    def generate_candidates(self, func):
        # Generate a mix of random samples and gradient-based candidates
        candidates = []
        for _ in range(10):
            # Random sample
            x = np.random.uniform(func.lower, func.upper)
            candidates.append(x)

            # Gradient-based candidate
            if self.best_x is not None:
                grad = np.random.normal(0, 0.1, self.dim)
                x = self.best_x + 0.1 * grad
                x = np.clip(x, func.lower, func.upper)
                candidates.append(x)

        return candidates
