import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple stochastic search algorithm to
#          minimize the provided black-box function. It maintains a population
#          of candidate solutions and iteratively updates the population by
#          generating new candidates and selecting the best ones.
# Search state: The search state consists of a population of candidate
#               solutions, represented as a 2D numpy array.
# Candidate generation: New candidate solutions are generated by adding
#                       Gaussian noise to the current population.
# Selection and replacement: The population is updated by selecting the best
#                            candidates from the current population and the
#                            newly generated candidates.
# Adaptation: There is no self-adaptation in this implementation.
# Exploration mechanisms: The Gaussian noise added to the population provides
#                         exploration.
# Exploitation mechanisms: The selection of the best candidates from the
#                          population provides exploitation.
# Boundary handling: Candidate solutions that violate the problem bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget to explore
#                  the search space.
# Closest known influences: This implementation is similar to a (1+1)-ES
#                           algorithm, but without self-adaptation.
# Novelty or unusual aspects: The implementation is very compact and uses only
#                             the Python standard library and numpy.
# Failure modes: The algorithm may struggle with highly multimodal or
#                deceptive objective functions, as it does not have any
#                mechanisms to escape local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.population_size = 10
        self.population = np.random.uniform(0, 1, (self.population_size, self.dim))

    def __call__(self, func):
        # Read bounds from the function
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            self.lower = func.lower
            self.upper = func.upper
        elif hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            raise ValueError('Function must have lower/upper or bounds.lb/bounds.ub attributes')

        # Evaluate the initial population
        self.population_values = np.array([func(x) for x in self.population])

        # Main optimization loop
        for _ in range(self.budget):
            # Generate new candidates
            new_candidates = self.population + np.random.normal(0, 0.1, (self.population_size, self.dim))

            # Evaluate new candidates and update the population
            new_values = np.array([func(x) for x in new_candidates])
            all_values = np.concatenate([self.population_values, new_values])
            all_candidates = np.concatenate([self.population, new_candidates])
            sorted_indices = np.argsort(all_values)
            self.population = all_candidates[sorted_indices[:self.population_size]]
            self.population_values = all_values[sorted_indices[:self.population_size]]

            # Clip population to bounds
            self.population = np.maximum(self.lower, np.minimum(self.upper, self.population))

        # Return the best solution
        best_index = np.argmin(self.population_values)
        best_x = self.population[best_index]
        best_y = self.population_values[best_index]
        return best_x, best_y
