import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a hybrid approach combining a random search with a
#          gradient-based optimization. It starts by generating a set of random
#          candidate solutions, then iteratively refines the best solution using
#          gradient information.
# Search state: The algorithm maintains the current best solution and its
#               objective function value.
# Candidate generation: Initial candidates are generated randomly within the
#                       problem bounds. Subsequent candidates are generated by
#                       perturbing the current best solution using a gradient
#                       update.
# Selection and replacement: The best candidate solution is always selected to
#                            replace the current best solution.
# Adaptation: The step size for the gradient update is adapted based on the
#             progress of the optimization.
# Exploration mechanisms: The random initial candidates provide exploration of
#                         the search space.
# Exploitation mechanisms: The gradient-based refinement of the best solution
#                          provides exploitation of promising regions.
# Boundary handling: Candidate solutions that violate the problem bounds are
#                    projected back into the feasible region.
# Budget strategy: The algorithm uses the full evaluation budget, attempting to
#                  make the most progress possible within the given budget.
# Closest known influences: This algorithm combines elements of random search
#                          and gradient-based optimization, which are commonly
#                          used techniques in black-box optimization.
# Novelty or unusual aspects: The adaptive step size for the gradient update is
#                             a novel aspect that may help the algorithm perform
#                             well across different problem instances.
# Failure modes: The algorithm may struggle in cases where the objective function
#                is highly multimodal or non-differentiable, as the gradient-based
#                refinement may get stuck in local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')
        self.step_size = 0.1

    def __call__(self, func):
        # Read problem bounds
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper

        # Generate initial random candidates
        x = np.random.uniform(lb, ub, (self.budget, self.dim))
        y = np.array([func(xi) for xi in x])
        self.best_x = x[np.argmin(y)]
        self.best_y = np.min(y)

        # Refine the best solution using gradient information
        for _ in range(self.budget):
            # Compute the gradient
            grad = np.zeros(self.dim)
            for i in range(self.dim):
                x_plus = self.best_x.copy()
                x_plus[i] += 1e-6
                x_minus = self.best_x.copy()
                x_minus[i] -= 1e-6
                grad[i] = (func(x_plus) - func(x_minus)) / (2e-6)

            # Update the best solution
            new_x = self.best_x - self.step_size * grad
            new_x = np.clip(new_x, lb, ub)
            new_y = func(new_x)
            if new_y < self.best_y:
                self.best_x = new_x
                self.best_y = new_y

            # Adapt the step size
            self.step_size *= 0.99

        return self.best_x, self.best_y
