import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple genetic algorithm implementation for the GNBG black-box minimization benchmark.
# Search state: The search state is represented by a population of candidate solutions, where each solution is a vector of real-valued parameters.
# Candidate generation: New candidate solutions are generated by applying mutation and crossover operators to the current population.
# Selection and replacement: The best candidates are selected for the next generation based on their objective function values. The population size is kept constant.
# Adaptation: The mutation step size is adapted based on the progress of the search.
# Exploration mechanisms: Mutation introduces randomness to explore the search space.
# Exploitation mechanisms: Crossover combines successful candidates to exploit promising regions of the search space.
# Boundary handling: Candidate solutions that violate the bounds are projected back into the feasible region.
# Budget strategy: The algorithm runs for the provided budget of function evaluations.
# Closest known influences: This implementation is based on standard genetic algorithm principles, with some adaptations for the black-box optimization setting.
# Novelty or unusual aspects: The algorithm does not require any problem-specific information or tuning, making it a general-purpose optimization method.
# Failure modes: The algorithm may struggle with highly multimodal or deceptive objective functions, as it relies on a relatively simple exploration-exploitation balance.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.pop_size = 20
        self.mut_scale = 0.1
        self.cross_prob = 0.5

    def __call__(self, func):
        # Initialize population
        lb = getattr(func, 'lower', func.bounds.lb)
        ub = getattr(func, 'upper', func.bounds.ub)
        self.pop = lb + (ub - lb) * np.random.rand(self.pop_size, self.dim)
        self.fit = [func(x) for x in self.pop]
        self.best_x, self.best_y = self.pop[np.argmin(self.fit)], min(self.fit)
        self.evaluations = self.pop_size

        # Optimize
        while self.evaluations < self.budget:
            # Select parents
            parents = np.random.choice(self.pop_size, size=(self.pop_size, 2), replace=True)

            # Apply crossover
            offspring = []
            for p1, p2 in parents:
                child = self.pop[p1].copy()
                mask = np.random.rand(self.dim) < self.cross_prob
                child[mask] = self.pop[p2][mask]
                offspring.append(child)

            # Apply mutation
            offspring = np.array(offspring)
            offspring += self.mut_scale * np.random.randn(*offspring.shape)

            # Bound handling
            offspring = np.clip(offspring, lb, ub)

            # Evaluate offspring
            off_fit = [func(x) for x in offspring]
            self.evaluations += len(offspring)

            # Select survivors
            self.pop = np.concatenate([self.pop, offspring])
            self.fit = self.fit + off_fit
            self.pop = self.pop[np.argsort(self.fit)[:self.pop_size]]
            self.fit = [self.fit[i] for i in np.argsort(self.fit)[:self.pop_size]]

            # Update best
            self.best_x = self.pop[0]
            self.best_y = self.fit[0]

            # Adapt mutation step size
            self.mut_scale *= 0.99

        return self.best_x, self.best_y
