import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact, robust implementation of a derivative-free
#          optimization algorithm for the GNBG black-box minimization benchmark.
#          It uses a random search approach with adaptive step sizes.
# Search state: The search state is represented by the current best solution (best_x)
#               and its corresponding objective function value (best_y).
# Candidate generation: New candidate solutions are generated by adding Gaussian
#                       noise to the current best solution, with the standard
#                       deviation of the noise adaptively adjusted based on the
#                       search progress.
# Selection and replacement: The new candidate solution replaces the current best
#                            solution if it has a lower objective function value.
# Adaptation: The standard deviation of the Gaussian noise is adapted based on the
#             ratio of successful versus total candidate evaluations.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         new candidate solutions using Gaussian noise.
# Exploitation mechanisms: The algorithm exploits the search space by focusing the
#                          search around the current best solution.
# Boundary handling: Candidate solutions that fall outside the search space bounds
#                    are projected back onto the boundary.
# Budget strategy: The algorithm aims to never exceed the provided evaluation
#                  budget.
# Closest known influences: The algorithm is inspired by simple randomized search
#                           techniques, such as those used in evolution strategies.
# Novelty or unusual aspects: The adaptive step size mechanism is a relatively
#                             straightforward but effective way to balance
#                             exploration and exploitation.
# Failure modes: The algorithm may struggle to efficiently optimize highly
#                multimodal or deceptive functions, as it relies on a simple
#                random search approach.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.success_count = 0
        self.step_size = 1.0

    def __call__(self, func):
        # Read the bounds from the function object
        if hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            self.lower = func.lower
            self.upper = func.upper

        # Initialize the search state
        self.best_x = np.random.uniform(self.lower, self.upper, self.dim)
        self.best_y = func(self.best_x)
        self.budget -= 1

        # Perform the optimization
        while self.budget > 0:
            # Generate a new candidate solution
            candidate = self.best_x + self.step_size * np.random.normal(0, 1, self.dim)
            candidate = np.clip(candidate, self.lower, self.upper)
            candidate_y = func(candidate)
            self.budget -= 1

            # Update the search state
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y
                self.success_count += 1

            # Adapt the step size
            self.step_size *= 0.9 ** (1 - 2 * (self.success_count / (self.budget + 1)))
            self.success_count = 0

        return self.best_x, self.best_y
