import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that samples points
#          uniformly within the provided bounds and keeps track of the best
#          solution found so far.
# Search state: The search state consists of the current best solution (best_x,
#                best_y) and the remaining evaluation budget.
# Candidate generation: Candidates are generated by sampling points uniformly
#                       within the provided bounds.
# Selection and replacement: The best candidate found so far is always kept.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space uniformly.
# Exploitation mechanisms: The algorithm exploits the best solution found so far.
# Boundary handling: Candidates that fall outside the provided bounds are
#                    rejected.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This algorithm is a basic random search algorithm
#                          with no additional mechanisms.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: This algorithm may struggle on high-dimensional problems or
#                problems with many local minima, as it has no mechanisms to
#                escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        remaining_budget = self.budget
        while remaining_budget > 0:
            # Generate a candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the candidate solution
            y = func(x)
            remaining_budget -= 1

            # Update the best solution if necessary
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
