import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a simple
#          gradient-free optimization algorithm based on Nelder-Mead simplex
#          method. It does not require any external dependencies and can
#          optimize functions of arbitrary dimension within the given budget.
# Search state: The algorithm maintains a simplex of size (dim+1) with
#               vertices representing candidate solutions.
# Candidate generation: New candidate solutions are generated by reflection,
#                       expansion, contraction, and shrinkage operations on
#                       the simplex.
# Selection and replacement: The worst vertex of the simplex is replaced by
#                            the new candidate solution if it improves the
#                            objective function value.
# Adaptation: The simplex is adapted by adjusting the step sizes based on
#             the success or failure of the previous iterations.
# Exploration mechanisms: The algorithm explores the search space by
#                         generating new candidates around the current
#                         simplex.
# Exploitation mechanisms: The algorithm exploits the search space by
#                          contracting the simplex towards the best
#                          solution found so far.
# Boundary handling: The algorithm handles boundary constraints by
#                    projecting the new candidate solutions back into
#                    the feasible region if they violate the bounds.
# Budget strategy: The algorithm uses the entire evaluation budget
#                  provided and does not have any specific budget
#                  management strategy.
# Closest known influences: Nelder-Mead simplex method, gradient-free
#                          optimization algorithms.
# Novelty or unusual aspects: The implementation is compact and does not
#                            require any external dependencies.
# Failure modes: The algorithm may struggle with highly multi-modal
#                or discontinuous objective functions, or when the
#                initial simplex is not well-positioned.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.f = np.inf
        self.simplex = np.zeros((dim + 1, dim))
        self.fvals = np.full(dim + 1, np.inf)
        self.step = 1.0
        self.alpha = 1.0
        self.gamma = 2.0
        self.rho = 0.5
        self.sigma = 0.5

    def __call__(self, func):
        # Initialize the simplex
        self.x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
        self.f = func(self.x)
        self.simplex[0] = self.x
        self.fvals[0] = self.f

        for i in range(1, self.dim + 1):
            self.simplex[i] = self.x + self.step * np.eye(self.dim)[i - 1]
            self.fvals[i] = func(self.simplex[i])

        # Optimize
        for _ in range(self.budget):
            # Order the vertices
            order = np.argsort(self.fvals)
            self.simplex = self.simplex[order]
            self.fvals = self.fvals[order]

            # Reflect the worst point
            xr = self.simplex[0] + self.alpha * (self.simplex[0] - self.simplex[-1])
            fr = func(xr)

            if self.fvals[0] <= fr < self.fvals[-2]:
                # Accept the reflected point
                self.simplex[-1] = xr
                self.fvals[-1] = fr
            elif fr < self.fvals[0]:
                # Expand the simplex
                xe = self.simplex[0] + self.gamma * (xr - self.simplex[0])
                fe = func(xe)
                if fe < fr:
                    self.simplex[-1] = xe
                    self.fvals[-1] = fe
                else:
                    self.simplex[-1] = xr
                    self.fvals[-1] = fr
            else:
                # Contract the simplex
                xc = self.simplex[0] + self.rho * (self.simplex[-1] - self.simplex[0])
                fc = func(xc)
                if fc < self.fvals[-1]:
                    self.simplex[-1] = xc
                    self.fvals[-1] = fc
                else:
                    # Shrink the simplex
                    for i in range(1, self.dim + 1):
                        self.simplex[i] = self.simplex[0] + self.sigma * (self.simplex[i] - self.simplex[0])
                        self.fvals[i] = func(self.simplex[i])

            # Update the best solution
            self.x = self.simplex[0]
            self.f = self.fvals[0]

        return self.x, self.f
