import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a randomized hill-climbing algorithm to
#          optimize the objective function within the given budget. It
#          generates new candidate solutions by perturbing the current
#          best solution, and selects the new best solution based on
#          objective function value.
# Search state: The current best solution (best_x) and its objective
#                function value (best_y).
# Candidate generation: New candidate solutions are generated by perturbing
#                       the current best solution with Gaussian noise.
# Selection and replacement: The new candidate solution is compared to the
#                            current best solution, and replaces it if the
#                            new solution has a lower objective function
#                            value.
# Adaptation: The standard deviation of the Gaussian noise used to generate
#             new candidates is adaptively adjusted based on the number of
#             function evaluations remaining.
# Exploration mechanisms: The Gaussian noise used to generate new candidates
#                         provides exploration by allowing the search to
#                         move away from the current best solution.
# Exploitation mechanisms: The selection of the new best solution based on
#                          objective function value provides exploitation by
#                          focusing the search on promising regions of the
#                          search space.
# Boundary handling: The candidate solution is constrained to the
#                    problem bounds by clipping its values.
# Budget strategy: The algorithm uses the entire evaluation budget,
#                  adjusting the Gaussian noise standard deviation to
#                  balance exploration and exploitation as the budget
#                  is consumed.
# Closest known influences: This algorithm is a simple randomized hill-climbing
#                           approach, similar to basic evolutionary algorithms
#                           and gradient-free optimization methods.
# Novelty or unusual aspects: The adaptive adjustment of the Gaussian noise
#                            standard deviation based on the remaining budget
#                            is a novel aspect of this implementation.
# Failure modes: The algorithm may get stuck in a local minimum, especially
#                for high-dimensional or multimodal problems. The adaptive
#                Gaussian noise adjustment may not be sufficient to escape
#                local minima in all cases.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        if self.best_x is None:
            # Initialize the search with a random starting point
            self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
            self.best_y = func(self.best_x)
            self.budget -= 1

        # Adapt the Gaussian noise standard deviation based on the remaining budget
        sigma = 0.1 * (func.upper - func.lower) * (self.budget ** 0.5) / self.dim

        while self.budget > 0:
            # Generate a new candidate solution by perturbing the current best
            candidate_x = self.best_x + np.random.normal(0, sigma, self.dim)

            # Clip the candidate solution to the problem bounds
            candidate_x = np.clip(candidate_x, func.lower, func.upper)

            # Evaluate the candidate solution
            candidate_y = func(candidate_x)
            self.budget -= 1

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
