import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a random search algorithm for the GNBG black-box minimization benchmark.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidates are generated by sampling from a uniform distribution within the problem bounds.
# Selection and replacement: The best candidate found so far is updated after each function evaluation.
# Adaptation: There is no adaptation; the search is purely random.
# Exploration mechanisms: Exploration is achieved through the random sampling of new candidates.
# Exploitation mechanisms: There are no explicit exploitation mechanisms; the algorithm relies on the random search to eventually find the optimum.
# Boundary handling: Candidates that fall outside the problem bounds are rejected and a new candidate is generated.
# Budget strategy: The algorithm uses the entire evaluation budget provided, making as many function evaluations as possible.
# Closest known influences: This algorithm is a simple random search, which is a fundamental optimization technique.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm; it is a straightforward implementation of random search.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional problems or problems with many local optima, as it has no mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
