import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a simple
# stochastic search strategy for black-box optimization problems. It uses a
# combination of random sampling and gradient-free hill-climbing to explore
# the search space efficiently within the given evaluation budget.
# Search state: The algorithm maintains a single current best solution,
# represented by a numpy array of decision variables.
# Candidate generation: New candidate solutions are generated by adding
# isotropic Gaussian noise to the current best solution.
# Selection and replacement: The best candidate solution is selected and
# replaces the current best solution if it improves the objective function
# value.
# Adaptation: The standard deviation of the Gaussian noise used to generate
# new candidates is automatically adapted based on the observed progress, in
# order to balance exploration and exploitation.
# Exploration mechanisms: The algorithm relies on random sampling to explore
# the search space, with the ability to escape local optima through the
# stochastic nature of the candidate generation process.
# Exploitation mechanisms: The algorithm uses a gradient-free hill-climbing
# approach, where the current best solution is iteratively improved by
# generating and evaluating nearby candidate solutions.
# Boundary handling: The algorithm ensures that candidate solutions remain
# within the specified bounds by clipping the decision variables if
# necessary.
# Budget strategy: The algorithm attempts to make the most of the available
# evaluation budget by carefully managing the balance between exploration
# and exploitation.
# Closest known influences: This algorithm is loosely inspired by evolution
# strategies and other simple stochastic search methods, but it is a
# custom-designed solution tailored for the GNBG black-box optimization
# benchmark.
# Novelty or unusual aspects: The adaptive standard deviation adjustment
# mechanism is a key feature that helps the algorithm adjust its behavior
# based on the observed progress during the optimization process.
# Failure modes: The algorithm may struggle in high-dimensional problems
# with complex, multimodal objective functions, as the simple stochastic
# search strategy may not be able to efficiently explore the search space
# within the limited evaluation budget.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.f = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        bounds = getattr(func, 'bounds', None)
        if bounds is None:
            lb = getattr(func, 'lower', -5.12 * np.ones(self.dim))
            ub = getattr(func, 'upper', 5.12 * np.ones(self.dim))
        else:
            lb, ub = bounds.lb, bounds.ub

        for _ in range(self.budget):
            candidate = self.x + self.sigma * np.random.normal(size=self.dim)
            candidate = np.clip(candidate, lb, ub)
            new_f = func(candidate)
            if new_f < self.f:
                self.x = candidate
                self.f = new_f

        # Adapt the standard deviation based on the progress made
        if self.budget > 0:
            self.sigma *= np.exp(min(0, (self.f - func(self.x)) / self.budget))

        return self.x, self.f
