import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple randomized search algorithm to
#          optimize the objective function within the provided budget. It
#          generates candidate solutions by sampling from a multivariate
#          normal distribution centered at the current best solution, and
#          updates the best solution as better candidates are found.
# Search state: The algorithm maintains a single current best solution.
# Candidate generation: Candidates are generated by sampling from a
#                      multivariate normal distribution centered at the
#                      current best solution, with a fixed covariance matrix.
# Selection and replacement: The best candidate solution is selected and
#                           replaces the current best solution if it is better.
# Adaptation: The algorithm does not adapt its search parameters during the
#             optimization process.
# Exploration mechanisms: The randomized sampling of candidates provides
#                        exploration of the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                         by sampling candidates around it.
# Boundary handling: Candidate solutions that are outside the bounds of the
#                   search space are rejected and not evaluated.
# Budget strategy: The algorithm uses the full evaluation budget and stops
#                  when the budget is exhausted.
# Closest known influences: This algorithm is a basic randomized search
#                          algorithm, similar to a simplified version of
#                          Covariance Matrix Adaptation Evolution Strategy
#                          (CMA-ES).
# Novelty or unusual aspects: The algorithm is very simple and does not
#                            include any advanced features or adaptations.
# Failure modes: The algorithm may struggle with highly multimodal or
#                deceptive objective functions, as it does not have any
#                mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Initialize the search with a random starting point
        self.best_x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
        self.best_y = func(self.best_x)

        # Covariance matrix for candidate generation
        cov = np.eye(self.dim) * 0.1

        # Optimize within the budget
        for _ in range(self.budget):
            # Generate a candidate solution
            candidate = np.random.multivariate_normal(self.best_x, cov)

            # Evaluate the candidate and update the best solution if necessary
            candidate_y = func(candidate)
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

        return self.best_x, self.best_y
