import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search strategy that samples from a uniform distribution within the
#          given bounds. It keeps track of the best solution found so far and returns it at the end of the
#          evaluation budget.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling from a uniform distribution within the given bounds.
# Selection and replacement: The best candidate (in terms of objective function value) replaces the current best
#                           solution if it is better.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by sampling around it, but this is
#                         not an explicit mechanism.
# Boundary handling: Candidate solutions that are outside the given bounds are clipped to the nearest feasible
#                    value.
# Budget strategy: The algorithm uses the full evaluation budget to sample as many candidate solutions as possible.
# Closest known influences: This algorithm is a basic random search strategy, which is a common baseline for
#                          black-box optimization problems.
# Novelty or unusual aspects: This algorithm does not have any novel or unusual aspects, as it is a very simple
#                            random search strategy.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional or multimodal
#                problems, as it lacks any sophisticated exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim

    def __call__(self, func):
        # Read the bounds from the function
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            self.lower = func.lower
            self.upper = func.upper
        elif hasattr(func, 'bounds'):
            self.lower = func.bounds.lb
            self.upper = func.bounds.ub
        else:
            raise ValueError('Function must have either lower/upper or bounds.lb/bounds.ub attributes.')

        # Initialize the best solution
        self.best_x = np.random.uniform(self.lower, self.upper, self.dim)
        self.best_y = func(self.best_x)

        # Evaluate the budget
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(self.lower, self.upper, self.dim)

            # Evaluate the candidate solution
            y = func(x)

            # Update the best solution if the candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
