import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple, compact implementation of a randomized black-box
#          optimization algorithm for the GNBG benchmark. It uses a combination
#          of random sampling and a greedy local search to find the minimum of
#          the objective function.
# Search state: The algorithm maintains the current best solution (best_x,
#                best_y) and the evaluation budget.
# Candidate generation: New candidates are generated by adding Gaussian noise
#                       to the current best solution.
# Selection and replacement: The new candidate replaces the current best
#                           solution if it has a lower objective value.
# Adaptation: The algorithm does not adapt its search strategy.
# Exploration mechanisms: The Gaussian noise added to the current best solution
#                         provides exploration.
# Exploitation mechanisms: The greedy local search exploits the current best
#                          solution.
# Boundary handling: Boundary violations are handled by reflecting the
#                    candidate back into the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget and does not
#                  attempt to manage the budget.
# Closest known influences: This algorithm is similar to a simple random search
#                           with local improvement.
# Novelty or unusual aspects: The algorithm is purposefully kept simple and
#                             compact to demonstrate a baseline approach.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive
#                objective functions, as it does not employ any advanced
#                mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(self.dim)
        self.best_y = float('inf')
        self.evals = 0

    def __call__(self, func):
        # Read bounds from func.lower, func.upper or func.bounds.lb, func.bounds.ub
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        while self.evals < self.budget:
            # Generate a new candidate by adding Gaussian noise to the best solution
            candidate = self.best_x + np.random.normal(0, 1, self.dim)

            # Reflect the candidate back into the feasible region if needed
            candidate = np.maximum(self.lb, np.minimum(self.ub, candidate))

            # Evaluate the candidate and update the best solution if it's better
            candidate_y = func(candidate)
            self.evals += 1
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

        return self.best_x, self.best_y
