import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized black-box optimization algorithm, using a multi-start approach with Gaussian sampling.
# Search state: The search state is represented by a set of candidate solutions, each with an associated objective value.
# Candidate generation: New candidate solutions are generated by sampling from a Gaussian distribution centered at the current best solution, with a covariance matrix that adapts to the search progress.
# Selection and replacement: The best solution from the set of candidates is selected and replaces the current worst solution in the search state.
# Adaptation: The covariance matrix of the Gaussian sampling distribution adapts based on the objective values of the candidate solutions, becoming more narrow along dimensions where progress is being made.
# Exploration mechanisms: The Gaussian sampling provides exploration, with the variance of the distribution controlling the level of exploration.
# Exploitation mechanisms: The algorithm focuses exploitation on the current best solution by centering the Gaussian sampling around it.
# Boundary handling: Candidate solutions that fall outside the defined bounds are reflected back inside the feasible region.
# Budget strategy: The algorithm attempts to use the entire evaluation budget by generating a number of candidates proportional to the remaining budget.
# Closest known influences: This algorithm is inspired by the CMA-ES and NEWUOA optimization methods, which use Gaussian sampling and covariance matrix adaptation.
# Novelty or unusual aspects: The algorithm is designed to be compact and self-contained, using only the Python standard library and NumPy.
# Failure modes: The algorithm may struggle in high-dimensional problems or problems with highly rugged or discontinuous objective functions, as the Gaussian sampling may not be able to effectively explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.f_best = np.inf
        self.candidates = []
        self.sigma = 1.0
        self.C = np.eye(self.dim)

    def __call__(self, func):
        self.candidates = []
        self.budget_remaining = self.budget
        self.x_best = np.zeros(self.dim)
        self.f_best = np.inf

        while self.budget_remaining > 0:
            num_candidates = max(1, int(self.budget_remaining / (self.dim + 1)))
            self.budget_remaining -= num_candidates

            # Generate new candidates
            for _ in range(num_candidates):
                x = self.x_best + self.sigma * np.random.multivariate_normal(np.zeros(self.dim), self.C)
                x = np.clip(x, func.lower, func.upper)
                f = func(x)
                self.candidates.append((x, f))

            # Select the best candidate and update the search state
            self.candidates.sort(key=lambda x: x[1])
            x_new, f_new = self.candidates[0]
            if f_new < self.f_best:
                self.x_best = x_new
                self.f_best = f_new

            # Adapt the covariance matrix
            dx = np.array([x[0] for x in self.candidates]) - self.x_best
            self.C = (1 - 1 / self.dim) * self.C + (1 / self.dim) * np.dot(dx.T, dx)
            self.sigma = min(1.0, np.sqrt(self.f_best / self.budget))

        return self.x_best, self.f_best
