import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that samples points uniformly within the search domain and keeps track of the best solution found so far.
# Search state: The algorithm maintains a single best solution found so far, represented by a point (best_x) and its objective function value (best_y).
# Candidate generation: New candidate solutions are generated by sampling points uniformly within the search domain.
# Selection and replacement: The new candidate solution is compared to the current best solution, and the best one is kept.
# Adaptation: The algorithm does not adapt or change its behavior during the search.
# Exploration mechanisms: The algorithm explores the search space by uniformly sampling new points.
# Exploitation mechanisms: The algorithm exploits the current best solution by using it as the reference point.
# Boundary handling: The algorithm samples points within the given bounds, and if a sampled point is outside the bounds, it is projected back onto the nearest point within the bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided, making as many function evaluations as possible within the budget.
# Closest known influences: This algorithm is similar to a basic random search or Monte Carlo sampling approach.
# Novelty or unusual aspects: The algorithm is very simple and straightforward, with no significant novel aspects.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional or multimodal problems, as it relies solely on random sampling without any adaptive or directed search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
