import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized downhill simplex
#          algorithm for blackbox optimization, with a focus on robustness and
#          simplicity.
# Search state: The search state is represented by a simplex, which is a set of
#               N+1 points in an N-dimensional space.
# Candidate generation: New candidates are generated by reflecting, expanding,
#                       or contracting the simplex.
# Selection and replacement: The point with the worst function value is
#                            replaced by the new candidate.
# Adaptation: The simplex size and shape are adapted based on the function
#             evaluations, with the goal of converging to the optimum.
# Exploration mechanisms: The initial simplex is constructed randomly within the
#                         search bounds.
# Exploitation mechanisms: The simplex is adapted to focus the search on
#                          promising regions.
# Boundary handling: If a candidate point falls outside the search bounds, it is
#                    projected back onto the closest valid point.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: The Nelder-Mead simplex method.
# Novelty or unusual aspects: The implementation is designed to be compact,
#                             robust, and self-contained.
# Failure modes: The algorithm may struggle with highly multimodal or
#                discontinuous functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex randomly within the search bounds
        x0 = np.random.uniform(func.lower, func.upper, size=(self.dim + 1, self.dim))
        y0 = [func(x) for x in x0]
        self.simplex = x0
        self.values = y0
        self.evaluations += self.dim + 1

        # Main optimization loop
        while self.evaluations < self.budget:
            # Reflect the worst point through the centroid
            worst = np.argmax(self.values)
            centroid = np.mean(self.simplex[:-1], axis=0)
            reflected = centroid + (centroid - self.simplex[worst])
            reflected = np.clip(reflected, func.lower, func.upper)
            reflected_value = func(reflected)
            self.evaluations += 1

            # Update the simplex based on the reflection
            if reflected_value < self.values[worst]:
                self.simplex[worst] = reflected
                self.values[worst] = reflected_value
            else:
                # Try expansion or contraction
                expanded = centroid + 2 * (reflected - centroid)
                expanded = np.clip(expanded, func.lower, func.upper)
                expanded_value = func(expanded)
                self.evaluations += 1
                if expanded_value < reflected_value:
                    self.simplex[worst] = expanded
                    self.values[worst] = expanded_value
                else:
                    contracted = centroid + 0.5 * (self.simplex[worst] - centroid)
                    contracted = np.clip(contracted, func.lower, func.upper)
                    contracted_value = func(contracted)
                    self.evaluations += 1
                    if contracted_value < self.values[worst]:
                        self.simplex[worst] = contracted
                        self.values[worst] = contracted_value

        # Return the best found solution
        best_idx = np.argmin(self.values)
        return self.simplex[best_idx], self.values[best_idx]
