import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple, randomized hill-climbing algorithm that attempts to
#          find the minimum of a black-box objective function. It starts with a
#          random initial point and iteratively updates the current point by
#          taking a random step within the bounds of the problem.
# Search state: The algorithm maintains a single current point, which is updated
#               in each iteration.
# Candidate generation: New candidate points are generated by adding a random
#                       perturbation to the current point, with the perturbation
#                       drawn from a normal distribution.
# Selection and replacement: The new candidate point is always accepted if it
#                            has a lower function value than the current point.
# Adaptation: The step size used to generate new candidates is adapted
#             dynamically based on the success rate of the previous steps.
# Exploration mechanisms: The algorithm relies on the random perturbations to
#                         explore the search space.
# Exploitation mechanisms: The algorithm greedily accepts better candidate
#                          points, which allows it to exploit promising regions
#                          of the search space.
# Boundary handling: If a candidate point falls outside the bounds of the
#                    problem, it is projected back onto the nearest valid point
#                    within the bounds.
# Budget strategy: The algorithm simply uses the full evaluation budget provided
#                  to it, without any explicit budget management.
# Closest known influences: This algorithm is a basic form of randomized
#                          hill-climbing, which is a common optimization
#                          technique.
# Novelty or unusual aspects: The algorithm does not have any particularly
#                             novel or unusual aspects.
# Failure modes: The algorithm may get stuck in local minima, especially for
#                multimodal or deceptive objective functions. Its performance
#                is also highly dependent on the choice of step size and the
#                dimensionality of the problem.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.step_size = 1.0
        self.success_count = 0
        self.total_count = 0

    def __call__(self, func):
        x = np.random.uniform(func.lower, func.upper, self.dim)
        best_x = x.copy()
        best_y = func(x)
        self.budget -= 1

        while self.budget > 0:
            candidate = x + np.random.normal(0, self.step_size, self.dim)
            candidate = np.clip(candidate, func.lower, func.upper)
            y = func(candidate)
            self.budget -= 1

            if y < best_y:
                best_x = candidate.copy()
                best_y = y
                self.success_count += 1
            self.total_count += 1

            # Adapt the step size based on the success rate
            if self.total_count % 10 == 0:
                self.step_size *= 0.9 if self.success_count / self.total_count < 0.2 else 1.1
                self.success_count = 0
                self.total_count = 0

        return best_x, best_y
