import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of the Nelder-Mead simplex algorithm for
#          black-box function optimization. It maintains a simplex of n+1 points in
#          the n-dimensional search space, and iteratively updates the simplex by
#          reflecting, expanding, contracting, or shrinking it to find the optimum.
# Search state: The search state is represented by the current simplex of n+1 points.
# Candidate generation: New candidate points are generated by reflecting, expanding,
#                       contracting, or shrinking the current simplex.
# Selection and replacement: The new candidate points are evaluated, and the worst
#                            point in the simplex is replaced by the best new point.
# Adaptation: The simplex adapts its shape and size to the local landscape by
#             performing the various simplex operations.
# Exploration mechanisms: The simplex operations of reflection, expansion, and
#                         contraction allow the algorithm to explore the search space.
# Exploitation mechanisms: The shrinking of the simplex towards the best point
#                          allows the algorithm to exploit the local optimum.
# Boundary handling: If a candidate point goes outside the bounds, it is projected
#                    back onto the nearest valid point within the bounds.
# Budget strategy: The algorithm uses the entire evaluation budget, stopping when
#                  the budget is exhausted.
# Closest known influences: This is a standard implementation of the Nelder-Mead
#                          simplex algorithm, which is a well-known and widely used
#                          derivative-free optimization method.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            implementation, as it follows the standard Nelder-Mead
#                            algorithm.
# Failure modes: The algorithm may converge to a local optimum, especially in
#                high-dimensional or multimodal problems. It can also be sensitive
#                to the initial simplex shape and size.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize the simplex
        x = np.random.uniform(func.lower, func.upper, (self.dim + 1, self.dim))
        y = np.array([func(xi) for xi in x])
        self.evaluations += self.dim + 1

        while self.evaluations < self.budget:
            # Order the simplex points by function value
            idx = np.argsort(y)
            x = x[idx]
            y = y[idx]

            # Calculate the centroid of the best points
            xbar = np.mean(x[:-1], axis=0)

            # Reflect the worst point through the centroid
            xr = xbar + (xbar - x[-1])
            yr = func(xr)
            self.evaluations += 1

            if yr < y[0]:
                # Expansion: try to go further in the reflection direction
                xe = xbar + 2 * (xr - xbar)
                ye = func(xe)
                self.evaluations += 1
                if ye < yr:
                    x[-1] = xe
                    y[-1] = ye
                else:
                    x[-1] = xr
                    y[-1] = yr
            elif yr < y[-2]:
                # Accept the reflected point
                x[-1] = xr
                y[-1] = yr
            else:
                if yr < y[-1]:
                    # Contraction: shrink towards the best point
                    xc = xbar + 0.5 * (xr - xbar)
                    yc = func(xc)
                    self.evaluations += 1
                    if yc <= yr:
                        x[-1] = xc
                        y[-1] = yc
                    else:
                        # Shrink the simplex towards the best point
                        for i in range(1, self.dim + 1):
                            x[i] = x[0] + 0.5 * (x[i] - x[0])
                            y[i] = func(x[i])
                            self.evaluations += 1

            # Ensure the points are within the bounds
            for i in range(self.dim + 1):
                x[i] = np.clip(x[i], func.lower, func.upper)

        # Return the best point found
        return x[0], y[0]
