import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm to minimize the
#          black-box function provided. It generates new candidate solutions uniformly
#          within the bounded search space, evaluates them, and keeps track of the
#          best solution found so far.
# Search state: The search state consists of the current best solution (best_x) and
#               its corresponding objective function value (best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly
#                       from the bounded search space.
# Selection and replacement: The best candidate solution found so far replaces the
#                           current best solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The random sampling of candidate solutions provides
#                         exploration of the search space.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidate solutions that fall outside the bounded search space
#                    are rejected and a new candidate is generated.
# Budget strategy: The algorithm evaluates candidate solutions until the provided
#                  evaluation budget is exhausted.
# Closest known influences: This implementation is a basic random search algorithm,
#                          which is a common baseline for black-box optimization.
# Novelty or unusual aspects: This implementation is designed to be compact and
#                            robust across dimensions, with no unusual aspects.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it relies solely
#                on random exploration without any guidance or exploitation.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        self.budget_remaining = self.budget
        while self.budget_remaining > 0:
            x = np.random.uniform(func.bounds.lb, func.bounds.ub, self.dim)
            y = func(x)
            self.budget_remaining -= 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
