import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a randomized gradient descent approach to
#          optimize the objective function within the given budget.
# Search state: The search state is represented by the current best point.
# Candidate generation: New candidate points are generated by adding
#                      Gaussian noise to the current best point.
# Selection and replacement: The best candidate point is selected and
#                            replaces the current best point if it
#                            improves the objective function value.
# Adaptation: The standard deviation of the Gaussian noise is adapted
#             based on the progress of the search.
# Exploration mechanisms: The Gaussian noise provides exploration
#                         capabilities.
# Exploitation mechanisms: The gradient-like update towards the current
#                          best point provides exploitation.
# Boundary handling: Candidate points that fall outside the bounds are
#                    reflected back inside the feasible region.
# Budget strategy: The full budget is used, with the step size adapting
#                  to the remaining budget.
# Closest known influences: Randomized gradient descent, evolution
#                          strategies, and Nelder-Mead algorithm.
# Novelty or unusual aspects: The combination of gradient-like updates
#                            and adaptive Gaussian noise is relatively
#                            uncommon in black-box optimization.
# Failure modes: The algorithm may struggle on highly multimodal
#                or deceptive functions, as the gradient-like
#                updates can get stuck in local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = np.zeros(dim)
        self.f_best = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        bounds = getattr(func, 'bounds', None)
        if bounds is None:
            lb = getattr(func, 'lower', -5 * np.ones(self.dim))
            ub = getattr(func, 'upper', 5 * np.ones(self.dim))
        else:
            lb, ub = bounds.lb, bounds.ub

        for _ in range(self.budget):
            x_candidate = self.x_best + self.sigma * np.random.normal(scale=self.dim ** 0.5, size=self.dim)
            x_candidate = np.clip(x_candidate, lb, ub)
            f_candidate = func(x_candidate)

            if f_candidate < self.f_best:
                self.x_best = x_candidate
                self.f_best = f_candidate
                self.sigma = max(0.1, self.sigma * 0.9)  # Decrease sigma on improvement
            else:
                self.sigma = min(1.0, self.sigma * 1.1)  # Increase sigma on no improvement

        return self.x_best, self.f_best
