import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple randomized search that samples points
#          within the given search bounds and keeps track of the best
#          solution found so far.
# Search state: The search state consists of the current best solution
#                (best_x, best_y).
# Candidate generation: Candidates are generated by sampling random points
#                       within the search bounds.
# Selection and replacement: The best candidate replaces the current best
#                            solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by
#                         randomly sampling points.
# Exploitation mechanisms: The algorithm exploits the search space by
#                          focusing on the best solution found so far.
# Boundary handling: Boundary violations are handled by sampling a new
#                    point within the search bounds.
# Budget strategy: The algorithm uses the entire evaluation budget to
#                  search for the best solution.
# Closest known influences: This algorithm is a basic random search
#                           approach, which is a common baseline for
#                           black-box optimization problems.
# Novelty or unusual aspects: The algorithm does not have any novel or
#                             unusual aspects.
# Failure modes: The algorithm may struggle to find the global optimum
#                in high-dimensional or multimodal problems, as it relies
#                on random sampling without any more sophisticated
#                search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float("inf")

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
