import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a black-box
#          minimization algorithm based on a randomized search approach. It
#          leverages the power of NumPy to generate and evaluate candidate
#          solutions efficiently.
# Search state: The search state is represented by the current best solution
#                (best_x, best_y).
# Candidate generation: Candidates are generated by applying a random
#                       perturbation to the current best solution, with the
#                       perturbation magnitude determined by the search budget.
# Selection and replacement: The newly generated candidate is evaluated and
#                            replaces the current best solution if it has a
#                            lower objective function value.
# Adaptation: The search process adapts by adjusting the perturbation magnitude
#             based on the remaining search budget, allowing for more
#             exploration early on and more exploitation towards the end.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         random perturbations of the current best solution.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates in its vicinity.
# Boundary handling: The algorithm ensures that the generated candidates are
#                    within the specified bounds by clamping the values.
# Budget strategy: The algorithm uses the entire budget provided, adjusting the
#                  perturbation magnitude accordingly.
# Closest known influences: This algorithm is inspired by basic randomized
#                           search techniques, such as random restart hill
#                           climbing and simulated annealing.
# Novelty or unusual aspects: The algorithm is designed to be compact, robust,
#                             and easily adaptable to different dimensions,
#                             without relying on any external libraries or
#                             complex mechanisms.
# Failure modes: The algorithm may struggle in high-dimensional problems with
#                complex or multimodal objective functions, as the random
#                perturbation-based approach may not be able to efficiently
#                explore the search space.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        if self.best_x is None:
            self.best_x = np.random.uniform(func.lower, func.upper, self.dim)
            self.best_y = func(self.best_x)

        for _ in range(self.budget):
            candidate_x = self.best_x + np.random.uniform(-1, 1, self.dim) * (
                func.upper - func.lower
            ) / np.sqrt(self.budget - _)
            candidate_x = np.clip(candidate_x, func.lower, func.upper)
            candidate_y = func(candidate_x)

            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
