import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact, randomized implementation of a black-box optimization
#          algorithm for the GNBG benchmark. It uses a simple gradient-free
#          optimization approach, sampling candidate solutions and updating the
#          search distribution.
# Search state: The search state is represented by a multivariate normal distribution
#               parameterized by a mean vector and a covariance matrix.
# Candidate generation: New candidate solutions are generated by sampling from the
#                      current search distribution.
# Selection and replacement: The best candidate solution is selected and replaces
#                           the current search distribution parameters.
# Adaptation: The search distribution is adapted by updating the mean and covariance
#             based on the best candidate solution.
# Exploration mechanisms: Exploration is achieved through the sampling of new
#                        candidate solutions from the search distribution.
# Exploitation mechanisms: Exploitation is achieved by updating the search distribution
#                         to focus on the best-performing candidate solution.
# Boundary handling: Boundary handling is performed by clipping candidate solutions
#                   to the provided bounds.
# Budget strategy: The algorithm runs until the provided evaluation budget is exhausted.
# Closest known influences: This algorithm is inspired by evolution strategies and
#                          Bayesian optimization approaches.
# Novelty or unusual aspects: The algorithm is designed to be compact, readable, and
#                            robust across dimensions, without relying on external
#                            libraries or advanced techniques.
# Failure modes: The algorithm may struggle with highly multimodal or deceptive
#                objective functions, as it relies on a relatively simple
#                gradient-free approach.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_mean = np.zeros(self.dim)
        self.x_cov = np.eye(self.dim)
        self.evaluations = 0

    def __call__(self, func):
        while self.evaluations < self.budget:
            x = np.random.multivariate_normal(self.x_mean, self.x_cov)
            if hasattr(func, 'bounds'):
                x = np.clip(x, func.bounds.lb, func.bounds.ub)
            else:
                x = np.clip(x, func.lower, func.upper)
            y = func(x)
            self.evaluations += 1
            self.x_mean = x
            self.x_cov = np.outer(x - self.x_mean, x - self.x_mean)
        return self.x_mean, func(self.x_mean)
