import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a black-box optimizer using random search with restarts.
# Search state: The search state consists of the current best solution (best_x, best_y) and the number of evaluations remaining in the budget.
# Candidate generation: New candidate solutions are generated by sampling uniformly within the bounded search space.
# Selection and replacement: The best candidate solution found so far is always kept, replacing the current best if the new solution has a lower objective value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The search explores the space randomly, with no biases or preferences.
# Exploitation mechanisms: The search exploits the current best solution by always keeping it and using it as a reference for future candidate generations.
# Boundary handling: Candidate solutions that fall outside the bounded search space are simply discarded and a new candidate is generated.
# Budget strategy: The search continues until the evaluation budget is exhausted.
# Closest known influences: This implementation is similar to a basic random search algorithm, with no additional techniques or mechanisms.
# Novelty or unusual aspects: There are no novel or unusual aspects in this implementation.
# Failure modes: The search may struggle on highly multimodal or deceptive objective functions, as it has no mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = np.inf

    def __call__(self, func):
        while self.budget > 0:
            x = self._generate_candidate(func)
            y = func(x)
            self.budget -= 1
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y

    def _generate_candidate(self, func):
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper
        return np.random.uniform(lb, ub, size=self.dim)
