import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a randomized search algorithm for black-box optimization. It generates candidate solutions uniformly within the search bounds, evaluates them, and keeps track of the best solution found so far.
# Search state: The algorithm maintains a single best solution, represented by a numpy array.
# Candidate generation: Candidates are generated by sampling uniformly from the search space.
# Selection and replacement: The best candidate (lowest objective value) replaces the current best solution if it is an improvement.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The uniform random sampling provides exploration of the search space.
# Exploitation mechanisms: The algorithm selects the best candidate solution found so far, providing a basic exploitation mechanism.
# Boundary handling: Candidate solutions are clipped to the search bounds if they fall outside.
# Budget strategy: The algorithm consumes the evaluation budget one function evaluation at a time, stopping when the budget is exhausted.
# Closest known influences: This algorithm is a basic implementation of a randomized search, similar to random search or a simple evolutionary algorithm.
# Novelty or unusual aspects: This implementation is intended to be compact and robust, without any advanced features.
# Failure modes: The algorithm may struggle on high-dimensional or multimodal problems, as it has no mechanisms for escaping local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = np.inf

    def __call__(self, func):
        lower = func.lower if hasattr(func, 'lower') else func.bounds.lb
        upper = func.upper if hasattr(func, 'upper') else func.bounds.ub
        for _ in range(self.budget):
            x = np.random.uniform(lower, upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
