import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a Particle Swarm Optimization (PSO) approach to
#          minimize the given black-box function within the specified budget.
# Search state: The algorithm maintains a population of particles, each with a
#                position and velocity, which explore the search space.
# Candidate generation: New candidate solutions are generated by updating the
#                       position and velocity of each particle based on its
#                       personal best and the global best solution found so far.
# Selection and replacement: The best solution found so far is used to update
#                            the global best, and each particle's personal best
#                            is updated if a better solution is found.
# Adaptation: The algorithm adapts the particle velocities and positions based
#             on the personal and global best solutions to guide the search.
# Exploration mechanisms: The random initialization of the particle positions
#                         and velocities, as well as the stochastic velocity
#                         update, provide exploration capabilities.
# Exploitation mechanisms: The particle updates focus on exploiting the regions
#                          around the personal and global best solutions.
# Boundary handling: Particle positions are clamped to the provided bounds to
#                    ensure feasibility.
# Budget strategy: The algorithm uses the entire evaluation budget, with no
#                  explicit budget management strategy.
# Closest known influences: This algorithm is inspired by the standard Particle
#                           Swarm Optimization approach.
# Novelty or unusual aspects: None.
# Failure modes: The algorithm may struggle with highly multimodal or
#                deceptive objective functions, as it relies on the global best
#                solution to guide the search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.num_particles = 20
        self.w = 0.729  # inertia weight
        self.c1 = 1.49  # cognitive acceleration coefficient
        self.c2 = 1.49  # social acceleration coefficient

    def __call__(self, func):
        # Initialize particles
        self.positions = np.random.uniform(func.lower, func.upper, (self.num_particles, self.dim))
        self.velocities = np.random.uniform(-1, 1, (self.num_particles, self.dim))
        self.personal_best_positions = self.positions.copy()
        self.personal_best_values = np.full(self.num_particles, np.inf)
        self.global_best_position = None
        self.global_best_value = np.inf

        # Evaluate initial positions
        for i in range(self.num_particles):
            self.personal_best_values[i] = func(self.personal_best_positions[i])
            if self.personal_best_values[i] < self.global_best_value:
                self.global_best_position = self.personal_best_positions[i].copy()
                self.global_best_value = self.personal_best_values[i]

        # Optimize
        for _ in range(self.budget - self.num_particles):
            # Update velocities and positions
            r1 = np.random.uniform(0, 1, (self.num_particles, self.dim))
            r2 = np.random.uniform(0, 1, (self.num_particles, self.dim))
            self.velocities = self.w * self.velocities + \
                              self.c1 * r1 * (self.personal_best_positions - self.positions) + \
                              self.c2 * r2 * (self.global_best_position - self.positions)
            self.positions += self.velocities

            # Clamp positions to bounds
            self.positions = np.clip(self.positions, func.lower, func.upper)

            # Evaluate new positions
            for i in range(self.num_particles):
                new_value = func(self.positions[i])
                if new_value < self.personal_best_values[i]:
                    self.personal_best_positions[i] = self.positions[i].copy()
                    self.personal_best_values[i] = new_value
                    if new_value < self.global_best_value:
                        self.global_best_position = self.positions[i].copy()
                        self.global_best_value = new_value

        return self.global_best_position, self.global_best_value
