import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a randomized search algorithm for
# black-box function minimization. It generates new candidate solutions by
# sampling from a normal distribution centered at the current best solution,
# with a decreasing standard deviation over time. The best solution found so
# far is returned.
# Search state: The algorithm maintains a single best solution found so far.
# Candidate generation: New candidates are generated by sampling from a normal
# distribution centered at the current best solution, with a standard deviation
# that decreases linearly with the number of function evaluations.
# Selection and replacement: The best candidate solution is always selected and
# replaces the current best solution if it is better.
# Adaptation: The standard deviation of the candidate generation distribution
# decreases linearly with the number of function evaluations.
# Exploration mechanisms: The initial standard deviation of the candidate
# generation distribution allows for broad exploration of the search space.
# Exploitation mechanisms: As the standard deviation decreases, the search
# focuses more on exploiting the region around the current best solution.
# Boundary handling: Candidate solutions that fall outside the search bounds
# are rejected and a new candidate is generated.
# Budget strategy: The algorithm strictly respects the provided evaluation
# budget and never exceeds it.
# Closest known influences: This algorithm is similar to a simple randomized
# search or randomized local search algorithm.
# Novelty or unusual aspects: The linear decrease in standard deviation is a
# simple and common adaptation mechanism, but the specific implementation is
# tailored to the GNBG black-box minimization benchmark.
# Failure modes: The algorithm may struggle in high-dimensional problems or
# problems with complex, multimodal objective functions, as it relies on a
# relatively simple search strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = np.zeros(dim)
        self.best_y = float('inf')
        self.evals = 0
        self.std_dev = 1.0

    def __call__(self, func):
        while self.evals < self.budget:
            # Generate a new candidate solution
            candidate_x = self.best_x + self.std_dev * np.random.normal(size=self.dim)

            # Check if the candidate is within the search bounds
            if hasattr(func, 'bounds'):
                lb, ub = func.bounds.lb, func.bounds.ub
            else:
                lb, ub = func.lower, func.upper
            candidate_x = np.clip(candidate_x, lb, ub)

            # Evaluate the new candidate
            candidate_y = func(candidate_x)
            self.evals += 1

            # Update the best solution if the new candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

            # Decrease the standard deviation
            self.std_dev = 1.0 - self.evals / self.budget

        return self.best_x, self.best_y
