import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized search algorithm
#          for black-box optimization, suitable for GNBG benchmarking.
# Search state: The search state is represented by the best candidate solution
#               found so far, and the current iteration count.
# Candidate generation: New candidate solutions are generated by sampling
#                       uniformly within the search bounds.
# Selection and replacement: The best candidate solution seen so far is
#                           always kept, and replaces the current best if a
#                           better solution is found.
# Adaptation: The algorithm does not adapt its search strategy.
# Exploration mechanisms: Exploration is achieved through uniform random
#                         sampling within the search bounds.
# Exploitation mechanisms: The algorithm exploits the best solution found so
#                          far by remembering and returning it.
# Boundary handling: Candidate solutions outside the search bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm terminates when the provided evaluation
#                  budget is exhausted.
# Closest known influences: This algorithm is similar to a simple random
#                           search or Monte Carlo method.
# Novelty or unusual aspects: The algorithm is designed to be compact and
#                             robust across dimensions, while still
#                             satisfying the GNBG requirements.
# Failure modes: The algorithm may struggle on highly multimodal or
#                deceptive functions, or when the evaluation budget is
#                very small.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
