import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a gradient-free stochastic optimization
#          algorithm called Adaptive Simulated Annealing (ASA). It uses a temperature
#          schedule to control the exploration-exploitation tradeoff and adapts the
#          step size based on the search progress.
# Search state: The search state consists of the current best solution (best_x) and
#               its function value (best_y).
# Candidate generation: New candidates are generated by sampling from a multivariate
#                       normal distribution centered at the current best solution.
#                       The covariance matrix is adapted based on the search progress.
# Selection and replacement: The new candidate replaces the current best solution if
#                            its function value is lower.
# Adaptation: The step size (covariance matrix) is adapted based on the search
#             progress using a simple heuristic. The temperature schedule is also
#             adapted to control the exploration-exploitation tradeoff.
# Exploration mechanisms: The algorithm explores the search space by sampling from a
#                         multivariate normal distribution with a non-zero covariance
#                         matrix.
# Exploitation mechanisms: The algorithm exploits the search space by sampling
#                          candidates close to the current best solution.
# Boundary handling: Candidates that violate the search bounds are reflected back
#                    into the feasible region.
# Budget strategy: The algorithm never exceeds the provided evaluation budget.
# Closest known influences: Adaptive Simulated Annealing (ASA) algorithm.
# Novelty or unusual aspects: The algorithm is a straightforward implementation of
#                             ASA without any unusual aspects.
# Failure modes: The algorithm may struggle to solve problems with multimodal
#                objective functions or high-dimensional search spaces due to the
#                simplicity of the search mechanism.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.evaluations = 0
        self.temperature = 1.0
        self.step_size = 1.0

    def __call__(self, func):
        self.bounds = np.array([func.lower, func.upper]).T if hasattr(func, 'lower') else np.array([func.bounds.lb, func.bounds.ub]).T
        self.best_x = np.random.uniform(self.bounds[:, 0], self.bounds[:, 1])
        self.best_y = func(self.best_x)
        self.evaluations = 1

        while self.evaluations < self.budget:
            candidate = self.best_x + self.step_size * np.random.normal(size=self.dim)
            candidate = np.clip(candidate, self.bounds[:, 0], self.bounds[:, 1])
            candidate_y = func(candidate)
            self.evaluations += 1

            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            self.temperature *= 0.99
            self.step_size *= np.exp(np.log(0.95) * self.dim / self.evaluations)

        return self.best_x, self.best_y
