import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple implementation of a randomized search algorithm
#          for the GNBG black-box minimization benchmark. It uses a random
#          search within the given bounds, keeping track of the best found
#          solution.
# Search state: The search state consists of the current best solution (best_x)
#                and its corresponding objective value (best_y).
# Candidate generation: Candidates are generated by sampling uniformly random
#                       points within the given bounds.
# Selection and replacement: The best candidate found so far replaces the
#                            current best solution if it has a lower objective
#                            value.
# Adaptation: There is no adaptation mechanism in this simple algorithm.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         random points within the given bounds.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                          by using it as the starting point for the next
#                          iteration.
# Boundary handling: The algorithm ensures that all generated candidates are
#                    within the given bounds by clamping the values to the
#                    bounds if necessary.
# Budget strategy: The algorithm uses the full evaluation budget provided,
#                  performing as many function evaluations as possible within
#                  the budget.
# Closest known influences: This algorithm is similar to a basic random search
#                           algorithm, which is a simple but effective
#                           optimization technique for black-box problems.
# Novelty or unusual aspects: This algorithm does not have any novel or
#                             unusual aspects; it is a straightforward
#                             implementation of a random search algorithm.
# Failure modes: The algorithm may struggle to find the global optimum
#                if the objective function has many local minima or
#                is highly multimodal.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        # Read the bounds from the function object
        if hasattr(func, 'bounds'):
            lb = func.bounds.lb
            ub = func.bounds.ub
        else:
            lb = func.lower
            ub = func.upper

        # Perform random search within the given budget
        for _ in range(self.budget):
            x = np.random.uniform(lb, ub, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
