import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search strategy to optimize the objective function within a given budget.
# Search state: The algorithm maintains a single candidate solution, which is updated on each iteration.
# Candidate generation: New candidate solutions are generated by sampling from a uniform distribution within the search bounds.
# Selection and replacement: The new candidate replaces the current solution if it has a lower objective value.
# Adaptation: The algorithm does not adapt its search strategy during the optimization process.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the current best solution by comparing it to new candidates and replacing it if a better solution is found.
# Boundary handling: The algorithm ensures that new candidate solutions are within the search bounds by sampling from a uniform distribution.
# Budget strategy: The algorithm uses the entire evaluation budget to explore the search space.
# Closest known influences: This algorithm is a basic random search approach, which is a simple and robust optimization method.
# Novelty or unusual aspects: The algorithm does not have any unusual or novel aspects, as it is a straightforward random search implementation.
# Failure modes: The algorithm may struggle to optimize functions with many local minima or highly rugged landscapes, as it does not have any mechanisms to escape local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
