import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that explores the search space by generating random candidate solutions, evaluating them, and keeping track of the best solution found so far.
# Search state: The search state is represented by the current best solution (best_x) and its objective function value (best_y).
# Candidate generation: Candidates are generated by sampling uniformly from the search space defined by the problem bounds.
# Selection and replacement: The best candidate solution found so far is always kept, replacing the previous best solution if a better one is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by generating random candidate solutions.
# Exploitation mechanisms: The algorithm exploits the best solution found so far by using it as the starting point for the next iteration.
# Boundary handling: Candidate solutions that fall outside the search space are simply discarded and a new candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided, spending one function evaluation per iteration.
# Closest known influences: This algorithm is a basic random search algorithm, which is a common baseline for black-box optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in high-dimensional or multimodal problems, as it relies solely on random exploration without any sophisticated search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
