import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search approach to find the
#          minimum of the given function, within the provided evaluation budget.
# Search state: The search state is represented by the current best solution
#                (best_x, best_y).
# Candidate generation: Candidate solutions are generated by sampling uniformly
#                       within the search space bounds.
# Selection and replacement: The best candidate found is selected and replaces
#                            the current best solution if it is better.
# Adaptation: There is no adaptation mechanism in this simple random search.
# Exploration mechanisms: The algorithm explores the search space by sampling
#                         uniformly random points.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          generating new candidates around it.
# Boundary handling: Candidate solutions that fall outside the search space
#                    bounds are rejected.
# Budget strategy: The algorithm uses the full evaluation budget to perform as
#                  many function evaluations as possible.
# Closest known influences: This algorithm is a simple implementation of
#                           random search, which is a well-known
#                           optimization technique.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                             implementation.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it does not
#                employ any advanced search mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Read bounds from the function object
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Perform random search within the budget
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(self.lb, self.ub, self.dim)

            # Evaluate the function
            y = func(x)

            # Update the best solution if the new candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
