import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm to minimize the objective function. It generates candidate solutions within the search space, evaluates them, and updates the best solution found so far.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling random points within the search space.
# Selection and replacement: The generated candidates are evaluated, and the best solution found so far is updated if a better solution is found.
# Adaptation: The algorithm does not adapt during the search process.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling points.
# Exploitation mechanisms: The algorithm does not have any explicit exploitation mechanisms.
# Boundary handling: The algorithm ensures that candidate solutions are within the search space bounds.
# Budget strategy: The algorithm uses the provided evaluation budget and stops when the budget is exhausted.
# Closest known influences: The algorithm is a simple random search approach, which is a basic optimization technique.
# Novelty or unusual aspects: The algorithm does not have any novel or unusual aspects.
# Failure modes: The algorithm may struggle to find the global optimum, especially for high-dimensional or multimodal problems, due to its simple random search approach.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        # Read the search space bounds
        if hasattr(func, 'bounds'):
            lb, ub = func.bounds.lb, func.bounds.ub
        else:
            lb, ub = func.lower, func.upper

        # Initialize the best solution
        self.best_x = np.random.uniform(lb, ub, size=self.dim)
        self.best_y = func(self.best_x)

        # Perform the search
        for _ in range(self.budget - 1):
            # Generate a new candidate solution
            x = np.random.uniform(lb, ub, size=self.dim)
            y = func(x)

            # Update the best solution if necessary
            if y < self.best_y:
                self.best_x, self.best_y = x, y

        return self.best_x, self.best_y
