import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a compact and efficient variant of the Nelder-Mead simplex method to perform the black-box optimization. The algorithm maintains a simplex of points in the search space and iteratively updates the simplex to move towards the optimum.
# Search state: The search state is represented by the vertices of the simplex, which are stored as a 2D numpy array.
# Candidate generation: New candidate points are generated by performing standard Nelder-Mead simplex operations, including reflection, expansion, contraction, and shrinkage.
# Selection and replacement: The best point in the simplex is always kept, and the worst point is replaced by the new candidate.
# Adaptation: The simplex is adapted by adjusting the step sizes based on the relative positions of the vertices.
# Exploration mechanisms: The simplex method explores the search space by moving the simplex towards regions with lower function values.
# Exploitation mechanisms: The simplex method exploits the information gathered during the search by contracting the simplex around the best point.
# Boundary handling: If a candidate point goes outside the bounds, it is projected back onto the nearest valid point within the bounds.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This implementation is based on the classical Nelder-Mead simplex method, which is a well-known and widely used algorithm for derivative-free optimization.
# Novelty or unusual aspects: The algorithm is designed to be compact, efficient, and robust across dimensions, while still adhering to the specified requirements.
# Failure modes: The algorithm may have difficulty in high-dimensional problems or problems with many local minima, as the simplex method can get stuck in local optima. Additionally, the algorithm may struggle with noisy objective functions or discontinuous functions.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0
        self.simplex = None
        self.step_size = 1.0
        self.reflection_coeff = 1.0
        self.expansion_coeff = 2.0
        self.contraction_coeff = 0.5
        self.shrinkage_coeff = 0.5

    def __call__(self, func):
        # Initialize the simplex
        self.simplex = np.zeros((self.dim + 1, self.dim))
        self.simplex[0] = np.zeros(self.dim)
        for i in range(1, self.dim + 1):
            self.simplex[i] = np.zeros(self.dim)
            self.simplex[i, i - 1] = self.step_size

        # Evaluate the initial simplex
        for i in range(self.dim + 1):
            self.simplex[i] = self.check_bounds(self.simplex[i], func)
            self.evaluations += 1

        # Main optimization loop
        while self.evaluations < self.budget:
            # Sort the simplex vertices by their function values
            sorted_simplex = self.simplex[np.argsort([func(x) for x in self.simplex]), :]

            # Calculate the centroid of the simplex, excluding the worst point
            centroid = np.mean(sorted_simplex[:-1], axis=0)

            # Reflect the worst point through the centroid
            reflected = centroid + self.reflection_coeff * (centroid - sorted_simplex[-1])
            reflected = self.check_bounds(reflected, func)
            self.evaluations += 1

            # Compare the reflected point to the other points
            if func(reflected) < func(sorted_simplex[0]):
                # Expand the simplex in this direction
                expanded = centroid + self.expansion_coeff * (reflected - centroid)
                expanded = self.check_bounds(expanded, func)
                self.evaluations += 1
                if func(expanded) < func(reflected):
                    sorted_simplex[-1] = expanded
                else:
                    sorted_simplex[-1] = reflected
            else:
                # Contract the simplex
                if func(reflected) < func(sorted_simplex[-1]):
                    sorted_simplex[-1] = reflected
                else:
                    # Shrink the simplex towards the best point
                    for i in range(1, self.dim + 1):
                        sorted_simplex[i] = sorted_simplex[0] + self.shrinkage_coeff * (sorted_simplex[i] - sorted_simplex[0])
                        sorted_simplex[i] = self.check_bounds(sorted_simplex[i], func)
                        self.evaluations += 1

            # Update the simplex
            self.simplex = sorted_simplex

        # Return the best point and its function value
        best_idx = np.argmin([func(x) for x in self.simplex])
        return self.simplex[best_idx], func(self.simplex[best_idx])

    def check_bounds(self, x, func):
        # Check if the point is within the bounds and project it back if necessary
        if hasattr(func, 'lower') and hasattr(func, 'upper'):
            return np.clip(x, func.lower, func.upper)
        elif hasattr(func, 'bounds') and hasattr(func.bounds, 'lb') and hasattr(func.bounds, 'ub'):
            return np.clip(x, func.bounds.lb, func.bounds.ub)
        else:
            raise ValueError('Unable to determine the bounds of the objective function.')
