import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates new candidate
#          solutions by sampling uniformly from the search space defined by the
#          provided bounds. It keeps track of the best solution found so far
#          and returns it at the end of the evaluation budget.
# Search state: The search state is simply the best solution found so far,
#               represented by the best_x and best_y variables.
# Candidate generation: New candidates are generated by sampling uniformly from
#                       the search space defined by the provided bounds.
# Selection and replacement: The best solution found so far is always kept, and
#                            new candidates replace the current best solution
#                            if they are better.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The uniform random sampling provides a simple
#                         exploration mechanism, exploring the entire search
#                         space.
# Exploitation mechanisms: There are no explicit exploitation mechanisms in
#                          this algorithm.
# Boundary handling: Candidate solutions that fall outside the search space
#                    defined by the provided bounds are rejected and a new
#                    candidate is generated.
# Budget strategy: The algorithm uses the full evaluation budget provided,
#                  generating and evaluating new candidates until the budget
#                  is exhausted.
# Closest known influences: This algorithm is a simple implementation of
#                          pure random search.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: The algorithm may struggle in high-dimensional problems or
#                problems with complex objective functions, as it relies solely
#                on random sampling without any additional mechanisms to guide
#                the search.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
