import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a compact and robust implementation of a randomized
#          search algorithm for black-box function minimization. It uses a
#          simple stochastic search approach with some adaptive mechanisms.
# Search state: The algorithm maintains a single current solution x, which is
#               updated through iterations.
# Candidate generation: New candidate solutions are generated by perturbing the
#                       current solution with Gaussian noise. The magnitude of
#                       the perturbation is adapted based on the history of
#                       improvements.
# Selection and replacement: If a new candidate solution improves upon the
#                            current solution, it replaces the current
#                            solution.
# Adaptation: The step size (standard deviation) of the Gaussian perturbation
#             is adapted based on the success rate of the previous iterations.
#             The step size is increased if the success rate is high, and
#             decreased if the success rate is low.
# Exploration mechanisms: The algorithm relies on the stochastic nature of the
#                         Gaussian perturbations to explore the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution by
#                          using it as the starting point for the next
#                          iteration.
# Boundary handling: If a candidate solution goes outside the bounds, it is
#                    projected back onto the nearest valid point within the
#                    bounds.
# Budget strategy: The algorithm uses the full evaluation budget provided,
#                  without any early stopping.
# Closest known influences: This algorithm is similar to a (1+1)-Evolution
#                          Strategy with adaptive step size.
# Novelty or unusual aspects: The algorithm is designed to be compact and
#                             robust, without any specialized mechanisms or
#                             tuning.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive
#                functions, where the simple stochastic search approach may get
#                stuck in local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x = np.zeros(dim)
        self.sigma = 1.0
        self.success_count = 0
        self.iteration = 0

    def __call__(self, func):
        while self.iteration < self.budget:
            candidate = self.x + self.sigma * np.random.normal(size=self.dim)
            if hasattr(func, 'bounds'):
                candidate = np.clip(candidate, func.bounds.lb, func.bounds.ub)
            else:
                candidate = np.clip(candidate, func.lower, func.upper)
            candidate_value = func(candidate)
            if candidate_value < func(self.x):
                self.x = candidate
                self.success_count += 1
            self.iteration += 1
            self.adapt_step_size()
        return self.x, func(self.x)

    def adapt_step_size(self):
        success_rate = self.success_count / (self.iteration + 1)
        if success_rate > 0.2:
            self.sigma *= 1.1
        else:
            self.sigma *= 0.9
        self.success_count = 0
