import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple, randomized search algorithm that generates new candidate
#          solutions by perturbing the current best solution. The algorithm keeps
#          track of the current best solution and updates it whenever a better
#          solution is found.
# Search state: The search state consists of the current best solution and its
#               corresponding objective function value.
# Candidate generation: New candidate solutions are generated by adding Gaussian
#                       noise to the current best solution. The noise standard
#                       deviation is adapted based on the success or failure of
#                       the previous step.
# Selection and replacement: The new candidate solution replaces the current best
#                            solution if it has a lower objective function value.
# Adaptation: The standard deviation of the Gaussian noise is adapted based on
#             the success or failure of the previous step. If the previous step
#             was successful, the standard deviation is increased to encourage
#             exploration. If the previous step was unsuccessful, the standard
#             deviation is decreased to encourage exploitation.
# Exploration mechanisms: The algorithm explores the search space by generating
#                         new candidate solutions using Gaussian noise.
# Exploitation mechanisms: The algorithm exploits the search space by selecting
#                          the best solution found so far and perturbing it.
# Boundary handling: The algorithm ensures that the new candidate solution
#                    remains within the specified bounds by clipping the values
#                    if necessary.
# Budget strategy: The algorithm uses the entire evaluation budget and does not
#                  have a specific budget strategy.
# Closest known influences: This algorithm is based on the basic principles of
#                          randomized search and adaptive step size control,
#                          which are common in many optimization algorithms.
# Novelty or unusual aspects: The algorithm does not have any particularly novel
#                            or unusual aspects, as it is a relatively simple
#                            randomized search algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                multimodal or highly rugged landscapes, as it does not have any
#                specific mechanisms to escape local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.x_best = None
        self.y_best = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        # Read bounds from the function object
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Initialize the best solution
        self.x_best = np.random.uniform(self.lb, self.ub, self.dim)
        self.y_best = func(self.x_best)
        evaluations = 1

        # Perform the optimization
        while evaluations < self.budget:
            # Generate a new candidate solution
            x_new = self.x_best + self.sigma * np.random.randn(self.dim)

            # Ensure the new solution is within the bounds
            x_new = np.clip(x_new, self.lb, self.ub)

            # Evaluate the new solution
            y_new = func(x_new)
            evaluations += 1

            # Update the best solution if the new solution is better
            if y_new < self.y_best:
                self.x_best = x_new
                self.y_best = y_new

            # Adapt the step size
            if y_new < self.y_best:
                self.sigma *= 1.2  # Increase the step size on success
            else:
                self.sigma *= 0.8  # Decrease the step size on failure

        return self.x_best, self.y_best
