import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple randomized search algorithm that samples candidate
# solutions uniformly within the search bounds and keeps track of the best seen
# so far.
# Search state: The search state is just the current best solution (best_x, best_y).
# Candidate generation: Candidates are generated by sampling uniformly within
# the search bounds.
# Selection and replacement: The best candidate replaces the current best if it
# has a lower objective value.
# Adaptation: There is no adaptation; the search is purely random.
# Exploration mechanisms: Exploration is achieved through the uniform random
# sampling of candidates.
# Exploitation mechanisms: There is no explicit exploitation; the algorithm
# simply keeps track of the best solution seen so far.
# Boundary handling: Candidates outside the search bounds are discarded.
# Budget strategy: The entire budget is used for function evaluations.
# Closest known influences: This is a basic random search algorithm, similar
# to pure random search or Monte Carlo tree search without any tree structure.
# Novelty or unusual aspects: None; this is a very simple, standard random
# search algorithm.
# Failure modes: The algorithm may struggle on highly multimodal or deceptive
# functions, as it has no mechanisms for escaping local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, size=self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
