import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of a randomized derivative-free optimization algorithm
#          that uses a combination of random sampling and a gradient-based local search to
#          efficiently explore the search space and find the global minimum.
# Search state: The search state consists of the current best solution (best_x, best_y) and a
#               set of candidate solutions that are generated and evaluated at each iteration.
# Candidate generation: Candidates are generated by randomly sampling within the search bounds,
#                       and by applying a gradient-based local search to the current best solution.
# Selection and replacement: The best candidate solution is selected to replace the current
#                            best solution if it improves the objective function value.
# Adaptation: The algorithm adapts the step size used in the local search based on the progress
#             of the optimization, increasing the step size when the local search is making
#             progress, and decreasing it when the local search is stuck.
# Exploration mechanisms: The algorithm explores the search space by randomly sampling new
#                         candidate solutions, and by applying a gradient-based local search
#                         to the current best solution.
# Exploitation mechanisms: The algorithm exploits the current best solution by applying a
#                          gradient-based local search to it, and by biasing the random
#                          sampling towards the region around the current best solution.
# Boundary handling: The algorithm handles boundary constraints by projecting any candidate
#                    solutions that fall outside the search bounds back onto the feasible
#                    region.
# Budget strategy: The algorithm attempts to use the entire evaluation budget by carefully
#                  managing the number of candidates generated and evaluated at each
#                  iteration.
# Closest known influences: This algorithm is inspired by a combination of techniques from
#                          Bayesian optimization, evolutionary algorithms, and gradient-based
#                          optimization.
# Novelty or unusual aspects: The algorithm uses a unique combination of random sampling and
#                            gradient-based local search, and adapts the step size used in the
#                            local search based on the progress of the optimization.
# Failure modes: The algorithm may struggle to find the global minimum if the objective
#                function is highly multimodal or if the search bounds are not set
#                appropriately.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.step_size = 1.0

    def __call__(self, func):
        # Read the search bounds from the objective function
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Initialize the search with a random point
        self.best_x = np.random.uniform(self.lb, self.ub, size=self.dim)
        self.best_y = func(self.best_x)
        self.budget -= 1

        # Optimize using a combination of random sampling and gradient-based local search
        while self.budget > 0:
            # Generate new candidates
            candidates = self.generate_candidates(func)

            # Evaluate the candidates and update the best solution
            for x in candidates:
                y = func(x)
                self.budget -= 1
                if y < self.best_y:
                    self.best_x = x
                    self.best_y = y

            # Adapt the step size for the local search
            self.adapt_step_size()

        return self.best_x, self.best_y

    def generate_candidates(self, func):
        candidates = []

        # Generate random candidates
        for _ in range(max(1, self.budget // 10)):
            x = np.random.uniform(self.lb, self.ub, size=self.dim)
            candidates.append(x)

        # Apply a gradient-based local search to the current best solution
        if self.best_x is not None:
            x = self.best_x.copy()
            for _ in range(max(1, self.budget // 10)):
                grad = self.estimate_gradient(func, x)
                x -= self.step_size * grad
                x = np.clip(x, self.lb, self.ub)
                candidates.append(x)

        return candidates

    def estimate_gradient(self, func, x):
        eps = 1e-8
        grad = np.zeros(self.dim)
        for i in range(self.dim):
            dx = np.zeros(self.dim)
            dx[i] = eps
            grad[i] = (func(x + dx) - func(x - dx)) / (2 * eps)
        return grad

    def adapt_step_size(self):
        if len(self.budget) > 0:
            if self.budget[-1] > self.budget[0]:
                self.step_size *= 1.1
            else:
                self.step_size *= 0.9
        self.step_size = max(1e-8, min(1.0, self.step_size))
