import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a compact implementation of the Nelder-Mead simplex algorithm for
#          black-box function minimization. It maintains a simplex of points, reflects,
#          expands, or contracts the simplex based on the function values at the vertices,
#          and iterates until the evaluation budget is exhausted.
# Search state: The search state is a simplex of 'dim + 1' points in the 'dim'-dimensional
#               search space, along with the function values at those points.
# Candidate generation: New candidate points are generated by reflecting, expanding, or
#                       contracting the current simplex.
# Selection and replacement: The point with the highest function value is replaced by a
#                            new candidate point.
# Adaptation: The simplex shape adapts based on the function values at the vertices.
# Exploration mechanisms: The initial simplex is constructed randomly within the bounds,
#                         providing exploration.
# Exploitation mechanisms: The simplex adapts to follow the function gradient, providing
#                          exploitation.
# Boundary handling: Candidate points outside the bounds are projected back onto the
#                    boundary.
# Budget strategy: The algorithm runs until the evaluation budget is exhausted.
# Closest known influences: This is a standard implementation of the Nelder-Mead simplex
#                           algorithm, which is a commonly used derivative-free optimization
#                           method.
# Novelty or unusual aspects: The implementation is compact and self-contained, using
#                             only the Python standard library and NumPy.
# Failure modes: The algorithm may converge to a local minimum, especially if the function
#                has many local minima. The performance also depends on the initial simplex
#                size and the function landscape.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.evaluations = 0

    def __call__(self, func):
        # Initialize a random simplex within the bounds
        self.x = np.array([func.lower + (func.upper - func.lower) * np.random.rand(self.dim)
                          for _ in range(self.dim + 1)])
        self.f = np.array([func(x) for x in self.x])
        self.evaluations += self.dim + 1

        # Nelder-Mead simplex algorithm
        while self.evaluations < self.budget:
            # Find the best, worst, and second-worst points
            i_best = np.argmin(self.f)
            i_worst = np.argmax(self.f)
            i_second_worst = np.argsort(self.f)[self.dim]

            # Compute the centroid of the best points
            x_centroid = np.mean(self.x[self.f < self.f[i_worst]], axis=0)

            # Reflection
            x_refl = x_centroid + 1 * (x_centroid - self.x[i_worst])
            f_refl = func(x_refl)
            self.evaluations += 1
            if self.f[i_best] <= f_refl < self.f[i_second_worst]:
                self.x[i_worst] = x_refl
                self.f[i_worst] = f_refl
                continue

            # Expansion
            if f_refl < self.f[i_best]:
                x_exp = x_centroid + 2 * (x_centroid - self.x[i_worst])
                f_exp = func(x_exp)
                self.evaluations += 1
                if f_exp < f_refl:
                    self.x[i_worst] = x_exp
                    self.f[i_worst] = f_exp
                else:
                    self.x[i_worst] = x_refl
                    self.f[i_worst] = f_refl
                continue

            # Contraction
            x_cont = x_centroid + 0.5 * (self.x[i_worst] - x_centroid)
            f_cont = func(x_cont)
            self.evaluations += 1
            if f_cont < self.f[i_worst]:
                self.x[i_worst] = x_cont
                self.f[i_worst] = f_cont
                continue

            # Shrink
            self.x = self.x[i_best] + 0.5 * (self.x - self.x[i_best])
            self.f = [func(x) for x in self.x]
            self.evaluations += self.dim

        # Return the best point found
        i_best = np.argmin(self.f)
        return self.x[i_best], self.f[i_best]
