import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a simple random search strategy to minimize the
#          given function within the provided budget. It generates new candidate
#          solutions by sampling from a uniform distribution bounded by the
#          function's lower and upper bounds, and keeps track of the best
#          solution found so far.
# Search state: The algorithm maintains the current best solution (best_x,
#               best_y) found so far.
# Candidate generation: New candidate solutions are generated by sampling from a
#                       uniform distribution bounded by the function's lower and
#                       upper bounds.
# Selection and replacement: The best solution found so far is replaced if a
#                            better solution is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the search space by keeping
#                          track of the best solution found so far and replacing
#                          it if a better solution is found.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                    within the function's lower and upper bounds by sampling
#                    from a uniform distribution bounded by these values.
# Budget strategy: The algorithm uses the provided evaluation budget and does
#                  not exceed it.
# Closest known influences: This algorithm is a simple random search strategy,
#                          which is a well-known optimization technique.
# Novelty or unusual aspects: The algorithm is straightforward and does not
#                            employ any sophisticated techniques.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multi-modal functions, as it relies solely
#                on random sampling without any additional mechanisms to escape
#                local optima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
