import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm uses a random search approach to minimize the
#          objective function within the given evaluation budget.
# Search state: The algorithm maintains a single current best solution.
# Candidate generation: Candidate solutions are generated by adding
#                       Gaussian-distributed random offsets to the current
#                       best solution.
# Selection and replacement: The best candidate solution (if any) replaces
#                            the current best solution.
# Adaptation: The algorithm does not adapt its search parameters during the
#             optimization process.
# Exploration mechanisms: The Gaussian-distributed random offsets provide
#                         exploration of the search space.
# Exploitation mechanisms: The algorithm exploits the current best solution
#                          by generating candidates in its vicinity.
# Boundary handling: If a candidate solution falls outside the bounds, it is
#                    projected back onto the nearest valid point.
# Budget strategy: The algorithm terminates when the evaluation budget is
#                  exhausted.
# Closest known influences: This algorithm is a simple random search approach,
#                          common in the optimization literature.
# Novelty or unusual aspects: The algorithm does not have any novel or
#                            unusual aspects.
# Failure modes: The algorithm may struggle to solve problems with complex
#                multi-modal or highly constrained search spaces, as it relies
#                solely on random exploration.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        self.budget_remaining = self.budget
        self.best_x = np.zeros(self.dim)
        self.best_y = func(self.best_x)
        self.budget_remaining -= 1

        while self.budget_remaining > 0:
            # Generate a candidate solution by adding Gaussian noise to the current best
            candidate_x = self.best_x + np.random.normal(0, 1, self.dim)

            # Ensure the candidate is within the bounds
            if hasattr(func, "bounds"):
                candidate_x = np.clip(candidate_x, func.bounds.lb, func.bounds.ub)
            else:
                candidate_x = np.clip(candidate_x, func.lower, func.upper)

            # Evaluate the candidate and update the best solution if it improves
            candidate_y = func(candidate_x)
            self.budget_remaining -= 1
            if candidate_y < self.best_y:
                self.best_x = candidate_x
                self.best_y = candidate_y

        return self.best_x, self.best_y
