import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This algorithm is a simple random search algorithm that generates new
#          candidate solutions by randomly sampling within the variable bounds.
# Search state: The algorithm maintains a single best solution found so far.
# Candidate generation: New candidate solutions are generated by randomly
#                       sampling each variable within the given bounds.
# Selection and replacement: The best solution found so far is updated whenever
#                            a new candidate solution with a lower function
#                            value is found.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The algorithm explores the search space by randomly
#                         sampling new candidate solutions.
# Exploitation mechanisms: The algorithm exploits the best solution found so
#                          far by using it as the starting point for new
#                          candidate generations.
# Boundary handling: The algorithm ensures that new candidate solutions are
#                    within the variable bounds by randomly sampling within the
#                    bounds.
# Budget strategy: The algorithm stops when the evaluation budget is exhausted.
# Closest known influences: This algorithm is a basic random search algorithm,
#                          which is a simple and straightforward approach to
#                          black-box optimization.
# Novelty or unusual aspects: This algorithm does not have any unusual aspects,
#                             as it is a standard random search algorithm.
# Failure modes: The algorithm may struggle to find the global optimum in
#                high-dimensional or multimodal problems, as it does not
#                have any advanced exploration or exploitation mechanisms.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
