import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple compact implementation of a black-box minimization algorithm
#          that uses a combination of random sampling and gradient-based local search.
# Search state: The algorithm maintains the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by adding Gaussian noise
#                       to the current best solution, with the noise standard deviation
#                       decreasing over time.
# Selection and replacement: The new candidate is compared to the current best solution,
#                            and replaces it if the new solution is better.
# Adaptation: The standard deviation of the Gaussian noise is adaptively decreased
#              over the course of the optimization, to transition from global exploration
#              to local exploitation.
# Exploration mechanisms: Random sampling of the search space using Gaussian noise.
# Exploitation mechanisms: Local gradient-based search around the current best solution.
# Boundary handling: Candidate solutions that fall outside the search bounds are
#                    reflected back into the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget, without any
#                  additional budget management.
# Closest known influences: This algorithm combines elements of evolutionary
#                           strategies and gradient-based local search.
# Novelty or unusual aspects: The adaptive noise standard deviation and the
#                             boundary handling are relatively simple but
#                             effective techniques.
# Failure modes: The algorithm may struggle in highly multimodal or
#                 discontinuous landscapes, where the local search
#                 can get stuck in poor local minima.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf
        self.sigma = 1.0

    def __call__(self, func):
        # Read bounds from the function
        if hasattr(func, 'bounds'):
            self.lb = func.bounds.lb
            self.ub = func.bounds.ub
        else:
            self.lb = func.lower
            self.ub = func.upper

        # Initialize the best solution
        self.best_x = np.random.uniform(self.lb, self.ub, size=self.dim)
        self.best_y = func(self.best_x)
        self.budget -= 1

        # Optimize
        for _ in range(self.budget):
            # Generate a new candidate solution
            candidate = self.best_x + self.sigma * np.random.normal(size=self.dim)

            # Ensure the candidate is within bounds
            candidate = np.maximum(self.lb, np.minimum(self.ub, candidate))

            # Evaluate the candidate
            candidate_y = func(candidate)

            # Update the best solution if the candidate is better
            if candidate_y < self.best_y:
                self.best_x = candidate
                self.best_y = candidate_y

            # Adapt the search strategy
            self.sigma *= 0.99

        return self.best_x, self.best_y
