import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This is a simple random search algorithm that generates candidate
#          solutions by sampling uniformly within the given bounds, and keeps
#          track of the best solution found so far.
# Search state: The algorithm maintains the current best solution and its
#                objective value.
# Candidate generation: Candidates are generated by sampling uniformly within
#                       the given bounds.
# Selection and replacement: The best candidate replaces the current best
#                            solution if it has a lower objective value.
# Adaptation: There is no adaptation mechanism in this algorithm.
# Exploration mechanisms: The uniform random sampling provides a basic
#                         exploration mechanism.
# Exploitation mechanisms: There are no explicit exploitation mechanisms.
# Boundary handling: Candidates that fall outside the bounds are rejected.
# Budget strategy: The algorithm simply uses the entire evaluation budget,
#                  without any budget management strategies.
# Closest known influences: This is a basic random search algorithm, similar
#                          to many stochastic optimizers.
# Novelty or unusual aspects: There are no novel or unusual aspects to this
#                            algorithm.
# Failure modes: The algorithm may struggle on high-dimensional problems or
#                problems with complex, multi-modal landscapes, as it has no
#                mechanisms to effectively navigate such search spaces.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = float('inf')

    def __call__(self, func):
        for _ in range(self.budget):
            x = np.random.uniform(func.lower, func.upper, self.dim)
            y = func(x)
            if y < self.best_y:
                self.best_x = x
                self.best_y = y
        return self.best_x, self.best_y
