import numpy as np

# ALGORITHM_ANALYSIS_NOTE_BEGIN
# Summary: This implementation uses a simple random search algorithm to minimize the
#          given objective function within the provided evaluation budget.
# Search state: The search state is represented by the current best solution (best_x, best_y).
# Candidate generation: New candidate solutions are generated by sampling uniformly within the
#                       given bounds.
# Selection and replacement: The new candidate solution replaces the current best solution
#                            if it has a lower objective function value.
# Adaptation: There is no adaptation mechanism in this implementation.
# Exploration mechanisms: The search explores the feasible space by randomly sampling
#                         new candidate solutions.
# Exploitation mechanisms: The search exploits the current best solution by
#                          focusing the sampling around it.
# Boundary handling: Candidate solutions that fall outside the given bounds are
#                    projected back onto the feasible region.
# Budget strategy: The algorithm uses the entire evaluation budget to explore the
#                  search space and find the best solution.
# Closest known influences: This implementation is a basic random search algorithm,
#                           which is a common baseline for black-box optimization problems.
# Novelty or unusual aspects: There are no novel or unusual aspects to this implementation.
# Failure modes: The algorithm may struggle to find the global optimum, especially in
#                high-dimensional or multimodal problems, due to its simplistic
#                exploration strategy.
# ALGORITHM_ANALYSIS_NOTE_END

class Algorithm:
    def __init__(self, budget, dim):
        self.budget = budget
        self.dim = dim
        self.best_x = None
        self.best_y = np.inf

    def __call__(self, func):
        for _ in range(self.budget):
            # Generate a new candidate solution
            x = np.random.uniform(func.lower, func.upper, self.dim)

            # Evaluate the candidate solution
            y = func(x)

            # Update the best solution if the candidate is better
            if y < self.best_y:
                self.best_x = x
                self.best_y = y

        return self.best_x, self.best_y
